### ISSUE TITLE
AMD A4-5000 APU with Radeon(TM) HD Graphics       1.50 GHz

### ISSUE THREAD

**Issue by king213d** [sebanc/brunch#1031]
AMD A4-5000 APU with Radeon(TM) HD Graphics       1.50 GHz is this cpu is compitible for chrome os ..?? plzz tell me

**Comment by aishivam** [comment]
Non-Working Device & Failed Installs and the reason is Possible incompatible instruction set, try to install it on a different device.
you can check compatibility here https://github.com/sebanc/brunch/wiki/Hardware-&-Device-Compatibility#non-working-devices--failed-installs
