### ISSUE TITLE
Linux showing in settings menu but not available

### ISSUE THREAD

**Issue by alessandrogian** [sebanc/brunch#1062]
I can search for Linux on my settings page but when I click on it nothing happens
![image](https://user-images.githubusercontent.com/78299311/118723137-52f8ac80-b82d-11eb-8918-309ef187550c.png)

I really need Linux for many apps so I have no idea what to do! I tried installing crouton but I can't get my system to boot in developer mode and refuses to execute the crouton file

**Comment by princepjamie06832** [comment]
I think virtualization feature disabled and Linux cannot be accessed, but you can enable it in BIOS/UEFI settings when supported by CPU. Virtualization disabled by default in BIOS/UEFI settings.
