### ISSUE TITLE
how to use microsoft word excel and powerpoint free in brunch chromeos

### ISSUE THREAD

**Issue by asukumar10248** [sebanc/brunch#1073]

**Comment by Param-Bhati** [comment]
You can download from play store on chromeOS.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: asukumar10248 ***@***.***>
Sent: Wednesday, May 26, 2021 8:23:01 AM
To: sebanc/brunch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sebanc/brunch] how to use microsoft word excel and powerpoint free in brunch chromeos (#1073)

**Comment by asukumar10248** [comment]
but it is asking for microsoft 365 subscription

**Comment by princepjamie06832** [comment]
Please note, you cannot create or edit document without subscription. When you open documents, it's read-only unless have subscription.
