### ISSUE TITLE
Failed to install chrome os on asus VivoBook Flip 14 TP470 notebook

### ISSUE THREAD

**Issue by wz6789** [sebanc/brunch#1079]
1. I have successfully installed chrome os on amd4700cpu laptop. The operation is also normal, using zork.
2. Then the installation of chrome os on asus VivoBook Flip 14 TP470 (cpu: i7-1165G7) failed.
3. The volteer used on the VivoBook Flip 14 TP470 notebook.
4. Error message: Failed during the brunch boot process, it prompts "Cannot find the chrome os file".

**Comment by asukumar10248** [comment]
use hatch recovery

**Comment by wz6789** [comment]
Okay, I'll try it now. Thank you

**Comment by wz6789** [comment]
The problem has not changed. Still prompted: brunch: chromeOS was not found on any device, falling back to shell

**Comment by wz6789** [comment]
Is there any alternative. Thank you

**Comment by princepjamie06832** [comment]
Use 'Volteer' that will support for 10th-11th Gen and required change kernel to 5.10 before booting into Chrome OS. Change from "/kernel" to "/kernel-5.10" by using nano text editing.

**Comment by wz6789** [comment]
Kernel-5.10 is currently used

**Comment by wz6789** [comment]
To solve the problem, the pci-e hard disk could not be found because of lack of vmd support. Solved by using the new version of the framework.
