### ISSUE TITLE
Could it boot in a partition formatted as Btrfs?

### ISSUE THREAD

**Issue by 1457384613gh** [sebanc/brunch#1083]
Could it boot in a partition formatted as Btrfs?
If it could boot in a partition formatted as Btrfs and make good use of function named subvolume, it would be superior and similar to Mac OS booting in APFS+.

I have also ask help there https://github.com/riverzhou/cgpt/issues/1

**Comment by simplyrajatgupta** [comment]
No, Only NTFS and ext4 supported
Check this also may be helpful
[https://github.com/sebanc/brunch/issues/1088]()

**Comment by 1457384613gh** [comment]
> No, Only NTFS and ext4 supported
> Check this also may be helpful
> https://github.com/sebanc/brunch/issues/1088

I'm sure it can be, because I have managed !

**Comment by simplyrajatgupta** [comment]
> > No, Only NTFS and ext4 supported
> > Check this also may be helpful
> > https://github.com/sebanc/brunch/issues/1088
> 
> I'm sure it can be, because I have managed !

But NTFS and ext4 is recommended by @sebanc

**Comment by simplyrajatgupta** [comment]
Please close your issue

**Comment by simplyrajatgupta** [comment]
@1457384613gh  Please close your issue
