### ISSUE TITLE
How to Install ChromeOS from Fedora ?

### ISSUE THREAD

**Issue by 1457384613gh** [sebanc/brunch#1084]
Fedora cannot `apt-get install cgpt.deb`.
Even though I `alien -r cgpt.deb`, and `yum -y localinstall cgpt.rpm`, it fail to install still.
Could you edit a brand new *chromeos-install.sh* for Linux distribution with both dnf and yum？
Wish Root-A, OEM, H-STATE and so on could be as sub-volumes,  friendly to SSD. Otherwise, it should install in a partition formatted as Btrfs.

I have also ask help there riverzhou/cgpt#1

**Comment by WiseMetalhead** [comment]
You can install cgpt via the command:
# sudo dnf install vboot-utils
Works also on Fedora 34.

**Comment by 1457384613gh** [comment]
> You can install cgpt via the command:
> **sudo dnf install vboot-utils**
> Works also on Fedora 34.

Thanks for your reply and how earnest you are !

**Comment by 1457384613gh** [comment]
Wish the next right thing might be to merge EFI system partitions and make use of function called subvolume.

**Comment by 1457384613gh** [comment]
> > > You can install cgpt via the command:
> > > **sudo dnf install vboot-utils**
> > > Works also on Fedora 34.
> > 
> > 
> > Thanks for your reply and how earnest you are ! One installed into Btrfs runs even fast than another installed into ext4.
> 
> did it work? were you able to sucessfully install chromeos using fedora

using fedora √
btrfs ？
I don't know if R-98 …
