### ISSUE TITLE
The way to resize disk image

### ISSUE THREAD

**Issue by yutouyes** [sebanc/brunch#110]
Hi,
As https://github.com/sebanc/brunch#dual-boot-chromeos-from-your-hdd says we need to place all partitions of CrOS into a .img. So if Chrome OS reports that free space is not enough, can we enlarge the .img to allocate more disk?

**Comment by sebanc** [comment]
Hi,

Sorry but the best way to do it is backup everything and re-create the image from the start. In theory there are ways to grow n image size but last time i tried that the gpt got corrupted which created multiple issues...
