### ISSUE TITLE
not enough space to create image file

### ISSUE THREAD

**Issue by Moon-Haze** [sebanc/brunch#1109]
When I install chrome os by using Ubuntu 20.04, I happened an error which is "not enough space to create image file".

**Comment by simplyrajatgupta** [comment]
@Moon-Haze      Restart your system

**Comment by princepjamie06832** [comment]
How much space you'll need to create image file on your drive or partition?

**Comment by simplyrajatgupta** [comment]
> How much space you'll need to create image file on your drive or partition?

14 gb for img and 1 gb for file system and other system information
# **(=15 GB)**

**Comment by Moon-Haze** [comment]
The resered space is 49G.

**Comment by Moon-Haze** [comment]
![image](https://user-images.githubusercontent.com/73505211/121793419-5109e980-cc31-11eb-99a7-cf35e99f175e.png)
I think this can try.

**Comment by Moon-Haze** [comment]
Thank you very much.

**Comment by simplyrajatgupta** [comment]
Please close your issue

**Comment by simplyrajatgupta** [comment]
@Moon-Haze  Please close your issue
