### ISSUE TITLE
[DELL Venue 11 Pro 7140] No audio

### ISSUE THREAD

**Issue by qtotter** [sebanc/brunch#1114]
I guess kernel doesn't support this tablet's sound board?  

****
DELL Venue 11 Pro 7140 (tablet): 
CPU: Intel core M-5Y10 (Broadwell)
Audio: Realtek HW Audio Codec/Intel Smart Sound Technology (from Device Manager of Win10)

Brunch: brunch_r90_stable_20210523.tar.gz
ROM: wizpig 
Kernel: 5.4
dmesg.txt: [https://drive.google.com/file/d/1IjUx-xGPXrOpruFJE356_wrLJMPbPOuc/view?usp=sharing](https://drive.google.com/file/d/1IjUx-xGPXrOpruFJE356_wrLJMPbPOuc/view?usp=sharing)
****

Almost everything works fine, including touchscreen, WiFi, BT, rotation, back camera, etc., except sound (and front camera, which is not really important for me.) What can I do with it?

Thanks to sebanc's continuous development, my Dell Inspiron 14 2-in1 (5400) now runs Chrome OS flawlessly with recent brunch and kernel 5.10! So, I bought a second-handed Venue 7140 Pro to use as a tablet, but I am facing this issue now. Any supports will be appreciated. Thanks!

qt

**Comment by sebanc** [comment]
Try kernel 5.10 first and if it does not work try kernel 5.10 with "disable_intel_hda" option.

**Comment by qtotter** [comment]
Hi sebanc, I tried 5.10 and 5.10+disable_intel_hda, and the result was the same, still no sound...

**Comment by qtotter** [comment]
```
$ grep -i codec /proc/asound/card*/codec#*
Codec: Intel Broadwell HDMI
```
I guess Intel Broadwell HDMI is for HDMI, but Realtek HW Audio for speaker is not recognized as a codec chip...

**Comment by qtotter** [comment]
broadwellrt286 is recognized as a card on brunch kernel, but it doesn't seem to be working. Audio is working fine on ubuntu...

**Comment by qtotter** [comment]
Reading [here](https://bbs.archlinux.org/viewtopic.php?id=208461&p=2), the command line, 
`$ amixer -c 1 set SPO on`
also works with Chrome OS, and Venue 11 Pro 7140 now plays sound. I hope this can be fixed at the kernel level...

**Comment by sebanc** [comment]
I think the issue is in "alsa-lib", chromeos currently uses a version which is quite old and is known to have some issues so I cannot really do much about it.

However, that command is a nice find and you can easily create a bootscritpt to enable it on startup by running the below commands in crosh shell:
```
sudo mkdir /var/brunch/bootscripts
echo "amixer -c 1 set SPO on" | sudo tee /var/brunch/bootscripts/sound.sh
sudo chmod 0755 /var/brunch/bootscripts/sound.sh"
```

Bootscripts persists across updates so you should only need to run those commands once.

**Comment by qtotter** [comment]
Hi sebanc, Thanks for the boot script tip!

qt
