### ISSUE TITLE
Autorotation not work in k4.19 testing 20200503

### ISSUE THREAD

**Issue by salvavic** [sebanc/brunch#112]
Hi,

With a surface pro 3, with the last testing version, r81-k4.19-testing-20200503, the tablet enters in tablet mode but the autorotation not works. 

In version r81 k4.19 testing 20200419 and with the same kernel options, it works.

Thank for the great work

**Comment by sebanc** [comment]
Hi,

This issue should be fixed in the new testing release I have just posted. Could you try it ?

**Comment by salvavic** [comment]
Hi,

It works in the last stable version. Thank you
