### ISSUE TITLE
Linux (beta)

### ISSUE THREAD

**Issue by FilipeF85** [sebanc/brunch#1124]
Hi i have installed "Brunch r91 stable 20210620" with the rammus recovery "chromeos_13904.55.0_rammus_recovery_stable-channel_mp-v2.bin.zip"
I have install it directly to single disk.
I have play store working everything fine, but i cannot activate the Linux (beta) option on Developers i turn it on then show the windows informing that will install i do next i select the username the space i let the recommended that is 7.5GB, press Install then i have this error:

Error installing Linux...

Error download the virtual machine. Please try again.

**Comment by forumi0721** [comment]
Me too.
Any others ok?

**Comment by skiv71** [comment]
Me and well... just tried cloudready, which was r89... worked ok there.

**Comment by iknoors** [comment]
hey i just saw this thread, is there linux for family link yet

**Comment by rocketprogrammer** [comment]
Happening for me too.

**Comment by toledompm** [comment]
Same thing here (intel celeron n4000), tried some brunch release - chrome os recovery images combos. With this one I was able to install the linux beta:
- Brunch: r91 stable
- Rammus: 90
I'm kinda of a noob when it comes to brunch though, are there any drawbacks to using an older recovery image or will I be fine?

**Comment by BiteDasher** [comment]
Me too

Recovery: rammus 91
Brunch: r91

**Comment by mm-a** [comment]
me too -  r91

**Comment by bhavishyamadan** [comment]
Set this flag to “disabled” 
By typing this in chrome

chrome://flags#crostini-use-dlc

Now 
Reboot and try again

**Comment by mm-a** [comment]
> Set this flag to “disabled”
> By typing this in chrome
> 
> chrome://flags#crostini-use-dlc
> 
> Now
> Reboot and try again

that worked for me, thank you

**Comment by FilipeF85** [comment]
> Set this flag to “disabled”
> By typing this in chrome
> 
> chrome://flags#crostini-use-dlc
> 
> Now
> Reboot and try again

Just tested your solution and it worked fine.
Thanks for your help.

**Comment by compnew2006** [comment]
> Set this flag to “disabled”
> By typing this in chrome
> 
> chrome://flags#crostini-use-dlc
> 
> Now
> Reboot and try again

It's Work as chrome  thanks for help.
