### ISSUE TITLE
At least, how many GB smaller than ext4 partition can the img file be ? 

### ISSUE THREAD

**Issue by 1457384613gh** [sebanc/brunch#1127]
If the ext4 partition is 1 GB larger than the upcoming img file, terminal will prompt for insufficient storage space to install. 
In order to install successfully, how many GB at least smaller than ext4 partition can the img file be ? 
1GB is extremely large.

**Comment by princepjamie06832** [comment]
When I install Chrome OS with multi-boot. For example, 59 GB on EXT4 64 GB or 63 GB on NTFS 63 GB. When I attempting to install Chrome OS to create image for 63 GB on EXT4 64 GB, not enough space to create image. When I put 59 GB to create image on 64 GB EXT4, it works fine. Image file size must be smaller than partition size.
