### ISSUE TITLE
Error installing Linux: Error downloading the virtual machine

### ISSUE THREAD

**Issue by siumingdev** [sebanc/brunch#1131]
Error message with title "Error installing Linux" and content "Error downloading the virtual machine. Please try again." shows up during initial setup of Linux (beta).

I am pretty sure there is no problem on the internet access.

![image](https://user-images.githubusercontent.com/40101736/123503101-516ba100-d683-11eb-963b-b62a691b2855.png)

**Comment by siumingdev** [comment]
Brunch: r91 stable 20210620
ChromeOS image: rammus 91.0.4472.114
Hardware: I guess not related?

**Comment by siumingdev** [comment]
per suggestion from sebanc in Telegram, downgraded to r90 and it works now.

**Comment by lucasgabrielmoreno** [comment]
> per suggestion from sebanc in Telegram, downgraded to r90 and it works now.

Same problem from r91! Works downgrade to r90
Thank you!!!
