### ISSUE TITLE
Is there an option to disable bluetooth ertm during boot with brunch?

### ISSUE THREAD

**Issue by MrHomebrew** [sebanc/brunch#1133]
Is there an option to disable bluetooth ertm during boot with brunch?

This would fix the constant reconnection of the xbox controller in Chrome OS.

Would allow us to play games with the xbox controller throught bluetooth.

**Comment by MrHomebrew** [comment]
Nvm issue fixed by adding

Bluetooth.disable_ertm=1

in the Kernel command line parameter section. As recommended between cros_debug and options= for example in the grub config.

**Comment by RedMaun** [comment]
thatnks a lot!
