### ISSUE TITLE
Volteer - Google's recovery images are currently down.

### ISSUE THREAD

**Issue by riqueps** [sebanc/brunch#1147]
Hello there, I'm trying to download volteer recovery images but it's showing me the following message: "Google's recovery images are currently down. They will return here as soon as they are up again. Sorry for the inconvenience!"
Someone could tell me when it will return or if someone has a link to let me download it ?
Thanks a lot.

**Comment by WesBosch** [comment]
Currently, this link still works
https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13904.55.0_volteer_recovery_stable-channel_mp-v6.bin.zip

**Comment by riqueps** [comment]
> Currently, this link still works
> https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13904.55.0_volteer_recovery_stable-channel_mp-v6.bin.zip

Thanks a lot!!
