### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Ohko25** [sebanc/brunch#1189]
Hello,

I cannot install linux bêta on rammus 81 + brunch 91 on bios legacy, 
chrome: // flags # crostini-use-dlc is not present in the flag.

**Comment by WesBosch** [comment]
if the flag is not present, I'd suggest reinstalling ChromeOS 90 and installing Linux beta there first, then update into 91. Make sure virtualization is avaliable and enabled in your bios.

**Comment by Ohko25** [comment]
Virtualization is not avaliable in my bios, I think that's the problem.
