### ISSUE TITLE
Support for Killer AX1650

### ISSUE THREAD

**Issue by shad0wfile** [sebanc/brunch#119]
Hello,

I've tried to setup chromeos on my 2019 Dell XPS 7590, it's almost there, but wireless isn't working. I know the killer wireless drivers were merged into the 5.x kernel, wondering if they could be ported in? Other then that everything else works, sound, video, mouse, keyboard, OLED doesn't have a brightness scale ability via the keyboard, but that's pretty standard on this machine with base Linux OS.

So, just looking to see if this particular driver could be added? 

Thanks!

**Comment by sebanc** [comment]
Hi,

Could you try to add "options=iwlwifi_backport" to the kernel command line (after cros_debug) ?

**Comment by shad0wfile** [comment]
Awesome, problem solved. 

Thanks!

**Comment by shad0wfile** [comment]
Any thoughts on OLED brightness control? Usually I utilize xrandr or something on Ubuntu/etc, curious if there is anything comparable?

**Comment by sebanc** [comment]
I was not aware of this issue and looked a bit into it, unfortunately all programs have x11 dependencies which cannot be resolved in chromeos.

However, some users points that brightness can be adjusted when adding "i915.enable_dpcd_backlight=1" to the kernel command line, would that be a solution for you ?

**Comment by shad0wfile** [comment]
No luck, I'll continue to dig around and see if I can find anything. Thanks again for all the help!

**Comment by sebanc** [comment]
You can try the croissant telegram group, someone might have encountered this issue and found a way to solve it

**Comment by shad0wfile** [comment]
I'll give it a shot, thanks again.

**Comment by sebanc** [comment]
If you are still interested, I tried to enable OLED brightness in the brunch-unstable repo release.
