### ISSUE TITLE
"Wrong EFI loader signature". After successfully getting into GNU GRUB section and selecting ChromeOS getting the "Wrong EFI loader signature" error.

### ISSUE THREAD

**Issue by NAS8910** [sebanc/brunch#1196]
### Not able to boot into Chrome OS even after installation done by Linux terminal. 

> My System Configuration:
> 
> CPU: **Core 2 duo E7500**
> RAM: **4gb DD3**

My PC doesn't support UEFI. I tried by using tutorial with the mbr support material but couldn't boot into chromeOS. 

> _**Note:** I got the "ChromeOS installed" message in the Linux mint terminal after completing all the steps as per the guide._

I have attached a video and some photos which tells about bootloop going through with the EFI loader signature error.

![Snapshot_1](https://user-images.githubusercontent.com/80639377/129082782-ca9fe004-acb1-4b6a-808b-9066edd787c4.png)
![Snapshot](https://user-images.githubusercontent.com/80639377/129083213-6d300a3d-df45-4b91-a182-b5d9a062ffb8.png)

_If you need any other information regarding this please inform_

_Sorry for the video to be faster than it was in real but couldn't get that under required size without it._

 

https://user-images.githubusercontent.com/80639377/129081854-d9cb0204-7f7a-482b-840e-bea18c06aef0.mp4

**Comment by Ccl00101** [comment]
how long have you waited? first boot can take from 5 to 10 minutes.. if it boots normally after just ignore that wrong efi signature message.

**Comment by NAS8910** [comment]
Actually When i try to boot into ChromeOS after the wrong efi screen the system reboots and this loops continues. You can refer the video to know the actual scene for the system.

**Comment by WesBosch** [comment]
Your CPU is not supported, and will not boot Brunch regardless of what settings you change. Please see the corresponding section of the readme or this page for further info. https://github.com/sebanc/brunch/wiki/CPUs-&-Recoveries

**Comment by NAS8910** [comment]
Oh okay that the reason. One last question Can i install neverware's version of ChromeOS or not. If not which OS should i opt then?
Thank you for your responses.

**Comment by WesBosch** [comment]
Neverware is also dropping support for Core 2 Duo devices soon. I'd honestly suggest updating, a 12+ year old cpu is going to lose support from a lot of distros.

There are some lightweight Linux distros you could try, but there are so many I couldn't suggest just one.

**Comment by NAS8910** [comment]
Thank you so much to all.
