### ISSUE TITLE
Intel Baytrail tablet - Android apps silent crash

### ISSUE THREAD

**Issue by clacalderonc** [sebanc/brunch#120]
Hello:

First, thanks for this  proyect. I was trying to revive my old lenovo miix 2  tablet (Baytrail cpu, atom z3740, brcm wifi adapter), i  tested with the suggested images, both (sammus and rammus) with stable and testing brunch releases without luck, installation ok from live usb (linux mint), but when it ends and then I reboot, the first boot attempt finish,It shows chromeos welcome screen, then it bootloops.

So, short story, i tried a diferent recovery, Octopus 80 release, and It worked , so now i'm trying to fix some issues to make it usable. (didn't really know why)

Wifi is working, take some time to connect at first, i guess could be a driver related issue.

Chrome video playback from youtube, netflix is working ok no issues detected. Installed some lighweight games like geometry dash, codycross, working ok (maybe a bit laggy sometimes). Tried other more "heavy" games like clashroyal, but it silent close after trying to open, can i see any log at OS level to get why it crash?

At least about://gpu shows 3d acceleration

Other stuff like front and back camera doesn't work, screen bright adjustment is working, would be nice to have some kind of auto brightness feature using the embedded light sensor.

Autorotation works but only when enable tablet mod, the rotate toggle switch from menu disappear on desktop mode, so, i switch from one to the other mode with CTRL+ALT+SHIFT + T for now.

So, could be posible to test and apply some of the workarrounds related to baytrails devices at os level?, i mean like enabling or disabling gpu features like the suggested on archlinux documentation for ex:

https://wiki.archlinux.org/index.php/intel_graphics#Troubleshooting

Regards!
Claudio.

**Comment by sebanc** [comment]
Hi,

> Hello:
> 
> First, thanks for this proyect. I was trying to revive my old lenovo miix 2 tablet (Baytrail cpu, atom z3740, brcm wifi adapter), i tested with the suggested images, both (sammus and rammus) with stable and testing brunch releases without luck, installation ok from live usb (linux mint), but when it ends and then I reboot, the first boot attempt finish,It shows chromeos welcome screen, then it bootloops.
> 
> So, short story, i tried a diferent recovery, Octopus 80 release, and It worked , so now i'm trying to fix some issues to make it usable. (didn't really know why)
> 

It's nice that you found a way to install it. I have no idea why octopus would work and not rammus but I will look into it.

> Wifi is working, take some time to connect at first, i guess could be a driver related issue.
> 
> Chrome video playback from youtube, netflix is working ok no issues detected. Installed some lighweight games like geometry dash, codycross, working ok (maybe a bit laggy sometimes). Tried other more "heavy" games like clashroyal, but it silent close after trying to open, can i see any log at OS level to get why it crash?

You can try to use adb to see the debug log but not all android apps work on chromebook and I would say clashroyal is one of them.

> 
> At least about://gpu shows 3d acceleration
> 
> Other stuff like front and back camera doesn't work, screen bright adjustment is working, would be nice to have some kind of auto brightness feature using the embedded light sensor.

The miix2 cameras are not supported by the linux kernel and are not usb so there is no chance it will work on chromeos.

For the auto brightness, you can add "options=advanced_als" to the kernel command line as mentioned in the main page.

> 
> Autorotation works but only when enable tablet mod, the rotate toggle switch from menu disappear on desktop mode, so, i switch from one to the other mode with CTRL+ALT+SHIFT + T for now.

Rotation working only in tablet mode is a standard chromeos behavior.

Tablet mode is poorly supported by the linux kernel, unless you can point a specific kernel patch for tablet mode CTRL+ALT+T is the way to go.

> 
> So, could be posible to test and apply some of the workarrounds related to baytrails devices at os level?, i mean like enabling or disabling gpu features like the suggested on archlinux documentation for ex:
> 
> https://wiki.archlinux.org/index.php/intel_graphics#Troubleshooting

The standard linux kernel configuration is the most stable so I will not apply tweaks but you can directly apply them to chromeos if you want.

> 
> Regards!
> Claudio.
