### ISSUE TITLE
risks of running on non-certified hardware?

### ISSUE THREAD

**Issue by RJVB** [sebanc/brunch#1202]
Hi,

I found this interesting project via https://beebom.com/how-install-chrome-os-on-pc/ . The author suggests to use a secondary gmail account to set up the system after installing when not running on hardware that has been certified by Google.

Is there any substance to the implied risk that your google account might be suspended for being used on an "illegal" ChromeOS install?

**Comment by khanhtranngoccva** [comment]
probably not. Many developers and power users use custom ROMs all the time. You don't really need to worry until you put devices for sale.

**Comment by RJVB** [comment]
Thanks, that's what I guessed (but one never knows if one is paranoid enough ;) )
