### ISSUE TITLE
Wrong EFI Loader Signature

### ISSUE THREAD

**Issue by jun447** [sebanc/brunch#1209]
I have dual core processor with **lagecy BIOS** latest Brunch , Rammus 87 recovery image but when i boot from Chrome OS in boot menu it asks **wrong efi loader** stuck at **Booting The Kernal**
![image](https://user-images.githubusercontent.com/72307789/130332210-55dbec02-a838-476e-ab84-663e0865f9ff.png)
*  then it starts  **boot looping**  in every loop it stuck at **Boting the kernal**

**Comment by lentas1** [comment]
same

**Comment by githubpub900** [comment]
you need mbr patch
