### ISSUE TITLE
Surface Pro 7 

### ISSUE THREAD

**Issue by LFmove** [sebanc/brunch#123]
Trying ti install on dualboot (from Windows) everything ok until usbdrive boot.

When chromeos install on the USB It ever stops at [636.710127] input: HDA Intel PCH HDMI/DP,pcm=3 as /devices/pci0000:00:1f.3/sound/card0/input13

I tryed more times, from USB.

One time i tryed ti install on a microSD, but doesn't work.

 (Lasted brunch r81 10/05/2020) (rammus recovery)
Surface pro 7 with Secure Boot disabled.

**Comment by LFmove** [comment]
![IMG_20200510_235204](https://user-images.githubusercontent.com/65065497/81511375-4fc50980-9319-11ea-9971-f72ff4c88207.jpg)

**Comment by sebanc** [comment]
Hi,

Your issue appears to be the exact same as #18. For now, I have just posted instructions on how to use kitakar's kernel 5.4 with brunch and will also try to fix the issue with brunch kernel 4.19.

I am closing this issue but don't hesitate to participate to the discussions in issue #18.
