### ISSUE TITLE
Changing Boot Animation

### ISSUE THREAD

**Issue by dtadptvl** [sebanc/brunch#1241]
Can I change the boot animation from showing "Loading Brunch Framework" to something more attractive? I'm a noob please send help

**Comment by GerardoHD** [comment]
[Here are instructions on how to view the available bootsplash in current release ](https://github.com/sebanc/brunch#bootsplashes)

You'll just have to change the "brunch_bootsplash=default" option when booting grub, later;
Press CTRL+ALT+T and type "shell" at the invite, and execute
sudo edit-brunch-config
Then change "brunch_bootsplash=default"  to whatever bootsplash you liked.
Be careful or you could break your system

Hope it helps you

**Comment by dtadptvl** [comment]
![image](https://user-images.githubusercontent.com/51063200/135735547-9366b222-c3b5-44a3-a56b-a9bfe6e24ed5.png)
I followed your instruction and encounterd this error

**Comment by dtadptvl** [comment]
Never mind I got it resolved. Thank you
