### ISSUE TITLE
Touch Panel Behavior on Surface Pro6

### ISSUE THREAD

**Issue by KohnoseLami** [sebanc/brunch#1249]
I tried namis and recommended rammus, which are similar to the i5 model of Surface Pro 6, but the touch panel doesn't recognize them (touch doesn't work).
Does anyone know how to make it work perfectly?

**Comment by KohnoseLami** [comment]
Now that I have enabled the ipts option, I can use the touch screen without any problems.
I have confirmed that it works perfectly on SurfacePro6.
However, it is a bit slow.

**Comment by MrMEEE** [comment]
@KohnoseLami Did you use the "edit-grub-config"?? did you enable anything other than ipts?.. which kernel did you choose??
