### ISSUE TITLE
Intel Bluetooth driver fault in kernel 5.10

### ISSUE THREAD

**Issue by librehat** [sebanc/brunch#1277]
Device: Samsung Galaxy Book Pro 360
Kernel 5.10
Brunch 93

Bluetooth shown disabled on Chrome OS and not able to switch on.

Error message from dmesg:

```
[  267.654561] Bluetooth: hci0: Reading Intel version information failed (-22)
[  267.654564] Bluetooth: hci0: Intel Read version failed (-22)
[  267.654580] Bluetooth: hci0: Intel reset sent to retry FW download
```

**Comment by sebanc** [comment]
Try kernel-macbook maybe

**Comment by dorp007** [comment]
Ok.

**Comment by librehat** [comment]
I tried kernel-macbook and it wouldn't even boot (it doesn't find my USB HDD drive).

I also have similar issues to #1239 where lsusb shows my fingerprint sensor but there is no fingerprint option in the settings. 

The fingerprint sensor says LighTuning Technology Inc EgisTec EH57E

**Comment by dorp007** [comment]
chromium-review.googlesource.com

**Comment by librehat** [comment]
Don't know what's your point. It's more likely the issue with the kernel/driver.
Bluetooth works out of box with OpenSUSE 15.3's Linux 5.3 kernel.

**Comment by sebanc** [comment]
Try kernel-macbook from this build:
https://github.com/sebanc/brunch-unstable/releases/tag/r94-unstable-20211103

**Comment by librehat** [comment]
> Try kernel-macbook from this build:
> https://github.com/sebanc/brunch-unstable/releases/tag/r94-unstable-20211103

Bluetooth works with this kernel build! Thank you so much for the timely fix

**Comment by librehat** [comment]
I just tried the latest Chrome OS 101 volteer + Kernel 5.15, and it works beautifully now! Thanks for the good work
