### ISSUE TITLE
Crostini does not work: Error starting penguin container: 5 Launching vmshell failed: Error starting crostini for terminal: 5

### ISSUE THREAD

**Issue by jjdct** [sebanc/brunch#1280]
I wanted to use Linux (Crostini) in Brunch, however this will not start, since I read that there is a detail with the microcodes from Chrome OS 91, and I don't know if there is any way to run Crostini with an Intel pentium 2020M from 2012, (which has Intel's Virtualization technology), if there is any way to modify the Grub or something like that to start Crostini, I will thank you in advance.

**Comment by sebanc** [comment]
Maybe try disabling crostini gpu acceleration in chrome://flags

**Comment by dorp007** [comment]
Hello Sebanc,

I hope you are doing well! May I please have a list of avelible crosh terminal commands and the man pages?

Thank you in advance.

Sincerely,

**Comment by jjdct** [comment]
It was fixed with a Chrome OS update.

**Comment by keaunuboskoyous70-cyber** [comment]
[====       ] Starting the container manager Error starting crostini for terminal: 51 (STAR
