### ISSUE TITLE
how can I turn on ssh into the chromebook running brunch?

### ISSUE THREAD

**Issue by cmsanta** [sebanc/brunch#1282]
Hi: 

How can I enable ssh login into my chromebook running brunch from another computer running Linux? For example, I am not interested in running ssh from Crostini, I just want to able to ssh from the cros shell environment into another computer running linux.

The cros_debug is already included in the kernel command line and also I am able to enable, and the wiki doesn't mention any of this.

As a pointer, I am able to ssh from within brunch to the outside world but not the other way around, why?

**Comment by cmsanta** [comment]
Issue is now resolved after trying option #3 from here: https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:src/third_party/chromiumos-overlay/chromeos-base/chromeos-sshd-init/files/openssh-server.conf.README

**Comment by dorp007** [comment]
https://ci.chromium.org/p/chromium/g/main/console
