### ISSUE TITLE
chrome OS doesnt boot up

### ISSUE THREAD

**Issue by prango71** [sebanc/brunch#1284]
CPU: AMD A8-7600
Recovery Image: grunt
Boot from: usb
Whenever i boot up my usb, it automatically restarts after a few seconds.
In debugging the last before it reboots is something like this:
Kernel Offset: 0x2e8000000 from 0xffffffff81000000(relocation range: 0xffffffff80......

My screen is too small for the whole error i suppose

Any help?

**Comment by Mihkuno** [comment]
Im running on AMD A8-7600 as well... and it bootloops
