### ISSUE TITLE
error message when installing on harddrive

### ISSUE THREAD

**Issue by au79912** [sebanc/brunch#129]
i ran chrome os on a usb stick but when i try to install it, it give me these messages 
any idea as to how i can fix them?
![image](https://user-images.githubusercontent.com/65231120/81700169-c1b86280-9481-11ea-9e88-b90e904c18c4.jpg)

**Comment by sebanc** [comment]
Hi,

Why did you use /dev/sda4 as destination ?

Either you want:
- to install fully on this drive (erasing all data) in which case you should use /dev/sda.
or
- to create an image on the partition /dev/sda4 in which case you have to mount the partition and the destination should be a filename (for example chromeos.img) on the mounted partition.

**Comment by au79912** [comment]
> Hi,
> 
> Why did you use /dev/sda4 as destination ?
> 
> Either you want:
> 
> * to install fully on the drive /dev/sda (erasing all data) in which case you should use /dev/sda.
>   or
> * to create an image on the partition /dev/sda4 in which case you have to mount the partition and the destination should be a filename (for example chromeos.img) on the mounted partition.

thanks, I was a bit confused
