### ISSUE TITLE
Cannot boot into new Chrome OS installation

### ISSUE THREAD

**Issue by akashdur** [sebanc/brunch#131]
I followed the guide and installed Chrome OS on one of my partitions.Now clicking chrome os in the grub menu does nothing,just shows the background image(which grub uses).
Note: Installation was using done using already installed Debian system.
Tried both NTFS and ext4 file systems,didn't work

**Comment by sebanc** [comment]
Hi,

How did you create the grub config ?

**Comment by akashdur** [comment]
Hello,
I used grub-customizer to create new menu entry using the config appeared at the end of installation.
Thanks

**Comment by sebanc** [comment]
Some distro appears to have a grub efi which is not compatible with brunch. In that case, the first thing to try is to replace your distro's grubx64.efi (usually located at /boot/efi/EFI/\<distro name>/) by the brunch grubx64.efi located in /efi/boot on partition 12.

**Comment by akashdur** [comment]
that worked.
Thanks
