### ISSUE TITLE
Jumbled graphics

### ISSUE THREAD

**Issue by clandestinz** [sebanc/brunch#134]
Booting from usb shows a screen with jumbled graphics. It would look like the setup process is working as I can figure out the loading bar somehow.

**Comment by sebanc** [comment]
Hi, 

Usually it is a bios setup issue, most users fix this by going to the bios and setting "Advanced > boot options > boot mode > UEFI Hybrid (with CSM)."

**Comment by clandestinz** [comment]
alright thanks. keep up the good work
