### ISSUE TITLE
Meet fault when preparing for the USB installation

### ISSUE THREAD

**Issue by zx5641** [sebanc/brunch#1345]
Hi there,
I'm following the guide on preparing for the USB installation, and have an issue at step 8 "Install Brunch".
[https://github.com/sebanc/brunch/blob/master/install-with-windows.md#install-brunch](url)
My environment is WSL2 with ubuntu 20.04, have followed all previous steps strictly.

But, when I typed 
`sudo bash chromeos-install.sh -src chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin -dst chromeos.img` 
it said 
`The ChromeOS disk image has to be installed outside of the WSL VM, please specify a path such as /mnt/<drive letter>/...`
![image](https://user-images.githubusercontent.com/32981838/146732583-15eab9c8-429c-4713-8cc6-10d152ed111b.jpg)

I couldn't find any useful information about this issue, can anyone help? Many Thanks!!!!

**Comment by ijinesh** [comment]
You can try putting in location where chromeos.img can be saved. For eg. \mnt\c\users\xavier\downloads\chromeos.img

**Comment by zx5641** [comment]
> You can try putting in location where chromeos.img can be saved. For eg. \mnt\c\users\xavier\downloads\chromeos.img

Hi ijinesh, thanks for your replying!

Do you mean that I have to change the command to, just like,
`sudo bash chromeos-install.sh -src chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin -dst \mnt\E\Downloads\chromeos.img`

I tried, but still failed, the same error prompt as before. Is my command wrong? So sorry that I am not very familiar with Linux commands.

**Comment by ijinesh** [comment]
> > You can try putting in location where chromeos.img can be saved. For eg. \mnt\c\users\xavier\downloads\chromeos.img
> 
> Hi ijinesh, thanks for your replying!
> 
> Do you mean that I have to change the command to, just like, `sudo bash chromeos-install.sh -src chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin -dst \mnt\E\Downloads\chromeos.img`
> 
> I tried, but still failed, the same error prompt as before. Is my command wrong? So sorry that I am not very familiar with Linux commands.
> 
> ![faults](https://user-images.githubusercontent.com/32981838/146907550-f594f66a-1688-47ec-baea-f56a189cd965.jpg)

Is location correct? Normally, it is \mnt\e\users\xxxx\downloads\
Is your download folder in the E:\ root?

I had the same error but putting the correct location for ChromeOS.img helped. Actuall, you can put any valid location and not necessarily to the Download folder. For eg, you can put in \mnt\E\

**Comment by zx5641** [comment]
> > > You can try putting in location where chromeos.img can be saved. For eg. \mnt\c\users\xavier\downloads\chromeos.img
> > 
> > 
> > Hi ijinesh, thanks for your replying!
> > Do you mean that I have to change the command to, just like, `sudo bash chromeos-install.sh -src chromeos_14150.74.0_rammus_recovery_stable-channel_mp-v2.bin -dst \mnt\E\Downloads\chromeos.img`
> > I tried, but still failed, the same error prompt as before. Is my command wrong? So sorry that I am not very familiar with Linux commands.
> > ![faults](https://user-images.githubusercontent.com/32981838/146907550-f594f66a-1688-47ec-baea-f56a189cd965.jpg)
> 
> Is location correct? Normally, it is \mnt\e\users\xxxx\downloads Is your download folder in the E:\ root?
> 
> I had the same error but putting the correct location for ChromeOS.img helped. Actuall, you can put any valid location and not necessarily to the Download folder. For eg, you can put in \mnt\E\

You know what? I tried and found that it is not acceptable to use any location but the root of the partition.
I tried to use location as /mnt/e/ChromeOS.img and it works
Thanks, again!
