### ISSUE TITLE
Updating to CrOS r96 or any CrOS Build powerwash my install

### ISSUE THREAD

**Issue by Lainasan** [sebanc/brunch#1356]
Hello, I read the changelog on brunch stable r94 update that after updating to CrOS r96 or up it will powerwash the install.

But, does this issue will get fixed if i update to the unstable brunch build (brunch r96)?

Like, after updating to brunch r96 does updating to the next stable or any other channel release of CrOS will not get powerwash?

**Comment by noka0206** [comment]
No. just use with r94.

**Comment by sebanc** [comment]
Unfortunately, for now, updating to brunch r96 does not fix the ChromeOS r96 powerwash issue and it is unlikely that I will be able to prevent this at all.

I am still looking into it but without results for now.

**Comment by Lainasan** [comment]
Ok thanks for the answer, I will look forward to it if this get fix.

Thanks again!
