### ISSUE TITLE
Graphics Issues - Surface Pro 2

### ISSUE THREAD

**Issue by ZProLegend007** [sebanc/brunch#1370]
### Discussed in https://github.com/sebanc/brunch/discussions/1369

<div type='discussions-op-text'>

<sup>Originally posted by **ZProLegend007** January  8, 2022</sup>
Hi There!
I'm relatively new to changing operating systems on different computers but i'm getting the hang of things. I just installed Chrome os on my Surface pro 2 and i'm having a few graphical issues, I've been using asphalt 9 to test my fixes to little or no avail. I'm not sure if it is officially supported on this laptop but if there is any way to fix this it would be greatly appreciated. I will attach some images below to compare what this loading symbol does and should look like.

![image](https://user-images.githubusercontent.com/97338659/148640982-3f60d410-a7e5-4268-ba0e-9a17c55e4f78.png)
![image](https://user-images.githubusercontent.com/97338659/148640985-8f77e2a8-bc61-45f0-9de8-2b167b60c9a6.png)
</div>

**Comment by ZProLegend007** [comment]
I have also realised that the GPU Drive isn't taking up any memory, could that be related?

**Comment by tejasraman** [comment]
Wait. How did you find that? htop? Chrome Diagnostics?

**Comment by tejasraman** [comment]
Also try kernel 5.10, maybe there was the old problem of some Intel GPUs being borderline unusable under 5.4/5.5 _due to driver issues_?

**Comment by ZProLegend007** [comment]
I've tried all the kernels, I used the ash-debug-shortcuts to view my memory usage (Ctrl+Shift+Alt+G). I have switched back to Windows,
