### ISSUE TITLE
Google play apps and services not working 

### ISSUE THREAD

**Issue by opkpEh** [sebanc/brunch#1371]
I've installed and reinstalled chrome os many times, when i installed chrome os for the first time "google play apps and services" were working, but after that they haven't. I've tried everything on internet , please help.

My laptop : HP Pavilion Gaming Ryzen 5 Quad Core 3550H
gpu : nvidia 1650
cpu : ryzen 3550H

chrome book version: 96.0.4664.111 
brunch version: r94 stable 20211121 
 
![Screenshot 2022-01-09 11 48 23 AM](https://user-images.githubusercontent.com/56930383/148671567-29a20d6a-b337-4c4a-80f4-3f2dfa812b34.png)
The error I'm getting. 

If there's any other info that you need feel free to reach out to me.

thanks for reading.

Just in case:
My email: harshpandeykp20@gmail.com

**Comment by ZProLegend007** [comment]
Which chrome os build are you using? E.g rammus or octopus

**Comment by ZProLegend007** [comment]
This happened to me briefly after a brunch update, maybe move to the unstable channel for brunch?

**Comment by opkpEh** [comment]
thanks for reaching out , sorry I wasn't able to reply quicker, i'm on
brunch stable (latest one)

**Comment by opkpEh** [comment]
I was ble to fix this btw I just spammed re-try button for like 30 times
and it worked idk why but it did
