### ISSUE TITLE
No sound card on Atom Z3795 Baytrail

### ISSUE THREAD

**Issue by the-leaf** [sebanc/brunch#1399]
NEC Versa pro VT-J
CPU : Atom Z3795 Baytrail

Sound And Bluetooth not work
[dmesg_kernel_5.4.163.txt](https://github.com/sebanc/brunch/files/7965832/dmesg_kernel_5.4.163.txt)

**Comment by tejasraman** [comment]
Run `sudo lshw -c Sound` and tell me the output. Seeing lots of similar issues with Atoms recently, have not got responses from anyone I have asked to run the lshw command.

Tjis tells me what sound device you have

**Comment by tejasraman** [comment]
Run `sudo lshw -c Sound` in shell(get to by pressing Ctrl+Alt+T and typing shell) and tell me the output. Seeing lots of similar issues with Atoms recently, have not got responses from anyone I have asked to run the lshw command.

This command tells me what sound device you have anyone I have asked to run the lshw command.

Tjis tells me what sound device you have

**Comment by the-leaf** [comment]
> Run `sudo lshw -c Sound` in shell(get to by pressing Ctrl+Alt+T and typing shell) and tell me the output. Seeing lots of similar issues with Atoms recently, have not got responses from anyone I have asked to run the lshw command.
> 
> This command tells me what sound device you have anyone I have asked to run the lshw command.
> 
> Tjis tells me what sound device you have

![Screenshot 2022-02-06 13 40 55](https://user-images.githubusercontent.com/20531916/152670398-35c68f3a-d5de-40e3-aa32-04c5d63a8307.png)

**Comment by tejasraman** [comment]
Try this:``  lspci -v | grep Audio ``

**Comment by the-leaf** [comment]
> Try this:` lspci -v | grep Audio`

![Screenshot 2022-02-08 08 13 03](https://user-images.githubusercontent.com/20531916/152899206-6d804384-b558-484f-9704-7c50cfbc485a.png)
![Screenshot 2022-02-08 08 13 17](https://user-images.githubusercontent.com/20531916/152899220-ef4bd88d-b0f7-419f-b393-a2449f5f4ad2.png)

**Comment by tejasraman** [comment]
Do you have a Thinkpad tablet?
Try adding broadcom_wl to the grub config for Bluetooth.
Try using kernel 5.10 in grub config for audio.

https://github.com/sebanc/brunch/blob/master/troubleshooting-and-faqs.md

**Comment by tejasraman** [comment]
Sorry did not read the first post
The NEC tablet is same board as a Thinkpad Model 221b(10 203C)

**Comment by the-leaf** [comment]
> Do you have a Thinkpad tablet? Try adding broadcom_wl to the grub config for Bluetooth. Try using kernel 5.10 in grub config for audio. https://github.com/sebanc/brunch/blob/master/troubleshooting-and-faqs.md
> […](#)
> On Feb 7, 2022, 6:14 PM -0700, the-leaf ***@***.***>, wrote: > Try this: lspci -v | grep Audio — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

grub config : broadcom_wl   Bluetooth not work
kernel 5.10  = No soundcards

**Comment by tejasraman** [comment]
Did you do it the way the link told you to?

**Comment by truongtam-fudosan** [comment]
@the-leaf change to kernel 4.19

**Comment by the-leaf** [comment]
> Did you do it the way the link told you to?

Kernel 5.10 
![Screenshot 2022-02-10 10 06 13](https://user-images.githubusercontent.com/20531916/153330192-e31ec8b9-fabb-42dd-b422-b038cd806ddd.png)
![Screenshot 2022-02-10 10 12 14](https://user-images.githubusercontent.com/20531916/153330209-946f8e5c-715b-4824-9ae0-8b1d4fc09421.png)

**Comment by tejasraman** [comment]
You have RealTek audio. Try the disable_intel_hda option.

**Comment by the-leaf** [comment]
> You have RealTek audio. Try the disable_intel_hda option.
> […](#)
> On Feb 9, 2022, 8:14 PM -0700, the-leaf ***@***.***>, wrote: > Did you do it the way the link told you to? Kernel 5.10 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

sound not work :(
![Screenshot 2022-02-10 19 57 49](https://user-images.githubusercontent.com/20531916/153413306-c467edad-89c6-4aeb-8ca6-5d4f7903efcb.png)

**Comment by tejasraman** [comment]
This seems to be an error where the Thinkpad board like yours has an ACPI error and declares the sound card wrong. There should be a patch, but I cannot help anymore.

**Comment by the-leaf** [comment]
> This seems to be an error where the Thinkpad board like yours has an ACPI error and declares the sound card wrong. There should be a patch, but I cannot help anymore.

thk. I fixed it.
sound and bluetooth this work 😀😀
![Screenshot 2022-02-15 14 08 09](https://user-images.githubusercontent.com/20531916/154010607-5f70a117-81d1-41dd-ace7-168e38cc2257.png)

**Comment by tejasraman** [comment]
How?
I did hear of some patches, but…

**Comment by the-leaf** [comment]
NEC Versa pro VT-J  Driver this same Lenovo Thinkpad 10 Tablet.

Fix In kernels/5.X/sound/soc/intel/common/soc-acpi-intel-byt-match.c   And kernels/5.4/sound/soc/codecs/rt5670.c

search ThinkPad 10

In  :  soc-acpi-intel-byt-match.c add

{
		.callback = byt_thinkpad10_quirk_cb,
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "NEC"),
			DMI_MATCH(DMI_PRODUCT_NAME, "PC-VK24VTAMJ"),
		},
	},

in rt5670.c add

{
		.callback = rt5670_quirk_cb,
		.ident = "Lenovo Thinkpad Tablet 10",
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "NEC"),
			DMI_MATCH(DMI_PRODUCT_NAME, "PC-VK24VTAMJ"),
		},
		.driver_data = (unsigned long *)(RT5670_DMIC_EN |
						 RT5670_DMIC1_IN2P |
						 RT5670_DEV_GPIO |
						 RT5670_JD_MODE1),
	},

**Comment by tejasraman** [comment]
Really? No default patching like Linux? Looks like NEC messed up ACPI just as badly as Lenovo did.

**Comment by nh0kbin2001** [comment]
> .callback = byt_thinkpad10_quirk_cb,
> .matches = {
> DMI_MATCH(DMI_SYS_VENDOR, "NEC"),
> DMI_MATCH(DMI_PRODUCT_NAME, "PC-VK24VTAMJ")

hello, can i ask  you, how to edit 2 file?? where is these??

**Comment by tejasraman** [comment]
@the-leaf built this from source. @the-leaf someone needs to make a PR for this issue. 

You need a brunch build with the patches @truongtam-fudosan

**Comment by nh0kbin2001** [comment]
> patches

i.e. I have to recompile a brunch for myself.  This seems too complicated for a newbie like me.  But anyway, have to try it once.  This problem seems to originate from the linux kernel.  I found my problem the same way the other guy found it.  My machine Nec pc-vk12 it corresponds to lenovo thinkpad helix 2 https://patchwork.kernel.org/project/alsa-devel/patch/E1dAAy5-002Sr-2s@finisterre/

**Comment by nh0kbin2001** [comment]
> @the-leaf built this from source. @the-leaf someone needs to make a PR for this issue.
> 
> You need a brunch build with the patches @nh0kbin2001

i.e. I have to recompile a brunch for myself. This seems too complicated for a newbie like me. But anyway, have to try it once. This problem seems to originate from the linux kernel. I found my problem the same way the other guy found it. My machine Nec pc-vk12 it corresponds to lenovo thinkpad helix 2 https://patchwork.kernel.org/project/alsa-devel/patch/E1dAAy5-002Sr-2s@finisterre/

**Comment by the-leaf** [comment]
@nh0kbin2001 hi bro You can check it out at my brunch.
brunch https://github.com/the-leaf/brunch/commits/r103-VersaPro

**Comment by tejasraman** [comment]
@the-leaf please submit a PR! This fix would be appreciated by many :⁠-⁠)

**Comment by the-leaf** [comment]
I've created a new patch file for kernel 5.10 and a new build brunch for my own use.

Example my patch file "NEC_rt5670.patch"
`--- a/sound/soc/codecs/rt5670.c
+++ b/sound/soc/codecs/rt5670.c
@@ -2863,6 +2863,18 @@
 						 RT5670_GPIO1_IS_IRQ |
 						 RT5670_JD_MODE1),
 	},
+	{
+		.callback = rt5670_quirk_cb,
+		.ident = "NEC Versapro VT-J",
+		.matches = {
+			DMI_MATCH(DMI_SYS_VENDOR, "NEC"),
+			DMI_MATCH(DMI_PRODUCT_FAMILY, "LaVie/VersaPro"),
+		},
+		.driver_data = (unsigned long *)(RT5670_DMIC_EN |
+						 RT5670_DMIC1_IN2P |
+						 RT5670_GPIO1_IS_IRQ |
+						 RT5670_JD_MODE1),
+	},
 	{
 		.callback = rt5670_quirk_cb,
		.ident = "Lenovo Thinkpad Tablet 10",
--- a/sound/soc/intel/common/soc-acpi-intel-byt-match.c
+++ b/sound/soc/intel/common/soc-acpi-intel-byt-match.c
@@ -44,6 +44,13 @@
 			DMI_MATCH(DMI_PRODUCT_VERSION, "ThinkPad 8"),
 		},
 	},
+	{
+		.callback = byt_thinkpad10_quirk_cb,
+		.matches = {
+			DMI_MATCH(DMI_SYS_VENDOR, "NEC"),
+			DMI_MATCH(DMI_PRODUCT_FAMILY, "LaVie/VersaPro"),
+		},
+	},
 	{
 		.callback = byt_thinkpad10_quirk_cb,
		.matches = {`

**Comment by tejasraman** [comment]
@the-leaf Ok, but can you add the patch file to all the kernels before submitting a PR?
Making it 5.10 specific could cause confusion and, as this applies to many devices (the thinkpad and others like your NEC) having it in more kernels will save people a great deal of trouble.

**Comment by the-leaf** [comment]
> @the-leaf Ok, but can you add the patch file to all the kernels before submitting a PR? Making it 5.10 specific could cause confusion and, as this applies to many devices (the thinkpad and others like your NEC) having it in more kernels will save people a great deal of trouble.

Yes, I need to try and fix it first.
when i finished testing i will update

**Comment by tomekb530** [comment]
It'll be great to add it to 6.1 kernel because in older kernels there is problem with keyboard
