### ISSUE TITLE
touchpad multifinger gestures not working

### ISSUE THREAD

**Issue by au79912** [sebanc/brunch#140]
Does this support focaltech devices because non of the multi finger gestures are working. Also in the settings/device its showing mouse settings instead of touchpad
any idea how to get them to work?

**Comment by sebanc** [comment]
Hi,

Could you attach a dmesg to this issue ?

run "dmesg > ~/Downloads/dmesg.txt in crosh shell and attach dmesg.txt to this issue

**Comment by sebanc** [comment]
No news for a while on this issue so I will close it, don't hesitate to re-open it if needed
