### ISSUE TITLE
wifi RTL8821CE working BUT cannot connect

### ISSUE THREAD

**Issue by spvmsolo** [sebanc/brunch#1402]
As the title reads, it's on my laptop, I managed to make the wifi work with networks that don't have security. But my main 5g wifi has WPA2 and it just won't connect. My router also has 2.4 but no dice. I made a shared wifi with my android and removed the security and it did connect, it works just fine but I cannot connect to anything else. I tried adding security to the android wifi but again it didn't connect.
It tries for some 15 seconds and it gives me a generic "unknown error: could not connect" message.
Windows and Kubuntu work just fine so I don't think is the antenna or anything.
Bluetooth says it's on but I have not tried to connect it with anything yet so it might have the same problem.

---------
chromeOS-volteer 94 on intel i3-10110U 11th gen 
brunch r97
hp laptop 15-dy20511a

**Comment by tejasraman** [comment]
1 - Are you using 8821CE option in grub config?
2 - Brunch R97 - ChromeOS update to r98

**Comment by spvmsolo** [comment]
1 - I added "options=rtl8821ce,rtbth" right after cros_debug, with a space on either side, editing grub on linux (i assume i did that right), no dice.
2 - I updated to 98.0.4758.91 using the check update button on settings, no dice.

The notification says "unknown error: not-associated" and the password window says in red "There was an error while the network was being configurated"
I tried using kernel 5.15 on first boot but it crashes right after the chrome logo shows up. I also tried not using cros_debug (on 5.10) on a first boot as well but it crashes after login.

A picture of linux nano grub edit https://imgur.com/a/A846WVB just in case

**Comment by tejasraman** [comment]
FYI, you need to use the enable_updates option to get updates in Settings.
Try Brunch Unstable

**Comment by spvmsolo** [comment]
I did use enable updates, that's how I updated it. I enabled it on the "chromeOS settings" thing on boot.
Will try unstable after work.

**Comment by spvmsolo** [comment]
Wait, where are the unstable ones?

**Comment by tejasraman** [comment]
Go to https://github.com/sebanc/brunch-unstable and download and install Brunch from this repository

or enable the pwa option in grub, install the PWA, and update to Brunch-unstable from there

**Comment by spvmsolo** [comment]
updated brunch to r97 unstable 2022 0205 still no luck

**Comment by tejasraman** [comment]
Try to remove the rat that in grub. Use the ChromeOS settings gs entry to edit, not Linux.

**Comment by spvmsolo** [comment]
> Try to remove the rat that in grub. Use the ChromeOS settings gs entry to edit, not Linux.

Not sure why this message didn't appear here (or why I can't see it?) and I'm also not 100% sure what is means but I did edited grub using chrome with the "sudo edit-grub-config" entry. This is how I managed to make the wifi work in the first place, but I still can't connect with password protected wifis. It just ain't having it.

**Comment by tejasraman** [comment]
Auto correct meant rtbth

**Comment by tejasraman** [comment]
You do not need the rtbth option. Your 8821ce does not use that chipset.

**Comment by tejasraman** [comment]
That rat was autocorrect, not grub :) autocorrect is a rat

**Comment by spvmsolo** [comment]
In other news, while looking at the forum for answers, apparently you are supposed to have multiple partitions? I only have one with a "chromeos.img" and a "chromeos.img.grub.txt" file on it. I used the dual boot guide on here to do it and while installing I did saw a couple of partitions being created, and then nothing.
A screenshot, also I did recorded a video of my woe
https://youtu.be/0q9DnzV4Kyg
![Captura de pantalla (89)_LI](https://user-images.githubusercontent.com/98722426/153476040-7b5e212f-1e63-4139-bf6a-ca8f83f800a3.jpg)

**Comment by tejasraman** [comment]
Yes - there should be 12 partitions(in my experience too)

**Comment by tejasraman** [comment]
Plus, Chrome OS should not be on an NTFS partition.

**Comment by tejasraman** [comment]
PLEASE do NOT use someone else’s GUI installer! Please use only the ChromeOS install instructions on Brunch website.

**Comment by spvmsolo** [comment]
I DID do that, sorry if I was not clear

**Comment by sebanc** [comment]
The rtl8821ce module is an unofficial one which works in many cases but it is probably not 100% compatible, there is not much I can do about that.

However I wonder about the "--part-uuid" error message, which grub do you use ? Is it grub2win ?

**Comment by sebanc** [comment]
Well, just in case, could you post the output of "sudo lspci" from crosh shell ?

Also, do not enable "rtbth" option

**Comment by spvmsolo** [comment]
I... did not use any grub? Or I used the default one? I followed the instructions in here to Dual Boot with Linux, they're both installed on a external SDD. Linux is Kubuntu 21.10
![photo_2022-02-12_17-02-16](https://user-images.githubusercontent.com/98722426/153726757-bcd5c54d-1cb3-49d3-a1fa-54cfd700b141.jpg)
![Screenshot 2022-02-12 4 54 01 PM](https://user-images.githubusercontent.com/98722426/153726760-a926fd9f-312d-4645-9430-7f00635bbc35.png)

**Comment by spvmsolo** [comment]
Uh... how do I do that again? Or am I supposed to be seeing something I don't?
![IMG_0072](https://user-images.githubusercontent.com/98722426/153731831-ac4335e5-6e5c-46cd-833e-8ddb446ae9a6.jpeg)

Ubuntu brings me to kubuntu's grub
Windows brings me to normal boot
Generic external (where kubuntu and chros are) reboots the laptop without any prompts 

Should I have the time tomorrow I will sacrifice Kubuntu and install ChrOS single boot.

**Comment by tejasraman** [comment]
Boot from Efi file

**Comment by spvmsolo** [comment]
Which one? there are two very long names:
The first one says:
+ ubuntu
- -  mmx64 --> shim uefi key manager
- -  shimx64  --> kubuntu
- -  grubx64  --> kubuntu

+ BOOT
- - mmx64  --> shim uefi key manager
- - fbx64  --> reboot
- - bootx64  --> reboot

The second one says:
- Microsoft
- Boot
- HP

**Comment by tejasraman** [comment]
In GRUb, highlight ChromeOS, press E, and add the settings there for a test boot. To add the changes permanently, download GRUB Configurator in Kubuntu and edit ChromeOS.

**Comment by tejasraman** [comment]
Guess? It didn’t work? Use GRUb configurator to change Kubuntu’s ChromeOS boot entry
I have an HP desktop with an 8821ce, should I test brunch and see if it is an issue with brunch? It is an M01-F0016

**Comment by sebanc** [comment]
It's a change in brunch unstable which caused your grub issue, you need to reinstall the stable brunch. Do you know which grub version is installed ?

I just noticed in your previous comments:
```
1 - I added "options=rtl8821ce,rtbth" right after cros_debug, with a space on either side, editing grub on linux (i assume i did that right), no dice.
```

This is not how it works anymore, please use the configuration menu.

**Comment by tejasraman** [comment]
I did the test on my desktop. I got the part-uuid error on unstable AND a boot loop(to add to the misery). Trying stable now, will get back

**Comment by tejasraman** [comment]
Hey! I just got brunch stable to boot(no errors). I needed kernel 5.10 to boot  on my PC, but it seems that the 8821ce driver works as expected. 

![Screenshot 2022-02-13 1 17 15 PM](https://user-images.githubusercontent.com/96961804/153773160-04621e68-c27d-4e82-98de-ded46367c48e.png)

**Comment by tejasraman** [comment]
although my PC's AMD, so things might be different. I used the settings menu to change, so idk if there is a differnece :)

**Comment by spvmsolo** [comment]
I'm so happy for you

Today's update:
1.- tejasraman says to edit grub and use the options line, sebanc says to not do that and use the configurations menu. Regardless I used both (independently and separately). Same as always: wifi works but it doesn't connect.
* For the record I did use the config the first time and this is how I got here. If I don't the wifi shows ON but the list is empty

2.- My wifi's name has special characters (í and ñ) so I thought it might have something to do with that. I used android share wifi and... it connected just fine, so it's not that.
* And as I mentioned before I can't use this 'cause android won't connect to wifi and share it at the same time. And I haven't found a jailbreak tweak for iOS 14 to do that with my ipad.
* On that note I found something weird. When I connect to share wifi it's fine, EVEN with the password. So it must be the router that's messing up, right? Well, my cousin was here today and it happens that he has a legit chromebook... and it works with my wifi, but my hackbook doesn't. So it's not that. (Lenovo Tab Ideapad duet)
* In any case I can't change the router settings because my isp is weird about it. (I can't even access the router with the usual address).

3.- I re-downloaded brunch stable and chros volteer recovery, just to be safe and I used ext4 again. It worked this time. But the wifi didn't. Same as always

I'm gonna be busy tomorrow so I might not have the chance but I'm gonna have to kill linux and try the single boot option.
Also, here's a long picture of the install, just in case https://imgur.com/a/A846WVB
Also also, quick question: can you install drivers using linux in chros or in the shell by any chance?

**Comment by tejasraman** [comment]
NO I used the config menu

**Comment by tejasraman** [comment]
Plus, trust sebanc, he is the dev of Brunch.

**Comment by tejasraman** [comment]
And also, I am using a tri-boot(PopOS, Arch Linux, and my new ChromeOS). Wi-Fi works fine

**Comment by tejasraman** [comment]
It worked with the Linux grub editor too though :)

**Comment by tejasraman** [comment]
![Screenshot 2022-02-13 8 52 05 PM](https://user-images.githubusercontent.com/96961804/153797309-d9a3b904-b77c-4a9f-8c7f-22a74f6640a3.png)
Updated to latest unstable, still works great

**Comment by spvmsolo** [comment]
Once more, I'm so happy for you
And I do appreciate all the help! XD

**Comment by tejasraman** [comment]
Thanks!

**Comment by spvmsolo** [comment]
I did the single boot. It didn't work. I'm out of ideas.
So that's the end of my story.

**Comment by tejasraman** [comment]
Replace the wifi card :)  8821ce seems to work for me, out of ideas.

**Comment by spvmsolo** [comment]
2 years and I tried again. Brunch r123 chros voxel v123 aaaand IT WORKS!
It's fixed! Up and running!
