### ISSUE TITLE
Play Store is not working!

### ISSUE THREAD

**Issue by Jaiendiran** [sebanc/brunch#1403]
I'm running chrome OS 97 from a pen drive. It feels laggy and also the play store is showing some error code: 8. Can anybody have the solution to fix it?
![Screenshot 2022-01-31 12 39 17 PM](https://user-images.githubusercontent.com/22840699/151752534-5457bdcd-8745-4d93-abf9-1a92e56c1dd2.png)Thanks in advance!

**Comment by ksoham622** [comment]
You need to install the chrome os on your disk. Pendrives have very slow read write speeds so the android container doesn't work as it is intended
Install the OS on the disk

**Comment by Jaiendiran** [comment]
Ok, I'll try it. Thanks for the response @ksoham622.
