### ISSUE TITLE
play services 

### ISSUE THREAD

**Issue by au79912** [sebanc/brunch#141]
after the first boot the play services wont open. 
they are stuck loading on the shelf. 
please help.

**Comment by hussainalhaddad** [comment]
> after the first boot the play services wont open.
> they are stuck loading on the shelf.
> please help.

Happened to me when i used eve recovery.. switch to rammus and it should work

**Comment by sebanc** [comment]
Hi,

What's your laptop model ?

First thing to try in any case is deleting google sync can help sometime:
https://support.google.com/chromebook/answer/2914794?hl=en
