### ISSUE TITLE
Stuck At Chromeos-Boot-alert : self repair

### ISSUE THREAD

**Issue by Aarshan123** [sebanc/brunch#1411]
So, I have installed rammus_image recovery file because i have intel core i3 8th gen processor but when i try to open chromeos boot menu through grub2win it just does like read only and then says chromeos-boot-alert :self repair for a long time. I Use Windows 11 UEFI Bios Mode.

also i use a custom code in grub2win that is -
img_part=/dev/sda3
img_path=/ChromeOS/rammus_image.img
search --no-floppy --set=root --file $img_path
loopback loop $img_path
linux (loop,gpt7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off
cros_secure cros_debug loop.max_part=16 img_part=$img_part img_path=$img_path
initrd (loop,gpt7)/initramfs.img

And Also If This Helps My rammus_image.img file is in ChromeOS (E:) under a folder named ChromeOS and its a ntfs file system drive.

I Downloaded the rammus_image.img file from a mega.nz website and the ChromeOS folder has only the rammus_image file the rammus_image file size is 14 GB. I Hope This Much Information Is Sufficient For You To help me.

**Comment by Aarshan123** [comment]
also i use a custom code in grub2win that is - 
img_part=/dev/sda3
img_path=/ChromeOS/rammus_image.img
search --no-floppy --set=root --file $img_path
loopback loop $img_path
linux (loop,gpt7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off \
	cros_secure cros_debug loop.max_part=16 img_part=$img_part img_path=$img_path
initrd (loop,gpt7)/initramfs.img

**Comment by Aarshan123** [comment]
And Also If This Helps My rammus_image.img file is in ChromeOS (E:) under a folder named ChromeOS and its a ntfs file system drive.

**Comment by ksoham622** [comment]
I think, you followed a video guide which was old. And there are some changes So follow this guide [Chrome OS Dualboot with windows](https://github.com/sebanc/brunch/blob/master/install-with-windows.md#dualboot-installations).

And download files from this Github page or links provided in there.

**Comment by ksoham622** [comment]
And if you have a slow HDD creating the image with WSL2 will take much time you can make LIVE USB with a Linux distro

**Comment by Aarshan123** [comment]
> I think, you followed a video guide which was old. And there are some changes So follow this guide [Chrome OS Dualboot with windows](https://github.com/sebanc/brunch/blob/master/install-with-windows.md#dualboot-installations).
> 
> And download files from this Github page or links provided in there.

Thanks! Will Try It!!

**Comment by Aarshan123** [comment]
Ok Gonna Reboot And Try It!

**Comment by Aarshan123** [comment]
and if it works imma close this thing

**Comment by ksoham622** [comment]
Ok

**Comment by Aarshan123** [comment]
I Have a problem i did the create user section thing and i booted in the grub menu but what do i do now?

**Comment by ksoham622** [comment]
Did you see grub2win ?
And was chrome os and chrome settings present in grub2win ?

**Comment by Aarshan123** [comment]
i did see grub2win options there were only 3 options Windows, boot information and utilities and shutdown the system how do i boot into chromeos?

**Comment by ksoham622** [comment]
boot into windows again
open grub2win
then go to the partition where your chromeos.img is there and open the txt file which is present with it select and copy all the contents from that txt file.
now go to grub2win manage boot 
add new entry
Select Create user section from the 'Type' section. This will open a text file and paste all the contents you copied from that txt file
Click Ok and Apply to save your entries into Grub2win.
Your entry will not be saved unless you click both Ok and Apply.

**Comment by Aarshan123** [comment]
i already did it

**Comment by ksoham622** [comment]
do it again

**Comment by Aarshan123** [comment]
ok

**Comment by Aarshan123** [comment]
u mean this code right? 
menuentry "ChromeOS" --class "brunch" {
	search --no-floppy --set=root --file /brunch/chromeos.img
	loopback loop /brunch/chromeos.img
	source (loop,12)/efi/boot/settings.cfg
	if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
			cros_secure cros_debug loop.max_part=16 img_uuid=f44b99ee-11b1-4194-b8d8-cb57b6991ab7 img_path=/brunch/chromeos.img \
			console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
	else
		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
			cros_secure cros_debug loop.max_part=16 img_uuid=f44b99ee-11b1-4194-b8d8-cb57b6991ab7 img_path=/brunch/chromeos.img
	fi
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

menuentry "ChromeOS (settings)" --class "brunch-settings" {
	search --no-floppy --set=root --file /brunch/chromeos.img
	loopback loop /brunch/chromeos.img
	source (loop,12)/efi/boot/settings.cfg
	linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \
		cros_secure cros_debug loop.max_part=16 img_uuid=f44b99ee-11b1-4194-b8d8-cb57b6991ab7 img_path=/brunch/chromeos.img
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

**Comment by ksoham622** [comment]
If you do it alright you can see chrome os and chrome os settings in grub2win

**Comment by ksoham622** [comment]
yes that one

**Comment by Aarshan123** [comment]
ok but i dont have a chromeos option tho

**Comment by ksoham622** [comment]
earch --no-floppy --set=root --file /brunch/chromeos.img
loopback loop /brunch/chromeos.img
source (loop,12)/efi/boot/settings.cfg
if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params
cros_secure cros_debug loop.max_part=16 img_uuid=f44b99ee-11b1-4194-b8d8-cb57b6991ab7 img_path=/brunch/chromeos.img
console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
else
linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params
cros_secure cros_debug loop.max_part=16 img_uuid=f44b99ee-11b1-4194-b8d8-cb57b6991ab7 img_path=/brunch/chromeos.img
fi
initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img






search --no-floppy --set=root --file /brunch/chromeos.img
loopback loop /brunch/chromeos.img
source (loop,12)/efi/boot/settings.cfg
linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1
cros_secure cros_debug loop.max_part=16 img_uuid=f44b99ee-11b1-4194-b8d8-cb57b6991ab7 img_path=/brunch/chromeos.img
initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img

**Comment by ksoham622** [comment]
remove and add entry again in grub2win

**Comment by Aarshan123** [comment]
![image](https://user-images.githubusercontent.com/98741492/152308915-623409dc-b101-4e64-b11a-5b5bf265d0c3.png)
this is the options that i have and below down is the create user section

**Comment by ksoham622** [comment]
it looks fine
press apply and ok

**Comment by Aarshan123** [comment]
ok

**Comment by Aarshan123** [comment]
should i add the code that u gave me?

**Comment by ksoham622** [comment]
no dont

**Comment by ksoham622** [comment]
if you add code copy it from that txt file

**Comment by Aarshan123** [comment]
but like how do i boot into chromeos when i dont have the chromeos option?

**Comment by ksoham622** [comment]
reboot

**Comment by Aarshan123** [comment]
ok i will

**Comment by Aarshan123** [comment]
just a sec

**Comment by Aarshan123** [comment]
same results only 3 options

**Comment by ksoham622** [comment]
if you do not see the options then copy the code in the brackets do not copy anything outside the brackets

**Comment by ksoham622** [comment]
search --no-floppy --set=root --file /brunch/chromeos.img
loopback loop /brunch/chromeos.img
source (loop,12)/efi/boot/settings.cfg
if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params
cros_secure cros_debug loop.max_part=16 img_uuid=f44b99ee-11b1-4194-b8d8-cb57b6991ab7 img_path=/brunch/chromeos.img
console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
else
linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params
cros_secure cros_debug loop.max_part=16 img_uuid=f44b99ee-11b1-4194-b8d8-cb57b6991ab7 img_path=/brunch/chromeos.img
fi
initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img

**Comment by ksoham622** [comment]
so did it work ?

**Comment by ksoham622** [comment]
ok so try this idk if this will work but it should probably
img_part=/dev/sda3
img_path=/brunch/chromeos.img
search --no-floppy --set=root --file $img_path
loopback loop $img_path
linux (loop,gpt7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off
cros_secure cros_debug loop.max_part=16 img_part=$img_part img_path=$img_path
initrd (loop,gpt7)/initramfs.img

make sure you replace sda3 by the partition you selected
and copy this code into grub2win and in grub2win select add new entry custom code or submenu

**Comment by Aarshan123** [comment]
okk

**Comment by Aarshan123** [comment]
wait lemme try

**Comment by ksoham622** [comment]
did it work ?

**Comment by Aarshan123** [comment]
yes

**Comment by ksoham622** [comment]
can you see 2 options ?

**Comment by Aarshan123** [comment]
the create user thing u told me earlier worked

**Comment by Aarshan123** [comment]
yes settings and chrome

**Comment by ksoham622** [comment]
> ok so try this idk if this will work but it should probably img_part=/dev/sda3 img_path=/brunch/chromeos.img search --no-floppy --set=root --file $img_path loopback loop $img_path linux (loop,gpt7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off cros_secure cros_debug loop.max_part=16 img_part=$img_part img_path=$img_path initrd (loop,gpt7)/initramfs.img
> 
> make sure you replace sda3 by the partition you selected and copy this code into grub2win and in grub2win select add new entry custom code or submenu

this ?

**Comment by ksoham622** [comment]
okay then

**Comment by Aarshan123** [comment]
noo

**Comment by Aarshan123** [comment]
but wait

**Comment by Aarshan123** [comment]
is it normal to be stuck on the patches are being applied thing for like 20 mins

**Comment by ksoham622** [comment]
first boot might take time
depending on the system though

**Comment by Aarshan123** [comment]
ohh thanks btw do u have discord

**Comment by Aarshan123** [comment]
then imma close this thing

**Comment by ksoham622** [comment]
yes i have

**Comment by Aarshan123** [comment]
whats the user

**Comment by Aarshan123** [comment]
mine is Tanjiro Kamado || Sun Hashira ||#2284

**Comment by ksoham622** [comment]
join brunch discord

**Comment by ksoham622** [comment]
https://discord.gg/x2EgK2M

**Comment by Aarshan123** [comment]
ok anyways imma reboot

**Comment by Aarshan123** [comment]
see brunch general

**Comment by Aarshan123** [comment]
TYSM IM ON CHROME OS RN!!!
