### ISSUE TITLE
Your System Is Repairing Itself. Please Wait.

### ISSUE THREAD

**Issue by Aarshan123** [sebanc/brunch#1416]
How do i solve it? i am on windows 11 UEFI and i use Grub2Win. i followed this link dualboot instructions https://github.com/sebanc/brunch/blob/master/install-with-windows.md#dualboot-installations

**Comment by ksoham622** [comment]
Helo again 
Was your Chrome OS working on first boot ?
And have you disabled fast startup and hibernation ?

**Comment by Aarshan123** [comment]
bro its done i fixed it :)

**Comment by Nryn215** [comment]
How ?

**Comment by leviOceans** [comment]
How?

**Comment by datascientyst** [comment]
How was it fixed? I shut down Windows, was greeted with a green screen with some text. Tried booting brunch and now this message 'Your system is repairing itself'

**Comment by jackiesogi** [comment]
Someone out there find a proper solution for this?
