### ISSUE TITLE
rEFInd config?

### ISSUE THREAD

**Issue by ReubenBTalbott** [sebanc/brunch#142]
Hi, I switched my PC to use [rEFInd](https://www.rodsbooks.com/refind) instead of grub and I'm not sure how to create a boot entry for Chrome OS with all of the right arguments in rEFInd.
Any help is appreciated.

**Comment by sebanc** [comment]
Hi,

brunch needs grub for several purposes, in my opinion the correct way to do this is to chainload grub from refind. (I cannot really help you with it as I don't use refind)

If you don't want to see the grub menu, you can replace "set timeout=2" in /efi/boot/grub.cfg on partition 12 by "set timeout=0".
