### ISSUE TITLE
Cannot launch android apps after updating to Chrome OS 98

### ISSUE THREAD

**Issue by u9wy** [sebanc/brunch#1437]
@sebanc After updating to Chrome OS 98 I'm unable to launch android apps. It's just loading forever in the taskbar. I've even tried to enable android_inix_fix and it has no effect.

**Comment by sebanc** [comment]
Unfortunately with certain recoveries chromeos r98 currently breaks the android subsystem and the only known solution to fix android apps is a powerwash. This issue is reproducible on legit chromebooks so hopefully it will be fixed shortly by Google.

**Comment by antoninchadima** [comment]
uninstalling android and reinstalling is enough

**Comment by u9wy** [comment]
> uninstalling android and reinstalling is enough

That worked
