### ISSUE TITLE
There is not R-95, 96, 97 for volteer, why?

### ISSUE THREAD

**Issue by 1457384613gh** [sebanc/brunch#1438]
There is not R-95, 96, 97 for volteer, why?

**Comment by tejasraman** [comment]
Download r94 and update from it.

**Comment by tejasraman** [comment]
Yes

**Comment by 1457384613gh** [comment]
> Yes
> […](#)
> On Feb 13, 2022, 7:06 PM -0700, Chauncy♋ ***@***.***>, wrote: > Download r94 and update from it. Should "option=pwa, enable_updates" be set for updating ? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

![image](https://user-images.githubusercontent.com/69227436/154651199-5c1862de-199c-4adf-88d0-31f8d42b65dd.png)
It fails to update.![image](https://user-images.githubusercontent.com/69227436/154651412-391e7aa0-7bb1-4a56-90a5-5409bd087c8e.png)

And PWA has no r97.

**Comment by tejasraman** [comment]
Remove the space between the comma and enable updates

**Comment by tejasraman** [comment]
PWA had no updates because it uses recovery images to update. Remove the space, use the ChromeOS(Settings menu) and don’t Edit the file using Linux/Windows next time.

**Comment by 1457384613gh** [comment]
> PWA had no updates because it uses recovery images to update. Remove the space, use the ChromeOS(Settings menu) and don’t Edit the file using Linux/Windows next time.


Thanks for your reply and how earnest you are !
But I do have edited [grub.cfg],[setting.cfg]and[theme.cfg] using linux before I got tips from you. Now, it cannot load desktop, and always does reboot automatically.

**Comment by tejasraman** [comment]
Reinstall, or undo the changes you did to theme.cfg and settings.cfg. For GRUB, use the ChromeOS(Settings) entry in the grub loader(options screen).

**Comment by 1457384613gh** [comment]
> Reinstall, or undo the changes you did to theme.cfg and settings.cfg. For GRUB, use the ChromeOS(Settings) entry in the grub loader(options screen).
> […](#)
> On Feb 18, 2022, 9:54 PM -0700, Chauncy♋ ***@***.***>, wrote: > PWA had no updates because it uses recovery images to update. Remove the space, use the ChromeOS(Settings menu) and don’t Edit the file using Linux/Windows next time. Thanks for your reply and how earnest you are ! But I do have edited [grub.cfg],[setting.cfg]and[theme.cfg] using linux before I got tips from you. Now, it cannot load desktop, and always does reboot automatically. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

I copy files from `(loop,12)/efi/boot` to `ESP: /EFI/brunch`
![image](https://user-images.githubusercontent.com/69227436/154790899-04406fdd-a982-4039-9827-fbd696709570.png)

And edit grub.cfg from `ESP: /EFI/brunch`
```
set timeout=2
regexp --set disk "(^.+)(,gpt)" $root
source /EFI/brunch/theme.cfg
source /EFI/brunch/settings.cfg

menuentry "ChromeOS" --class "brunch" {
	search --no-floppy --set=root --file /chrome/chromeos.img
	loopback loop /chrome/chromeos.img
	source (loop,12)/efi/boot/settings.cfg
	if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
			cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img \
			console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
	else
		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
			cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img
	fi
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

menuentry "ChromeOS (settings)" --class "brunch-settings" {
	search --no-floppy --set=root --file /chrome/chromeos.img
	loopback loop /chrome/chromeos.img
	source (loop,12)/efi/boot/settings.cfg
	linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \
		cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}
```

It can enter desktop successfully for the first time after installing, but does always reboot for the second+ time.
Why?
I want to use `Refind Boot Manager`, so I need `ESP: /EFI/brunch/bootx64.efi`
Behind BIOS setup can I add a `New Boot Entry` called `Brunch Framework`
![image](https://user-images.githubusercontent.com/69227436/154791271-176216fd-63cf-4533-852d-3780cb88111d.png)

It is a good way for old Brunch like R92, but fails to boot the second+ time with the newest Brunch.
Could you help me?

**Comment by tejasraman** [comment]
I am not sure. I also use Brunch with rEFInd, and what I did was install GRUB from Linux(I have PopOS, which doesn’t use grub) and I copied /etc/grub.d/07-custom to /etc/grub.d/09-brunch and added the boot entries there. I will compare my grub config a bit later(I am on my iPad, not my PC) and see what exactly is going on. Are you using the Brunch documentation dualboot procedure(creates a .img file, not partitions). You could also use grub2win though, just a suggestion. Do you have a Linux installed?

**Comment by 1457384613gh** [comment]
> I am not sure. I also use Brunch with rEFInd, and what I did was install GRUB from Linux(I have PopOS, which doesn’t use grub) and I copied /etc/grub.d/07-custom to /etc/grub.d/09-brunch and added the boot entries there. I will compare my grub config a bit later(I am on my iPad, not my PC) and see what exactly is going on. Are you using the Brunch documentation dualboot procedure(creates a .img file, not partitions). You could also use grub2win though, just a suggestion. Do you have a Linux installed?
> […](#)
> On Feb 19, 2022, 12:26 AM -0700, Chauncy♋ ***@***.***>, wrote: > Reinstall, or undo the changes you did to theme.cfg and settings.cfg. For GRUB, use the ChromeOS(Settings) entry in the grub loader(options screen). > … > On Feb 18, 2022, 9:54 PM -0700, Chauncy♋ @.>, wrote: > PWA had no updates because it uses recovery images to update. Remove the space, use the ChromeOS(Settings menu) and don’t Edit the file using Linux/Windows next time. Thanks for your reply and how earnest you are ! But I do have edited [grub.cfg],[setting.cfg]and[theme.cfg] using linux before I got tips from you. Now, it cannot load desktop, and always does reboot automatically. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.> I copy files from (loop,12)/efi/boot to ESP: /EFI/brunch And edit grub.cfg from ESP: /EFI/brunch set timeout=2 regexp --set disk "(^.+)(,gpt)" $root source /EFI/brunch/theme.cfg source /EFI/brunch/settings.cfg menuentry "ChromeOS" --class "brunch" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg if [ -z $verbose ] -o [ $verbose -eq 0 ]; then linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img \ console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet else linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img fi initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } menuentry "ChromeOS (settings)" --class "brunch-settings" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } It can enter desktop successfully for the first time after installing, but does always reboot for the second+ time. Why? I want to use Refind Boot Manager, so I need ESP: /EFI/brunch/bootx64.efi Behind BIOS setup can I add a New Boot Entry called Brunch Framework It is a good way for old Brunch like R92, but fails to boot the second+ time with the newest Brunch. Could you help me? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

![image](https://user-images.githubusercontent.com/69227436/154830139-e66a68f8-6ef5-41a0-865c-0dc71dc0574f.png)

```
menuentry "ChromeOS" --class "brunch" {
	search --no-floppy --set=root --file /chrome/chromeos.img
	loopback loop /chrome/chromeos.img
	source (loop,12)/efi/boot/settings.cfg
	if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
			cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img \
			console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
	else
		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
			cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img
	fi
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

menuentry "ChromeOS (settings)" --class "brunch-settings" {
	search --no-floppy --set=root --file /chrome/chromeos.img
	loopback loop /chrome/chromeos.img
	source (loop,12)/efi/boot/settings.cfg
	linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \
		cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}
```
I try to use grub2win, and fail.

**Comment by tejasraman** [comment]
Reinstall ChromeOS. Cannot think of anything else. What Linux do you have? Boot into bios and select grub2win first though.

**Comment by 1457384613gh** [comment]
> Reinstall ChromeOS. Cannot think of anything else. What Linux do you have? Boot into bios and select grub2win first though.
> […](#)
> On Feb 19, 2022, 10:42 PM -0700, Chauncy♋ ***@***.***>, wrote: > I am not sure. I also use Brunch with rEFInd, and what I did was install GRUB from Linux(I have PopOS, which doesn’t use grub) and I copied /etc/grub.d/07-custom to /etc/grub.d/09-brunch and added the boot entries there. I will compare my grub config a bit later(I am on my iPad, not my PC) and see what exactly is going on. Are you using the Brunch documentation dualboot procedure(creates a .img file, not partitions). You could also use grub2win though, just a suggestion. Do you have a Linux installed? > … > On Feb 19, 2022, 12:26 AM -0700, Chauncy♋ @.>, wrote: > Reinstall, or undo the changes you did to theme.cfg and settings.cfg. For GRUB, use the ChromeOS(Settings) entry in the grub loader(options screen). > … > On Feb 18, 2022, 9:54 PM -0700, Chauncy♋ @.>, wrote: > PWA had no updates because it uses recovery images to update. Remove the space, use the ChromeOS(Settings menu) and don’t Edit the file using Linux/Windows next time. Thanks for your reply and how earnest you are ! But I do have edited [grub.cfg],[setting.cfg]and[theme.cfg] using linux before I got tips from you. Now, it cannot load desktop, and always does reboot automatically. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.> I copy files from (loop,12)/efi/boot to ESP: /EFI/brunch And edit grub.cfg from ESP: /EFI/brunch set timeout=2 regexp --set disk "(^.+)(,gpt)" $root source /EFI/brunch/theme.cfg source /EFI/brunch/settings.cfg menuentry "ChromeOS" --class "brunch" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg if [ -z $verbose ] -o [ $verbose -eq 0 ]; then linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img \ console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet else linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img fi initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } menuentry "ChromeOS (settings)" --class "brunch-settings" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } It can enter desktop successfully for the first time after installing, but does always reboot for the second+ time. Why? I want to use Refind Boot Manager, so I need ESP: /EFI/brunch/bootx64.efi Behind BIOS setup can I add a New Boot Entry called Brunch Framework It is a good way for old Brunch like R92, but fails to boot the second+ time with the newest Brunch. Could you help me? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.> menuentry "ChromeOS" --class "brunch" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg if [ -z $verbose ] -o [ $verbose -eq 0 ]; then linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img \ console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet else linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img fi initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } menuentry "ChromeOS (settings)" --class "brunch-settings" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } I try to use grub2win, and fail. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

OK, I will try again.
I have fedora.

**Comment by tejasraman** [comment]
Thanks!

**Comment by tejasraman** [comment]
Hey, a Cros 98 recovery image was released a few days ago. Use it with brunch unstable. Use the ChromeOS(Settings) menu to enable updates and PWA. https://cros.tech/device/volteer

**Comment by tejasraman** [comment]
It is a bit weird that they still have no r95,96,97 available

**Comment by 1457384613gh** [comment]
> Hey, a Cros 98 recovery image was released a few days ago. Use it with brunch unstable. Use the ChromeOS(Settings) menu to enable updates and PWA. https://cros.tech/device/volteer
> On Feb 20, 2022, 3:28 AM -0700, Chauncy♋ ***@***.***>, wrote:
> > > Reinstall ChromeOS. Cannot think of anything else. What Linux do you have? Boot into bios and select grub2win first though.
> > > …
> > > On Feb 19, 2022, 10:42 PM -0700, Chauncy♋ @.>, wrote: > I am not sure. I also use Brunch with rEFInd, and what I did was install GRUB from Linux(I have PopOS, which doesn’t use grub) and I copied /etc/grub.d/07-custom to /etc/grub.d/09-brunch and added the boot entries there. I will compare my grub config a bit later(I am on my iPad, not my PC) and see what exactly is going on. Are you using the Brunch documentation dualboot procedure(creates a .img file, not partitions). You could also use grub2win though, just a suggestion. Do you have a Linux installed? > … > On Feb 19, 2022, 12:26 AM -0700, Chauncy♋ @.>, wrote: > Reinstall, or undo the changes you did to theme.cfg and settings.cfg. For GRUB, use the ChromeOS(Settings) entry in the grub loader(options screen). > … > On Feb 18, 2022, 9:54 PM -0700, Chauncy♋ @.>, wrote: > PWA had no updates because it uses recovery images to update. Remove the space, use the ChromeOS(Settings menu) and don’t Edit the file using Linux/Windows next time. Thanks for your reply and how earnest you are ! But I do have edited [grub.cfg],[setting.cfg]and[theme.cfg] using linux before I got tips from you. Now, it cannot load desktop, and always does reboot automatically. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.> I copy files from (loop,12)/efi/boot to ESP: /EFI/brunch And edit grub.cfg from ESP: /EFI/brunch set timeout=2 regexp --set disk "(^.+)(,gpt)" $root source /EFI/brunch/theme.cfg source /EFI/brunch/settings.cfg menuentry "ChromeOS" --class "brunch" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg if [ -z $verbose ] -o [ $verbose -eq 0 ]; then linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img \ console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet else linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img fi initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } menuentry "ChromeOS (settings)" --class "brunch-settings" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } It can enter desktop successfully for the first time after installing, but does always reboot for the second+ time. Why? I want to use Refind Boot Manager, so I need ESP: /EFI/brunch/bootx64.efi Behind BIOS setup can I add a New Boot Entry called Brunch Framework It is a good way for old Brunch like R92, but fails to boot the second+ time with the newest Brunch. Could you help me? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.> menuentry "ChromeOS" --class "brunch" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg if [ -z $verbose ] -o [ $verbose -eq 0 ]; then linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img \ console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet else linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img fi initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } menuentry "ChromeOS (settings)" --class "brunch-settings" { search --no-floppy --set=root --file /chrome/chromeos.img loopback loop /chrome/chromeos.img source (loop,12)/efi/boot/settings.cfg linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \ cros_secure cros_debug loop.max_part=16 img_uuid=2c3a25f7-76ae-4cb9-a009-ad4c66eb9e3d img_path=/chrome/chromeos.img initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img } I try to use grub2win, and fail. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.>
> > OK, I will try again.
> > I have fedora.
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android.
> > You are receiving this because you commented.Message ID: ***@***.***>
> 



I use grub2win this time.
Reinstall but it fails to boot for the second+ time.

**Comment by tejasraman** [comment]
Copy boot entries from Brunch script.

**Comment by 1457384613gh** [comment]
I have tried another installed into ext4 again, without any bugs.

So I think the bug before is around one installed into NTFS.
One installed into NTFS cannot load desktop for the second+ time, and always does reboot automatically.

Ext4 is better than NTFS.

**Comment by tejasraman** [comment]
NTFS is Microsoft's proprietary filesystem designed for Windows. Native Chromebooks(ChromeOS is Linux based) use EXT4 too. And I use EXT4 too with no bugs.

Great!

**Comment by 1457384613gh** [comment]
![IMG_20220401_074103](https://user-images.githubusercontent.com/69227436/161166914-b800a20a-97f5-4ff0-80f7-0408dcdbcc4f.jpg)

Here, NTFS.

**Comment by 1457384613gh** [comment]
I have tried one installed into btrfs.
It works fine.
But after using pwa or brunch-toolkit to update, the grub cannot boot the updated system.

**Comment by tejasraman** [comment]
The reason they say that is windows cannot format to ext4 :) The Linux guide:

**Comment by tejasraman** [comment]
NTFS doesn’t work for me anyway so look at the Linux guide

**Comment by tejasraman** [comment]
Sorry, using mail cannot send images to Github.
![2022-04-09_18-49](https://user-images.githubusercontent.com/96961804/162596536-255b3164-90bd-4a48-bf40-a5ba988c06ed.png)
