### ISSUE TITLE
Fingerprint sensor support ?

### ISSUE THREAD

**Issue by skandavc18** [sebanc/brunch#146]
Everything works fine in my Lenovo Yoga 730. 
Wanted to know if support for fingerprint sensor can be added. There is support for fingerprint sensor in Ubuntu.

Would be helpful if you could tell me the steps to add those Ubuntu drivers to Chrome OS.

**Comment by ldti** [comment]
ChromeOS doesn't support it yet, AFAIK..

**Comment by sebanc** [comment]
Hi,

it's unlikely that it will happen, it would require a motivated dev with the same hardware to make the linux fingerprint sensor driver output data the same way as the chromeos one (which is rather complicated).

**Comment by skandavc18** [comment]
> ChromeOS doesn't support it yet, AFAIK..

It does. There are many Chromebooks which support fingerprint sensor.
example : https://www.androidpolice.com/2020/05/02/asus-chromebook-flip-c436-review-premium-hardware-poor-value/

**Comment by skandavc18** [comment]
> Hi,
> 
> it's unlikely that it will happen, it would require a motivated dev with the same hardware to make the linux fingerprint sensor driver output data the same way as the ChromeOS one (which is rather complicated).

Ok. Anyways thanks for this wonderful project.
