### ISSUE TITLE
Float Question: How Likely Playstore will work to any device?

### ISSUE THREAD

**Issue by revdeluxe** [sebanc/brunch#1469]
This isn't really a issue but for those who stumble upon my crappy post.

out of 10 brands of budget computers/laptop.

How likely is it going to run. either will it run, little hiccups, or impossible.

I'm currently(this summer 2022) going to try brunch(should i say chrome os.). to my HP Intel Celeron n3060.

**Comment by elder5** [comment]
How did it go?
I ordered a chromebook for someone else. same one with same processor. But it's support ends on June 2022...so my fix would be to go with brunch, no expiration date on the OS.
My main device is a dell venue 11 with brunch OS, I love it!

**Comment by revdeluxe** [comment]
> How did it go? I ordered a chromebook for someone else. same one with same processor. But it's support ends on June 2022...so my fix would be to go with brunch, no expiration date on the OS. My main device is a dell venue 11 with brunch OS, I love it!

I'd said that i was not successful. but i was able to boot into the cloudready installer. but it keeps crashing so i moved to Archcraft instead.

**Comment by elder5** [comment]
Update:
I have inform that I successfully bypass Google "AUE"  (auto update expiration) using brunch on the 3189!!
I used "windows install helper - coolstar. Org" tutorials. 
Then Ubuntu live usb to install brunch. 

![IMG_20220428_125459](https://user-images.githubusercontent.com/6239094/165836764-661f3a75-d9cf-467b-a37a-3b043a6a62f7.jpg)
![IMG_20220428_130614](https://user-images.githubusercontent.com/6239094/165836785-56f18055-e653-4466-b2c1-4949c5bacd66.jpg)
