### ISSUE TITLE
No rtl8723de support (Wifi is not working on HP BS658TX)

### ISSUE THREAD

**Issue by AshuSharma7** [sebanc/brunch#147]
I've Successfully dual booted chrome os on my HP BS658TX.
Everything else works fine except wifi
My Laptop has rtl8723de wifi adapter

**Comment by sebanc** [comment]
Hi,

Could you try the release in the "brunch-testing" repo (not this one) and boot with "options=rtl8723de" added to the kernel command line ?

**Comment by AshuSharma7** [comment]
Thanks for responding quickly
I'll test and report

**Comment by AshuSharma7** [comment]
Thanks, Now Wifi is working properly after adding options=rtl873de to the command line.

**Comment by DDynamites** [comment]
> Thanks, Now Wifi is working properly after adding options=rtl873de to the command line.

hey, how do i add mine , i have also dual booted and same wifi adapter, please help
