### ISSUE TITLE
'Brunch has been successfully installed on your device' not 'ChromeOS'

### ISSUE THREAD

**Issue by gigglypup** [sebanc/brunch#1472]
When installing brunch via Linux mint terminal, it says 'Brunch has been successfully installed on the device /dev/sda'. In the tutorial I watched, it said 'ChromeOS installed'. ChromeOS does not boot up once I restart my laptop (stuck on 'loading brunch framework'). How do I fix this so that it installs ChromeOS, not brunch?

**Comment by WesBosch** [comment]
Brunch is what you're installing, and any YouTube video you're watching is outdated and unsupported. This issue can be closed.

**Comment by gigglypup** [comment]
> Brunch is what you're installing, and any YouTube video you're watching is outdated and unsupported. This issue can be closed.

Okay thank you
