### ISSUE TITLE
System failed to detect ChromeOS install on USB and launches an init shell instead

### ISSUE THREAD

**Issue by khanhtranngoccva** [sebanc/brunch#149]
The usb /dev/sdb is always plugged in and active, so that I can boot into ChromeOS.

**Comment by sebanc** [comment]
Hi,

Could you post the text that appears when you run "chromeos-install.sh" to create the usb ?

Also, what size is your usb flashdrive ?

**Comment by khanhtranngoccva** [comment]
![20200516_184849](https://user-images.githubusercontent.com/61155608/82119187-a82b5980-97a6-11ea-8547-46c35ab1d896.jpg)

**Comment by khanhtranngoccva** [comment]
There is one device /dev/sdb as well.

**Comment by sebanc** [comment]
Ok got it, brunch comes with a timeout of 10 seconds to make sure all devices are loaded (usually all devices are loaded in 1/2 seconds). Your usb device took 25 seconds to be loaded which is not normal and is the origin of this issue.

Could you try to plug it on another usb port or looking for suspicious settings in your bios ?

You can also try another usb flashdrive.

**Comment by khanhtranngoccva** [comment]
How do I set its timeout?

**Comment by sebanc** [comment]
The timeout is in the code you cannot change it

**Comment by khanhtranngoccva** [comment]
Where is the code of the timeout please, and is it readable?

**Comment by sebanc** [comment]
It's in the initramfs, if you want to modify it, you have to unpack it and repack it, i will not provide support for that.

**Comment by khanhtranngoccva** [comment]
OK. I have got another issue too, would you mind answering?

**Comment by sebanc** [comment]
No what is it ?

**Comment by khanhtranngoccva** [comment]
https://github.com/sebanc/brunch/issues/150

**Comment by khanhtranngoccva** [comment]
How to unpack/repack initramfs without kernel panic, please?
