### ISSUE TITLE
ChromeOS 78+ failed to run ARC across reboots.

### ISSUE THREAD

**Issue by khanhtranngoccva** [sebanc/brunch#150]
This error is caused by signal 15, signal 9 or EOF bugs. I do not know how to fix it.

**Comment by khanhtranngoccva** [comment]
![15896312457395959741080795373461](https://user-images.githubusercontent.com/61155608/82119516-7667c200-97a9-11ea-820d-4bf125598809.jpg)

**Comment by sebanc** [comment]
If android is able to setup, it means that all is working correctly on kernel side. If arc refuses to launch in subsequent reboots, it means that there is something in your google profile / apps you have downloaded... which breaks the chromeos android container.

My only suggestions are:

- Deleting google sync:
https://support.google.com/chromebook/answer/2914794?hl=en

- Clearing cache & data from Google Play Services:
https://support.google.com/googleplay/answer/7512202?hl=en
