### ISSUE TITLE
How to set the size in MB ?

### ISSUE THREAD

**Issue by 1457384613gh** [sebanc/brunch#1507]
`sudo bash chromeos-install.sh -src chromeos_filename.bin -dst ~/tmpmount/chromeos.img -s size`
The size is in GB.
If the size I want to set is 61,036 MB=59.60547 GB , how could I input?

**Comment by darethehair** [comment]
Not answering your question directly, but in my case I typically just want to 'fill' a partition, so rather than trying to figure out what size this is, I just try values that are too large/high.  The utility will tell you this, and then I just keep trying -- using 1gb smaller each time -- until it works/fits.

**Comment by tejasraman** [comment]
Type the 59.xxxxx number

**Comment by 1457384613gh** [comment]
How about MB?

If GB，some number is too long to type, even is recurring decimal.

![Screenshot_2022-04-19-10-07-19-816_com.miui.calculator.jpg](https://user-images.githubusercontent.com/69227436/163905900-651835a3-3e62-462b-a69b-9d6bc4f980a9.jpg)

**Comment by tejasraman** [comment]
I could try to modify the script…

**Comment by tejasraman** [comment]
or not

Tejas Raman (he/him/his)

Contact me at ***@***.*** ***@***.***/0?redirect=mailto%3Atejasraman%40icloud.com&recipient=cmVwbHkrQVhEWUtEQ0laQzM0S1NPREhFMkRKUk9BTk5HSlRFVkJOSEhFTzc1NUZRQHJlcGx5LmdpdGh1Yi5jb20%3D)
My website: tejasraman.36bit.com ***@***.***/1?redirect=https%3A%2F%2Ftejasraman.36bit.com&recipient=cmVwbHkrQVhEWUtEQ0laQzM0S1NPREhFMkRKUk9BTk5HSlRFVkJOSEhFTzc1NUZRQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by 1457384613gh** [comment]
What?

**Comment by tejasraman** [comment]
The script takes GB directly, so there is no workaround to this. Setting the partition size is the best way I can think of because about 1.2GB of space is taken by Brunch system files

Tejas Raman (he/him/his)

Contact me at ***@***.*** ***@***.***/0?redirect=mailto%3Atejasraman%40icloud.com&recipient=cmVwbHkrQVhEWUtER1VXSDVYSjdWSlBST0daTUdBTlJZSEJFVkJOSEhFTzc1NUZRQHJlcGx5LmdpdGh1Yi5jb20%3D)
My website: tejasraman.36bit.com ***@***.***/1?redirect=https%3A%2F%2Ftejasraman.36bit.com&recipient=cmVwbHkrQVhEWUtER1VXSDVYSjdWSlBST0daTUdBTlJZSEJFVkJOSEhFTzc1NUZRQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by 1457384613gh** [comment]
But the size of the partition is 128 GB≈122,070 MiB.
I want a chromeos.img of 64 GB≈61,034 MiB, and remain of 61,036 MiB≈64GB.

So I should `sudo bash … 61,034 MiB`

**Comment by 1457384613gh** [comment]
Just only MiB, could you?
Type the number without unit is of MiB.
If users type number with $GiB, it will ×1024 automatically.

$GiB
GiB='×1024'

`sudo bash … 64$GiB`=`sudo bash … 65536`

Could you?

**Comment by tejasraman** [comment]
What is the remaining for? (is it for chromeOS?)

Tejas Raman (he/him/his)

Contact me at ***@***.*** ***@***.***/0?redirect=mailto%3Atejasraman%40icloud.com&recipient=cmVwbHkrQVhEWUtERUtHRlVKUVJQSTJLQ0pWTk9BTlI1U05FVkJOSEhFTzc1NUZRQHJlcGx5LmdpdGh1Yi5jb20%3D)
My website: tejasraman.36bit.com ***@***.***/1?redirect=https%3A%2F%2Ftejasraman.36bit.com&recipient=cmVwbHkrQVhEWUtERUtHRlVKUVJQSTJLQ0pWTk9BTlI1U05FVkJOSEhFTzc1NUZRQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by 1457384613gh** [comment]
What?
The link for you is following. https://github.com/sebanc/brunch/issues/1507

**Comment by tejasraman** [comment]
What?
That was my stupid email sugnature

**Comment by 1457384613gh** [comment]
> What is the remaining for? (is it for chromeOS?)
> 
> 

For installing Android x86_64 with gearlock and MagiskSU.

Apks needing SU and several kinds of modules could be installed in it.

**Comment by tejasraman** [comment]
I've used Magisk before, believe me.

Make 2 partitions. This is an answer.

**Comment by 1457384613gh** [comment]
I have another idea with inspiration of Android x86_64.

Dual boot

Don't re-size the img file when installing ChromeOS with brunch.

Just turn the bin file into img file and rename without re-sizing.

Make a new folder named `stage` following the x.img file and x-grub.txt file.

Edit grub and so on to mount the folder named `stage` in place of the last partition named `stage` into img disk.

If so, ChromeOS could make full use of all the space of the ext4 partition.

**Comment by tejasraman** [comment]
No... .bin does not = .img. Brunch patches it to work too
You should try Bliss OS , not Android x86

**Comment by 1457384613gh** [comment]
OK，patch without re-sizing.

I want to mount a folder as stage out of img disk.

**Comment by tejasraman** [comment]
The thing is, in Brunch dualboot, no system partitions are made - they are all _inside the IMG file_. It would be best to leave the

**Comment by tejasraman** [comment]
The last version of android-x86 is 9.0. Bliss OS has android 11 and 12 already.

**Comment by 1457384613gh** [comment]
I'm sorry but how about `Downloads`?

ext4: 
/xxx/x.img
/xxx/x-grub.txt
/xxx/Downloads   (a folder)

Mount /xxx/Downloads as Downloads into img.

Or link Downloads to Downloads.

**Comment by tejasraman** [comment]
The img contains all the partitions like the custom ROOTC and system reserved - you can't just create some weird custom IMG file with only the plain recovery image, as that needs files extracted and put in the right places.

**Comment by 1457384613gh** [comment]
OK, I get it.
How about f2fs?
It's faster friendlier to flash than ext4.
Could img disk be put into f2fs and then be booted into f2fs?

**Comment by tejasraman** [comment]
You could copy the img to an f2fs partition (or try), as the grub entry has no partition specified. Do you have an add though? F2fs isn't much use if not

**Comment by tejasraman** [comment]
Errors - silly autocorrect meddling with my comments, I meant ssd

**Comment by tejasraman** [comment]
There's no guarantee it will work

**Comment by 1457384613gh** [comment]
Thank you very much for your early reply and how earnest you are!

**Comment by tejasraman** [comment]
Thanks! (you said that in the colter r95-6-7 post too)

**Comment by 1457384613gh** [comment]
What do you thank me for?
Just a bug around NTFS.

I think that I can help you less than you can help me.

**Comment by tejasraman** [comment]
Thanks...

**Comment by tejasraman** [comment]
Did it work?
Did you manage to get chrome is installed?

**Comment by 1457384613gh** [comment]
I haven't try.
I just have a 75GB chromeos.img into ext4 for stable use.

**Comment by tejasraman** [comment]
Ok... you have approx. 53 GB for the Bliss OS/android-x86...

**Comment by 1457384613gh** [comment]
https://github.com/1457384613gh/rEFInd-theme-named-Yours
This is my repository.
Would you like to try?

![image](https://user-images.githubusercontent.com/69227436/164479464-442996f7-ffc3-47f2-94c5-a258369c3a5e.png)

**Comment by tejasraman** [comment]
Ok... I love the concept of using a jpg file. Would this open in something other than office 2021?

**Comment by tejasraman** [comment]
FYI I have WPS and Office365 for Mac

**Comment by tejasraman** [comment]
How many OSes do you have?
I see opencore, fedora, brunch,

**Comment by 1457384613gh** [comment]
> FYI I have WPS and Office365 for Mac

Maybe，but I haven't try. I cannot promise the resolution of the banner exported is right. `Office 365` could be tried. 
I will make `BannerEditor.psd` for `Photoshop` to edit, because many users using Mac have `Adobe Zii`.

**Comment by 1457384613gh** [comment]
I haven't counted.

![image](https://user-images.githubusercontent.com/69227436/164583967-cd329838-ded1-4b42-a4b7-b612c42f7921.png)

![image](https://user-images.githubusercontent.com/69227436/164584037-b96eac3a-0926-49e8-a731-c11574eca8a3.png)

![image](https://user-images.githubusercontent.com/69227436/164584068-411bde1d-535e-4d76-860d-65de1e5f304e.png)

![image](https://user-images.githubusercontent.com/69227436/164584199-41d47339-5965-4524-bc31-a0c29f86a114.png)

**Comment by tejasraman** [comment]
I mean how many do you have installed.
Did you fix your chrome problem?

**Comment by 1457384613gh** [comment]
I‘m sorry but they are only icons.
All I have installed is a few.
![image](https://user-images.githubusercontent.com/69227436/164586281-3556bc5b-1d4b-42ea-b58f-4de109dba799.png)

Brunch works very well
![image](https://user-images.githubusercontent.com/69227436/164586194-4a1661f3-1c66-4b35-bb80-0a8c87aa56ce.png)

**Comment by tejasraman** [comment]
Great.., did android x86/bliss is work?

**Comment by 1457384613gh** [comment]
> Great... did android x86/bliss is work?

Yeah, they can work well, too.
If bliss, the folder containing `grubx64.efi` of bliss should be renamed `blissos` for its icon.

**Comment by tejasraman** [comment]
Did they work for you? Remember the original issue?

**Comment by 1457384613gh** [comment]
> Did they work for you? Remember the original issue?

I haven't tried to type a decimal.

**Comment by 1457384613gh** [comment]
But I still think MiB is better than GiB, which called GB though.
![image](https://user-images.githubusercontent.com/69227436/164590636-efdb9883-23e6-44a9-805c-1b4214a66058.png)

**Comment by tejasraman** [comment]
Don’t grow a decimal, type a whole number = to the size of the partition. Now, is the issue resolved?
I will try your refind theme at some point - my computer relies on refind as I have 4 OSes (Pop, Win11, Arch, ChromeOS) and I don’t like grub.

**Comment by tejasraman** [comment]
GB = gigabyte
GiB = gibibyte

I
1 GB = 0.93 GiB

**Comment by 1457384613gh** [comment]
Ok, thank you for your coming experience.
And what I really want is make a chromeos.img with size of real GB not GiB, so I want to use MiB to turn GiB into around GB.
If `sudo bash ... 75`, I get a chromeos.img of 75GiB not 75GB.

**Comment by tejasraman** [comment]
69 GiB = 75 GB (approx)

**Comment by 1457384613gh** [comment]
There is a new release. Adjust fonts.
![image](https://user-images.githubusercontent.com/69227436/164609533-dbaa87f5-4384-4cbb-b8f3-8c457af7169b.png)

**Comment by tejasraman** [comment]
Try 69 gib

**Comment by 1457384613gh** [comment]
Select fonts whichever you would like.

Thank you for the number though the margin of error is more than 0.25%.

**Comment by tejasraman** [comment]
Its ok to have so,e space

**Comment by tejasraman** [comment]
That is the best I can do. It doesn’t accept decimals (I tried)

**Comment by 1457384613gh** [comment]
Considering the partition alignment, the size of partitions are multiple of 2MiB.

So, 2MiB is like a bridge between real GiB and almost GB.

Those who always use Windows like using GiB,
for whom, here is nothing;

Those who always use Mac or Fedora like using GB,
for whom, here is this.

- 2GB∧4=  16GB≈ 15,258 MiB
- 2GB∧5=  32GB≈ 30,518 MiB
- 2GB∧6=  64GB≈ 61,036 MiB
- 2GB∧7= 128GB≈122,070 MiB
- 2GB∧8= 256GB≈244,140 MiB
- 2GB∧9= 512GB≈488,282 MiB
- 2GB∧X=1024GB≈976,562 MiB

They could have gotten a `.img` with size of almost 2GB∧n, and n=4,5,6,7,8,9,10…

Maybe, it's obsessive-compulsive disorder.

However, `disk tool` of Mac and real disk capacity have that which make people have better feelings.

If `sudo bash … [number] #MiB`, we will get a `.img` disk with all kinds of sizes of both really GiB and almost GB.

**Comment by 1457384613gh** [comment]
Upside down.

If we want to get a `.img` disk of almost 64GB, we could have typed `sudo bash … 61,036 #MiB`.
🤣🤣🤣
So if only MiB!

**Comment by tejasraman** [comment]
🤣🤣 😁 was that really  the solution? Typing #MiB after the number in bash?
That is just what I needed because my disk wasn’t big enough.
You helped me more than I helped you.

**Comment by 1457384613gh** [comment]
Look this is my disk.

![正在上传 r2{d1e1439} (6d9ef9d8-fb24-450f-920d-6cc05235e2cf id=0x7f0a03b3 tag=BaseCommentFragment)…]()

**Comment by 1457384613gh** [comment]
Look, here is my SSD.
![Screenshot_2022-04-23-11-24-01-018_com miui notes](https://user-images.githubusercontent.com/69227436/164873504-ab358541-226f-41be-86b8-fe3b7a399238.jpg)

**Comment by tejasraman** [comment]
Great!
Where’s the android?

**Comment by 1457384613gh** [comment]
Here is ext4, now. I have updated it, just now!
![IMG_20220423_114135](https://user-images.githubusercontent.com/69227436/164873980-b0cf4672-1846-4a1c-bc73-ed75c98fdeaa.jpg)

Android is here. I have updated again, just now.
![IMG_20220423_114531](https://user-images.githubusercontent.com/69227436/164874040-eb019c7d-d6c3-434b-ae9a-0b6d16e34589.jpg)

**Comment by tejasraman** [comment]
That's great! Thanks so much!

**Comment by 1457384613gh** [comment]
This is `disk tool` of gnome.
Look at sizes of partitions.
![image](https://user-images.githubusercontent.com/69227436/164878453-ee564096-3fba-4894-90af-3d02f5c48940.png)

**Comment by tejasraman** [comment]
I know it is the disk tool of gnome, I interact with gnome on a daily basis in my PC.
I see what you mean now. Nice that your issue is resolved.
Oh, that is a lot of partitions! (External drive mounting saga for the files partitions)
In Brunch, there is a native drives option so you can access all the partitions (it’s in the brunch settings)

**Comment by 1457384613gh** [comment]
Thank you!
So could we typed `sudo bash … [number] #MiB` by using soon-coming `Brunch Framework R-101`?

**Comment by 1457384613gh** [comment]
> 1. Agency FB isn't preinststalled on anything
> 2. French Script MT is only installed when Office 365 Windows is installed
> 
> 

https://github.com/1457384613gh/rEFInd-theme-named-Yours/releases/tag/Fonts
