### ISSUE TITLE
ChromeOS UEFI menu entry turns into ?? icon after clicking shutdown button

### ISSUE THREAD

**Issue by khanhtranngoccva** [sebanc/brunch#152]
There is no error when using sudo poweroff or sudo reboot. Other ChromiumOSes doesn't suffer this, but Project Croissant OSes do.

**Comment by khanhtranngoccva** [comment]
2 menu entries with disk model and name was replaced by 1 entry with ??.
![1589640626349297226405604576712](https://user-images.githubusercontent.com/61155608/82122702-52af7680-97bf-11ea-94f2-6b9138611fed.jpg)
![15896406652915198373300363582604](https://user-images.githubusercontent.com/61155608/82122716-64911980-97bf-11ea-92a5-8fc62c0bb15a.jpg)

**Comment by sebanc** [comment]
I don't understand what you mean, 2nd printscreen is before chromeos install and first printscreen is after chromeos install ?

**Comment by khanhtranngoccva** [comment]
No, the first screen happened when rebooting after clicking the shutdown button.

**Comment by sebanc** [comment]
The usb disk is not changed by the reboot therefore it is not an issue with chromeos but with your bios. Maybe for some obscure reason it does not happen with chromiumos distro but anyway it's not chromeos related. All I can say is try to update to the latest bios.
