### ISSUE TITLE
Im stuck at loading brunch

### ISSUE THREAD

**Issue by yogoplay** [sebanc/brunch#1529]
PLS HELPPPP

**Comment by chengqingtan** [comment]
Maybe you need to connect your monitor to the motherboard's GPU port and enable the integrated graphics in the bios, chrome os didn't work with discrete graphics.

**Comment by yogoplay** [comment]
i just have "loading brunch framework" and then restarts and again and again

**Comment by yogoplay** [comment]
and i have a laptop

**Comment by yogoplay** [comment]
I think i used wrong rammus image
