### ISSUE TITLE
MacBook Pro 2011, Dual-Boot With Fedora, Not Booting

### ISSUE THREAD

**Issue by daudix-UFO** [sebanc/brunch#1539]
Followed dual-boot [official] instructions (https://github.com/sebanc/brunch/blob/master/install-with-linux.md#dualboot-installations) updated grub, with fedora analog of grub-update "grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg", vboot-utils installed, does not boot
![PXL_20220514_081508295](https://user-images.githubusercontent.com/77155297/168417699-dbe52727-4c4b-4b02-b549-a31857d62c4a.jpg)
![PXL_20220514_082020950](https://user-images.githubusercontent.com/77155297/168417701-b1f98f27-d336-4c89-95d9-684318ac4013.jpg)
Daily driving fedora ofc, have experience with terminal, so I open to any help

**Comment by 1457384613gh** [comment]
Hi, I am a user of Brunch, too.
I have happened to see your issue.
Here my repository is, https://github.com/1457384613gh/rEFInd-theme-named-Yours
You can copy `img_file(loop,12): /efi/boot` into `ESP: /EFI` and rename it `brunch`.
And then edit `grub.cfg`.
![image](https://user-images.githubusercontent.com/69227436/168510311-9bf3f013-6954-48b8-bafd-386f9686463c.png)

**Comment by 1457384613gh** [comment]
You can download [EFI.zip](https://github.com/sebanc/brunch/files/8696850/EFI.zip).
![image](https://user-images.githubusercontent.com/69227436/168512007-f49576e0-194c-4531-835a-c3ed1d4f3980.png)

**Comment by Dakai** [comment]
Hi, @daudix-UFO, I have the same Linux setup as you and the same error output when installing dual boot, did you find a way to fix it? Thanks.
