### ISSUE TITLE
Issues getting linux beta to work.

### ISSUE THREAD

**Issue by B3ATDROP3R** [sebanc/brunch#155]
I have a dell studio 1569. Android apps work fine but the linux beta fails to start.

**Comment by sebanc** [comment]
Hi,

I think gpu acceleration is included in the recovery image but will not work with your gpu. Could you try to turn it off in chrome://flags and then try crostini again ?

Note: with samus recovery image, you can only access chrome://flags through guest mode.

**Comment by B3ATDROP3R** [comment]
I have an Intel b450m with integrated graphics. I set the flag when I was in guest mode and Linux beta still doesn't work. I am using sammus

**Comment by sebanc** [comment]
Are you booting from usb or have you installed brunch to hdd ?

**Comment by B3ATDROP3R** [comment]
I am booting from a hard drive (I used that thing you'd want to make it boot on bios PC's) Android apps work fine but Linux beta refuses to start

**Comment by sebanc** [comment]
I don't have much control over crostini as it only globally consist in enabling the official crostini configs in the kernel so I am no sure what could be the issue on that case. If you have parameters in your bios related to graphics/virtualisation... Could you try maxing them out ?

**Comment by sebanc** [comment]
If it does not work, could you attempt to install crostini and attach to this issue the "/var/log/message" file just after it fails ?

**Comment by B3ATDROP3R** [comment]
I'll have to install it back to a flash drive because I whiped it for Debian.

**Comment by sebanc** [comment]
Found out that for crostini to launch on Gen 1 intel, you need to remove "virtio_gpu" from /etc/ui_use_flags.txt

**Comment by B3ATDROP3R** [comment]
Ooh. What does that do?

**Comment by sebanc** [comment]
It disables crostini gpu acceleration, it appears that modifying the flag in guest mode is not working.

**Comment by B3ATDROP3R** [comment]
I forgot to say that fixed it. Thank you

**Comment by B3ATDROP3R** [comment]
after using this more i have come to the conclusion that doing this will break android apps. Some randomly crash or just wont open.

**Comment by diego9090dd** [comment]
how did you do to use a chrome os in a legacy bios (mbr) ????? @B3ATDROP3R
