### ISSUE TITLE
microphone not working on xps 13 9310

### ISSUE THREAD

**Issue by 6itH** [sebanc/brunch#1557]
I'm running version 101 with kernel 5.15. Everything works perfectly but the microphone. I tried all the options but nothing worked. On Chrome OS Flex everything works fine (microphone included) with kernel 5.10

Any ideas? Thanks

**Comment by librehat** [comment]
just found out microphone not working with my Samsung Galaxy Book Pro 360 as well (also Kernel 5.15). Tried both internl_mic_fix and internal_mic_fix2, none of them works.

**Comment by channelup69** [comment]
Im using a Lenovo x1 carbon 5.10 kernal i7 11 gen and my mic works if I plug in a headset. In the audio settings i can toggle internal mic and head phone mic and both work along with the speaker toggle. Once I unplug from the head phones mic does not work. I was wondering if it was a driver issue. I had posted in another thread about SOF drivers. https://github.com/thesofproject/sof-bin

**Comment by 6itH** [comment]
Very similar specs with the xps. On my device I don't see an internal mic (but a dmic), so the internal_mic_fix wouldn't work I guess
![Screenshot 2022-06-10 18 12 29](https://user-images.githubusercontent.com/94733250/173117807-dd05673e-6b5d-4212-b8af-2f323694c168.png)

**Comment by channelup69** [comment]
![Screenshot 2022-06-10 11 21 09 AM](https://user-images.githubusercontent.com/37353868/173127330-87aaf34e-06f5-49d5-b31c-94729244ff7f.png)

**Comment by channelup69** [comment]
Yes

**Comment by 6itH** [comment]
This has been fixed with release 102. Thank you
