### ISSUE TITLE
Brunch rootfs check takes too long to finish (50s)

### ISSUE THREAD

**Issue by khanhtranngoccva** [sebanc/brunch#156]
![20200517_073752](https://user-images.githubusercontent.com/61155608/82134232-e1ec7680-981f-11ea-8a83-701efe113f0c.jpg)

**Comment by sebanc** [comment]
Hi,

The 50 seconds are not rootfs check but many things:
- 10s timeout
- partition 7 md5sum calculation
...

All those steps are necessary for brunch but croissant should boot faster if you are interested in a quicker boot.
