### ISSUE TITLE
Chrome OS repeatedly restarting.

### ISSUE THREAD

**Issue by Anuragisme** [sebanc/brunch#1571]
#1571  ChromeOS is restarting again and again after the brunch logo. How can I solve this? I am sharing the video with you.

Video Link : https://photos.app.goo.gl/Yn6jTmGtbPTjB2Pt6

**Comment by Anuragisme** [comment]
@sebanc Could you help me ?

**Comment by Anuragisme** [comment]
@tejasraman Please help me. This issue started when I turned on PWA. Whenver I turn on PWA this issue arrives.

**Comment by tejasraman** [comment]
Hi @Anuragisme I want some basic info. What - is your
- model of CPU
- brunch version
- recovery image

Does this occur if the pwa setting is off?

- Tejas

**Comment by Anuragisme** [comment]
CPU --- AMD Athlon Silver 3050U
Brunch Version --- 106
Recovery Image --- Zork


No, this did not occur when pwa setting is off.

**Comment by Anuragisme** [comment]
My system works normally until I keep the pwa setting off but when I turn it on, the system gets stuck on the Chrome OS logo and keeps on restarting form that step.

**Comment by tejasraman** [comment]
Just as a troubleshooting measure update brunch to 107 without the PWA and see if the PWA option works then.

To do this, download brunch from the github, open crosh (ctrl+Alt+t), and type these 2 commands in order:
```
shell
cd ~/Downloads
sudo chromeos-update -f yourchromeosfile.tar.gz
```
(substitute the name of the downloaded file for that file)

**Comment by Anuragisme** [comment]
No, the problem is not solved it again got stuck at chrome Os logo which
slowly turn fainter to bolder.

**Comment by Anuragisme** [comment]
@tejasraman

**Comment by Anuragisme** [comment]
Thank you so much now the issue is resolved. I reinstalled the Chrome OS with latest version files and when I turn the PWA setting on it was working well. 

Thank You so much @tejasraman

**Comment by tejasraman** [comment]
You're welcome!
