### ISSUE TITLE
Can’t expand hdd partition free space

### ISSUE THREAD

**Issue by blonqe** [sebanc/brunch#158]
Installed chrome os to hdd partition (64gb)

Img maxed out at 14gb and can’t access the rest of remaining hdd space?

Using usb method to expand data doesn’t work

**Comment by sebanc** [comment]
Hi, 

You had to select the disk image size at image creation time (when running chromeos-install) by using the -s option.

The only solution is to re-create the image with the correct size.

**Comment by blonqe** [comment]
Thanks for the reply, unfortunately every time I tried to specify size it stated “not enough room” so Installed it without -s

Do we have to take off the 10gb required? Therefore quote 54gb rather then the full 64gb?

Cheers

**Comment by blonqe** [comment]
Was being stupid! I was inputting kB instead of gb (should have taken more notice, sorry)

Though I had 62gb free I had to state 58gb
