### ISSUE TITLE
Error in installing linux ( chrome OS Version 102.0.5005.125 ) 

### ISSUE THREAD

**Issue by nameismohitkumar** [sebanc/brunch#1586]
Linux is not installing in My laptop, I have tried a lot but it is always showing the same message " Error installing Linux ". I saw old solutions for this in which they are saying to disable crostini....(.something something ) but it is not showing in my chrome://flags. �
![Screenshot 2022-07-13 8 09 31 PM](https://user-images.githubusercontent.com/98254212/178762139-03158ca4-2564-47ba-a554-461d57e18ddf.png)
�

**Comment by SuRmsu** [comment]
> Try enabling "enable updates" in the Brunch framework options. Just enable this option. Do not actually upgrade to 103 but stay on 102. See https://github.com/sebanc/brunch/blob/master/troubleshooting-and-faqs.md for information how to set the enable updates option.

It works. Don't upgrade Brunch by mistake

**Comment by Jeweldation** [comment]
> It works. Don't upgrade Brunch by mistake
What happens if you upgrade?

**Comment by block6791** [comment]
This will happen: https://github.com/sebanc/brunch/issues/1574

**Comment by nameismohitkumar** [comment]
@block6791 thanks :)
