### ISSUE TITLE
Installation on nvme

### ISSUE THREAD

**Issue by Anshu-gits** [sebanc/brunch#1596]
Im not able to run the install command on the chrono shell, fdisk cant detect my nvme internal ssd.

**Comment by Anshu-gits** [comment]
hello>??

**Comment by Taipoka** [comment]
Do you have a laptop with intel rapid storage?
If so i did install on mine doing:  
1) Install from linux mint live
2) On first boot, change the kernel to 5-XX 
* You have to change it in the boot screen to enter the configuration.

**Comment by Anshu-gits** [comment]
.
