### ISSUE TITLE
Storage is using 60 gb in system 

### ISSUE THREAD

**Issue by Anshu-gits** [sebanc/brunch#1608]
@sebanc

**Comment by tejasraman** [comment]
Huh?
We need more context. What storage? How much space does your HDD have? And are you using single or dualboot?

**Comment by Anshu-gits** [comment]
I have a nvme of 256gb and am using it in single boot mode. The storage taken my system is now 77gb
![image](https://user-images.githubusercontent.com/104699588/183724222-5649beb0-a43d-4223-ae53-6230d6f730a7.png)

**Comment by tejasraman** [comment]
Ouch...
It should only take a few GB...
Reinstall maybe?

What did you do to it?

**Comment by DTayA1** [comment]
It may just be the fact that this is running within an img, CrOS doesn't seem to mesh well with certain sizes, but 3rd party file managers etc usually detect the proper size even when the OS doesn't. Try CX File Manager, it detected the proper storage size for me.

**Comment by tejasraman** [comment]
If you installed in singleboot, an img is not used.

**Comment by tejasraman** [comment]
@DTayA1 are you using dualboot?

**Comment by Anshu-gits** [comment]
No, it was a single boot

**Comment by tejasraman** [comment]
@Anshu-gits I know that it was a single boot because you said that earlier.

> I have a nvme of 256gb and am using it in **single boot mode**. The storage taken my system is now 77gb ![image](https://user-images.githubusercontent.com/104699588/183724222-5649beb0-a43d-4223-ae53-6230d6f730a7.png)

@DTayA1 was obviously using it in **dualboot**.
The best advice I can give you is to reinstall Brunch using the guide in this repo.
