### ISSUE TITLE
What's up with the CPU support?

### ISSUE THREAD

**Issue by stxrrynight008** [sebanc/brunch#1617]
ChromeOS Flex seems to support CPUs older than Sandy Bridge without issues (e.g. my ThinkPad L512 with i5-540M) but brunch doesn't.
Is this a special thing for ChromeOS Flex or is it an issue with brunch? Please let me know. Thanks!

**Comment by sebanc** [comment]
In order to optimize chromebooks performance, chromeos recovery images are built with specific cpu instructions which target the end device cpu whereas chromeos flex is built with a limited set of cpu instructions to support more devices.

**Comment by stxrrynight008** [comment]
Alright, thanks! Before I close this, do you know any alternatives to ChromeOS with Play Store that will work on legacy devices? I have tried FydeOS but that turns out to only support GPT.

**Comment by Anurag1061** [comment]
Is Intel Kaby Lake Supported Core-i5 7th gen (Kaby Lake) Running r120 well ?
