### ISSUE TITLE
frecon[312] monitor not available, running headless!

### ISSUE THREAD

**Issue by Prismnity** [sebanc/brunch#163]
On VBox, there is text that is showed, but frecon does NOT recognize the display, which cause Chrome to be terminated infinitely

2nd, if you try to switch tty, it just straight up wont work.

**Comment by sebanc** [comment]
Hi,

Sorry but nobody has been able to run official chromeos images in a virtual machine yet and it's not supported by this project. My personal opinion is that it might maybe work with a very technical setup in a tool such as qemu but I am pretty sure it's impossible to make it work with VBox.
