### ISSUE TITLE
Touchscreen kernel commands no longer working in kernel 5.15?

### ISSUE THREAD

**Issue by clee604** [sebanc/brunch#1632]
*edit* it appears it has nothing to do with r100 vs r103, but rather kernel 5.10 (works) vs kernel 5.15 (doesn't work)

Hi there,

I'm not sure if there is a regression in the new releases or if there's something that now breaks the kernel command to invert the touchscreen. Previously using r100/chromeos100 I would use 
of_touchscreen.custom=1 of_touchscreen.invert_x=1 in the brunch kernel config to fix my touchscreen. This is the solution I found in https://github.com/sebanc/brunch/issues/1228, I have a similar cherry trail tablet.

In the new release, this doesn't seem to work anymore, it's the same with or without the extra parameters. Does this kernel configuration no longer work?

**Comment by sebanc** [comment]
Ah indeed, could you try with "input-core.custom=1 input-core.invert_x=1" ?

or "touchscreen.custom=1 touchscreen.invert_x=1" if the first suggestion does not work ?

**Comment by clee604** [comment]
"input-core.custom=1 input-core.invert_x=1" worked! Thanks!

**Comment by clee604** [comment]
maybe more of a feature request, but is there the possibility to put touchscreen x and y inversion as configuration options? or at least a way to bring up/select previously used custom parameters when entering the configuration?
