### ISSUE TITLE
Brunch R103 ==> Loading Bruch Framework loop

### ISSUE THREAD

**Issue by dneusitz** [sebanc/brunch#1666]
Just upgraded to RAMMUS 105.0.5195.134 using Brunch r103 stable 20220721
results in the boot loop ==> Loading Bruch Framework...

Saw a similar issue and tried the unstable R103 220720, but same result.
Let me know what doc you need to diagnose.
Thanks

**Comment by ameyjoshi3068** [comment]
Try latest Brunch r105 unstable 20221005 + chromeps 105

**Comment by dneusitz** [comment]
@ameyjoshi3068 

Thanks for responding.
Where can I find Brunch r105 unstable 20221005?

**Comment by ameyjoshi3068** [comment]
Here https://github.com/sebanc/brunch-unstable

**Comment by dneusitz** [comment]
Sorry
I do not understand. is there a specific file name or folder that I should be looking for in the link you gave me? @ameyjoshi3068

**Comment by ameyjoshi3068** [comment]
Just download brunch unstable release from *release* section

Since you have no acess to terminal in chromros the easiest way is to reinstall ChromeOS using 105 rammus and brunch unstable 105
