### ISSUE TITLE
booting to chromeos shows a line of grub errors

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [sebanc/brunch#1667]
installed brunch according to the installation guidelines from official website but shwoing the error when booting to chromeos. did do a reinstallation like 3 times and recreating the 99_brunch file too. please help. using fedora 37 pre-release.
![photo_2022-10-05_06-49-16](https://user-images.githubusercontent.com/78001660/193959034-06c38243-a611-4e16-8132-0979025267b7.jpg)

**Comment by sebanc** [comment]
Could you try to add "rmmod tpm" as the first line of each menuentry of the grub configuration ?

**Comment by Midnightmadwalk-coder** [comment]
u mean like sticking the the first menumetry line or above the menumetry line?

**Comment by sebanc** [comment]
Add it as the first line within each menu entry

**Comment by Midnightmadwalk-coder** [comment]
`rmmod` tpm menuentry "ChromeOS" --class "brunch" {
        img_path=/chromeos.img
        img_uuid=21cb5266-3851-4254-8b5a-a5ceea418542
        search --no-floppy --set=root --file $img_path
        loopback loop $img_path
        source (loop,12)/efi/boot/settings.cfg
        if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
                linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
                        cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path \
                        console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
        else
            	linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
                        cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
        fi
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

rmmod tpm menuentry "ChromeOS (settings)" --class "brunch-settings" {
        img_path=/chromeos.img
        img_uuid=21cb5266-3851-4254-8b5a-a5ceea418542
        search --no-floppy --set=root --file $img_path
        loopback loop $img_path
        source (loop,12)/efi/boot/settings.cfg
        linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \
                cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
        initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

**Comment by Midnightmadwalk-coder** [comment]
did u mean like this?

**Comment by sebanc** [comment]
No, this:

```
menuentry "ChromeOS" --class "brunch" {
rmmod tpm
img_path=/chromeos.img
img_uuid=21cb5266-3851-4254-8b5a-a5ceea418542
search --no-floppy --set=root --file $img_path
loopback loop $img_path
source (loop,12)/efi/boot/settings.cfg
if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params
cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
else
linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params
cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
fi
initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

rmmod tpm menuentry "ChromeOS (settings)" --class "brunch-settings" {
rmmod tpm
img_path=/chromeos.img
img_uuid=21cb5266-3851-4254-8b5a-a5ceea418542
search --no-floppy --set=root --file $img_path
loopback loop $img_path
source (loop,12)/efi/boot/settings.cfg
linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1
cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}
```

**Comment by Midnightmadwalk-coder** [comment]
Tysm, it works now 👍

**Comment by Midnightmadwalk-coder** [comment]
hi, sorry got the same issue again. now it appears like this.
![SHA_20221005_2018256670](https://user-images.githubusercontent.com/78001660/194094428-7bb7241b-7861-469e-b3ba-110827fa295c.jpg)

**Comment by tejasraman** [comment]
Are you using fedora or ubuntu?

**Comment by Midnightmadwalk-coder** [comment]
I'm using fedora.

**Comment by tejasraman** [comment]
That makes a ton of sense. Could you try rebuilding grub? Something like grub2-mkconfig  pointing at some place. My main PC is also a fedora PC so I have had some problems like this before :)

Tejas

**Comment by Midnightmadwalk-coder** [comment]
hi, which intel were you using btw?

**Comment by Midnightmadwalk-coder** [comment]
> That makes a ton of sense. Could you try rebuilding grub? Something like grub2-mkconfig pointing at some place. My main PC is also a fedora PC so I have had some problems like this before :)
> 
> Tejas

Hiz I couldn't understand ur suggestion. rebuilding grub at what different place?

**Comment by tejasraman** [comment]
I'll check and tell you. I forgot already.

Tejas

**Comment by tejasraman** [comment]
I'm using a Ryzen and fedora KDE if you need to know.

**Comment by Midnightmadwalk-coder** [comment]
> I'll check and tell you. I forgot already.
> 
> Tejas

Alright. 👍

**Comment by tejasraman** [comment]
Thanks!

**Comment by tejasraman** [comment]
It's ‘sudo grub2-mkconfig -o /etc/grub2-efi.cfg‘

**Comment by Midnightmadwalk-coder** [comment]
Did you also add rmmod TPM in your 99_brunch btw?

**Comment by tejasraman** [comment]
Yes

**Comment by Midnightmadwalk-coder** [comment]
well also what to do about the old file created here from this old command? <[drex@fedora ~]$ sudo grub2-mkconfig -o /boot/grub2/grub.cfg>. 

still showing error for me tho in grub menu

**Comment by Midnightmadwalk-coder** [comment]
> Yes, I did. It refused to boot otherwise. I also had to rebuild grub before it booted properly.
> 
> Tejas

Sorry to say this. I followed your command but still it shows this same error for some reason I don't understand. ![IMG_2022-10-22-20-02-33-463.jpg](https://user-images.githubusercontent.com/78001660/197344890-6f987ff2-4977-425c-b40d-84624d7abd9a.jpg)

**Comment by tejasraman** [comment]
Are you installing to a partition?

**Comment by Midnightmadwalk-coder** [comment]
> Are you installing to a partition?
> 

Yes a seperate partition. I'm using dual boot installation.

**Comment by tejasraman** [comment]
Weird... I'll test it and try

**Comment by Midnightmadwalk-coder** [comment]
> Weird... I'll test it and see for myself

Btw I'm sending a screenshot of my 99_brunch, incase of any error or mistake involved in it.

**Comment by Midnightmadwalk-coder** [comment]
![Screenshot from 2022-10-22 21-11-50](https://user-images.githubusercontent.com/78001660/197348240-4394552a-710c-461e-977b-95c0005c8498.png)

**Comment by tejasraman** [comment]
Looks ok. What brunch version are you using (so I can test)?

**Comment by Midnightmadwalk-coder** [comment]
> Looks ok. What brunch version are you using (so I can test)?
> 

Well I'm using latest brunch  r103 stable and for Chrome OS "volteer". Same issue when using"brya"recovery too. using 12th gen Intel i5

**Comment by tejasraman** [comment]
I can only test with “zork” but I will test with 103 stable.

Tejas

**Comment by Midnightmadwalk-coder** [comment]
thanks, btw i don't understand that message id of yours.
Tejas

**Comment by v-mod** [comment]
> > Yes, I did. It refused to boot otherwise. I also had to rebuild grub before it booted properly.
> > Tejas
> 
> Sorry to say this. I followed your command but still it shows this same error for some reason I don't understand. ![IMG_2022-10-22-20-02-33-463.jpg](https://user-images.githubusercontent.com/78001660/197344890-6f987ff2-4977-425c-b40d-84624d7abd9a.jpg)

Have you tried disabling secure boot?

**Comment by tejasraman** [comment]
This error does **not** imply a SecureBoot related issue. That would be an error like this:
![image](https://user-images.githubusercontent.com/96961804/198863950-beb8d368-6974-47a3-98e2-1934988a7382.png)

**Comment by Midnightmadwalk-coder** [comment]
So @tejasraman what may be the next step?

**Comment by tejasraman** [comment]
That's just the thing. I'll test 

1 favor: can you take a screenshot of the disks app in fedora?

**Comment by Midnightmadwalk-coder** [comment]
Ok

**Comment by tejasraman** [comment]
Thanks!

**Comment by Midnightmadwalk-coder** [comment]
> That's just the thing. I'll test it. For now I'm unsure.
> 
> 1 favor: can you take a screenshot of the disks app in fedora?

No wait. I'm so sorry for the trouble. I think that guy was right. I never enabled secure boot but it seems like it has been enabled this whole time. Just now disabled and everything works now![SGCAM_20221030_112312694.jpg](https://user-images.githubusercontent.com/78001660/198864647-9de73d05-b3dc-4bf9-bc8e-b12bdbcfcc6c.jpg)

**Comment by tejasraman** [comment]
Weird.....

If this is resolved could you close it?

**Comment by Midnightmadwalk-coder** [comment]
Btw @tejasraman if u r on telegram my username is icyfiretechbolt. My gmail id is bargunanns @ gmail . com

**Comment by Midnightmadwalk-coder** [comment]
> > > Yes, I did. It refused to boot otherwise. I also had to rebuild grub before it booted properly.
> > > Tejas
> > 
> > Sorry to say this. I followed your command but still it shows this same error for some reason I don't understand. ![IMG_2022-10-22-20-02-33-463.jpg](https://user-images.githubusercontent.com/78001660/197344890-6f987ff2-4977-425c-b40d-84624d7abd9a.jpg)
> 
> Have you tried disabling secure boot?

Thanks. U were right. afaik I never enabled secure boot but to my surprise it seems to be enabled by some unknown actions. Just verified and disabled it. Now works.

**Comment by Midnightmadwalk-coder** [comment]
> Weird.....
> 
> If this is resolved could you close it?

Ok

**Comment by UnsuitableFollower** [comment]
My mine same error, how to fix that?
I using fedora 37

**Comment by tejasraman** [comment]
@UnsuitableFollower did you add `rmmod tpm` to the grub file?

This is a well documented issue with the script when it comes to fedora...

**Comment by UnsuitableFollower** [comment]
> @UnsuitableFollower did you add `rmmod tpm` to the grub file?
> 
> This is a well documented issue with the script when it comes to fedora...

Already, still.
![Screenshot from 2022-12-20 23-12-53](https://user-images.githubusercontent.com/88485719/208713826-c0fb92f9-cb6c-4589-a8c7-df974dbda697.png)

**Comment by tejasraman** [comment]
Is secure boot enabled?

**Comment by UnsuitableFollower** [comment]
Already disable tho

**Comment by tejasraman** [comment]
Please take a picture of the errors...

**Comment by UnsuitableFollower** [comment]
![PXL_20221220_232752623](https://user-images.githubusercontent.com/88485719/208716991-02e84216-f281-453e-8579-8bea0e75a400.jpg)

**Comment by tejasraman** [comment]
Did you [update grub](https://fedoraproject.org/wiki/GRUB_2) after adding the line?

**Comment by UnsuitableFollower** [comment]
Already, hmm idk only fedora have this issue, looks like btrfs moment.

**Comment by tejasraman** [comment]
This happened to me too :D

Adding the line and updating it solved it.

I'm currently using Fedora 37 (KDE)


![PXL_20221220_163946155.jpg](https://user-images.githubusercontent.com/96961804/208719155-b182a618-11bd-4a0c-bedf-54568b0a7a42.jpg)

**Comment by tejasraman** [comment]
And is the partition that the brunch image is on btrfs? That will never in a million years work

**Comment by tejasraman** [comment]
If you install grub-customizer it should show in the menu

![PXL_20221220_164143561.jpg](https://user-images.githubusercontent.com/96961804/208719605-6f766158-5c08-4b82-9421-a8147f36cd88.jpg)

**Comment by UnsuitableFollower** [comment]
> And is the partition that the brunch image is on btrfs? That will never in a million years work

I mean btrfs on fedora not chromeos XD




> If you install grub-customizer it should show in the menu
> 
> ![PXL_20221220_164143561.jpg](https://user-images.githubusercontent.com/96961804/208719605-6f766158-5c08-4b82-9421-a8147f36cd88.jpg)

Ik Still not working:")

**Comment by tejasraman** [comment]
I know.... I went out of my way to avoid btrfs when I installed fedora even though it's the default...

Someone asked if btrfs was possible with brunch. Spoiler - it's not.

Try updating grub, then rebooting.

One more question: what is your laptop model and recovery image?

**Comment by UnsuitableFollower** [comment]
> I know.... I went out of my way to avoid btrfs when I installed fedora even though it's the default...
> 
> Someone asked if btrfs was possible with brunch. Spoiler - it's not.
> 
> Try updating grub, then rebooting.
> 
> One more question: what is your laptop model and recovery image?

Acer aspire 3 A314-32-C52Q (Rammus)
Anyway I already done with fedora, I installed archlinux and try install ChromeOS now working. *but I have bug hardware acceleration disable idk why*
![Screenshot 2022-12-21 9 21 28 AM](https://user-images.githubusercontent.com/88485719/208807100-21756b9a-96de-4a63-8482-ca351e46bc05.png)

**Comment by tejasraman** [comment]
How do you know that hw accel is disabled?

**Comment by UnsuitableFollower** [comment]
> How do you know that hw accel is disabled?

Very laggy

> Also, is it this? https://mdp.co.id/product/55349
> 
> I would recommend the octopus image for ApolloLake celerons like the n4000. IME it works better :D

Yes :), you have linkfoctopus image?

**Comment by tejasraman** [comment]
Here: https://cros.tech/device/octopus

**Comment by UnsuitableFollower** [comment]
> Also, can you type chrome://GPU into the browser and check if acceleration is enabled?

I think it's working but idk why very lagging

![PXL_20221221_095211940](https://user-images.githubusercontent.com/88485719/208810028-326aab24-3761-408e-ab9c-110baf2c4e6c.jpg)

**Comment by tejasraman** [comment]
Idk but try octopus just for troubleshooting purposes

It works the same way, just use the octopus image instead of the rammus one

**Comment by usmaanmohammed** [comment]
Same error please help

**Comment by usmaanmohammed** [comment]
![IMG20250525021106.jpg](https://github.com/user-attachments/assets/524f66ce-523d-4d6a-8529-eca37700e357)
