### ISSUE TITLE
Brunch bootloop

### ISSUE THREAD

**Issue by NovenyEteto** [sebanc/brunch#1673]
I installed Brunch on my Lenovo IdeaPad g550 but when I start my laptop I get in a bootloop

**Comment by NovenyEteto** [comment]
Video https://photos.app.goo.gl/G6Hs3C8BbgMA3FTA6

**Comment by tejasraman** [comment]
You're using a Core2Duo era chip. Try Chrome OS flex, Brunch won't work.

**Comment by NovenyEteto** [comment]
But flex doesn't have android apps

**Comment by tejasraman** [comment]
I know... But brunch won't work on your laptop because your CPU is a Core2 generation chip

**Comment by NovenyEteto** [comment]
Well then that is sad
