### ISSUE TITLE
Brunch Framework Bootloop

### ISSUE THREAD

**Issue by piemanny** [sebanc/brunch#1690]
I'm not sure how to describe the error. Firstly I just want to say that Chrome OS was working on my PC. I had linux apps running and android apps running. Then the whole system crashed and when I tried to boot it again, it would show the splash screen for 2 seconds, and then restart again. 

I'm running a 5th gen i7 Dell laptop

**Comment by ameyjoshi3068** [comment]
Have you updated chromeos recently? or do you have enable_updates option turned on? Can you tell which chromeOS and brunch version you were using?

**Comment by piemanny** [comment]
I have just clean installed it again, which is a pain but there was nothing i could do

**Comment by ameyjoshi3068** [comment]
Please close this issue if it is solved

**Comment by piemanny** [comment]
It is not solved but I will close this issue though i think many others will discover this issue again
