### ISSUE TITLE
Screen auto-rotation

### ISSUE THREAD

**Issue by cobernicus** [sebanc/brunch#17]
Hi. First of all, thank you very much for your work. On my Lenovo D330 everything works well except auto-rotate. I tried "options=enable_sensors" but this did not work for me. My screen is always in portrait orientation. What can I do ?

![9d9c45d9-1247-428c-8ce6-48b16f464b68](https://user-images.githubusercontent.com/62382994/77084296-734d9100-6a07-11ea-8541-dca2217a7410.jpg)
![719a9350-1b9c-419b-b116-61e6f95e5f03](https://user-images.githubusercontent.com/62382994/77084311-78aadb80-6a07-11ea-809c-a0f3604a9e7c.jpg)

**Comment by sebanc** [comment]
Hi,

The screen will only rotate in chromeos when in tablet mode, what you can do first is change the default desktop orientation in settings.

When you fold your laptop, does it trigger tablet mode ? (the desktop should change a bit)
It 's only once you are in tablet mode that the sensors can work.

If something is still not working, could you attach a dmesg and an lsmod to this issue ?

Thank you.

**Comment by cobernicus** [comment]
Yes without keyboard Chrome os enable tablet mode but auto rotation is not working.

> could you attach a dmesg and an lsmod to this issue ?

Yes if you tell me how

**Comment by sebanc** [comment]
Go to chromeos shell:

then type:
- "cd ~/Downloads"
- "dmesg > dmesg"
- "lsmod > lsmod"

You will then have dmesg and lsmod files in your Downloads folder, could you attach them to this issue ?

**Comment by cobernicus** [comment]
[lenovo_d330.zip](https://github.com/sebanc/brunch/files/4356395/lenovo_d330.zip)

**Comment by sebanc** [comment]
Hi,

I am sorry but your laptop is not equipped with the standard hid sensors but with a specific driver "bmc150_accel" which is unsupported.
