### ISSUE TITLE
Network adapter not detected

### ISSUE THREAD

**Issue by halcut** [sebanc/brunch#170]
Installation went well on my desktop which previously had Linux mint. However after booting it is stuck on initial setup as it could not detect any network connection. I cannot proceed any further as I need to select a network connection first. Desktop only has wired connection.. no wifi adapter. Pls help.

**Comment by sebanc** [comment]
Hi,

Could you try the release I have just uploaded in the "brunch-testing" repo (not this one), I have added support for more ethernet adapters.

If it still does not work, could you attach a dmesg to this issue ? (run "dmesg > ~/Downloads/dmesg.txt" in crosh shell and attach dmesg.txt from your downloads directory)

**Comment by halcut** [comment]
Thanks. Let me try it.

**Comment by halcut** [comment]
It worked. Thanks a lot.
