### ISSUE TITLE
Delayed trackpad on Lenovo YOGA 6 82ND

### ISSUE THREAD

**Issue by oreo-zip** [sebanc/brunch#1702]
I have tried brunch on v105, and it was a NIGHTMARE! Everything worked if you use the right settings. But if you use the trackpad, all hope is lost in the world and you must install linux. I want to use stock chromeOS and not flex. But I cannot.

**Comment by ycavan** [comment]
Have you tried any of the fixes in the config menu?

**Comment by oreo-zip** [comment]
Yup. Made this before I disabled native_chromebook_image (sorry for no code markup, on an iPhone) and it worked!
