### ISSUE TITLE
Acer Spin 1 - can't install on its eMMC built-in storage

### ISSUE THREAD

**Issue by leosel** [sebanc/brunch#171]
Acer Spin 1 - can't install on its eMMC built-in storage, boot to linux mint successfully, but after executing to terminal sudo sh install.sh, it says can't update sda/dev. won't install on the internal storage

**Comment by sebanc** [comment]
Sorry but I do not support scripts made by others, please create an issue on the repo of the guy who made the script or follow the official instructions.
