### ISSUE TITLE
Atheros NFA435 Wifi not working

### ISSUE THREAD

**Issue by leosel** [sebanc/brunch#172]
Atheros NFA435 Wifi not working, it's was disabled. Even by sliding on the settings to turn it on, it won't let it enable. Please help

**Comment by sebanc** [comment]
Hi, could you post a dmesg (run "dmesg > ~/Downloads/dmesg.txt" in crosh shell and attach the dmesg.txt file from your downloads folder to this issue) ?

**Comment by leosel** [comment]
Thank you for the respond. anyway i already found a way to make it work, still testing it on my acer spin 1, I'll report it if i found some more errors.
