### ISSUE TITLE
ES8336 broken audio

### ISSUE THREAD

**Issue by elfametesar** [sebanc/brunch#1749]
Support in Linux kernels for this audio card is fairly new and the mainline kernel 6.1 and above has commits that get it working. Can these commits be cherry picked and implemented? 

![image](https://user-images.githubusercontent.com/58091473/210655404-88f4e9e5-c398-4ad3-bef7-28de5c0e4031.png)

![image](https://user-images.githubusercontent.com/58091473/210655447-ad964287-8b2f-4d9a-ad9f-e228cb386e5e.png)

**Comment by mirek190** [comment]
yep ... for me with that audio es8336 not working either ...

**Comment by tejasraman** [comment]
Hi @elfametesar @mirek190 6.1 is now in the unstable builds!

**Comment by mirek190** [comment]
> Hi @elfametesar @mirek190 6.1 is now in the unstable builds!

Yea ..but kernel 6.1 ans sof drivers requires new sof binaries 2.0+ and ucm .

I actually made my own driver for kernel 5 15 and is compatible with old sof binaries.

**Comment by tejasraman** [comment]
I know… see my attempts to get steamdeck audio on ChromeOS. A lot of outdated components which makes something as simple as UCMs impossible.

But seriously, submit a PR to Brunch Unstable. We’d love to have that driver available in Brunch.

**Comment by mirek190** [comment]
My driver is for intel sof 8336. 
AMD has a different one.

**Comment by tejasraman** [comment]
@mirek190 I know, just saying about a similar issue.

**Comment by mayaru** [comment]
Hi @mirek190 
I have the same problem with the intel sound card. any chance you can share your driver so i can test it out?
Thanks a lot

**Comment by ashah-apriori** [comment]
Not working for me too, and manjaro works with sound. not sure how to make it work with brunch. i tried building a kernel and I also tried adding sof drivers. but not working yet.
