### ISSUE TITLE
How to install Chrome OS on SSD? / USB Boot only Shows the USB Flashdrive

### ISSUE THREAD

**Issue by Diotrihhi** [sebanc/brunch#175]
How can I install Chrome OS with Brunch on my SSD? I can boot with my USB stick, but then only this drive is shown, I don't see my SSD.

**Comment by sebanc** [comment]
Hi,

If you never had linux installed, I can only guess that you have to change your bios SATA setting from RAID to AHCI. (warning: changing this setting this will require you to reinstall windows)

**Comment by primetimelive** [comment]
I had the same problem.

I did 
`sudo lsblk`

and found it was listed as mmcblk1.
