### ISSUE TITLE
Attempting to boot Chrome OS on Hades Canyon NUC8i7HVB



### ISSUE THREAD

**Issue by nathaneltitane** [sebanc/brunch#1767]
I am testing the boot process through a USB install before committing to an nvme install on the device.

The hardware configuration is weird as the computer uses an Intel CPU with an amd GPU, namely:

- Board Chipset Mobile Intel® HM175 Chipset
- Processor Included Intel® Core™ i7-8809G Processor with Radeon™ RX Vega M GH graphics

Brunch has reconfigured roots on first boot as expected and now all I get is the white chrome os logo.

is there any way past this for this sort of configuration?

EDIT:

image used was version 107 recovery rammus/leona
now attempting process with rammus/shyvana

EDIT 2:

neither of the two images worked. same result.

**Comment by tejasraman** [comment]
Rammus Leona and shyvana images are exactly the same, no one seems to realize this. 

Could you please try the octopus recovery image?
