### ISSUE TITLE
My Bluetooth is completely dead and not even showing the option.

### ISSUE THREAD

**Issue by Anuragisme** [sebanc/brunch#1769]
@tejasraman Bluetooth in my Chrome OS is completely gone. In the morning it was working well. I tried to charge a phone via usb suddenly my Chrome OS shut down and since then Bluetooth is not working.

**Comment by tejasraman** [comment]
Have you tried manually updating brunch to the same version? Also, what is the output of `lspci | grep Wireless` (if you have a wifi/BT combo card like most laptops)

**Comment by Anuragisme** [comment]
I have reinstalled Chrome OS thrice but the Bluetooth option is completely dead. 


But where to put this command.

**Comment by Anuragisme** [comment]
Here is the screenshot
(https://user-images.githubusercontent.com/99806758/215455044-f71ee864-dac2-44ab-ade1-dd2173d20953.png)

**Comment by Anuragisme** [comment]
Here the output of the command 
![image](https://user-images.githubusercontent.com/99806758/215455858-ca505cf9-ca3b-4727-b3fa-02580cf893b3.png)

**Comment by tejasraman** [comment]
Enable 8821ce in the menu with the PWA option.

**Comment by Anuragisme** [comment]
@tejasraman , BUt from where to enable this. I don't know how can I do that?

**Comment by tejasraman** [comment]
Go to crosh (Ctrl+Alt+T), type `shell`, and then type `sudo edit-brunch-config`. Enable 8821ce as well as any other options (such as PWA) and reboot. Remember to use kernel 5.10 (recommended) or 5.15.

Tejas

**Comment by tejasraman** [comment]
@Anuragisme is this resolved?

**Comment by Anuragisme** [comment]
@tejasraman Actually the problem was in my hardware.So, I got it repaired
in the service centre.

Thank You for your support and help, I would be very grateful to you.

**Comment by tejasraman** [comment]
You're welcome @Anuragisme
