### ISSUE TITLE
Screen resolution is wrong after updating. 

### ISSUE THREAD

**Issue by theportal2** [sebanc/brunch#177]
I installed chrome os and everything was good but i was running chrome os 80 so i updated to 81.  After that my screen size is small, see photos
![IMG_2020-05-21-01-14-53-030](https://user-images.githubusercontent.com/65706166/82539196-e657ae80-9b01-11ea-9d49-52a76b2cabdb.jpg)
![Screenshot 2020-05-21 at 1 14 25 AM](https://user-images.githubusercontent.com/65706166/82539209-ece62600-9b01-11ea-8e08-4a82754e7805.png)Any fix?

**Comment by sebanc** [comment]
Hi,

With r81, google changed the shelf size, you can restore it with a flag I don't remember right now but that you will find easily on chromeos reddit.
Aside from that maybe google changed something with dpi calculation but it is not related to brunch. You can also use the resolution slider in display settings to adapt your screen size.

**Comment by FaiekA** [comment]
Hi - I installed Chrome - everything's working great - thanks! - one issue i can't get a higher resolution then 1024×768 - running my PC with my TV so at that resolution it's not great.
Any suggestions will be appreciated 
Thanks

**Comment by sebanc** [comment]
How is your pc connected to your tv ? hdmi or usb hub display port ?

**Comment by FaiekA** [comment]
Hi - via VGA

**Comment by sebanc** [comment]
Your graphic card is i915 ?

**Comment by FaiekA** [comment]
Intel HD Graphics Family 
HD graphics 2500

**Comment by theportal2** [comment]
i don't think i have resolution slider in display settings
![Screenshot 2020-05-21 at 11 50 54 AM](https://user-images.githubusercontent.com/65706166/82594749-6c531400-9b59-11ea-99cd-843f244f28c2.png)

**Comment by FaiekA** [comment]
Thanks- I moved the slider to tiny - doesn't really make a differance.
- Windows is obviously fone 
- Linux I had the same problem used  Xrandr commands to fix that. 
Only chrome now - I know it would look great if I can get this sorted ....

**Comment by FaiekA** [comment]
Your screen shot looks great 1980x1080 if I could only get there...

**Comment by sebanc** [comment]
Could you try this new release ?
https://github.com/sebanc/brunch-testing/releases

**Comment by FaiekA** [comment]
Ok - Thanks will do 
Will let you know once installed

**Comment by FaiekA** [comment]
Hi - Thanks for the assistance
Still the same 1024×768 highest setting
( triple boot System ) - with win2grub
Procedure Followed 
Downloaded brunch-testing/release from link - copied in to Chrome OS folder on USB drive.
Ran in Linux Ubuntu DDE ..
Run multi_boot.sh and install as per Kedar instructions
Completed installations successfully. 
You think it could be my internal video card ?
I don't know -

**Comment by sebanc** [comment]
Actually I did not really understand that there were 2 different reports in this issue and kind of mixed them both.

@theportal2 The slider can be seen on your printscreen (between Tiny / Huge settings, currently set on tiny), the native resolution indicates 1920x1080 is it correct ?

@FaiekA If it is the same with the linux kernel, could you try booting with "vga=ask" added to the kernel command line ? It should let you select the resolution from a list

**Comment by FaiekA** [comment]
@sebanc it's my fault I should have opened a new issue -  instead of jumping in on thePortal2 thread --- Yes I hade the same issue with Ubuntu DDE and fixed it via xrandr.
If you could explain where and how to add this as I'm fairly new to this.
I would really appreciate it - again this is excellent - I just cant get enough of it ( hooking up with the rest of my google home stuff )

**Comment by sebanc** [comment]
@FaiekA No worries, open crosh (CTRL+ALT+T), type "shell", run "sudo edit-grub-config" and add a space and "vga=ask" after cros_debug. Then CTRL+x, "y" to save and enter to confirm.

On next reboot, you should get a prompt to choose which resolution to use.

**Comment by FaiekA** [comment]
@sebanc - Hi no luck - didnt prompt at all  - here's the code from crosh 
`menuentry "ChromeOS" {
  regexp --set disk "(^.+)(,gpt)" $root
  linux ($disk,7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off cros_secure cros_debug vga=ask
  initrd ($disk,7)/initramfs.img
}
`

As well as a screen shot - is it normal for the display to be unknown .

![Screenshot 2020-05-23 at 20 18 04](https://user-images.githubusercontent.com/52759676/82737682-1043e780-9d33-11ea-8601-ff2cb2127460.png)
 As you can see it just too big  my screens a  42"

**Comment by FaiekA** [comment]
It might be time to invest in a graphics card and see what happens.

**Comment by sebanc** [comment]
@FaiekA Could you try adding to the kernel command line "video=1920x1080-32" ?

**Comment by FaiekA** [comment]
@sebanc  Ok that will be in the place of vga=ask ?

**Comment by sebanc** [comment]
yes, exactly

**Comment by FaiekA** [comment]
@sebanc will do - Thanks

**Comment by FaiekA** [comment]
@sebanc - Hi been a bit busy - finally got it working with "video=1920x1080-32" 
Had to update the detail in the grub customiser app.
But thank a million for your assistance - keep up the great work, cant wait to see whats next.
![Screenshot 2020-05-27 at 13 56 28](https://user-images.githubusercontent.com/52759676/83016636-922d5c80-a022-11ea-972e-5165d3f3c7ac.png)

Thank again
