### ISSUE TITLE
Android Stopped Working After r109 Update [IMPORTANT]

### ISSUE THREAD

**Issue by islekcaganmert** [sebanc/brunch#1772]

**Comment by islekcaganmert** [comment]
Switching to Another Recovery is Solved.

Rammus Leona having difficulties with brunch r109, Shyvana is great.

**Comment by tejasraman** [comment]
@islekcaganmert afaik Rammus is unibuild and there is no real difference between Leona and Shyvana. Probably just a reinstall fixed it
