### ISSUE TITLE
remap function keys?

### ISSUE THREAD

**Issue by tungmeister** [sebanc/brunch#178]
@sebanc is there any way to remap the function keys so that they correspond with the correct keys?

**Comment by sebanc** [comment]
No, sorry I don't know if it is possible

**Comment by tungmeister** [comment]
No worries, it's the only thing that's slightly annoying - having to remember to press F3 for page refreshes and trying to remember which buttons correspond to brightness and volume. Are they hard coded?

**Comment by kitakar5525** [comment]
I guess you mean this setting?
Settings -> Device -> Keyboard -> "Treat top-row keys as function keys"

**Comment by sebanc** [comment]
Yes, it's hardcoded:
https://support.google.com/chromebook/answer/1047364?hl=en

Apparently though there is a setting to “Treat top-row keys as function keys”:
https://beebom.com/how-enable-function-keys-chromebook/

**Comment by sebanc** [comment]
@kitakar5525 Thanks ! beat me to it
