### ISSUE TITLE
Stuck on booting Kernel, then restarts. AMD processor and using zork image.

### ISSUE THREAD

**Issue by bruh-person** [sebanc/brunch#1785]

**Comment by bruh-person** [comment]
INFO: MBR LEGACY BIOS SYSTEM, 64B SYSTEM

**Comment by tejasraman** [comment]
Ok, @bruh-person what's your CPU? Just "an AMD processor" doesn't suffice

**Comment by Priyanshu6517** [comment]
Same issue I have an amd a6 4400m cpu

**Comment by bruh-person** [comment]
I use legacy BIOS and I will get the processor now

**Comment by bruh-person** [comment]
Also, you are very late.

**Comment by tejasraman** [comment]
@Priyanshu6517 An A6-4400M won’t work with brunch (it’s based on the Piledriver architecture from the Trinity series. The only AMD that will work are a very small subset of newer A-series CPUs and all Ryzen CPUs)

**Comment by tejasraman** [comment]
@bruh-person what do you mean “late”?

**Comment by bruh-person** [comment]
> @bruh-person what do you mean “late”? And what’s your CPU?

bruh i posted 3 weeks ago and you come now

**Comment by bruh-person** [comment]
I'm getting it.

**Comment by bruh-person** [comment]
apparently it is a AMD Turion 64 X2 Mobile Technology TL-60 (2) @ 800MHz

**Comment by bruh-person** [comment]
what i got from neofetch in partedmagic
:\

**Comment by tejasraman** [comment]
@bruh-person thats incompatible, maybe try chromeos flex?

**Comment by bruh-person** [comment]
the pc i'm using right now is **Ryzen**

**Comment by bruh-person** [comment]
so i should just use a random image or something until it works :+1:
@bruh-person

**Comment by tejasraman** [comment]
Is this a joke? (AMD Turion 64 X2 Mobile Technology TL-60 (2) @ 800MHz)

**Comment by bruh-person** [comment]
sure if you want it to be

**Comment by tejasraman** [comment]
Ok what computer are you trying to install ChromeOS on?

**Comment by bruh-person** [comment]
laptop

**Comment by bruh-person** [comment]
I'm using my desktop pc to github issues

**Comment by tejasraman** [comment]
Oh, the laptop has the turion? Ok so you can't install it on the laptop (the CPU is from 2007. Could you try ChromeOS flex?) but it would work with zork on the desktop.

**Comment by bruh-person** [comment]
ChromeOS Flex doesn't support Google Play Store apps: https://support.google.com/chromeosflex/answer/11542901?hl=en#:~:text=Supported%20VMs%20and%20apps,Android%20apps%20or%20Google%20Play.

**Comment by bruh-person** [comment]
and i'm installing it on a usb

**Comment by tejasraman** [comment]
That's true, but Brunch doesn't support your CPU and Flex will...

Also, the certified models for flex don't matter - every PC I've tested works with it, even really old stuff (2008, 2011)

**Comment by tejasraman** [comment]
That's true, but Brunch doesn't support your CPU and Flex will...

Also, the certified models for flex don't matter - every PC I've tested works with it, even really old stuff (2008, 2011)

**Comment by bruh-person** [comment]
also i could use a vm on the desktop, since vmware just replicates host cpu and stuff :\ but why wouldn't brunch support VMs?

**Comment by tejasraman** [comment]
Because v,ware virtualizes your gpu.

**Comment by bruh-person** [comment]
QEMU?

**Comment by tejasraman** [comment]
Not unless you want unaccelerated... and IME it doesn't work at all in qemu

**Comment by tejasraman** [comment]
(see this image:)
![Screenshot 2023-03-04 074200](https://user-images.githubusercontent.com/96961804/222915425-3e634c1b-aac9-42d9-a821-508a3a383b36.png)

**Comment by bruh-person** [comment]
> (see this image:) ![Screenshot 2023-03-04 074200](https://user-images.githubusercontent.com/96961804/222915425-3e634c1b-aac9-42d9-a821-508a3a383b36.png)

ya ok

**Comment by tejasraman** [comment]
So do you understand that you cannot install brunch on your laptop?

(Try fydeos as well, it has Android support but isn’t ChromeOS per se)

**Comment by bruh-person** [comment]
y

**Comment by bruh-person** [comment]
ok
