### ISSUE TITLE
Brunch works on StoneyRidge and 2nd Gen Intel

### ISSUE THREAD

**Issue by tejasraman** [sebanc/brunch#1797]
@sebanc I tested Brunch r109-stable and [this unstable build ](https://github.com/sebanc/brunch-unstable/releases/tag/r110-unstable-20230224) on SandyBridge and StoneyRidge and they work fine. Is there a reason why the readme no longer lists these as supported platforms?

**Comment by sebanc** [comment]
Which chromeos recovery image / version did you use for the SandyBridge test ? Is the android subsystem fucntional ?

**Comment by tejasraman** [comment]
I used rammus. Android and crostini are functional. I'll send screenshots later if you'd like.

**Comment by sebanc** [comment]
Devices with Intel Gen below 4 stopped working a while ago (around r101) due to some incompatible cpu instructions used by ChromeOS, it is possible that something changed again recently. What are your device's specs ?

(Regarding AMD StoneyRidge, the number of devices that work with grunt recovery image is so limited that I removed it completely from compatibility)

**Comment by tejasraman** [comment]
Core i5 2435M

**Comment by tejasraman** [comment]
I'll send screenshots soon (in less than an hour.

**Comment by tejasraman** [comment]
It's booting but **what's the MacBook T2 kernel?** (Using 5.15 for my test as that's what I used last time)

**Comment by tejasraman** [comment]
Nevermind, I have a login loop with nami. Trying rammus or coral next?

**Comment by tejasraman** [comment]
Ok trying rammus with 5.4 right now...

**Comment by tejasraman** [comment]
Looking through for rammus and nami there are illegal opcode errors (missing instructions)

Coral works surprisingly

**Comment by tejasraman** [comment]
Ok cut that, Coral doesn't work. It seemed like it did... It works on IvyBridge but not Sandy Bridge (tbh rammus works on ivy too)
