### ISSUE TITLE
No audio Lenovo Duet i5

### ISSUE THREAD

**Issue by manelscout4life** [sebanc/brunch#1798]
i5-1235u w/AX211. 

Wifi only works on the 0228 unstable with steamdeck kernel but audio does not work.

Audio and wifi both work on FydeOS 16.

Any ideas to troubleshoot? I am using Brya 110 recovery.

**Comment by sebanc** [comment]
You can try the latest brunch-unstable build, select kernel 6.1 in the configuration menu and enable "snd-intel-dspcfg.dsp_driver=1" kernel parameter.

https://github.com/sebanc/brunch-unstable

**Comment by manelscout4life** [comment]
That fixed it. Thank you! I did stay on the steamdeck kernel though. Wifi was not working for me on the 6.1 kernel.
