### ISSUE TITLE
using ChromiumOS instead of ChromeOS

### ISSUE THREAD

**Issue by c4ttysam** [sebanc/brunch#1805]
can it be possible to use ChromiumOS

**Comment by ccchan234** [comment]
I am on same ship, i want to dual boot win10 (bitlocker protected) /w os flex.

the author told me yes,
we can use os flex /w brunch, and dual boot.
yet, using his other tool linuxloop is even better.

i haven't tried, could only try later.

**Comment by c4ttysam** [comment]
linux loop is good, im checking it. ChromeOS flex uses entirely different partitions than chrome/chromiumos. it should be possible to boot chromium os as looped disk images with it, lemme check
