### ISSUE TITLE
CN60 doesn't load rammus, samus,  or teemo. 

### ISSUE THREAD

**Issue by EvoGier** [sebanc/brunch#1807]
I'm pretty new to the whole 'brunch' thing, but I had Mr. Chromebox's firmware installed and was running Windows 10 until I had to deal with the reality of how 32 gigs for Windows isn't exactly gonna cut it. I would've just sucked it up or kept it on the stock firmware... but its support stopped in 2019! Does anyone know of a supported recovery image & brunch version that would work with this machine? (Oh yeah the machine's got 12GB of ram and 32GB of storage with the Intel Celeron 2955U).

**Comment by tejasraman** [comment]
You can get one of [these drives](Transcend 512GB SATA III 6GB/S MTS430S 42 mm M.2 SSD 430S Solid State Drive TS512GMTS430S https://a.co/d/5VVqy1T) to upgrade a CN60.

Also, can you enable verbose mode and tell me the boot error?

@EvoGier
