### ISSUE TITLE
Never used brunch because heard update sucks. But anyway to deal /w it? reinstall?

### ISSUE THREAD

**Issue by ccchan234** [sebanc/brunch#1809]
hi,

finally i think the best thing for me will be a 10inch x86 dual boot win10+chromeos FLEX.

flex, i guess is specifically ENGINEERED NOT to dual boot for specific reasons.

so i turn to brunch for dual boot.

yet i heard even using original google chromebook images, there could be update problem.

may i ask if i use brunch /w flex, it will be the same?

and how to deal /w the update problem?

is it that files are always safe there, and just for each update, i have to manually install once again and its done till next update?

thank you.

**Comment by sebanc** [comment]
If your hardware is compatible with chromeos flex and you just want to dualboot, you should use this:
https://github.com/sebanc/linuxloops

As chromeos is not supposed to be dualbooted, there is always a chance it will break but the risks should be much more limited with this other project as it barely changes the OS files.

**Comment by ccchan234** [comment]
i found some directions in linuxloop s readme.md

i will try later, and will try to keep win10 on bitlocker.

let's see

thx
