### ISSUE TITLE
Can't put my broadcom WiFi working

### ISSUE THREAD

**Issue by Stecknight** [sebanc/brunch#181]
Hey guys,

I would like to thank you for this amazing version. 

Could you help me since I can't get my WiFi adapter working. Its a broadcom WiFi adapter and in Linux distros I usually get that working by running the driver manager in the Linux UI.

Some enlightment here will be more than welcome.

**Comment by midi1996** [comment]
add `options=broadcom_wl` in your boot arguments.

**Comment by Stecknight** [comment]
It worked, thanks. Now just need to make this permanent.

**Comment by sebanc** [comment]
run "sudo edit-grub-config" from crosh shell to make it permanent

**Comment by Stecknight** [comment]
Worked fine. Thank you so much for your help.

**Comment by sebanc** [comment]
You are welcome
