### ISSUE TITLE
tablet mode

### ISSUE THREAD

**Issue by caleb-gamer** [sebanc/brunch#1830]
i have a asus laptop i use chrome os for school.
its one of those laptops that can flip all the way around. i want to know if there is away to get tablet mode to turn on by its self when i flip it inside out?

**Comment by XenHat** [comment]
Try setting `force_tablet_mode` with the brunch config utility

**Comment by caleb-gamer** [comment]
1. That forced tablet mode even when the laptop isn't in table mode
2. This post was so old that the laptop is long broken. Lol
