### ISSUE TITLE
Play store not opening

### ISSUE THREAD

**Issue by au79912** [sebanc/brunch#184]
Non of the google play stores apps are opening after the firsst boot
I deleted the google sync but its still not working
Any ideas on how to fix this?

**Comment by au79912** [comment]
im using a dell lattitude E6440

**Comment by sebanc** [comment]
Hi,

Are they working correctly on first boot and not after or are they not even opening on first boot ?

**Comment by au79912** [comment]
it was working fine on the first boot. after shutting down and rebooting its stuck on loading

**Comment by sebanc** [comment]
Your issue seems similar to #74, could you try letting the system rest 2 minutes on the login screen before logging ?

**Comment by Narayanbhat166** [comment]
Same issue here, but it's not working on the first boot itself. It says setting up Google Play and then fails

**Comment by au79912** [comment]
> Your issue seems similar to #74, could you try letting the system rest 2 minutes on the login screen before logging ?


waiting 2 mins after booting worked
thanks!

**Comment by sebanc** [comment]
@Narayanbhat166 Could you try deleting google sync ?
https://support.google.com/chromebook/answer/2914794?hl=en

Also, what are your laptop/pc specs ?

**Comment by Narayanbhat166** [comment]
Also there are frequent lags, it becomes unresponsive for about 30 seconds. Iam unable to install linux virtual machine on it

Laptop specs:
Intel i5 4th gen
Rammus recovery release 80

**Comment by sebanc** [comment]
Try deleting google sync and updating to r81 stable brunch if you are not on it. Also, do you have a dual gpu ?
