### ISSUE TITLE
Support for Amd radeon hd 7570?

### ISSUE THREAD

**Issue by halcut** [sebanc/brunch#185]
Hi Sebanc - Are AMD/ATI gpus supported? I tried to use discrete graphic card (Amd radeon hd 7570) instead of integrated Intel HD graphics and after boot its stuck on Chrome screen.

**Comment by sebanc** [comment]
Hi, no there is no support for userspace support for gpu other than intel in chromeos recovery images, I left the gpu drivers enabled in the kernel as some features might still work like hdmi output but that's mainly it.
