### ISSUE TITLE
Sound..

### ISSUE THREAD

**Issue by geofrey89** [sebanc/brunch#189]
Hi .
Is there a way to have maximum sound like in windows.. 
Huawei mateBook hz-w09.
Thanks

**Comment by sebanc** [comment]
Hi,

Warning: Modifying sound output volume can permanently damage your speakers so be cautious while attempting any of this.

The different things you can try:
- browse linux forums to see if there is an "official" solution to this problem for your device
- run "alsamixer" and try to see if some volume settings can be increased
- use "cat /proc/asound/cards" to identify your soundcard and modify sound volume directly in the related ucm files (located in /usr/share/alsa/ucm)
