### ISSUE TITLE
Chromeos reboots randomly occasionally 

### ISSUE THREAD

**Issue by Mou786Aha** [sebanc/brunch#1901]
Sometimes while doing important work, Chromeos reboots randomly. So far I've seen this issue while using Linux apps. I'm on an SSD. I'm not sure whether it happens while Linux is not running or not. The cooling fan of my laptop works fine. It doesn't have any hardware issue as far as I know. On other OS, it never reboots automatically. It doesn't show rebooting or something else. It crashes directly.
I'm on Inspiron 3505 Ryzen 3.

**Comment by null-von-sushi** [comment]
I too am having this issue, and I am not even sure how to check what's causing it on Chrome OS

**Comment by Mou786Aha** [comment]
This kind of issue occurs when not installing the correct versions. It's hard to know what caused it. But after installing recommended versions for both the brunch and image, it works fine.
