### ISSUE TITLE
No Internet on r115 

### ISSUE THREAD

**Issue by User8395** [sebanc/brunch#1915]
I set up Brunch on my Acer C720 but I'm can't load any websites. I see `trap invalid opcode` in dmesg.

Is there any way to fix this without switching to another image because the first boot takes waaaaay too long.

EDIT: I can also ping from the terminal and even load websites with a text based browser

EDIT 2 ELECTRIC BOOGALOO: I fixed this by downgrading to r100 with [this link](https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14526.69.0_rammus_recovery_stable-channel_mp-v2.bin.zip) from #1549.

**Comment by ZProLegend007** [comment]
You should probably mark this as solved, as you have found a solution and there will be no more progress as the chipset you are using is out of support. Thank you :)

**Comment by User8395** [comment]
Oops, forgot to do it...
