### ISSUE TITLE
Unable to Boot Into Installation Media (Fails to Build)

### ISSUE THREAD

**Issue by xeu100** [sebanc/brunch#192]
Using m80 Rammus with Brunch m81 4.19 stable (latest). 

I have tried this across different brunch builds, but it fails. Everything happens so fast that I couldn't take a proper photo, these are screenshots from a slow-motion recording. They include all the details. It looks like one of the partitions fails.

![image](https://user-images.githubusercontent.com/18571399/82742776-34ea9000-9d30-11ea-9e12-61e3bb82253e.png)
![image](https://i.xeu100.com/3cb71a.png)
![image](https://user-images.githubusercontent.com/18571399/82742810-74b17780-9d30-11ea-80bf-ee96b90714ea.png)
![image](https://i.xeu100.com/4a973e.png)

**Comment by sebanc** [comment]
Hi,

Thanks for the screenshots.

The first screenshot error warning can be normal and harmless if you have created the usb from windows.

The second one is the real culprit as it shows that ROOT-B partition is corrupt which is not normal.

The third one is a consequence of the second screenshot issue.

We therefore need to identify why ROOT-B partition is corrupt:
- Did you get error messages while creating the chromeos image ?
- Which tool have you used to write it on the usb flashdrive ?

**Comment by xeu100** [comment]
> Hi,
> 
> Thanks for the screenshots.
> 
> The first screenshot error warning can be normal and harmless if you have created the usb from windows.
> 
> The second one is the real culprit as it shows that ROOT-B partition is corrupt which is not normal.
> 
> The third one is a consequence of the second screenshot issue.
> 
> We therefore need to identify why ROOT-B partition is corrupt:
> 
> * Did you get error messages while creating the chromeos image ?
> * Which tool have you used to write it on the usb flashdrive ?

I didn't get any error messages while compiling brunch, except for some size issues related to 512 multiplier. I used Balena Etcher and Chromebook Recovery Utility with the same images and the same results.

**Comment by sebanc** [comment]
The "512 multiplier" errors are not normal, it can either mean that the recovery image was not unzipped or that you wrote to a partition instead of a block device.

**Comment by xeu100** [comment]
In-case anyone experiences this issue, it was related to file validity. My download of the recovery image was corrupt, attempt a redownload.
