### ISSUE TITLE
Linux doesn't show up on settings.

### ISSUE THREAD

**Issue by EstPC13** [sebanc/brunch#193]
I'm using the rammus recovery image, latest dev build of Chrome OS (84) and latest Brunch release.

However, the Linux (Beta) option is nowhere to be seen on my settings page. Is this normal? If so, is there any other way to install Linux?

**Comment by XeroWolf7** [comment]
You have to enable virtualization in the bios

**Comment by PixelOFC** [comment]
> You have to enable virtualization in the bios
Enable VT-d, VT-x or just Intel VT, or Intel Virtualization.

**Comment by sebanc** [comment]
I guess the issue is solved, if not you can re-open it.
