### ISSUE TITLE
BIOS Dual boot: ChromeOS not found

### ISSUE THREAD

**Issue by XeGrox** [sebanc/brunch#195]
Hello, I'm using the dual boot method in the Linux section but I'm getting the following error:

```
brunch: Scanning device /dev/sda
brunch: Chromeos was not found on any device, fallback to shell... 
```

I do know that mbr/bios dual boot is not supported, but why is brunch searching for Chromeos partitions in my drive instead of the chromeos.img file? Thanks! 😊

**Comment by sebanc** [comment]
Hi,

brunch will search for an image if both "img_part" and "img_path" variables are set in the kernel command line from the grub config.

This means that either those variables are not set in your grub config or that grub does not manage it correctly (actually my issue for dual boot with bios is that grub does not seem to handle variables the same way as the efi one)

**Comment by XeGrox** [comment]
I've gotten it to work by manually setting the variables, but there are some errors that I came across

`losetup -P /mnt/loop15 /mainroot/chromeos.img` 
ends up with `loop480p*` being created instead of `loop15p*` (really weird and I have no explanation to this)

`exec switch_root /system /sbin/init` requires a `-c /dev/console` argument in order to work

I've successfully booted using the USB method without the need for any fix, so I'm not sure why these are happening

Cheers! 😁

**Comment by sebanc** [comment]
There should be only one "\" in the output from the script as the "cat" command which generates it remove one.
Have you generated the script by copying it from the installer script ?

**Comment by XeGrox** [comment]
Oops, the grub config was missing from the mbr install script so I copied it directly...
But there isn't an issue with the variables and I've booted just fine

**Comment by sebanc** [comment]
Good to know that it worked, from which linux distro did you apply the dual boot procedure ?

**Comment by XeGrox** [comment]
Arch
