### ISSUE TITLE
Intel Dual Band Wireless-AC 3165 Not working

### ISSUE THREAD

**Issue by PixelOFC** [sebanc/brunch#199]
any fixes mayb?

**Comment by sebanc** [comment]
Have you tried adding "options=iwlwifi_backport" to the kernel command line ?

**Comment by PixelOFC** [comment]
where and how? Im new to ChromeOS on brunch, I only tried FydeOS 2 years ago.

**Comment by PixelOFC** [comment]
@sebanc ?

**Comment by sebanc** [comment]
Run "sudo edit-grub-config" in crosh shell (CTRL+ALT+T and type "shell" at the invite). Then add a space and "options=iwlwifi_backport" after "cros_debug". Press CTRL+X to save, "y" and ENTER to confirm the file name.

**Comment by PixelOFC** [comment]
Ill try

**Comment by PixelOFC** [comment]
@sebanc Cant open crosh bcuz um stuck on the ChromeOS setup, i need to put an network but it doesn't give me any network option, already tried my RPi0 wifi dongle, and i dont have any eth cables

**Comment by sebanc** [comment]
Press CTRL+ALT+F2 type "root" as user.

Run "edit-grub-config" in crosh shell. Then add a space and "options=iwlwifi_backport" after "cros_debug". Press CTRL+X to save, "y" and ENTER to confirm the file name. Reboot

**Comment by PixelOFC** [comment]
now the networks appear for minus than one sec

**Comment by PixelOFC** [comment]
@sebanc i hate my crappy lenovo

**Comment by sebanc** [comment]
Press CTRL+ALT+F2, then type "root" as user.

What does "dmesg | grep firmware" returns ? (you can attach a photo if it is easier)

**Comment by PixelOFC** [comment]
![IMG_20200525_134857570](https://user-images.githubusercontent.com/60579010/82831615-472f1000-9e8f-11ea-8e6d-0a50c0e66500.jpg)
Image ^^
and im uploading an video on YT showing what happen (exactly) btw soory for my english, im brazillian

**Comment by sebanc** [comment]
what is the output of "rfkill list all" ?

**Comment by PixelOFC** [comment]
https://www.youtube.com/watch?v=E19PLDCTDp8 vid

**Comment by sebanc** [comment]
Ok, I definitely need the output of "rfkill list all"

**Comment by PixelOFC** [comment]
@sebanc image
![IMG_20200525_140405358](https://user-images.githubusercontent.com/60579010/82832330-210a6f80-9e91-11ea-8486-73647cf5388e.jpg)

**Comment by sebanc** [comment]
run "rfkill unblock all" and then press CTRL+ALT+F1 to return to the main screen, you should see the networks

**Comment by PixelOFC** [comment]
ok

**Comment by PixelOFC** [comment]
god bless you, im writing this on my Chrome OS, how many years you work on this

**Comment by sebanc** [comment]
Probably around one year but chromeos is mainly linux in the end and I use linux since longer than that.

Which brunch version did you use ?
Could you attach an "lsmod" to this issue ? (open crosh with CTRL+ALT+T, type "shell", run "lsmod > ~/Downloads/lsmod.txt" and attach lsmod.txt from your downloads folder to this issue)

**Comment by sebanc** [comment]
I don't think you want to close the issue yet, your wifi will still be blocked after each reboot

**Comment by PixelOFC** [comment]
[lsmod.txt](https://github.com/sebanc/brunch/files/4678287/lsmod.txt)
here it is

**Comment by sebanc** [comment]
You used brunch r80 stable ?

**Comment by PixelOFC** [comment]
yes

**Comment by PixelOFC** [comment]
im feeling an lag, that is normal?

**Comment by sebanc** [comment]
I think the wifi issue should be solved if you update to r81 stable, download it and run "sudo chromeos-update -f <path_to_r81_release_package>".

The lag might be normal if you run it on usb or if it is still setting up android apps.

**Comment by PixelOFC** [comment]
i was doing some stuff, ill try rn

**Comment by PixelOFC** [comment]
i feel lag on the location when u open apps (idk name in english)

**Comment by sebanc** [comment]
Try installing it on hdd or dual boot procedure, the experience is not very good on usb

**Comment by PixelOFC** [comment]
it is triple booted

**Comment by sebanc** [comment]
What's your laptop model ?

**Comment by PixelOFC** [comment]
lenovo ideapad 320 80yh0008br, updated Brunch too

**Comment by PixelOFC** [comment]
btw lag is only on animations

**Comment by sebanc** [comment]
Your laptop should be powerful enough, I have no specific tweaks to recommend.

However, chromeos animations are maybe not as smooth as you would have expected, you can look for ways to disable them on chromeos reddit/forums.

**Comment by PixelOFC** [comment]
ty, should i close this now? Wifi problem fixed, ill try changing my region to US bcuz google assistant isnt avaliable in PT-BR

**Comment by sebanc** [comment]
Yes, I think it can be closed, you can still re-open it if you notice other issues.

**Comment by PixelOFC** [comment]
@sebanc can i update using settings app?
