### ISSUE TITLE
Startup in laptop mode

### ISSUE THREAD

**Issue by cobernicus** [sebanc/brunch#20]
My tablet always startup at laptop mode. For enable tablet mode I need connect and disconnect some keyboard. It make my tablet without keyboard almost useless. Can I force tablet mode at startup ? (octopus r79)

I tried rammus. On rammus tablet mode totally not working

**Comment by Mayk728** [comment]
I'm using Ultima R80 (same with R78) on my surface 3 and it starts up in tablet mode with the keyboard already disconnected.

**Comment by sebanc** [comment]
Hi, I have added the "force_tablet_mode" option in the new release which should let your device in tablet mode all the time. But to be honest, i completely forgot to test it.

If you want to give it a try, add "options=force_tablet_mode" to the kernel command line (after cros_debug) in grub.cfg on partition 12.

**Comment by sebanc** [comment]
Tested this option and it works fine for me, let me know how it goes

**Comment by sebanc** [comment]
I am cleaning the issues list, as this one is supposedly fixed for 1 month I will close it but you can re-open it if it still does not work.
