### ISSUE TITLE
Will AMD dedicated GPUs work in brunch?

### ISSUE THREAD

**Issue by MarioNooo** [sebanc/brunch#2033]
I know Nvidia GPUs aren't supported, but I am not sure about AMD ones. I am asking this question because sometime later I am going to buy a dedicated graphics card replacing my AMD iGPU. Any tips, anyone?

**Comment by rama982** [comment]
It works, but the hdmi audio is somewhat broken

**Comment by MarioNooo** [comment]
It's okay, I have my PC speakers.

**Comment by MarioNooo** [comment]
You don't need to do change anything, same kernel modules, right?
