### ISSUE TITLE
Upgrading from Rammus to Nocturne

### ISSUE THREAD

**Issue by Khang5687** [sebanc/brunch#208]
I'm having an issue when trying to get PIN login to work at boot but I've read the issue #126 I've known that PIN login is just working for supported devices. I wanna try out the "nocturne" recovery image which you discussed about in issue #126 But I don't wanna reinstall the whole system again..So can I ask if I can just do `sudo chromeos-update -r < path to the ChromeOS recovery image >` to upgrade from rammus to nocturne?

**Comment by sebanc** [comment]
In theory yes but backup your important data first just in case

**Comment by Khang5687** [comment]
It worked! It was lucky because the recovery image was compatible with my device
