### ISSUE TITLE
accelerometer working but DELAY

### ISSUE THREAD

**Issue by siawzen** [sebanc/brunch#209]
hello anyone can help my device HID sensor collection VEN_8087&PID_0A04&REV_0001 is WORKING but delay about 1 second how to solve this issue rammus 8.1 and brunch 8.1 thanks

**Comment by PixelOFC** [comment]
how u got rammus 81

**Comment by PixelOFC** [comment]
do you really need real time accelerometer?

**Comment by siawzen** [comment]
How to do that?

**Comment by sebanc** [comment]
Could you precise your use case ? In which app are you experiencing this latency ?

**Comment by siawzen** [comment]
In cpuz accelerometer value change but delay, i try another app like level meter & labyrinth game is delay but it's work my device acer w700 tablet, thanks for your support

**Comment by sebanc** [comment]
I tried to reproduce it but the accelerometer value change is instant for me, the issue might be with your accelerometer. Have you checked if it is not the same in windows/linux ?

**Comment by sebanc** [comment]
It's not exactly the same device but indeed try the dual boot method, even if it's just to test, the device speed is most likely the issue.

**Comment by siawzen** [comment]
Please give me tutorial step by step to make dual boot using linux mint or windows, thanks
