### ISSUE TITLE
Just a little question

### ISSUE THREAD

**Issue by PixelOFC** [sebanc/brunch#210]
I have made some research and noticed that currently cros version is 81 (stable, canary is 85), and im stuck on 80 what do i do, btw im using rammus.

**Comment by Lucaacer** [comment]
Type

Typoe



CTRL+ALT+T

shell

sudo edit-grub-config

after cros_debug (in the same line)

add

options=enable_updates

CTRL+X

and save the edits

Reboot and you'll be able to get native updates.

Just be careful, because such updates could conflict with the custom ROOTC by Sebanc:)

**Comment by PixelOFC** [comment]
i got triple boot m8

**Comment by PixelOFC** [comment]
didnt worked @Lucaacer

**Comment by sebanc** [comment]
If you are using dual/triple boot, you have to add "options=enable_updates" to your linux distro grub config.
