### ISSUE TITLE
Regenerate GRUB configuration.

### ISSUE THREAD

**Issue by satyrnhub** [sebanc/brunch#212]
Hi. I know this is a stupid question, but, I created my Chrome OS image and then closed the script by accident, when the GRUB config came up. Is there a way to regenerate that configuration?

**Comment by sebanc** [comment]
Hi, there could be complicated methods to re-generate it but a more simple one would be to re-run the script, or is it a problem ?

**Comment by satyrnhub** [comment]
Well, re-running the script takes a while. For me it took 2 hours. I'd like to not have to rerun it, but I guess i'll have to.
