### ISSUE TITLE
Flickering screen

### ISSUE THREAD

**Issue by geofrey89** [sebanc/brunch#215]
Thanks again @sebanc . For the r83 testing update....
I have today updated to that release. I have noticed that the screen starts flickering after a few seconds when the chrome boot screen appears...
Everything else is working ok so far..

**Comment by sebanc** [comment]
Does the flickering occur just a few second during boot or is it permanent ?

**Comment by geofrey89** [comment]
@sebanc ..just few seconds like 4 or 5 seconds ....

**Comment by geofrey89** [comment]
![GIF-200529_093933](https://user-images.githubusercontent.com/44962989/83229374-8cee2000-a190-11ea-9eba-c654cb39dcdb.gif)

**Comment by geofrey89** [comment]
@sebanc . I found a solution.. I added no_ui_delay..to grub ....as per your release notes. ..

**Comment by geofrey89** [comment]
@sebanc . I found a solution.. I added no_ui_del
