### ISSUE TITLE
force tablet mode doesn't work

### ISSUE THREAD

**Issue by widifirmaan** [sebanc/brunch#219]
option force_tablet_mode does not work, how to fix it/

**Comment by sebanc** [comment]
Hi, do you use dual boot or single boot ? could you post your grub config ?

**Comment by widifirmaan** [comment]
heres my grub config...
menuentry "ChromeOS" {
	img_part=/dev/sda3
	img_path=/chromos.img
	search --no-floppy --set=root --file $img_path
	loopback loop $img_path
	linux (loop,gpt7)/kernel boot=local noresume noswap disablevmx=off \
		cros_secure cros_debug options=force_tablet_mode,enable_updates loop.max_part=16 img_part=$img_part img_path=$img_path
	initrd (loop,gpt7)/initramfs.img
}

tablet mode cant enable after i use sysfs_tablet_mode,after I delete it, it's the same

**Comment by sebanc** [comment]
What's your laptop model ?

**Comment by sebanc** [comment]
Also, could you post a screenshot of your desktop with force_tablet_mode enabled ?
