### ISSUE TITLE
Battery draining quickly

### ISSUE THREAD

**Issue by memphisraynz** [sebanc/brunch#226]
Hi,
Im using a Macbook Air and have noticed teh battery drains very quickly compared to MacOS. I can fully appreciate what you have done here, and that ChromeOS is not designed for this laptop.
Is it possible to change anything, firmware, that may assist this issue? Or is this ossibly just as good as it gets?
I did notice that after upgrading from Brunch 81 to 83, that on initial boot it appeared to have errors when attempting to do something with the CPU.
Happy for this issue to be closed if its just not possible.

**Comment by sebanc** [comment]
Hi, sorry for not answering earlier but I did not really know what to with regards to battery life issues. In the end, I created issue #357 to discuss battery life, feel free to comment and explain what is your use in both os and the difference in battery life observed.
