### ISSUE TITLE
How do I update my Chrome OS to V83?

### ISSUE THREAD

**Issue by leosel** [sebanc/brunch#229]
How do I update my Chrome OS to V83 can you please help me

**Comment by petertriho** [comment]
Add enable_updates to options https://github.com/sebanc/brunch#framework-options

OR

Wait for 83 recovery image (80 is the latest avaliable for most devices) https://github.com/sebanc/brunch#framework-options

**Comment by leosel** [comment]
thank you

**Comment by au79912** [comment]
> Add enable_updates to options https://github.com/sebanc/brunch#framework-options then update through settings
> 
> OR
> 
> Wait for 83 recovery image (80 is the latest avaliable for most devices) https://github.com/sebanc/brunch#framework-options

sorry i am new to all this can you specify how you can add the command to the kernel?

**Comment by petertriho** [comment]
I'm assuming you have a basic set up going (just single boot)

If so:
- Ctrl + Alt + T in the chrome browser
- `shell`
- `sudo edit-grub-config`
- Add `options=enable_updates` next to `cros_debug` (space after `cros_debug`)
