### ISSUE TITLE
options=enable_updates not working

### ISSUE THREAD

**Issue by PixelOFC** [sebanc/brunch#231]
I tried using sudo edit-grub-config and tried changing oon my grub entry (on linux).

**Comment by khanhtranngoccva** [comment]
Mount the efi partition manually, that will be faster.

**Comment by PixelOFC** [comment]
bruh, i used crosh and nano

**Comment by khanhtranngoccva** [comment]
How about linux mint?

**Comment by PixelOFC** [comment]
i use ubuntu

**Comment by khanhtranngoccva** [comment]
Any linux and GUI text editors would work, but don't use Windows to edit bootable stuffs.

**Comment by khanhtranngoccva** [comment]
Or I can send you my config.
[grub.txt](https://github.com/sebanc/brunch/files/4705695/grub.txt)

**Comment by PixelOFC** [comment]
this is from the linux grub or from the cros?

**Comment by khanhtranngoccva** [comment]
This is CrOS's grub config with updates enabled. Rename its extension and paste it into the efi partition.

**Comment by PixelOFC** [comment]
i put this using sudo edit-grub-config or on my linux grub config /boot/grub/?

**Comment by khanhtranngoccva** [comment]
The efi partition of the Chrome OS disk, not your linux one!

**Comment by PixelOFC** [comment]
ok ill try

**Comment by khanhtranngoccva** [comment]
Ahhh, you use edit-grub-config on Chrome OS or edit the grub.cfg file on the ChromeOS' efi partition, DON'T use edit-grub-config on the linux used to install ChromeOS!

**Comment by Skawtnyc** [comment]
Something to keep in mind: Even on chromebooks, triggering the update in Settings doesn't always work. The solution for me has been to reboot, log in, and before doing ANYTHING else, trigger the update from settings. Then don't touch it and let it finish until it tells you to reboot.

**Comment by PixelOFC** [comment]
tbh i didnt tried yet, too much school shit

**Comment by PixelOFC** [comment]
didnt worked, i tried normally and using @Skawtnyc method

**Comment by PixelOFC** [comment]
any suggestion @sebanc ?

**Comment by sebanc** [comment]
Could you post your linux grub config ?

**Comment by khanhtranngoccva** [comment]
Mine failed as well.
[grub.txt](https://github.com/sebanc/brunch/files/4721167/grub.txt)

**Comment by khanhtranngoccva** [comment]
chromeos hatch r80. My config boots, but no updates.

**Comment by sebanc** [comment]
hatch recovery image is not yet supported for updates

**Comment by khanhtranngoccva** [comment]
I really tried to use first-class Chromebook images, but it's a shame it won't work.

**Comment by PixelOFC** [comment]
@sebanc im using Rammus r80, i dont have any update (stable is r81 if ikr)

[grub.txt](https://github.com/sebanc/brunch/files/4725130/grub.txt)

**Comment by PixelOFC** [comment]
worked i was puting the option in the wrong location
