### ISSUE TITLE
storage managment

### ISSUE THREAD

**Issue by au79912** [sebanc/brunch#234]
I have a 500gb HD and when I open the storgage mangment it gives me 251gb of avialable space and the rest of thee 249 gb is taken by system
is this normal?

**Comment by sebanc** [comment]
Hi,

Could you post the output of "df -h" in crosh shell ?

**Comment by au79912** [comment]
![image](https://user-images.githubusercontent.com/65231120/83352959-a77af180-a368-11ea-87d7-fab60fe42989.png)

**Comment by sebanc** [comment]
Ok, so the issue is that the data partition is only taking 284gb out of your 500 gb hdd.

How did you install ? from chromeos or from a linux live flashdrive ?

**Comment by au79912** [comment]
No, I made a chrome os ISO in windows and then flashed it on a usb by Rufus
![image](https://user-images.githubusercontent.com/65231120/83355296-101d9a80-a378-11ea-9468-cd91787a9954.png)

**Comment by sebanc** [comment]
but how did you install on hdd ? or is it a usb hdd ?

**Comment by au79912** [comment]
> but how did you install on hdd ? or is it a usb hdd ?

i installed it by running
 sudo chromeos-install -dst /dev/sda
on the terminal while booted from the usb

**Comment by sebanc** [comment]
It looks like there is an issue with my install script, chromeos should have taken all the space on the disk instead of just 284 gb. Do you remember which brunch version you used when you installed chromeos on the disk ?

**Comment by au79912** [comment]
brunch 81v4 but updated it to 83 beta about a few days ago

**Comment by sebanc** [comment]
Updates do not modify the partition table but brunch 81v4 is probably recent enough that the issue is still present.

Could you backup your important data, reboot, press CTRL+ALT+F2 before login, login as "root" and run "sudo resize-data" ?

After rebooting, could you post the output of "sudo cgpt show /dev/sda" ?

**Comment by au79912** [comment]
![image](https://user-images.githubusercontent.com/65231120/83388126-58d06480-a407-11ea-9ad1-3a2dc85fc6aa.png)

**Comment by sebanc** [comment]
What's the output of: cat "/sys/block/sda/size" ?

**Comment by au79912** [comment]
625142448

**Comment by sebanc** [comment]
What's weird is that your hdd reports a size of 625142448 blocks of 512 bytes size which is around 300gb. Based on that the installer created an 300gb size partition table.

I don't understand why your 500gb hdd would report itself as 300gb but that's the origin of the issue.

You might try to reset your hdd through gparted on a linux live distro, verify that it is recognized as 500gb and then reinstall chromeos.
