### ISSUE TITLE
Enable Developer Mode

### ISSUE THREAD

**Issue by JakunGamer** [sebanc/brunch#235]
So I wanted to activate Developer Mode for tinkering a bit with the system ( That is what I always do ). Anyway that I can do that? When first boot I already choose Enable Developer Mode and set the root password but it didn't work.

**Comment by sebanc** [comment]
Hi,

With brunch, chromeos is in developer mode by default without selecting any additional debugging option and the rootfs is already writable.

What are you trying to achieve ?

**Comment by JakunGamer** [comment]
> Hi,
> 
> With brunch, chromeos is in developer mode by default without selecting any additional debugging option and the rootfs is already writable.
> 
> What are you trying to achieve ?

oh ok

**Comment by dheerau** [comment]
how do i off the developer mode with brunch chrome os

**Comment by ankitdasuni** [comment]
> Hi,
> 
> With brunch, chromeos is in developer mode by default without selecting any additional debugging option and the rootfs is already writable.
> 
> What are you trying to achieve ?

how to install vs code please help
