### ISSUE TITLE
Chrome Os not booting HDD on Linux. 

### ISSUE THREAD

**Issue by dumanOktay** [sebanc/brunch#236]
I can boot Chrome Os from my USB but can't boot from my HDD. 

when I select ChromOs from grub stopping on a black screen with no errors.

**Comment by sebanc** [comment]
Hi,

I guess you are dual booting with linux. Could you try replacing your linux distro grubx64.efi (usually located in /boot/efi/EFI/<your_linux_distro>) with the brunch one located in /efi/boot in partition 12 of your usb ?

**Comment by dumanOktay** [comment]
won't it break my system completely? :)

**Comment by sebanc** [comment]
It should not but back up your ditro's grubx64.efi first and if it does not work from a live linux and change it back.

**Comment by dumanOktay** [comment]
Thank you @sebanc  it works :)

**Comment by khanhtranngoccva** [comment]
Does your image support legacy boot?

**Comment by dumanOktay** [comment]
its support but it is on UEFI mode

**Comment by srulikuk** [comment]
@sebanc 
Please pin this issue or add it to setup instructions, been troubleshooting for hours until i found this.. almost opened a ticket 5 times...
