### ISSUE TITLE
error: no suitable video mode found. Booting in blind mode

### ISSUE THREAD

**Issue by pwnrepeat** [sebanc/brunch#238]
Hi sebanc,
I get this error when I try to boot into Chrome OS on my laptop:
error: no suitable video mode found. 
Booting in blind mode
If you could help me out, that would be great :D 
Thanks,
pwnrepeat

**Comment by pwnrepeat** [comment]
Update: I extracted the mbr.tar.gz and ran the setup again, I am now getting a log

**Comment by pwnrepeat** [comment]
However It gets past a certain point then restarts...

**Comment by sebanc** [comment]
Do you have a laptop or a desktop ?

Try to verify in your bios if boot mode is set to UEFI Hybrid (with CSM).

Else, you can try setting the video mode in kernel command line by adding something like "video=1920x1080-32"

**Comment by pwnrepeat** [comment]
how would i set the video mode

**Comment by pwnrepeat** [comment]
I have a laptop

**Comment by pwnrepeat** [comment]
my boot mode is set to EFI or it can be set to legacy

**Comment by pwnrepeat** [comment]
It now boots but it restarts at a certain point

**Comment by pwnrepeat** [comment]
https://gofile.io/d/icg4bV

**Comment by pwnrepeat** [comment]
There is the video of it booting.

**Comment by pwnrepeat** [comment]
> Do you have a laptop or a desktop ?
> 
> Try to verify in your bios if boot mode is set to UEFI Hybrid (with CSM).
> 
> Else, you can try setting the video mode in kernel command line by adding something like "video=1920x1080-32"

I have a laptop

**Comment by pwnrepeat** [comment]
I updated to the latest testing release, chromeos is not found...

**Comment by pwnrepeat** [comment]
I am now going to try the latest stable release, as I was using R80 to start out with.

**Comment by sebanc** [comment]
I cannot open the link you provided for the video, could you try to attach it here as zip ?

Also, what's your laptop model ? Did you try to update to r83 ?

**Comment by pwnrepeat** [comment]
yeah
ok

**Comment by pwnrepeat** [comment]
my laptop is a samsung r530

**Comment by pwnrepeat** [comment]
i updated to r83
and i got chromeos is not found.

**Comment by pwnrepeat** [comment]
im using samus

**Comment by pwnrepeat** [comment]
If you have discord, can you dm me at pwnrepeat#0001

**Comment by sebanc** [comment]
Sorry I mixed 2 issues, your laptop never booted brunch right ?

**Comment by pwnrepeat** [comment]
it has now

**Comment by pwnrepeat** [comment]
But it restarts after 15 - 20 seconds

**Comment by pwnrepeat** [comment]
https://youtu.be/xL6f9DelBfE

**Comment by sebanc** [comment]
The chromeos images prebuilt by google contains cpu instructions which are not present in core 2 duo cpu. It cannot boot further than this.

You can try:
- Fydeos is built from chromiumos source so it might work.
- orl an android-x86 fork, someone on the Telegram group recently mentioned "PrimeOS Classic".

**Comment by pwnrepeat** [comment]
Ah ok

**Comment by pwnrepeat** [comment]
Thanks alot.

**Comment by hacker1024** [comment]
I'm getting this on boot, and no kernel logs show or anything - but soon after, the UI opens, and everything seems fine. Does anyone know what could be going on here?

I am using r84, so that may be it
