### ISSUE TITLE
CPU frequency stuck at 1800Mhz

### ISSUE THREAD

**Issue by Zatfer17** [sebanc/brunch#241]
Hi, I installed today Rammus 80 img on my t480s. I've been enjoying it but the battery life is not the best. In particular I noticed that the cpu consistantly sits on 1800mhz. Any thoughts on how to solve this?

**Comment by sebanc** [comment]
Are you using a recent brunch version ? I remember having a similar issue on old builds

**Comment by Zatfer17** [comment]
Yup, I'm on brunch r83 k4.19 testing 20200528

**Comment by sebanc** [comment]
No, it will be the same, the issue was in performance mode instead of ondemand in old releases but I fixed it in recent ones. Just in case, could you post the output of:
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

**Comment by Zatfer17** [comment]
I eventually figured out that I was gathering this info in the Linux (beta) terminal, so it was completely different from the output of the shell. I can confirm you that the output you are requesting is powersave and that the cpu idles correctly at 800mhz. Last time I used ChromeOs there was no Crostini and just Crouton so I got kinda confused. Thank you so much!
