### ISSUE TITLE
issues after reboot

### ISSUE THREAD

**Issue by tungmeister** [sebanc/brunch#242]
@sebanc  I've noticed every time I switch back to WIndows after a reboot from Chrome OS the time is behind by one hour. Also if I try and switch to ubuntu (triple boot) it fails to boot the first time (sits at the loading animation indefinitely) through a reboot cures this.  The ubuntu issue only happens when I've been in Chrome OS as does the clock in WIndows. Any ideas?

**Comment by khanhtranngoccva** [comment]
Clock? Chrome OS corrupts the BIOS and CMOS data, since it's trying to communicate with their own proprietary BIOS. This resets the time zone, and sometimes the UTC time itself.  I've seen some BIOS malfunction in my computer as well.

**Comment by sebanc** [comment]
Have you tried the latest r83 brunch ? This should not happen anymore.

**Comment by petertriho** [comment]
Use option 2 https://www.howtogeek.com/323390/how-to-fix-windows-and-linux-showing-different-times-when-dual-booting/

**Comment by midi1996** [comment]
it's probably windows UTC issue, pretty known when dualbooting.
