### ISSUE TITLE
Boot Loop

### ISSUE THREAD

**Issue by memocl** [sebanc/brunch#243]
updated brunch
options=updates_enabled
installed the latest chrome os release 
Boot
Unable to get to the Chrome Logo.
Loops back to boot

**Comment by sebanc** [comment]
Hi, what's your laptop cpu and which recovery are you using ?

**Comment by memocl** [comment]
Acer Aspire V with  Intel Core i7-3537U 
rammus recovery

**Comment by sebanc** [comment]
From r83, google builds rammus with cpu instructions which are unsupported by intel processors <= gen 3.
To be able to update, you have to switch to samus recovery image.

**Comment by memocl** [comment]
Will do and comment back.
Thanks in advance.
And thanks a bunch for Brunch

**Comment by DennisLfromGA** [comment]
I can confirm this also.

I started with an M80 rammus recovery image on an old Acer C7 and all worked fine until the upgrade to M83 - boot loop.

I then used an M80 samus recovery image and once I enabled upgrades it upgraded just fine - NO boot loop.

I should've checked my CPU gen. *before* I dove in - lesson learned.

'brunch` is *awesome*, thanx so much.

**Comment by memocl** [comment]
Resolved.
Worked as @DennisLfromGA  said.
Thankyou @sebanc
