### ISSUE TITLE
Lenovo G570 | Compatibility results

### ISSUE THREAD

**Issue by OkameProductions** [sebanc/brunch#251]
# Devices entry

Device | Type | Brunch version | Recovery | Status | Known issues | Notes
-- | -- | -- | -- | -- | -- | --
Lenovo G570 | Notebook | Brunch r83 k4.19 | nocturne | Working | Crostini not available because of lack of virtualization. | Microphone not tested, this laptop doesn't have (U)EFI, tested in a dualboot with Arch Linux.

# Hardware config entry

CPU | Generation | GPU | Drives | Status | Known issues | Notes
-- | -- | -- | -- | -- | -- | --
Intel Pentium B960 | 2nd Gen | Intel® HD Graphics for 2nd Generation Intel® Processors | Any modern hardrive or SSD | Working | Crostini not available due to lack of VT-x | None

# Known issues tests
* [x] Does the Android Subsystem (Android apps) run?
* [ ] Is Linux container install option available?
* [ ] Does Linux container install?
* [ ] Does Linux terminal run?
* [x] Is Bluetooth working?
* [x] Is WiFi working?
* [x] Is the camera working?
* [ ] Is microphone working? (Not tested)
* [x] Does trackpad and gestures work?

**Comment by sebanc** [comment]
For crostini, is it not possible to enable VT-X in your bios ?

**Comment by OkameProductions** [comment]
The Intel Pentium B960 itself doesn't support VT-x. Virtualization is enabled in BIOS.

**Comment by OkameProductions** [comment]
The camera now decided to load, and it works.
