### ISSUE TITLE
Option to switch volume and brightness keys

### ISSUE THREAD

**Issue by IdrisMC** [sebanc/brunch#255]
On many HP devices the volume keys are switched with the brightness and the other way around.

I would suggest a option=switch_vol_brit

**Comment by sebanc** [comment]
Hi,

Chromeos Function keys are hardcoded to F1-F12 keys, so there is not much I can do about that::
https://support.google.com/chromebook/answer/1047364?hl=en

However, there is a setting to “Treat top-row keys as function keys” which should solve your issue:
https://beebom.com/how-enable-function-keys-chromebook/

**Comment by sebanc** [comment]
Sorry but as you can use “Treat top-row keys as function keys” I don't see the point in doing that
