### ISSUE TITLE
Bootloop after updating to 83

### ISSUE THREAD

**Issue by clandestinz** [sebanc/brunch#256]
as the title suggests. using the latest brunch release. after enabling updates and updating to 83 the computer is stuck in bootloop.

**Comment by sebanc** [comment]
I guess you have a cpu with Intel gen <=3 and you are using rammus recovery image.

**Comment by clandestinz** [comment]
that's true. alright I'll try it as soon as I can

**Comment by OkameProductions** [comment]
Same happened here, using the nocturne img.
Switched recovery device to samus and updated, worked smoothly.

**Comment by DennisLfromGA** [comment]
Yup, it was also discussed not long ago in this closed issue: Boot Loop #243
