### ISSUE TITLE
Call of Duty stuck at Activision logo screen

### ISSUE THREAD

**Issue by leosel** [sebanc/brunch#259]
Call of Duty stuck at Activision logo screen, kindly help me, I'm using an Acer Spin 1, model sp111-31-c2w3

**Comment by sebanc** [comment]
Hi,

Sorry but Call of Duty app is not compatible with chromebooks:
https://www.reddit.com/r/chromeos/comments/cf17pk/anyone_get_call_of_duty_mobile_to_work_on_their/

**Comment by leosel** [comment]
Thank you for the respond...
