### ISSUE TITLE
can i install the image enguarde?

### ISSUE THREAD

**Issue by djgerman10** [sebanc/brunch#261]
It turns out that laptops with this image have the same specifications as mine. I was wondering if I can install this image (grow).

specifications of my laptop [https://www.intel.com/content/www/us/en/support/articles/000006284/education/intel-education-hardware.html](https://www.intel.com/content/www/us/en/support/articles/000006284/education/intel-education-hardware.html)

**Comment by sebanc** [comment]
Hi,

Aside from the kernel, all chromebooks recovery images are very similar. You can try enguarde image but as brunch replaces the kernel with its own I doubt it will provide any advantage over using rammus recovery image.

**Comment by djgerman10** [comment]
Another query would be if I have the image in version 80 I have to also put the brunch of version 80 right?

because I put vercion 83 and it is in chrome os coming soon

remains on the screen chrome os coming soon in uefi and legacy

**Comment by sebanc** [comment]
> Another query would be if I have the image in version 80 I have to also put the brunch of version 80 right?

Not necessarily brunch r83 is backwards compatible with r80 recovery images.

> 
> because I put vercion 83 and it is in chrome os coming soon
> 
> remains on the screen chrome os coming soon in uefi and legacy

I don't understand what you mean, I have never seen a "chrome os coming soon" message, could you post a short video of the boot process ?

**Comment by djgerman10** [comment]
[https://www.youtube.com/watch?v=phA-pM9qCis](https://www.youtube.com/watch?v=phA-pM9qCis)
5:55
remains on the screen chrome os coming soon in uefi and legacy

**Comment by sebanc** [comment]
samus

**Comment by djgerman10** [comment]
### apparently the page fell
Do you know any alternative link to download the image of "samus"?

![n](https://user-images.githubusercontent.com/48584512/83782327-09d43a80-a666-11ea-8de8-b00cff2aeb5f.png)


_Thank you very much, sorry for the inconvenience._

**Comment by sebanc** [comment]
Try:
https://webcache.googleusercontent.com/search?q=cache:js20L4Y_5LYJ:https://cros-updates-serving.appspot.com/+&cd=1&hl=fr&ct=clnk&gl=fr

**Comment by djgerman10** [comment]
install "enguarde" image with brunch r80, apparently it has 83 incompatibility with "enguarde" image.

I can't find where to activate play store

![Screenshot 2020-06-05 at 00 46 46](https://user-images.githubusercontent.com/48584512/83835043-286a1e00-a6c6-11ea-8993-c394741361fb.png)

**Comment by sebanc** [comment]
enguarde image does not have android apps support:
https://www.chromium.org/chromium-os/chrome-os-systems-supporting-android-apps

Not sure why you are trying that hard to install this image...

**Comment by djgerman10** [comment]
Now I understand, I thought that this image is more optimized for laptops like mine, but if it does not have android support it is not worth it.

gravare image "samus"

**Comment by djgerman10** [comment]
another query chrome os is compatible with the graphics intel gma 3600?
because fydeos and cloudready is not, I was wondering if official chrome is?


_and again I appreciate that you share your knowledge, thank you very much_

**Comment by sebanc** [comment]
I don't think I have seen reports on this hardware but I have seen chromeos run on weirder configs. I cannot guarantee anything but it's probably worth trying it.
