### ISSUE TITLE
Booting with Clover / Grub 

### ISSUE THREAD

**Issue by raagk** [sebanc/brunch#264]
Hey!
I have clover boot loader installed on my PC to boot OSX . However i want to boot Chrome OS.
So is there any way to boot clover from grub or grub from clover ?
Please answer

**Comment by raagk** [comment]
Can you send link Please !

**Comment by sebanc** [comment]
Here: https://t.me/chromeosforpc

**Comment by raagk** [comment]
Thanks , also I wanted to ask for legacy boot , where should I apply -l in command for installation on USB? I applied it after chromeos-install.sh and it didn't work , my PC didn't boot on Pendrive.

**Comment by sebanc** [comment]
"-l" option is legacy efi.

What you are looking for is probably the "mbr_support.tar.gz" package in the master branch of this repo. Extract brunch release, then "mbr_support.tar.gz" in the same directory and proceed as usual.

**Comment by raagk** [comment]
Hey ! It worked !
Also is there any grub entry to disable Nvdia GPU?
