### ISSUE TITLE
chrome os was not found on any device, fallback to shell ?

### ISSUE THREAD

**Issue by Herzog1701** [sebanc/brunch#273]
Hi,
during boot up from the Chrome OS Stick on my old **HP Compac nx7400** and also my old **AsusEee PC Seashell series Laptop** it stops, showing:
"Chromeos was not found on any device, fallback to shell?"

I don't know why this happens, because on other legacy machines Chrome OS works flawless.
Can anybody help?

**Comment by sebanc** [comment]
Hi,

This happens because "core 2 duo" processors and "atom 1st gen" do not support the cpu instructions included in current chromeos recovery images.

The built from source chromiumos distros (cloudready, fydeos...) might still work

**Comment by Herzog1701** [comment]
Hi sebanc,
thanks for your reply.
Good to know! this saves me time.

thx
Mike

**Comment by abdullahemad12** [comment]
did it work ?

**Comment by Herzog1701** [comment]
Hi it worked on x5-Z8350 but not on Atom Gen1.
thx
