### ISSUE TITLE
My experience with Chrome OS

### ISSUE THREAD

**Issue by djgerman10** [sebanc/brunch#275]
### I wanted to share my experience with ChromeOS.

I had a bad experience with the image "samus" I was slow.
So I recommend taking the chromebook from the image as a reference, I don't know if it is understood.

for example "samus" has on chromebooks [Google Chromebook Pixel (2015)].
the characteristics of the Google Chromebook Pixel (2015) are not the same as my laptop.

- I found an image almost identical to that of my laptop the image (enguarde that have the chromebooks [Lenovo N21 Chromebook].
The bad thing about the image (enguarde) is that it does not have android compatibility.

- So you look for another image, the other image that resembles is the one of "reks" that they have in the [Lenovo N22 Chromebook].
image performance [reks] relative to samus is considerably faster and more stable on my laptop.

**I leave this here, maybe it will be useful for someone.**

_forgive my english, greetings from Argentina_

**Comment by sebanc** [comment]
Hi,

Thanks for sharing, I just need to clarify one thing, most users with the "samus" recovery image will not be able to install "reks" as it does not support devices with Intel Gen <= 3.

For your device, rammus is currently the recommended image but if reks works fine, it is all good.
