### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by Rboysen61** [sebanc/brunch#282]
Brunch r81 k4.19 stable 20200510 release file is downloading as a blank page not file that can be unzipped and content extracted.
![Screenshot (294)](https://user-images.githubusercontent.com/66505252/83980775-376eed00-a8cd-11ea-9537-4ba51d80b843.png)

**Comment by Vatri91** [comment]
7zip can unpackage tar.gz files
https://www.7-zip.org/download.html
np

**Comment by Rboysen61** [comment]
Thank You for your help
