### ISSUE TITLE
ThinkPad T460s. Headphone issue.

### ISSUE THREAD

**Issue by Tash254-ke** [sebanc/brunch#284]
@sebanc Thank you very much for giving me something to do and some form of escapism in these Miss Rona times.
Now, I'm a complete newbie literally the first commands I've ever written are the ones on this guide. I didn't even know how to look for HDD device name.
I have just (it's been an hour) installed chrome os fully as my main os on T460s with no issues expect that the headphone jack seems not to be working. Bluetooth audio works, I can switch between internal speakers and Bluetooth speaker seamlessly. But when I fix the earphones in, no sound and also when I select the internal speakers no audio.
Hope to hear from you soon. Greetings from 🇰🇪

**Comment by sebanc** [comment]
Hi,

I am not so good at debugging audio issues and for now only rely on linux resources as chromeos and linux appear to be very similar.

Could you try to add "snd_hda_intel.model=tpt460" to the kernel command line ?

Found here: https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_T460s#Sound

**Comment by Tash254-ke** [comment]
![Screenshot_20200608-175206](https://user-images.githubusercontent.com/66575669/84045020-fbad5380-a9b0-11ea-9e66-4ec587e7e696.png)
I followed the procedure on this screenshot and added snd_hda_intel.model=tpt460 nothing happened when I booted.
Is this what I was supposed to do?

**Comment by sebanc** [comment]
In theory it works but something must have gone wrong if it did not boot.

If you are booting from a usb flashdrive or complete hdd install, run "sudo edit-grub-config" and add "snd_hda_intel.model=tpt460" after cros_debug.

If you used the dual boot procedure, "snd_hda_intel.model=tpt460" after cros_debug in your linux distro grub config for chromeos.

**Comment by Tash254-ke** [comment]
It's complete HDD install. Where will I run that sudo edit...command?
Please don't mind my questions🙈

**Comment by sebanc** [comment]
No worries.

Press CTRL+ALT+T in chromeos, it will display crosh.
Type "shell" at the invite.

Then apply the above procedure.

**Comment by Tash254-ke** [comment]
I did exactly as you told me and referring to the article that I took a screenshot of earlier, I spaced after cros_debug then I added snd_hda... pressed ctrl+x then typed y.
Tried playing audio via headphones immediately and there was no success so I restarted. This time it worked, problem is, once i disconnected the headphones, audio didn't play again and as long as the headphones are plugged in, internal speakers don't work either.
Turns out it only works if I start the laptop with the headphones plugged in. Once I pull them out or I try to change audio to internal speakers, it doesn't work anymore.
I've tested bluetooth too and this one works flawlessly.

**Comment by Tash254-ke** [comment]
> In theory it works but something must have gone wrong if it did not boot.
> 
> If you are booting from a usb flashdrive or complete hdd install, run "sudo edit-grub-config" and add "snd_hda_intel.model=tpt460" after cros_debug.
> 
> If you used the dual boot procedure, "snd_hda_intel.model=tpt460" after cros_debug in your linux distro grub config for chromeos.

I used this process to add snd_hda_intel.model=headset-mic then ctrl+x then y.
But issue still remains the same. Headphones work only when connected when booting.

**Comment by sebanc** [comment]
Could you boot again with "snd_hda_intel.model=headset-mic" and post the output of "cat /sys/module/snd_hda_intel/parameters/model" ?

**Comment by Tash254-ke** [comment]
You lost me at post the output of...
What's that and how do I do it?

**Comment by sebanc** [comment]
Open crosh (CTRL+ALT+T), type "shell" at the invite and then type "cat /sys/module/snd_hda_intel/parameters/model"

**Comment by Tash254-ke** [comment]
![MVIMG_20200613_025717](https://user-images.githubusercontent.com/66575669/84554984-3998d780-ad23-11ea-92f1-50a70154720a.jpg)
Followed the sudo edit-grub-config. Then added snd_hda_intel... Pressed Ctrl+x then y then enter. Restarted, then posted the output of cat/sys/module/snd_hda_intel/parameters/model

**Comment by sebanc** [comment]
Could you try again with a space between "cat" and "/sys/...":
`cat /sys/module/snd_hda_intel/parameters/model`

**Comment by xpduyson** [comment]
> Could you try adding "snd_hda_intel.model=headset-mic" to the kernel command line ?
> 
> Source: https://unix.stackexchange.com/questions/405640/no-headphones-output-on-debian-buster

Can confirm this fix my headphone jack issue. My laptop is Dell Latitude E5470.
Output of the above command:
```
chronos@localhost / $ cat /sys/module/snd_hda_intel/parameters/model
headset-mic,(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)
```
![Screenshot 2020-06-13 at 21 01 51](https://user-images.githubusercontent.com/6981890/84570713-67306000-adb9-11ea-84f8-64292d63d333.png)

**Comment by Tash254-ke** [comment]
> > Could you try adding "snd_hda_intel.model=headset-mic" to the kernel command line ?
> > Source: https://unix.stackexchange.com/questions/405640/no-headphones-output-on-debian-buster
> 
> Can confirm this fix my headphone jack issue. My laptop is Dell Latitude E5470.
> Output of the above command:
> 
> ```
> chronos@localhost / $ cat /sys/module/snd_hda_intel/parameters/model
> headset-mic,(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)
> ```
> 
> ![Screenshot 2020-06-13 at 21 01 51](https://user-images.githubusercontent.com/6981890/84570713-67306000-adb9-11ea-84f8-64292d63d333.png)

The result on crosh is same as this one and now headset works anytime. However, I can't switch between internal speaker and headset when they're plugged in. But I can switch between bluetooth speaker and headset flawlessly.
As long as headset works, I'm okay.
Thank you very much. Be blessed.
