### ISSUE TITLE
Touch pad, Boot, Slow computer

### ISSUE THREAD

**Issue by SPIDER-MAN859** [sebanc/brunch#285]
Touchpad not working properly
Boot takes too much time
4GB RAM but very slow
HP Notebook

**Comment by sebanc** [comment]
Did you install it or are you running it from usb ? If you run it from usb it only goes as fast as your usb flahdrive.

For the touchpad, have you tried adding "options=alt_touchpad_config" to the kernel command line ?

For the boot time, yes it is slow but it is what's needed to boot make a chromeos widely compatible.

**Comment by SPIDER-MAN859** [comment]
Where should I give this commands because I can't find Linux beta option
 'options=alt_touchpad_config'

**Comment by SPIDER-MAN859** [comment]
And I can find only EFI Boot UEFIis not available

**Comment by SPIDER-MAN859** [comment]
I have installed it on my harddrive

**Comment by sebanc** [comment]
Run "sudo edit-grub-config" to change the kernel command line. Fyi in chromeos EFI partition is number 12.

Also, which recovery image have you used ?

**Comment by SPIDER-MAN859** [comment]
Rammus
Processors-Intel CORE i3 7th GEN
Integrated Graphics-Intel HD Graphics 620

**Comment by SPIDER-MAN859** [comment]
I am using a single boot Chrome OS

**Comment by sebanc** [comment]
There is no mute button in chromeos so it is normal your mute buttons does nothing.

HP does not provide chromeos compliant bios/drivers updates so it is not possible to update. Use dual boot with windows if you need to update the bios.

There is no restart button directly accessible in chromeos but you can the hold power button and a menu with reboot should appear.

rammus recovery image has camera issues with some devices that I have not been able to fix. Try "reef" recovery image instead.

I will follow-up the issues related to your device here, could you close all the issues you have created ? (except family link which might be something more general and can remain in its own issue)
