### ISSUE TITLE
ChromeOS won't start on a HW platform with nVidia GPU

### ISSUE THREAD

**Issue by lMarenda** [sebanc/brunch#287]
message moved from different thread/issue

<blockquote> 

Wrt nvidia, It depends on what you mean:

- If you mean a dual gpu setup with both intel and nvidia, I left the nvidia driver enabled in the kernel so that certain functions like hdmi out can be used. However, there is no userspace driver for nvidia graphics in chromeos but I don't think that chromeos with its current design would really benefit from using a dGPU. Also, if needed to play games, the dGPU can apparently be activated in crouton.

- If you mean nvidia as single gpu, the chromeos android apps framework is currently not compatible with nvidia gpu, cloudready therefore already provides a similar experience.

_Originally posted by @sebanc in https://github.com/sebanc/brunch/issues/274#issuecomment-640384111_ </blockquote>

**Comment by lMarenda** [comment]
https://github.com/sebanc/brunch/issues/274#issuecomment-640442193

**Comment by sebanc** [comment]
Hi,

I am closing this issue with regards to the explanations provided in issue #303. To have chromeos working only with nvidia drivers, someone would have to find a way to add nvidia mesa drivers to chromeos (my attempt failed to boot using updated mesa i915 drivers and I don't even have nvidia graphics to test).

The issue #303 can be used for the devs interested in getting this working to share their progress.
