### ISSUE TITLE
Wifi and Bluetooth not work on Macbook air 2011

### ISSUE THREAD

**Issue by kelvin701** [sebanc/brunch#295]
after install chrome os, driver not support macbook.

**Comment by raytrix71** [comment]
Did you try « options=broadcom_wl »?

https://youtu.be/db4Xo_xPTR4

Go to 1.01 it will show you how to add options 

( the guy in in the video is just showing how to turn on auto updates, you just have to replace the text with Broadcom)

**Comment by kelvin701** [comment]
> Did you try « options=broadcom_wl »?
> 
> https://youtu.be/db4Xo_xPTR4
> 
> Go to 1.01 it will show you how to add options
> 
> ( the guy in in the video is just showing how to turn on auto updates, you just have to replace the text with Broadcom)

Oh, thank you so much, all work now after change wifi driver.
