### ISSUE TITLE
Disabling integrated monitor/lcd panel

### ISSUE THREAD

**Issue by Z3r0shin** [sebanc/brunch#297]
Would there be a way, before the kernel loads, to disable the internal monitor (like the lcd panel from a laptop or an All-in-One) so Brunch only loads to an external monitor? Either that I can modify the .sh script(s) somewhere or some other thing I don't know.
In linux, I would ctrl-alt-t once loaded from live usb, then "sudo xrandr --auto && sudo xrandr --output eDP-1 --off" (all while being unable to see what I was doing since it only showed half the whole desktop on the broken All-in-One's intergrated lcd panel and the other half from the hdmi output).
From bios, I can't do it. Either the bios (modded or not) won't do anything to do that, or I am a complete donkey not being able to do it.

**Comment by tornadox** [comment]
I had a similar issue, just pressing the lower brightness hotkey to zero did the job.

**Comment by sebanc** [comment]
Hi,

The correct way to do this is probably to use the "video=" linux kernel parameter.

Try adding "video=eDP-1:d" to the kernel command line.

**Comment by Z3r0shin** [comment]
@sebanc , as usual, you have the correct solution!
Works great! Thank you!
