### ISSUE TITLE
How to backup and migrate Chrome OS to another SSD?

### ISSUE THREAD

**Issue by tornadox** [sebanc/brunch#298]
_I'm ok for this issue to be closed after a reply =)_

Just a general question: I'm planning to move the Chrome OS installation on my laptop to another SSD. For Windows I used Macrium Reflect or other kinds of software, it can backup but I have doubts that it will restore properly(it seems empty space between some partitions), plus not sure how it will restore to different capacity ssd, in general on windows and linux it either shrinks or extends the os partitions. Of course I could copy all of the user files and make a new install, but just out of curiosity, perhaps clonezilla?

Another note: tried brunch with grunt recovery on desktop with AMD A8-5600k (Trinity) - I get kernel crash, so I would propose to change the wiki to include **AMD A4/A6/A9/E2 9XXX APU** I think this makes sense as based on there articles https://arstechnica.com/gadgets/2019/05/hp-chromebook-14-review-one-of-the-first-amd-chromebooks-tested/ (plus I checked almost all models that have grunt recovery) which has AMD A4-9120C APU which in theory should allow to work on all http://www.cpu-world.com/Cores/Stoney_Ridge.html Stoney Ridge and Bristol Ridge cores. I also checked the issues and I can't confirm that anyone tested brunch on these CPU and got it working on others, so it might save a couple of hours people spending on trying it to boot on non supported old AMD hardware =(

P.S. I think that for the upcoming **Ryzen** based chromebooks there will be a new recovery other than grunt as those have **Radeon Vega** iGPUs and the older Stoney Ridge APUs have **Radeon R2/R3/R4/R5**

**Comment by kaned84** [comment]
Question is... why bother? Simpliest method is to backup any files you have on current hdd/ssd. make a Install on new SSD and copy files back again. Chrome OS is very light system... when you will log on on new SSD drive for the verty first time you will have same shortcuts or even wallpaper as on old drive...

**Comment by sebanc** [comment]
Hi,

Sorry but I don't know much about cloning tools, I only use "dd".

I think you can only do this If the new hdd is bigger than the old one. In that case, you could clone your old hdd to the new one with "dd if=<old_hdd> of=<new_hdd> bs=1M" and use "sudo resize-data" once in ChromeOS to adjust data partition size. (make a backup of your important data first)

Thanks for the pointers on AMD CPUs, I think I will change all mentions to supported AMD CPUs to "Stoney Ridge" wording.

**Comment by tornadox** [comment]
Thanks, I already reinstalled, not worth the hassle with chrome os.
