### ISSUE TITLE
ChromeOS on VMWare and Virtualbox

### ISSUE THREAD

**Issue by vineethrp** [sebanc/brunch#302]
Now that we have chromeos booting on most x86 hardware, would it be possible to enable support for virtualization platforms like vmware, virtualbox etc.

I did give it a try once, but did not boot. Will try again and post the logs here

**Comment by vineethrp** [comment]
![image](https://user-images.githubusercontent.com/808507/84412033-a2c20300-abdc-11ea-9a30-3f615a41a28d.png)

**Comment by princepjamie06832** [comment]
It won't run on virtual machine. Only be installed on your computer.

**Comment by sebanc** [comment]
Hi,

I am closing this issue with regards to the explanations provided in issue #303. To have chromeos working in Virtualbox, you have first to find a way to add virtualbox mesa drivers to chromeos.

**Comment by pagkly** [comment]
> Now that we have chromeos booting on most x86 hardware, would it be possible to enable support for virtualization platforms like vmware, virtualbox etc.
> 
> I did give it a try once, but did not boot. Will try again and post the logs here

mine has similar problem but it stuck at
[ 51.782565] input: ImExPS/2 Generic Explorer Mouse as devices/platform/i8042/serio1/input/input6

**Comment by szalony9szymek** [comment]
for me it gets stuck I allowed UEFI

**Comment by dragonBall561** [comment]
what I did w/ VMware

1. SATA Hard Drive
2. No VT-X
3. UEFI Boot Mode

Result. So close...
https://drive.google.com/file/d/14xkdi3vKAS-henCKulbuIbkEF1kFILLH/view?usp=sharing

**Comment by Warrentheo** [comment]
A distant relative to this issue, but you might want to check this out:
https://github.com/WSA-Community/WSAGAScript
_Working for me_
