### ISSUE TITLE
Linux Support Not Working

### ISSUE THREAD

**Issue by dkay0670** [sebanc/brunch#310]
I have installed brunch, got everything but the Linux Support (Beta) feature working. I'm making this issue because **I know for a fact** that it can work, as I got it to work once before I reinstalled brunch. It downloads and installs fine, but won't start the container.

Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/63021402/84578220-2ebc6200-ad78-11ea-828b-6d48f3166cb3.png)

**Comment by sebanc** [comment]
Hi,

Which brunch release do you use ?
What are your laptop specs ?
Are you running chromeos on hdd or usb ?

**Comment by dkay0670** [comment]
Brunch 83.
It's running on the internal HDD.
Intel i7-7700HQ (4) @ 3.800GHz

**Comment by sebanc** [comment]
That's very weird, it should work with your hardware. Could you try to remove crostini in settings and to reinstall it.

If it still does not work, could you try the new build ?

**Comment by dkay0670** [comment]
I can do that

**Comment by dkay0670** [comment]
Although I have tried reinstalling crostini

**Comment by dkay0670** [comment]
That worked, thanks!

**Comment by dkay0670** [comment]
It's not working again...

**Comment by MilesPong** [comment]
I'm also having this same issue, anyone solved it at last?

My device info,

Brunch r83 k4.19 testing 20200614
HP Envy13 notebook, Intel i5-6500, 8GB RAM
Only 1 SSD, and boot from one of the partitions from SSD (The others are Window 10 and Ubuntu 20.04, total have 3 OS)   

BTW, the first boot I got a black screen but solved it by replace the grubx64.efi mentioned in #30

**Comment by dkay0670** [comment]
@MilesPong I fixed it by going on my mobile hotspot

**Comment by MilesPong** [comment]
Seems to update to latest brunch release 0704 has solved this issue
