### ISSUE TITLE
Netflix Android App Won't Play Anything.

### ISSUE THREAD

**Issue by Tash254-ke** [sebanc/brunch#311]
![Screenshot 2020-06-14 at 01 03 25](https://user-images.githubusercontent.com/66575669/84580145-ee42ff80-addc-11ea-9c86-01bb919bd8a7.png)
I sideloaded an app from APK Mirror, logged in, downloaded some movies and series episodes. But nothing plays whether downlaoded or streaming. Is there a work around to this?
I need downloads coz I live in the country side and we don't have FTTH yet and normal data can be expensive.

**Comment by Skawtnyc** [comment]
It's the DRM in the app. You will only be able to use the website version of Netflix using Brunch.

**Comment by raytrix71** [comment]
It’s currently working for me

**Comment by sebanc** [comment]
Netflix needs widevine drm which is only available after disabling developer mode (by removing "cros_debug" on the kernel command line) and doing a powerwash.

However, note that disabling developer mode will restore selinux which might prevent chromeos from booting or some devices (wifi notably) from functionning.

**Comment by Skawtnyc** [comment]
Ah, that explains why I never had video in the Netflix app. Fortunately the website works fine, I can use the Android app on my Duet tablet, and I actually need to have dev mode for my normal workflow.

**Comment by Tash254-ke** [comment]
> It’s currently working for me

The app itself? Or the website?

**Comment by Tash254-ke** [comment]
> The official Netflix app (with Download capability) needs widevine drm which is only available after disabling developer mode (by removing "cros_debug" on the kernel command line) and doing a powerwash.
> 
> However, note that disabling developer mode will restore selinux which might prevent chromeos from booting or some devices (wifi notably) from functionning.

😪 That's fine I'll look for otherways. Thank you once again for Brunch.

**Comment by Tash254-ke** [comment]
> Ah, that explains why I never had video in the Netflix app. Fortunately the website works fine, I can use the Android app on my Duet tablet, and I actually need to have dev mode for my normal workflow.

How long have you had the Duet? Is it a good device? Mama needs a device to just to some simple work and I had suggested this device. Problem is it's not yet here.

**Comment by Skawtnyc** [comment]
> How long have you had the Duet? Is it a good device? Mama needs a device to just to some simple work and I had suggested this device. Problem is it's not yet here.

Off-topic, but I will say that it's great as a tablet. I use it all the time when I'm not at my desk.
