### ISSUE TITLE
bcm4314 issues

### ISSUE THREAD

**Issue by TipzTeam** [sebanc/brunch#312]
I have a laptop with the card bcm4314, and wifi doesn't work while being detected

**Comment by kaned84** [comment]
did you try brunch options for wifi card?

**Comment by sebanc** [comment]
Try adding "options=broadcom_wl" to the kernel command line.

**Comment by TipzTeam** [comment]
Wlan will definitely be fixed by that but Bluetooth? This is a BT+WLAN card

Also you mean adding that by running like export command or the kernel makefile?

**Comment by tornadox** [comment]
@TipzTeam just check the https://github.com/sebanc/brunch/wiki/Getting-Started under the Framework options. The guide is quite simple. I think the question about wifi compatibility is somewhat similar to hackintosh communities, where if it doesn't work (like an intel wifi) you need to replace the module.

**Comment by TipzTeam** [comment]
> @TipzTeam just check the https://github.com/sebanc/brunch/wiki/Getting-Started under the Framework options. The guide is quite simple. I think the question about wifi compatibility is somewhat similar to hackintosh communities, where if it doesn't work (like an intel wifi) you need to replace the module.

You mean kexts?

**Comment by sebanc** [comment]
I guess this issue is fixed, if not feel free to re-open it

**Comment by TipzTeam** [comment]
> I guess this issue is fixed, if not feel free to re-open it

I am unable to compile myself but it is possible to compile correctly, idk why it doesn't work for me.
