### ISSUE TITLE
Install fails on resize2fs

### ISSUE THREAD

**Issue by pheppy** [sebanc/brunch#313]
During install I get a "resize2fs" error (see image) 
![screen](https://user-images.githubusercontent.com/16946996/84599626-acb16380-ae73-11ea-809b-a7b239e201cb.jpg)
and thereafter many "no diskspace left on device" errors.
I've installed via SD, via Mint liveCD. Same result. Previous versions of chromeos and brunch.
I'm using the MBR version which seems to work.

**Comment by sebanc** [comment]
Hi,

The issue is not resize2fs but "ILL_ILLOPN" and "trap invalid opcode" errors which means that the recovery image uses cpu instructions not supported by your cpu.

What are your laptop specs ?

**Comment by pheppy** [comment]
Old. ASUS UL50V with an Intel U7300 processor, so I used samus. It works on cloudready, so I thought it had a chance.

**Comment by sebanc** [comment]
No, sorry there are no current chromeos recovery images compatible with core 2 duo. Cloudready works because it is built from source without specific cpu instructions, whereas google includes specific cpu instructions in recovery images to improve devices performance.

**Comment by pheppy** [comment]
OK. maybe sometime.
