### ISSUE TITLE
ACPI Bios Error

### ISSUE THREAD

**Issue by desmondam** [sebanc/brunch#320]
I don't know if this trouble is caused because my pc has any issue. I am a newbie.
When I try to boot the grub boot loader appears and I select chromeos. Then the booting log moves fastly and after some time the movement of the log stops showing
ACPI Bios error....
...
...
...
AE_NOT_FOUND while evaluating GPE method
This appears four times and after that a short log is shown and the system reboots
This reoccurs like a cycle
Can anyone help me out?
I first tried chromefy and just got a blank screen on boot and it stuck there
Then I tried brunch.. but I am stuck with this problem
Please help me out of here

**Comment by sebanc** [comment]
Hi, what are your laptop/pc specs ?

**Comment by desmondam** [comment]
Thanks for replying sebanc
My laptop is a low end one it is a Toshiba Sattelite C50-A. It's specs are:
>Intel Celeron CPU N2820 @2.13Ghz 2.13Ghz
>2gb Ram

**Comment by sebanc** [comment]
Which recovery image are you using ? Could you post a short video of the boot process ? (The ACPI warnings you mention are generally harmless and I doubt it is the real issue)

**Comment by desmondam** [comment]
I also doubt it because it also appears in ubuntu while booting but it does not affect booting it works perfectly
I used eve recovery image

**Comment by sebanc** [comment]
Pentium CPU are not compatible with eve, try rammus recovery image

**Comment by desmondam** [comment]
Sorry sebanc I used eve because I downloaded it for check chromefy.
But today I use sammus as instructed in read me.
It just worked great
But it is bit laggy.I don't know if my computer does not have the specs to run chrome os.please reply me on this.
But your work is so great.Thanks for that.You are just awesome

**Comment by sebanc** [comment]
Not sure why it is laggy but you can try "rammus" or "reef" images which are better and should be compatible with your cpu

**Comment by desmondam** [comment]
Ok i will try it

**Comment by desmondam** [comment]
I tried to use rammus recovery
but when i run sudo bash chromeos-install.sh -src recovery.bin -dst /dev/sdc
It's giving me an error:
chromeos-install.sh: warning: chromeos-install.sh: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
WARNING: Primary GPT header is invalid
WARNING: Secondary GPT header is invalid
ERROR: GptSanityCheck() returned 2: GPT_ERROR_INVALID_HEADERS
chromeos-install.sh: line 187: [: -eq: unary operator expected
WARNING: Primary GPT header is invalid
WARNING: Secondary GPT header is invalid
ERROR: GptSanityCheck() returned 2: GPT_ERROR_INVALID_HEADERS
chromeos-install.sh: line 187: [: -gt: unary operator expected
WARNING: Primary GPT header is invalid
WARNING: Secondary GPT header is invalid
ERROR: GptSanityCheck() returned 2: GPT_ERROR_INVALID_HEADERS
.....
....
....
partx: specified range <1:0> does not make sense
Writing partition 1
pv: /dev/loop5p1: No such file or directory
Writing partition 2
pv: /dev/loop5p4: No such file or directory
Writing partition 3
pv: /dev/loop5p3: No such file or directory
Writing partition 4
pv: /dev/loop5p4: No such file or directory
Writing partition 5
pv: /dev/loop5p3: No such file or directory
Writing partition 6
pv: /dev/loop5p6: No such file or directory
Writing partition 7
1.00GiB 0:00:45 [22.6MiB/s] [=======================================================================================================>] 100%            
Writing partition 8
pv: /dev/loop5p8: No such file or directory
Writing partition 9
pv: /dev/loop5p9: No such file or directory
Writing partition 10
pv: /dev/loop5p10: No such file or directory
Writing partition 11
pv: /dev/loop5p11: No such file or directory
Writing partition 12
32.0MiB 0:00:01 [22.7MiB/s] [=======================================================================================================>] 100%            
ChromeOS installed.

**Comment by desmondam** [comment]
Thanks it works great.You are awesome
