### ISSUE TITLE
Macbook Air 2012 iSight Camera Crashes

### ISSUE THREAD

**Issue by JPyke3** [sebanc/brunch#322]
Hi,

First of all I wanted to thank you for this awesome project. I really cant believe how well it works even on a MacBook. (Which always have tendancies to never play nice).

However, I have noticed that whenever I try to use the integrated iSight Camera on my 2012 MacBook air model. The camera seems to start for a split second. And then crash, after that the device will not be recognized. I am happy to provide any debug logs or output. I just didn't really know where to start with ChromeOS.

Cheers.

**Comment by sebanc** [comment]
Hi,

Which recovery image do you use ?

**Comment by JPyke3** [comment]
I used `rammus` as the recovery Image.

**Comment by sebanc** [comment]
I think your laptop must have intel gen < 4, you should use "samus" it also has a better camera compatibility than "rammus" currently.

**Comment by JPyke3** [comment]
Oh I do believe you are right. It's an Ivy Bridge processor which I completley overlooked. I will try with the `samus` image and report back.

**Comment by JPyke3** [comment]
With that image camera works great 👍
Sorry for the delay in reporting back
