### ISSUE TITLE
Wi-Fi Realtek not working

### ISSUE THREAD

**Issue by Shershshsh** [sebanc/brunch#332]
Hey my laptop is Lenovo v145-15ast (AMD A4 9125) I have installed grunt and everything working perfect but wifi. I tried options=broadcom_wl and it is not working too. Google says that my wifi adapter is Realtek RTL8821CE. help pls if you can

**Comment by Skawtnyc** [comment]
Try using the latest build of Brunch. That option you used is for Broadcom.

**Comment by sebanc** [comment]
Hi,

If your wireless card is RTL8821CE, you should try adding "options=rtl8821ce"

**Comment by Shershshsh** [comment]
Really thank you bro options=rtl8821ce worked
