### ISSUE TITLE
Surface Pro 4 touchscreen issues

### ISSUE THREAD

**Issue by eldergom** [sebanc/brunch#336]
The touchscreen does not respond when I use it a little after booting.
To solve the problem, you must either reboot or enter the sleep mode by covering the type cover.
(If you press the power button to enter the sleep mode, it will not be resolved)

**Comment by sebanc** [comment]
Hi,

Some SP4/SB1 needs a special kernel parameter for touchscreen not to fail. Could you try adding "intel-ipts.no_feedback=1" to the kernel command line ?

**Comment by eldergom** [comment]
It's solved
thank you
