### ISSUE TITLE
Crostini Inconsistencies

### ISSUE THREAD

**Issue by dkay0670** [sebanc/brunch#337]
Crostini Is working very inconsistently when enabling, requiring to press Retry a ton to try to get it to enable. It downloads and installs fine, but get error 13 when attempting to start the container.
![image](https://user-images.githubusercontent.com/63021402/85343218-2b745500-b4a1-11ea-8596-4a7635b336b0.png)

**Comment by dkay0670** [comment]
I will also note that I have tried looking up error 13, but nothing that was actually error 13 came up...

**Comment by sebanc** [comment]
Hi,

Could you try to install crostini, wait for it to fail, then run "cp /var/log/messages ~/Downloads/msg.txt" in crosh shell and attach msg.txt from your downloads folder to this issue ?

**Comment by dkay0670** [comment]
[msg.txt](https://github.com/sebanc/brunch/files/4821822/msg.txt)

**Comment by ralphwig** [comment]
I had a similar issue and I don't think it told me but I didn't have enough space. Did you do the "sudo resize-data" command in the shell?

**Comment by sebanc** [comment]
Is it a log from a crostini install or when trying to launch crostini ?

**Comment by dkay0670** [comment]
It is the end of /var/log/messages

**Comment by dkay0670** [comment]
I think it's when it's installing

**Comment by sebanc** [comment]
This issue is very weird and I don't understand why you are the only one having it. As far as I can tell it seems to be related to the network/internet/router. Could you try to use install crostini while connected to your phone in tethering mode instead of your normal wifi/lan ?

**Comment by dkay0670** [comment]
Yeah, that worked... Now the question is why doesn't it work on my network?

**Comment by sebanc** [comment]
I am not very good at debugging networking issues, I would say it is something related to the DHCP server not working properly but that's just a guess. Or maybe you have mac adress / IP based filtering setup ?

**Comment by dkay0670** [comment]
Okay, thanks for the help!
