### ISSUE TITLE
What is the best recovery image to use for Dell laptops?

### ISSUE THREAD

**Issue by leosel** [sebanc/brunch#339]
What is the best recovery image to use for Dell laptops?

**Comment by hbarsaiyan** [comment]
Depends on your processor. Overall samus recovery works well for most devices.

**Comment by kowalski7cc** [comment]
On my XPS 13 I'm using Nami, if you have a Skylake+ you should not have issues

**Comment by sebanc** [comment]
Hi, I tried to clarify my recovery image recommendation in #359. I think the telegram group or discord server might be better to have other recovery images recommendations.
