### ISSUE TITLE
Play services not working after installing on hdd

### ISSUE THREAD

**Issue by desmondam** [sebanc/brunch#340]
When i installed it on USB it worked but it was bit laggy, So i installed it on HDD after installation it boots ChromeOS. But It shows play services..something went wrong and android apps also are not  working and linux is also not installing.Other things are working fine. Perfomance also improved a bit.

**Comment by sebanc** [comment]
Hi,

Could you try deleting google sync ?
https://support.google.com/chromebook/answer/2914794?hl=en

**Comment by sebanc** [comment]
I guess this issue is closed, if not feel free to re-open it.
