### ISSUE TITLE
RTL8821CE wireless card will not work.

### ISSUE THREAD

**Issue by noahyz** [sebanc/brunch#341]
The wi-fi does not work with my laptop with a RTL8821CE wireless card, even after enabling the RTL8821CE framework option.

**Comment by sebanc** [comment]
Hi,

Could you attach a dmesg to this issue ? (run "dmesg > ~/Downloads/dmesg.txt" in crosh shell and attach dmesg.txt from your downloads folder)

**Comment by noahyz** [comment]
Nevermind, I forgot to save the changes in the grub config.
