### ISSUE TITLE
After a couple of days disk image loses read and write access and cannot boot

### ISSUE THREAD

**Issue by DavidIlie** [sebanc/brunch#342]
I am pretty sure the title sums everything up. I installed brunch a couple of days ago and now it won't boot. It will go into a self repair state and just get stuck there. If anyone can help I have a recording of it booting

**Comment by sebanc** [comment]
Hi,

Did you disable "Fast startup" in Windows ?

**Comment by DavidIlie** [comment]
How do I do that?

**Comment by sebanc** [comment]
https://www.windowscentral.com/how-disable-windows-10-fast-startup

**Comment by DavidIlie** [comment]
Thanks

**Comment by DavidIlie** [comment]
Thanks it works now. Have a good one!
