### ISSUE TITLE
what is the best recovery image for Lenovo Ideapad u310/u410?

### ISSUE THREAD

**Issue by leosel** [sebanc/brunch#348]
what is the best recovery image for Lenovo Ideapad u310/u410?

**Comment by WindowsXP95** [comment]
Which one do you own?

**Comment by treypop** [comment]
https://github.com/sebanc/brunch#chromeos-recovery-images

> "samus" is the recommended image for devices with 3rd generation Intel CPU and older.

**Comment by b1t0y** [comment]
I have the lenovo u410 touch and has been using samus recovery.  Everything is working well so far.  Added some frameworks like no_ui_delay, broadcom_wl, acpi_power_button and  advanced_als.  I added also enforce_hyperthreading=1.

**Comment by sebanc** [comment]
Hi, I tried to clarify my recovery image recommendation in #359. I think the telegram group or discord server might be better to have other recovery images recommendations.
