### ISSUE TITLE
No external storage in "Files app"

### ISSUE THREAD

**Issue by Ebbot9876** [sebanc/brunch#35]
Hi, I have ASUS Transformer Book T200TA. (Rammus R80, Brunch R80 Stable)
External storage does not show up in Files App. 
It worked earlier with Nautilus R79, Brunch R79 Stable.

**Comment by jhedfors** [comment]
Sorry to jump in here. Not sure if it is for the same reason as you, but I have been struggling with getting my external USB (2TB) HDD drive to show up as well. I can access in terminal however just not in Files app. Flash drives show up fine for me - what kind of external drive?

**Comment by Ebbot9876** [comment]
All kind of external storage, SDCARD, USB-HDD, MMC. Nothing shows up in R80! 
When in R79 with kernel 4.14 everything was mounted under /media/removable/...

**Comment by sebanc** [comment]
Hi, I confirm that it is a regression linked to an attempt at fixing the high cpu workload generated by the android media server. This issue should be fixed in the next brunch release which should arrive shortly (tomorrow if everything goes well).

**Comment by Ebbot9876** [comment]
Thanks, i am looking forward tog next Brunch!

**Comment by sebanc** [comment]
Hi, I have just released the new version which should fix those issues.

**Comment by Ebbot9876** [comment]
I Cannes confirm, the newblue version works.

**Comment by Ebbot9876** [comment]
I can confirm, the newblue version works. All media mounts to files    app.

**Comment by jhedfors** [comment]
Yes, I second that -  I can see my 2TB drive. :)
