### ISSUE TITLE
Silent boot

### ISSUE THREAD

**Issue by Donster4** [sebanc/brunch#352]
This isn't necessarily an issue, but it would be nice if there was a way that I could have a more "silent boot" without seeing all the logs and detecting of devices, but perhaps a splash screen or just a loading screen, or even black screen. Is there any way to do this in grub? Thanks!

**Comment by albsrocha** [comment]
use the quiet option after cros_debug

**Comment by Donster4** [comment]
Thanks mate, works fine now, its a lot more silent now and it goes into the splash screen quicker. I also set set_timeout to 0 as it was my only OS taking me straight to it. Thanks.
