### ISSUE TITLE
Wifi problem: not reconnecting in a session  (Rtl8723de hp-15notebook)

### ISSUE THREAD

**Issue by debendrakumar** [sebanc/brunch#358]
Wifi is connecting once in one session or one boot 
if wifi gets disconnected then not reconnenting and says " unknown connection problem " but if restart chrome os then connecting but reconnecting problem remains there
Please give a solution for this problem......

**Comment by sebanc** [comment]
Hi,

Could you try the below release without "options=rtl8723de" ? (validate the github email invite first)
https://github.com/sebanc/brunch-testing/releases

**Comment by debendrakumar** [comment]
This release worked .... Now wifi can reconnect  thank you so much...
