### ISSUE TITLE
Trackpad Not Working - Lenovo ideapad 120S-14IAP

### ISSUE THREAD

**Issue by ryanbatiuk** [sebanc/brunch#364]
I followed the instructions here:
https://www.youtube.com/watch?v=ROBpXNonVxc

And everything works great except for the Trackpad. I had to plug in a USB mouse in order to get a mouse to work.
Using:
•  Lenovo ideapad 120S-14IAP
•  rammus Recovery Build 83
•  Brunch r83 k4.19 testing 20200614

Ran a quick 'udevadm info' in crosh:

chronos@localhost / $ ls /dev/input/mouse*
/dev/input/mouse0  /dev/input/mouse1
chronos@localhost / $ udevadm info /dev/input/mouse1
P: /devices/pci0000:00/0000:00:16.2/i2c_designware.1/i2c-6/i2c-ELAN060F:00/input/input14/mouse1
N: input/mouse1
S: input/by-path/pci-0000:00:16.2-platform-i2c_designware.1-mouse
E: DEVLINKS=/dev/input/by-path/pci-0000:00:16.2-platform-i2c_designware.1-mouse
E: DEVNAME=/dev/input/mouse1
E: DEVPATH=/devices/pci0000:00/0000:00:16.2/i2c_designware.1/i2c-6/i2c-ELAN060F:00/input/input14/mouse1
E: ID_INPUT=1
E: ID_INPUT_TOUCHPAD=1
E: ID_PATH=pci-0000:00:16.2-platform-i2c_designware.1
E: ID_PATH_TAG=pci-0000_00_16_2-platform-i2c_designware_1
E: ID_SERIAL=noserial
E: MAJOR=13
E: MINOR=33
E: POWERD_ROLE=internal_touchpad
E: POWERD_TAGS=usable_when_laptop usable_when_display_off role_internal_touchpad
E: POWERD_TAGS_USABLE=usable_when_laptop usable_when_display_off
E: SUBSYSTEM=input
E: TAGS=:powerd:
E: USEC_INITIALIZED=32462464

Does anyone see anything, or have any suggestions? Thanks!

**Comment by sebanc** [comment]
Hi,

Please read #305 and re-open the issue if:
- your touchpad does not work in crouton
- you find a working config by editing /etc/gesture/40-touchpad-cmt.conf.
