### ISSUE TITLE
REOPENING: Trackpad Not Working - Lenovo ideapad 120S-14IAP

### ISSUE THREAD

**Issue by ryanbatiuk** [sebanc/brunch#378]
#364 
So I am reopening an issue in which I explored reopening requirements and installed Crouton to see if the mouse worked inside of the Croton install.

It did not work. Please see video of me testing the trackpad not working: https://www.youtube.com/watch?v=ddxmvdHtKmY

Everything works great except for the Trackpad. I had to plug in a USB mouse in order to get a mouse to work.
Using:
• Lenovo ideapad 120S-14IAP
• rammus Recovery Build 83
• Brunch r83 k4.19 testing 20200614

Ran a quick 'udevadm info' in crosh:

chronos@localhost / $ ls /dev/input/mouse*
/dev/input/mouse0 /dev/input/mouse1
chronos@localhost / $ udevadm info /dev/input/mouse1
P: /devices/pci0000:00/0000:00:16.2/i2c_designware.1/i2c-6/i2c-ELAN060F:00/input/input14/mouse1
N: input/mouse1
S: input/by-path/pci-0000:00:16.2-platform-i2c_designware.1-mouse
E: DEVLINKS=/dev/input/by-path/pci-0000:00:16.2-platform-i2c_designware.1-mouse
E: DEVNAME=/dev/input/mouse1
E: DEVPATH=/devices/pci0000:00/0000:00:16.2/i2c_designware.1/i2c-6/i2c-ELAN060F:00/input/input14/mouse1
E: ID_INPUT=1
E: ID_INPUT_TOUCHPAD=1
E: ID_PATH=pci-0000:00:16.2-platform-i2c_designware.1
E: ID_PATH_TAG=pci-0000_00_16_2-platform-i2c_designware_1
E: ID_SERIAL=noserial
E: MAJOR=13
E: MINOR=33
E: POWERD_ROLE=internal_touchpad
E: POWERD_TAGS=usable_when_laptop usable_when_display_off role_internal_touchpad
E: POWERD_TAGS_USABLE=usable_when_laptop usable_when_display_off
E: SUBSYSTEM=input
E: TAGS=:powerd:
E: USEC_INITIALIZED=32462464

Does anyone see anything, or have any suggestions? Thanks!

**Comment by sebanc** [comment]
Hi, could you check in lsmod if you have "elan_i2c" module ? If so, could you try adding "module_blacklist=elan_i2c" to the kernel command line ?

Source: https://bugzilla.kernel.org/show_bug.cgi?id=203467

**Comment by ryanbatiuk** [comment]
Hi @sebanc 

It looks like I don't have one. Here is my output:

`chronos@localhost / $ lsmod
Module                  Size  Used by
snd_seq_dummy          16384  0
snd_seq                69632  5 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
tcp_diag               16384  0
inet_diag              20480  1 tcp_diag
tun                    36864  0
nf_nat_tftp            16384  0
nf_conntrack_tftp      16384  1 nf_nat_tftp
nf_nat_ftp             16384  0
nf_conntrack_ftp       16384  1 nf_nat_ftp
esp6                   20480  0
ah6                    16384  0
xfrm6_mode_tunnel      16384  0
xfrm6_mode_transport    16384  0
xfrm4_mode_tunnel      16384  0
xfrm4_mode_transport    16384  0
ip6t_REJECT            16384  2
ip6t_ipv6header        16384  0
rfcomm                 61440  2
cmac                   16384  1
uinput                 20480  0
intel_rapl             20480  0
intel_telemetry_pltdrv    20480  0
intel_punit_ipc        16384  1 intel_telemetry_pltdrv
intel_telemetry_core    16384  1 intel_telemetry_pltdrv
intel_pmc_ipc          16384  1 intel_telemetry_pltdrv
x86_pkg_temp_thermal    16384  0
intel_powerclamp       16384  0
crct10dif_pclmul       16384  0
crc32_pclmul           16384  0
ghash_clmulni_intel    16384  0
pcbc                   16384  0
btusb                  53248  0
btrtl                  20480  1 btusb
btbcm                  16384  1 btusb
btintel                24576  1 btusb
bluetooth             462848  34 btrtl,btintel,btbcm,btusb,rfcomm
ecdh_generic           20480  2 bluetooth
aesni_intel           200704  1838
aes_x86_64             20480  1 aesni_intel
crypto_simd            16384  1 aesni_intel
cryptd                 20480  919 crypto_simd,ghash_clmulni_intel,aesni_intel
glue_helper            16384  1 aesni_intel
serio_raw              16384  0
intel_xhci_usb_role_switch    16384  0
roles                  16384  1 intel_xhci_usb_role_switch
ccm                    20480  6
joydev                 24576  0
i2c_hid                28672  0
snd_hda_codec_hdmi     49152  1
zram                   24576  1
ath10k_pci             40960  0
ath10k_core           446464  1 ath10k_pci
**_elan_i2c               36864  0_**
snd_hda_codec_realtek    98304  1
snd_sof_pci            16384  0
snd_sof_intel_byt      16384  1 snd_sof_pci
snd_sof_intel_ipc      16384  1 snd_sof_intel_byt
snd_sof_xtensa_dsp     16384  1 snd_sof_pci
snd_hda_codec_generic    69632  1 snd_hda_codec_realtek
snd_sof_intel_hda_common    53248  1 snd_sof_pci
snd_soc_hdac_hda       20480  1 snd_sof_intel_hda_common
snd_sof_intel_hda      16384  1 snd_sof_intel_hda_common
snd_sof                73728  4 snd_sof_pci,snd_sof_intel_hda_common,snd_sof_intel_byt,snd_sof_intel_ipc
mac80211              774144  1 ath10k_core
ath                    32768  1 ath10k_core
snd_soc_skl            81920  0
snd_soc_skl_ipc        49152  1 snd_soc_skl
snd_hda_ext_core       16384  4 snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_soc_sst_dsp        16384  1 snd_soc_skl_ipc
snd_soc_sst_ipc        16384  1 snd_soc_skl_ipc
snd_soc_acpi_intel_match    28672  3 snd_sof_pci,snd_sof_intel_hda_common,snd_soc_skl
snd_soc_acpi           16384  3 snd_sof_pci,snd_soc_acpi_intel_match,snd_soc_skl
snd_hda_intel          36864  2
idma64                 16384  0
snd_intel_nhlt         16384  3 snd_hda_intel,snd_sof_intel_hda_common,snd_soc_skl
virt_dma               16384  1 idma64
snd_hda_codec         110592  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek,snd_soc_hdac_hda
snd_hda_core           65536  10 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_hda_codec_realtek,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
mei_me                 24576  0
intel_lpss_pci         20480  0
snd_hwdep              16384  1 snd_hda_codec
mei                    65536  1 mei_me
intel_lpss             16384  1 intel_lpss_pci
cfg80211              589824  3 ath,mac80211,ath10k_core
i915                 1478656  49
intel_gtt              20480  1 i915
video                  40960  1 i915
input_leds             16384  0
mac_hid                16384  0`

Looked in both Crosh as well as Crouton. Any other thoughts?

**Comment by sebanc** [comment]
I think you missed it, it appears In the middle of your log: "elan_i2c 36864 0". Could you try adding "module_blacklist=elan_i2c" to the kernel command line ?

**Comment by ryanbatiuk** [comment]
Hey that did it!

I nano'd into:
/etc/modprobe.d/blacklist.conf

And added:
blacklist elan_i2c

And gave it a reboot, and the trackpad is working. Granted, the right mouse button doesn't work, but 2-finger click works for "right-clicking"

Thanks again @sebanc

**Comment by navidreko** [comment]
hey could you post the commands you used if you know? I would be very thankful!

**Comment by ryanbatiuk** [comment]
Hi @navidreko, read the post about yours.

I did the following:
`nano /etc/modprobe.d/blacklist.conf`

And added this new line to the blacklist.conf file.:
`blacklist elan_i2c`

And rebooted

**Comment by navidreko** [comment]
Thank you very much!!!!

I'll try it !!!!!

Have a nice easter!!!

Ryan Batiuk ***@***.***> schrieb am Mi., 31. März 2021, 22:20:
