### ISSUE TITLE
Some issues the 

### ISSUE THREAD

**Issue by divya789vidya** [sebanc/brunch#383]
> **Audio Switch not working **

when i connect headphone and  want to use only the microphone of headphone and internal speaker 
the sound doesn't come from the speaker 
that means the audio switch options are not working 
![image](https://user-images.githubusercontent.com/67728911/87061509-758f6180-c229-11ea-8c17-725246d04bee.png)

> **Internal drive mount  option**
 not working with the non dev chromeos i.e. when os start the after mounting the screen gets blanked
and when the  cros_debug is enabled in and mount internal drive is enabled  the Android apps not start it get loading  continuously

> **Bluetooth not working **
the  bluetooth not working in the rtl8723de wireless devices 
![Screenshot 2020-07-09 at 9 10 45 PM](https://user-images.githubusercontent.com/67728911/87061362-47aa1d00-c229-11ea-8bf2-091be8e7fbd9.png)

> **acpi_power_button problem **
 i think some the option doesn't work with the  non dev chrome os 
 just as the acpi_power_button  not working with the non dev chrome os(cros_debug not enabled)
> **Not a big issue **
the android apps takes 3 to 4 min on startup to load  the apps 

 and all other the thing are GOOD , VERY VERY THANK YOU FOR THE CREATOR/DEVELOPER OF THIS FRAMEWORK

**Comment by sebanc** [comment]
Most of those bugs have been subject to very recent changes. Could you confirm you are using the latest brunch version ?

**Comment by divya789vidya** [comment]
yes

**Comment by divya789vidya** [comment]
sorry i diint sethe stable release

**Comment by divya789vidya** [comment]
going to update

**Comment by divya789vidya** [comment]
[dmesg.txt](https://github.com/sebanc/brunch/files/4904620/dmesg.txt)
the Dmesg text info Bluetooth problem

**Comment by divya789vidya** [comment]
@sebanc 
today when i enabled the options=mount internal drive option and lot of problem get detected

**Comment by divya789vidya** [comment]
> **None of the internal drive is mounted**

![canvas](https://user-images.githubusercontent.com/67728911/87213760-e6776c00-c344-11ea-842c-f0aa7b5969b8.png)


> **Andriod app loading failed**

![canvas (1)](https://user-images.githubusercontent.com/67728911/87213782-158ddd80-c345-11ea-98d8-800afff7acf2.png)

after sometime
![canvas (1)](https://user-images.githubusercontent.com/67728911/87213804-39512380-c345-11ea-902b-df6460c63baf.png)
![canvas (3)](https://user-images.githubusercontent.com/67728911/87213812-4ff77a80-c345-11ea-9625-452f81ad9941.png)

> **Bluetooth Problem**

![canvas (4)](https://user-images.githubusercontent.com/67728911/87213842-91882580-c345-11ea-8c93-807f17e2492a.png)



DMESG TXT FILE
[dmesg2.txt](https://github.com/sebanc/brunch/files/4906115/dmesg2.txt)
