### ISSUE TITLE
permission denied for /dev/sda6

### ISSUE THREAD

**Issue by oneironaut2209** [sebanc/brunch#386]
I booted chrome os from a USB pen drive (/dev/sdb) and I have an HDD (/dev/sda) and there is a 64 GB NTFS partition (/dev/sda6) where I want to get disk image and dual boot from that disk image from HDD  so I typed command in shell 

1 mkdir -p ~/tmpmount
2 sudo mount </dev/sda6> ~/tmpmount

Then it says "sudo /dev/sda6 permission denied"

BTW I have windows if that matters...

**Comment by sebanc** [comment]
Remove the "<" ">" around /dev/sda6
