### ISSUE TITLE
Out of space errors on a 128GB USB thumb drive

### ISSUE THREAD

**Issue by fifn2** [sebanc/brunch#388]
The shell output for:
```
sudo bash chromium-install.sh -src chromeos_13020.87.0_rammus_recovery_stable-channel_mp-v2.bin -dst  /dev/sda
```
![image](https://user-images.githubusercontent.com/38477874/87213928-797cbb80-c2dd-11ea-86be-63aac9d41f97.png)
![image](https://user-images.githubusercontent.com/38477874/87213942-91ecd600-c2dd-11ea-8806-c093778858ad.png)

It doesn't boot.

**Comment by hbarsaiyan** [comment]
> The shell output for:
> 
> ```
> sudo bash chromium-install.sh -src chromeos_13020.87.0_rammus_recovery_stable-channel_mp-v2.bin -dst  /dev/sda
> ```
> 
> ![image](https://user-images.githubusercontent.com/38477874/87213928-797cbb80-c2dd-11ea-86be-63aac9d41f97.png)
> ![image](https://user-images.githubusercontent.com/38477874/87213942-91ecd600-c2dd-11ea-8806-c093778858ad.png)
> 
> It doesn't boot.

Format /dev/sda and do a reboot. After that it should work fine.

**Comment by Skawtnyc** [comment]
Make sure to clean off all of the existing partitions on the USB stick. If you have a Windows system, diskpart is perfect for this.

**Comment by sebanc** [comment]
If I am not mistaken, this issue was due to an old cgpt version that came with ubuntu 16.04 and has been fixed.
