### ISSUE TITLE
Usage syntax error

### ISSUE THREAD

**Issue by ranjith6303** [sebanc/brunch#389]
Chromeos-install. sh: line 7: syntax error near unexpected token `$’\r’ ‘
‘hromeos-install. sh: line 7: `usage( )

How can i fix this

**Comment by ranjith6303** [comment]
![IMG_20200711_200945](https://user-images.githubusercontent.com/68160748/87231742-6a7a3400-c3d7-11ea-9972-ae846435623c.jpg)

**Comment by sebanc** [comment]
As mentioned in "Please read this before creating issues #307", I am not related to any youtube video and don't provide support if you have installation issues while following one.

If you have issues with the official way in the readme, I will try to help you. Else please submit your issue to Kedar.

**Comment by ranjith6303** [comment]
Sir i am unable to  run this code
sudo bash chromeos-install.sh -src < path to the ChromeOS recovery image > -
dst chromeos.img
please give me a solution





*Yours faithfully,*

*RanJith Tr,9400016777,8101555000*
