### ISSUE TITLE
Camera not detected - Surface Pro 6

### ISSUE THREAD

**Issue by BuzzKnightbeer** [sebanc/brunch#392]
Hello,

I just prepared a USB stick and everything except the Camera seems to be working great.

Before creating a dual boot setup, I just wanted to see if this is fixable.

I used the latest Brunch (Brunch r83 k4.19 stable 20200708) and the 83 rammus recovery image.

I've read in a different post that using samus might fix the camera issue but before testing it I wanted to make sure that this won't introduce new problems as in the readme it says ramus is only for 4th generation and older CPUs. The Surface Pro 6 has an 8th generation CPU.

Does anyone have any experience with this?

Also, unrelated to this, what is the difference between Brunch and Crossaint? I haven't used the later because Brunch works nearly perfect so far. Just curious...

**Comment by Skawtnyc** [comment]
This is a Linux driver issue. As in, there are no Linux drivers for Surface cameras. My solution was to simply get an inexpensive external Logitech webcam, which works fine.

**Comment by BuzzKnightbeer** [comment]
Ahh sorry, I meant Crossaint. I edited the original post.

Is there a way to add support for the cameras manually?

**Comment by Skawtnyc** [comment]
None that anyone is aware of. It seems that Microsoft hasn't shared any code or specs for the hardware, so no drivers are available except for Windows drivers.

**Comment by sebanc** [comment]
Indeed I confirm what @Skawtnyc says, there is currently no linux kernel driver for Surface devices camera (still the nice guys at linux-surface github seem to be working on it) and "samus" recovery image will not help without driver, you should therefore stay on "rammus".

With regards to the difference between croissant and brunch, you can find a quick summary in the issue #59 .

**Comment by BuzzKnightbeer** [comment]
Thanks, got it!
