### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by hacker1024** [sebanc/brunch#4]
This looks like a great project, but I've noticed a regression compared to Project Croissant.

I have a Dell Inspiron 7586 (with a 1280x720 front camera). This worked fine with Project Croissant with several base chromium builds, but it doesn't seem to work with brunch and the Octopus image. It's not detected.

**Comment by sebanc** [comment]
Hi, 

Could you try with "eve" recovery image and see if it works ?

If it does not work, could you please post the content of "/etc/camera/camera_characteristics.conf" and "lib/udev/rules.d/50-camera.rules" ?

Thank you.

**Comment by sebanc** [comment]
Hi,
I just uploaded a new "testing" release, could you try both camera support and tablet mode with it ?
Thank you

**Comment by hacker1024** [comment]
> Hi,
> I just uploaded a new "testing" release, could you try both camera support and tablet mode with it ?
> Thank you

Sorry for the late response.
I can't see any testing releases, should I use the latest one?

**Comment by hacker1024** [comment]
The latest release still doesn't work. Should I still try eve, and provide those files?

**Comment by sebanc** [comment]
Could you try the new testing build ?

**Comment by hacker1024** [comment]
The latest testing build works, thanks!

**Comment by hacker1024** [comment]
What did you change?

**Comment by sebanc** [comment]
For camera, i fixed a bug in my camera patch. Is touchpad working too ?

**Comment by hacker1024** [comment]
Unfortunately not, I'm going to grab a dmesg tomorrow and post on that issue page.

**Comment by sebanc** [comment]
Ok thanks for the feedback :) could you post the dmesg in your touchpad issue ? i will close this one as the camera is fixed.
