### ISSUE TITLE
brunch USB fails to boot with illegal instruction

### ISSUE THREAD

**Issue by da0ist** [sebanc/brunch#402]
ThinkPad X220 brunch 83 USB stick created on ElementaryOS.
![IMG_20200714_095550994](https://user-images.githubusercontent.com/7945846/87454540-f4352780-c5b8-11ea-9886-6df46d987baa.jpg)

**Comment by sebanc** [comment]
It's 2nd gen, try "samus" recovery image.

**Comment by da0ist** [comment]
I could have sworn I used rammus before say around 80? Will try sammus, thanks!

**Comment by sebanc** [comment]
You are right google changed something to "rammus" in r83 which makes it incompatible with Intel Gen < 4

**Comment by da0ist** [comment]
Looks like it's working, but the screen went to sleep and I can't wake it. I see disk activity (during the install) so I'll just have to trust the process. It'll shut down if it completes successfully, right?

**Comment by sebanc** [comment]
No it does not shutdown at the end, you should probably do it again

**Comment by da0ist** [comment]
It eventually woke up and installed fine! I am posting this from it. My ThinkPad X201 won't boot from the stick, is it too old (lacks secure boot?)

**Comment by sebanc** [comment]
It does probably not support uefi boot, you can try the mbr_support.tar.gz package in the master branch of this repo (extract the brunch release, then the mbr_support.tar.gz in the same folder and install as usual)

**Comment by da0ist** [comment]
I'll give that a try after I Rammus my ThinkPad X1C6! Thanks for this awesome project!
