### ISSUE TITLE
Chrome Cpu Consumption?

### ISSUE THREAD

**Issue by roynatech** [sebanc/brunch#408]
I have installed altas image with the latest brunch framework. It works well including wifi gpu sound etc. One problem is cpu load. Process named 'Browser' (Probably chrome) takes about 20~30% of cpu. And the pc was idle at the moment. Is chrome os heavy like that? I think it can be hardware issue 'cause my cpu is Intel Core i5-5200U (2core 4thread 2.2Ghz, boost clock 2.5Ghz) 
I wanted a different OS than Windows and Linux, so I installed this. But now, the fan sound disturbs me... It's too loud even though the computer being idle.

**Comment by roynatech** [comment]
![Screenshot 2020-07-17 at 2.43.28 PM.png](https://user-images.githubusercontent.com/65128262/87752740-0ffc3000-c83c-11ea-926d-4f0af29a44f2.png)
Attaching screenshot

**Comment by Crescendo-BLYAT** [comment]
Browser itself is the OS & 30% is not heavy....
maybe you could clean the heatsink & change the paste if it's begin heating up....

I could run some Android apps + some tabs on my Celeron N3350 & the CPU usage only jumped to 32%...

so it's not heavy, unlike Windows 10 which can go to constant 70% idling in the very same laptop....

**Comment by tornadox** [comment]
Have you tried other recoveries?

**Comment by sebanc** [comment]
Atlas has an ipu3 camera framework so the android camera service fails and runs in a loop in the background. You should probably use "rammus" or "eve" instead (refer to issue #359).

**Comment by rayqusa** [comment]
whats the name of the apps that show like task manager?
