### ISSUE TITLE
What's a good image for Intel Celeron N4000?

### ISSUE THREAD

**Issue by efbe2121** [sebanc/brunch#412]
This might be not an issue but a question. I cant find what generation is N4000, so if there's any one that know which image better to be used, i'd be thankful

**Comment by Skawtnyc** [comment]
The N4000 is Goldmont, an evolution of Apollo Lake which is 7th gen. You should be able to use Rammus with it.

**Comment by efbe2121** [comment]
Aight thanks for the info, it helps me a lot
