### ISSUE TITLE
Bluetooth seems bugged.

### ISSUE THREAD

**Issue by mounis-bhat** [sebanc/brunch#414]
Bluetooth seems to have some issue, it keeps on searching but doesn't find anything and is not discoverable by other devices as well.
My device is HP pavilion 15 and I'm using rammus recovery. 
Latest brunch and OS (83)

**Comment by Crescendo-BLYAT** [comment]
AFAIK you can only connect headset + mouse + sth like that...
Not phone & yes it's not visible on other devices...

Confirmed on real Chromebook ASUS C214MA I just purchased. I thought my new Chromebook is broken, but I can connect mouse + BT headset just fine.
