### ISSUE TITLE
No linux install option?

### ISSUE THREAD

**Issue by da0ist** [sebanc/brunch#417]
![image](https://user-images.githubusercontent.com/7945846/88075459-ad51af80-cb2d-11ea-9dca-c8d957f50e53.png)

ThinkPad T440p with rammus

**Comment by princepjamie06832** [comment]
Did you check virtualization is enabled on your BIOS? What CPU did you have if virtualization feature available?

**Comment by da0ist** [comment]
That was it! Thanks!
