### ISSUE TITLE
Shortcut to Overview screen?

### ISSUE THREAD

**Issue by jhedfors** [sebanc/brunch#422]
Is there a shortcut to the overview screen, as we do not have the Chromebook overview button?

It would be great f the Overview button could be mapped to an unused F-key. On my keyboard, I have an unlabled F7 which functions as a redundant "brightness-up", and an unlabled F10 which does not appear to do anything.

**Comment by dubagunta-rohit** [comment]
f5 on mine asus vivobook x507uar

**Comment by jhedfors** [comment]
> f5 on mine asus vivobook x507uar

Thanks!. Fn+F5 worked for me - I had not tried the Fn+ keys.

**Comment by efbe2121** [comment]
Here's what i found so far
F1 F2 : Backward Forward
F3 : Refresh
F4 : Full Screen
F5 : Overview Screen (what youre looking for)
F6 F7 : Brightness control
F8 F9 F10 : Volume control

**Comment by jhedfors** [comment]
@efbe2121 Thanks. I can confirm all those work for me as well when selected with Fn key. I know I can change that in BIOS but then I will need to press Fn+ to use the media controls. For now, using the Fn+F5 works for accessing the Overview Screen.

**Comment by Crescendo-BLYAT** [comment]
no need to change it in BIOS, just go to Chrome OS settings > device > keyboard > (there is a toggle) Treat top-row keys as function keys.

**Comment by jhedfors** [comment]
> no need to change it in BIOS, just go to Chrome OS settings > device > keyboard > (there is a toggle) Treat top-row keys as function keys.
Thanks, however I don't think that is what that toggle actually does. This toggle just re-maps the modifier key from Fn+ to Search+. In my case (since I do not have a hardware search key) it simply disabled access to the alternate functions.

**Comment by ayushbathrey** [comment]
search + f5 works for me
