### ISSUE TITLE
Camera rotated and flipped(mirrored)

### ISSUE THREAD

**Issue by Ebbot9876** [sebanc/brunch#432]
Camera in Chuwi HI10 X is rotated and mirrored!I´ve mentioned this in issue #276 .
![IMG_20200727_105010833](https://user-images.githubusercontent.com/62138441/88552604-92e36e80-d024-11ea-9275-ddeaae6637d7.jpg)
[dmesg.txt](https://github.com/sebanc/brunch/files/4982491/dmesg.txt)

**Comment by sebanc** [comment]
Hi, there will be an attempt to fix it in the next release which has been delayed but should now arrive shortly.

**Comment by ccchan234** [comment]
so this shd be fixed,
how about the stylus?
thanks, from 2023
