### ISSUE TITLE
Intel 10th Gen - Intel Iris Plus Graphics Chrome OS not booting and stuck

### ISSUE THREAD

**Issue by ganesh8592** [sebanc/brunch#438]
![chrome os](https://user-images.githubusercontent.com/7200536/89097911-e2e57b00-d400-11ea-915b-ec3b3e893005.jpeg)

my laptop details are: hp spectre x360 13t late 2019 with i7 1065G7 and intel iris Graphics 

can you please provide kernel 5.4 with specific repo

**Comment by ganesh8592** [comment]
got successful installation

**Comment by Namaneo** [comment]
Exact same issue here, and exact same configuration on an recent XPS 13. How did you manage to fix this? Manually replacing the kernel inside the image, or something else?

**Comment by ganesh8592** [comment]
tomorrow I will provide link with related all files

**Comment by Namaneo** [comment]
That would be fantastic ! Thank you 🙂

**Comment by ganesh8592** [comment]
hi bro,

sry  for delay

intel 10th gen need kernel 5.4 or ablove

brunch: Brunch r83 k5.4 unstable 20200711
<https://github.com/sebanc/brunch-next/releases/tag/r83-k5.4-unstable-20200711>
link:
https://github.com/sebanc/brunch-next/releases/tag/r83-k5.4-unstable-20200711
developer/supported by https://github.com/sebanc

thanks & regards
Ganesh

**Comment by Namaneo** [comment]
Thank you 🙂 It seems this repository is private.

@sebanc Is it possible to have the permissions to access it? 
And when do you think the update we will moved to the stable repo?

Thanks !

**Comment by sebanc** [comment]
I happened to catch this one by chance but you are commenting on a closed issue. Please use issue #18 instead.

@Namaneo you have received an invite to brunch next, however it is not planned to be merged to stable for now as kernel 5.4  is currently not compatible with many devices with Intel gen < Skylake.

**Comment by ryansg8** [comment]
@sebanc Sorry for the spam you must get, but I am in the process of trying to install this onto my Ice Lake laptop, and access to brunch-next branch for kernel 5.4 would be awesome so I can get it booting. Thanks!
