### ISSUE TITLE
Changing Channel

### ISSUE THREAD

**Issue by jhedfors** [sebanc/brunch#44]
In your latest test release, you mention that it can be used on the Dev channel to try out version 83 new functionality.  Are there recovery images avalable for different channels, or do you have to just switch channel, and the apply the test Brunch build similar to the instuctions for automatic updates?

**Comment by sebanc** [comment]
No, there are no recoveries for dev channel. If you want to try it, I recommend to update brunch first, then add options=enable_updates to the kernel command line, reboot and change channel to dev in settings.

**Comment by jhedfors** [comment]
Cool. Thanks for the information!

**Comment by jhedfors** [comment]
I was fully expecting an automatic Powerwash when switching channels, but it did not. Confused, but pleasantly surprised... :)  Booted right up and Linux and Android apps both work!

**Comment by sebanc** [comment]
Nice that it worked :)

Just for info, there will be a powerwash if you revert to stable.

**Comment by jhedfors** [comment]
Got it. Thanks!
