### ISSUE TITLE
Terminal/Command Line support

### ISSUE THREAD

**Issue by RedcatPhoenix2** [sebanc/brunch#445]
I think there should be a command using Chrome OS's Terminal or Windows's Command Line. For dual boot or full download.

Chrome OS (Full Download, Chromebooks only or Linux Terminal Full or Dual boot): `sudo brunch chromeos-install.sh`

What you should see on Chrome OS (on a Chromebook):
`Device Name: (device)
Model: (model)
Date of Release: (device's year of release)
Brunch Legacy Support: (yes/no)
Brunch UEFI Support: (yes/no/WP Enabled)
Brunch USB Support (yes/no (obviously yes unless there is no usb ports))`

Dual booting or Fully Downloading from Linux:
`Device Name: (device)
Model: (model)
Version: (LTS, Latest, Beta)
Brunch Legacy Support: (yes/no)
Brunch UEFI Support: (yes/no/WP Enabled)
Brunch USB Support (yes/no (obviously yes unless there is no usb ports))

Confirm to Download (1 = Dual Boot, 2 = Full Download): (1/2)`

Windows (Dual Boot): `C:\PATH\TO\FOLDER\Brunch.bat` (Downloads the command) Then, `brunch dual-boot`
When you download the command:
`Brunch
Downloading (=====================>) 100%`
When you run the Dual Boot Command
`Device Name: (device)
Model: (model)
Windows Version: (Needs to be Windows 7 and above, Windows 10 users can get the linux terminal.)
Brunch UEFI Support: (yes/no/WP Enabled (Yes, windows has WP))
Brunch USB Support (yes/no)`

Windows (Full Download): `C:\PATH\TO\FOLDER\Brunch.bat` (Downloads the command) Then, `brunch download`
When you download the command:
`Brunch
Downloading (=====================>) 100%`
When you run the Full Download Command
`Device Name: (device)
Model: (model)
Windows Version: (Needs to be Windows 7 and above, Windows 10 users can get the windows terminal.)
Brunch USB Support: (yes/no)`

**Comment by sebanc** [comment]
Sorry but in my opinion the install process is easy enough so this is not part of my current plans. However, you can still add your own wrapper to the brunch install script.
