### ISSUE TITLE
WiFi not working

### ISSUE THREAD

**Issue by OCActivated** [sebanc/brunch#45]
Hello. Following the guide, I managed to make a bootable USB. The Chrome OS setup screen has opened, but I cannot use WiFi. I cannot see any network in Select network section.

**Comment by anubthomas** [comment]
I had a similar issue. Could you try the steps mentioned in the below bug. It solved the issue for me.
https://github.com/sebanc/brunch/issues/19

**Comment by sebanc** [comment]
@OCActivated What is your laptop model ?

**Comment by OCActivated** [comment]
> @OCActivated What is your laptop model ?

Lenovo G50-30.

**Comment by OCActivated** [comment]
I pressed Ctrl+Alt+F3 and it opened developer console but it wants a password.

**Comment by sebanc** [comment]
Indeed the solution provided by @anubthomas seems to be the right one.

At boot, when you see the grub screen, quickly press "e".
Write "module_blacklist=ideapad-laptop" after cros_debug and then F10 to boot.
Verify if you have wifi.

If you have, finish the setup, open cros shell and run "sudo edit-grub-config" to add the "module_blacklist=ideapad-laptop" in a persistent way.

**Comment by OCActivated** [comment]
Nope. I typed "module_blacklist=ideapad-laptop" after "cros_debug" but it didn't worked. I can only access internet by using ethernet cable. Also I'm getting error on the screen like this:
![15868538261488439812575637842001](https://user-images.githubusercontent.com/62648794/79204484-485b2f00-7e45-11ea-910c-85ed24a9e9bd.jpg)

**Comment by sebanc** [comment]
Ah great, since you can login, could you send me a dmesg (taken after a reboot):
Open cros shell
Type "dmesg > ~/Downloads/dmesg.txt"
And post here the dmesg.txt file from your downloads directory.

**Comment by OCActivated** [comment]
It says "ERROR : unknown option: > ~/Downloads/dmesg.txt

**Comment by sebanc** [comment]
I think you were not completely in cros shell, to open cros shell press CTRL-ALT-T and type "shell" at the invite.
Once you are there, run "dmesg > ~/Downloads/dmesg.txt"

**Comment by OCActivated** [comment]
Okay, It worked. 
[dmesg.txt](https://github.com/sebanc/brunch/files/4474361/dmesg.txt)

**Comment by sebanc** [comment]
Could you try to add "options=broadcom_wl" to the kernel command line ?

Go to cros shell again:
- run "sudo edit-grub-config"
- add "options=broadcom_wl" after cros_debug
- Press CTRL-X to quit and y to save when requested

Reboot your laptop

**Comment by OCActivated** [comment]
Oof. Idk why but brunch started to rebuild rootfs again, my toaster takes a long time to do this.

**Comment by OCActivated** [comment]
**Yeah, it worked!** I'm now successfully connected to my network. But I have 2 more problems. Shall I continue the issue here or open a new issue?

**Comment by sebanc** [comment]
Yes, you can continue here, what are the other issues ?

**Comment by OCActivated** [comment]
I get an error, as it appears in the photo I took.

> Nope. I typed "module_blacklist=ideapad-laptop" after "cros_debug" but it didn't worked. I can only access internet by using ethernet cable. Also I'm getting error on the screen like this:
> ![15868538261488439812575637842001](https://user-images.githubusercontent.com/62648794/79204484-485b2f00-7e45-11ea-910c-85ed24a9e9bd.jpg)

**Comment by sebanc** [comment]
For the android apps issue, could you try to reset google sync:
https://support.google.com/chromebook/answer/2914794?hl=en

And then do a powerwash.

**Comment by OCActivated** [comment]
Nice, now I can access to Google Play Store. Now, I want to wipe everything on the laptop and install Chrome OS to my laptop permanently. There are parted areas on the hard disk. I want to combine them all into one partition but how?

**Comment by OCActivated** [comment]
Thank you so much. I did a powerwash and now i can access to Google Play Store. 👍
