### ISSUE TITLE
how to enable open GL 3? dota Underlords required it

### ISSUE THREAD

**Issue by rayqusa** [sebanc/brunch#450]
hi there, I dont know if original chrome OS support it or not, but several games like Dota underlords, and vainglory required open GL3 and or vulkan.

does anyone know how to enable it? or chrome OS simply doesn't support open GL 3?

my rig is lenovo thinkpad yoga 260. 6200u

thank you

**Comment by sebanc** [comment]
Both android and crostini work on bunch the same way as on chromebooks, you will probably find for information on the chromeos forums.
