### ISSUE TITLE
Disabling android media server scanning

### ISSUE THREAD

**Issue by ameyjoshi3068** [sebanc/brunch#451]
I have done an extra option mount_internal_drives
But it eats lots of CPU and resources 
I am asking if there is any way to disable the scanning.

**Comment by rayqusa** [comment]
me too, always 50% on idle.
they say if scnning complete, it going normal

**Comment by ameyjoshi3068** [comment]
Please tell how to disable it

**Comment by rayqusa** [comment]
it seem rescanning after reboot. how to disable it?

**Comment by sebanc** [comment]
Either remove "mount_internal_drives" or disable android media server directly into android apps settings.
