### ISSUE TITLE
Chrome OS stucks everytime

### ISSUE THREAD

**Issue by yegender124001** [sebanc/brunch#453]
I have an Intel CPU of 2nd generation. And I am using sammus age.  It stucks on everytime on:
`chromeos-boot-alert:chromeos_selfrepair`
How much time does it takes on its first boot.

**Comment by rayqusa** [comment]
it seem your windows not shutting down properly, try shutting down your windows with pressing shift key

**Comment by yegender124001** [comment]
> it seem your windows not shutting down properly, try shutting down your windows with pressing shift key

Ok I will do And then I will tell about what Happens

**Comment by yegender124001** [comment]
> > it seem your windows not shutting down properly, try shutting down your windows with pressing shift key
> 
> Ok I will do And then I will tell about what Happens

It Works thanks a lot.
