### ISSUE TITLE
Is there a way to install this on /dev/sdb?

### ISSUE THREAD

**Issue by thoratica** [sebanc/brunch#454]
In my computer, /dev/sda is an 1TB HDD, and /dev/sdb is an 128GB SSD. So, I want to install this on the ssd, but I can't see an option to install on sdb. How can I do it?

**Comment by jhedfors** [comment]
I followed these instructions:
https://github.com/sebanc/brunch#dual-boot-chromeos-from-your-hdd
Choosing the location is included in the steps.

There are other installation methods as well that allow you to specify the location, but I have only used the method above, and it works great.

**Comment by khanhtranngoccva** [comment]
Depends. If they are permanently mounted, use dual boot. Otherwise use the method for USB.

**Comment by thoratica** [comment]
Thanks! I'll try it.
