### ISSUE TITLE
Dual Boot installing?

### ISSUE THREAD

**Issue by OCActivated** [sebanc/brunch#47]
When I type "sudo mount /sda5 > ~/tmpmount", it says "bash: /home/chronos/user/tmpmount: Is a directory". I'm new to things like this. Sorry for taking your time.

**Comment by sebanc** [comment]
The command is incorrect, it should be `sudo mount /dev/sda5 ~/tmpmount`

**Comment by OCActivated** [comment]
I'm getting the same error.

**Comment by sebanc** [comment]
I am pretty sure the command I provided should work, did you remove your ">" ?
