### ISSUE TITLE
"loopfile not found" but is there and named correctly

### ISSUE THREAD

**Issue by smac0** [sebanc/brunch#473]
When booting it displays the following errors:
![IMG_20200815_195604](https://user-images.githubusercontent.com/69737533/90323379-d3b60f80-df60-11ea-999b-2ca7efd5d699.jpg)
The img file name is entered "correctly", here my grub config:
![IMG_20200815_200640](https://user-images.githubusercontent.com/69737533/90323408-50e18480-df61-11ea-8bd7-61cd883e1321.jpg)
I'm (trying to) run Chromeos (sda4) alongside Arch (sda6), Android-x86 (sda2) and Windows (sda1).
I tried to do some troubleshooting but everything looks fine to me:
![IMG_20200815_200217](https://user-images.githubusercontent.com/69737533/90323418-7ff7f600-df61-11ea-9b98-260a96111307.jpg)
I'm running it on an old Acer Extensa 5635Z trying both with rammus 80 and 83 with the corresponding brunch versions, got the same results.

**Comment by rayqusa** [comment]
it happen on me. easy. login to your windows, then shutdown with shift key. I don't know but it work perfectly 

It happen several times, usually after booting to windows.

**Comment by rayqusa** [comment]
what is your CPU?

**Comment by ameyjoshi3068** [comment]
I will try to help you in this issue 

<b>I recommend you to check if secure boot is disabled in windows control panel </b>
If it is done then read ahead

<b>Here are steps</b>

1)First boot into arch Linux

2)If you have already installed gparted then open    it and verify the partition where chrome os is installed again

3)Open any file explorer and mount partition where chrome os is installed and check if file named chromeos.img is present there

If in case you have installed chrome os on different partition or partition number got changed after resize or any activity add correct img path to menuentry

**Comment by ameyjoshi3068** [comment]
<b>I got what is wrong here</b>
In your menuentry you mispelled
 ``chromeos.img``
As ``chromos.img``

**Comment by sebanc** [comment]
The "trap invalid opcode" means that your CPU is not compatible which is why it cannot find the image

**Comment by smac0** [comment]
> I got what is wrong here
> In your menuentry you mispelled
> `chromeos.img`
> As `chromos.img`
> Correct it

that's not it, as the file is also misspelled (see the output of ls (hd0,4)/)
(First both were spelled correctly but I changed it in the menuentry and also in the img file name to "chromos" because when it was correct it didn't work either and I wanted to see if it changed something.)

**Comment by smac0** [comment]
> The "trap invalid opcode" means that your CPU is not compatible which is why it cannot find the image

ah ok thanks! 
I just assumed it was supported that's why I didn't check, sorry.
Thanks very much for your help!
