### ISSUE TITLE
Surface Go

### ISSUE THREAD

**Issue by manelscout4life** [sebanc/brunch#48]
It seems like the webcam. Maybe I'm missing something. 

I used the newest testing brunch along with rammus r80

Everything else is just perfect! Thank you so much you have no idea how happy this makes me.

**Comment by sebanc** [comment]
Hi, unfortunately there are no drivers for the Surface Go webcams in the linux kernel.

All I can say for now is that if someone makes a driver at some point, I will try to include it (but I doubt it will happen).

Happy to hear that otherwise it works as expected :)
