### ISSUE TITLE
Realtek RTL8723BU Support

### ISSUE THREAD

**Issue by arzanulhaq** [sebanc/brunch#482]
By default, Realtek RTL8723BU will use rtl8xxxu kernel module. There is a problem when we use both wifi and bluetooth at the same time with rtl8xxxu kernel module. The bluetooth connection will works poorly, it will make the audio output stutter.

There is another kernel module for Realtek RTL8723BU at https://github.com/lwfinger/rtl8723bu that works with both bluetooth and wifi connection at the same time. Please add support for Realtek RTL8723BU with Non-Concurrent Mode (concurrent mode disable). Thank you.

**Comment by kishanrajbhat** [comment]
I cant help you much cuz I am not a pro when it comes to this stuff...try joining the discord server and ask there.....link is in the wiki...

**Comment by arzanulhaq** [comment]
So, this modprobe ERROR should be fixed first before brunch will officially have support for Realtek RTL8723BU?

**Comment by sebanc** [comment]
Is RTL8723BU driver stable in a more recent mainline kernel (5.4 or even newer) ?

**Comment by arzanulhaq** [comment]
Yies, it is stable. I'm using the driver on Ubuntu and Manjaro for about 2 years and never face any problem.
If it will be included in brunch, please make sure that Non-Concurrent Mode is activated (concurrent mode disable) and rtl8xxxu is blocked. Thank you.

**Comment by sebanc** [comment]
Sorry but that's not what I meant, my question was "is the standard rtl8xxxu stable in recent linux kernels ?"

**Comment by arzanulhaq** [comment]
The standard rtl8xxxu will make bluetooth connection unstable. An example, listening spotify using bluetooth headset will make the sound stutter because the wifi and bluetooth being used at the same time.

For wifi conncection only, there is no problem using rtl8xxxu.

**Comment by arzanulhaq** [comment]
Please check comment about the rtl8xxxu performance at https://github.com/lwfinger/rtl8723bu/issues/112#issuecomment-418560172

**Comment by sebanc** [comment]
I checked https://github.com/lwfinger/rtl8723bu and concurrent mode is enabled in the source Makefile:
EXTRA_CFLAGS += -DCONFIG_CONCURRENT_MODE

Should I comment this line or build the driver as it is ?

**Comment by arzanulhaq** [comment]
Please disable concurrent mode by comment the line EXTRA_CFLAGS += -DCONFIG_CONCURRENT_MODE

**Comment by sebanc** [comment]
rtl8723bu driver was added in the new release, use "options=rtl8723bu" to activate it

**Comment by arzanulhaq** [comment]
Thank you very much. I found that the rtl8xxxu module is still loaded with lsmod. I already activated the options=rtl8723bu.
And when i removed the rtl8xxxu with rmmod, the wifi stop working.

**Comment by arzanulhaq** [comment]
I can enable the 8723bu by removing the rtl8xxxu and 8723bu and then load the 8723bu.
It works perfeclty. Thank you very much.

chronos@localhost ~ $ lsmod | grep 8723bu
8723bu                925696  0
cfg80211              589824  2 mac80211,8723bu

chronos@localhost ~ $ lsmod | grep rtl8xxxu
rtl8xxxu              110592  0
mac80211              774144  1 rtl8xxxu

chronos@localhost ~ $ sudo /sbin/rmmod rtl8xxxu
chronos@localhost ~ $ sudo /sbin/rmmod 8723bu
chronos@localhost ~ $ sudo /sbin/insmod /lib/modules/rtl8723bu.ko

**Comment by sebanc** [comment]
I don't really understand why "rtl8xxxu" gets probed whereas I blacklist it....

1) Could you confirm the file /etc/modprobe.d/rtl8723bu.conf is correctly created with the below content ?
`blacklist rtl8xxxu`

2) If the first point is correct, could you try to remove "modprobe mac80211" from /etc/init/rtl8723bu.conf and confirm if it solves the issue ?

**Comment by arzanulhaq** [comment]
1. Yes. There is /etc/modprobe.d/rtl8723bu.conf file with "blacklist rtl8xxxu" content

2. I rremove "modprobe mac80211" from /etc/init/rtl8723bu.conf and the rtl8xxxu still loaded.

**Comment by sebanc** [comment]
Could you provide the full lsmod after boot ? (before running any modprobe/rmmod command)

**Comment by arzanulhaq** [comment]
Here you go.
[lsmod.txt](https://github.com/sebanc/brunch/files/5202272/lsmod.txt)

**Comment by sebanc** [comment]
Thanks !

Could you try to replace the below text in /etc/modprobe.d/rtl8723bu.conf:
"blacklist rtl8xxxu"
by:
"install rtl8xxxu /bin/true"

**Comment by arzanulhaq** [comment]
Today i just up dated the recovery to version 85. 
Everything work perfectly and the rtl8xxxu not loaded on fresh boot without any modification to /etc/modprobe.d/rtl8723bu.conf and /etc/init/rtl8723bu.conf.

So your script to activate the options=rtl8723bu actually work and maybe my system got dirty because I modified it.

Thank you very much.
