### ISSUE TITLE
video playback issue (Waiting for help)

### ISSUE THREAD

**Issue by ameyjoshi3068** [sebanc/brunch#484]
A black screen is visible instead of video
Audio is clearly heared
Video can be watched in chrome browser and in youtube playstore app
But video is not visible in android apps which use youtube player in them

I am using rammus 84 with debug mode disabled and able to install Netflix
I also have same problem with Google movies 
I am using it on my old dell Inspiron 3647 
Monitor :Dell(TM) 20 Monitor, 19.5 Inch VIS, E2014H , DVI/VGA
Cpu :Intel(R) Pentium(R) Processor G3240 (3M Cache, 3.1GHz)×86_64
With integrated graphics
Ram : 4gb DDR 3

**Comment by ameyjoshi3068** [comment]
Please help me because I am unable to study online without it

**Comment by ameyjoshi3068** [comment]
I am using rammus 84 with debug mode disabled and able to install Netflix
I also have same problem with Google movies 
I am using it on my old dell Inspiron 3647 
Monitor :Dell(TM) 20 Monitor, 19.5 Inch VIS, E2014H , DVI/VGA
Cpu :Intel(R) Pentium(R) Processor G3240 (3M Cache, 3.1GHz)×86_64
With integrated graphics
Ram : 4gb DDR 3

**Comment by sebanc** [comment]
Sorry but drm does not work on external monitors even on real chromebooks, this is the chromeos standard behavior as far as I can tell.

**Comment by ameyjoshi3068** [comment]
Can we set our monitor as internal by any of software/firmware/kernel modification?

**Comment by sebanc** [comment]
I would not know how to do that

**Comment by ameyjoshi3068** [comment]
Ok no problem
Just asking because
I thought It would be better if I could install online learning android application of school in pc
If there is no way to do it then OK

**Comment by ameyjoshi3068** [comment]
Again thanks for this wonderful project

**Comment by ameyjoshi3068** [comment]
Now I noticed in my dmesg that during boot brunch loads microphone and and speakers and mark them as **Internal**
![Screenshot 2020-09-05 at 8 12 28 PM](https://user-images.githubusercontent.com/69226625/92307432-2dd05080-efb4-11ea-919b-a1fc089d4f96.png)

So my question is can't we mount desktop monitor as internal in same way ?

I believe this will definitely solve this issue

**Comment by sebanc** [comment]
ChromeOS has its own rules to define if hardware is internal or external (probably based on the connector used).

Brunch does not interact with this mechanism and I would not know how to change the detected type (internal / external) for speakers nor for video.

**Comment by ameyjoshi3068** [comment]
@sebanc sorry for taking you time
I didn't now I that
I am closing this issue
