### ISSUE TITLE
Display issue on Intel atom z8300

### ISSUE THREAD

**Issue by picklrick** [sebanc/brunch#488]
I successfully installed chrome os using latest brunch and rammus but there is no display after boot but there is boot sound.i also tried samus and some other recoveries ,with every recovery same situation.  Device: Acer switch 10e with Intel atom z8300 processor.

**Comment by sebanc** [comment]
Hi, could you try with a brunch r81 version ? (it is just to see if a patch I added recently is causing you issue)

**Comment by picklrick** [comment]
Hi, thanks for the reply.Tried r81 but still same problem. Can i get access to next brunch.I want to try kernel 5.4.###

**Comment by sebanc** [comment]
Sure, you should have received the invite. However, for now it appears to only work with recent devices (after skylake gen)

**Comment by picklrick** [comment]
The reason i want to try is because the recent Linux mint is working perfectly.Thanks for the invite

**Comment by sebanc** [comment]
Just found this:
https://bugs.freedesktop.org/show_bug.cgi?id=109760

Adding "i915.fastboot=1" to the kernel command line should be a temporary fix. There is also a kernel patch applied that I will try to add in brunch.

**Comment by sebanc** [comment]
Actually I misread, there is no kernel patch attached.

**Comment by sebanc** [comment]
You should also probably add "intel_idle. max_cstate=1" (for performance, not related to the display issue)

**Comment by picklrick** [comment]
Thank you so much , it worked. However WiFi not working.Is there any fix.

**Comment by picklrick** [comment]
Adapter : RTL8723BS

**Comment by picklrick** [comment]
Updated to unstable brunch k 5.4 ,WiFi works.Still backlight control not working,Bluetooth doesn't turn on.

**Comment by sebanc** [comment]
Nice, it is the first device below skylake gen that I see which is able to boot with 5.4 kernel.

For now RTL8723BS is not well supported but I will try to add a driver for it.

For backlight contol, that's the issue I saw nearly everywhere on linux forums for this device but I did not find any mention of a kernel patch, if you find the kernel patch to fix it I don't mind including it.

**Comment by picklrick** [comment]
backlight control works with latest Linux mint
