### ISSUE TITLE
Wifi not working

### ISSUE THREAD

**Issue by 1arrcy1** [sebanc/brunch#490]
[dmesg.txt](https://github.com/sebanc/brunch/files/5139724/dmesg.txt)
This might be a verry specefic issue but i cant get the wifi to work
lspci -nnk:
`Network controller [0280]: Broadcom Corporation BCM43142 802.11b/g/n [14e4:4365] (rev 01)
        Subsystem: Foxconn International, Inc. Device [105b:e071]`
As you can see no kernel driver in use. Wich i would expect because most linux distro's dont have support on default so i normaly install the drivers. The problem is i dont know how to do it on chrome os. so therefore the question if driver support can be added or sent me in the right direction to do it myself. 

thx in advance

UPDATE:
for those that have the same problem running `insmod /lib/modules/broadcom_wl.ko
` fixes it untill next reboot. how can i make it that it will be fixed even if i reboot
[dmesg.txt](https://github.com/sebanc/brunch/files/5139730/dmesg.txt)

**Comment by sebanc** [comment]
Normally, this is done automatically by adding "options=broadcom_wl" to the kernel command line (after cros_debug). Did you try that ?

**Comment by 1arrcy1** [comment]
> Normally, this is done automatically by adding "options=broadcom_wl" to the kernel command line (after cros_debug). Did you try that ?

Obviously yes, but after `cros_debug` i did not. might be more helpful to say this it in the beginning of documentation of**Framework options** works like a charm.

Much tanks, Arrcy
