### ISSUE TITLE
[question] can update to 84?

### ISSUE THREAD

**Issue by rayqusa** [sebanc/brunch#491]
I was saw at official website that there is update image for 84. can we just update, or wait for stable brunch v84?

thank you

**Comment by eldergom** [comment]
I installed it with brunch r83 + recovery 83 on Surface Pro 4 and updated it to 84 (using framework options) so it works fine.

**Comment by sebanc** [comment]
There have been no specific issues raised with r84, you should be able to update safely.

**Comment by dubagunta-rohit** [comment]
@sebanc r85 will be coming soon, are you working on updating the brunch?

**Comment by rayqusa** [comment]
thank you

**Comment by stucki** [comment]
see also #504
