### ISSUE TITLE
Linux mode missing

### ISSUE THREAD

**Issue by GabrielFarias9989** [sebanc/brunch#492]
I downloaded the samus recovery 83, my cpu is the 2nd gen (sandy bridge) and after install and setup all the system when I go to settings I can't find the "linux beta" mode.

**Comment by sebanc** [comment]
You need to enable virtualization options (VT-X) in your bios for linux beta to appear. Also you need to use a recovery image that has linux support but I guess you are using "samus" as recommended.

**Comment by GabrielFarias9989** [comment]
Oh, thanks i will try this on bios!
