### ISSUE TITLE
Non UEFI BIOS support?

### ISSUE THREAD

**Issue by huizichin** [sebanc/brunch#495]
Does this have non UEFI BIOS support??
If yes how to do it

**Comment by bobzane** [comment]
As far as I know you need to have UEFI.

**Comment by huizichin** [comment]
There is a MBR version in the code thingy but it doesn't work
![IMG_20200830_024827](https://user-images.githubusercontent.com/16850884/91644085-64b1de00-ea6b-11ea-84fa-6f2f296ffbfb.jpg)

**Comment by huizichin** [comment]
oh after looking at #173 i found that you cant run brunch chromeos on duo core cpu
is there really no way to do it?

**Comment by efbe2121** [comment]
No, i have pentium duo core on my old PC, I've tried everything. But seems like there's no way.
My error was different from yours tho

**Comment by huizichin** [comment]
well this is sad
i heard that fydeos support android play store
gonna try that out i guess

**Comment by sebanc** [comment]
Indeed core 2 duo cpu are not supported by current chromeos recovery images.
