### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by MaxenceAdnot** [sebanc/brunch#497]
In the README.md you mentionned: 
`As such, many bad things can happen with your device and mostly your data. Make sure you only use this framework on a device which does not contain any sensitive data and keep non-sensitive data synced with a cloud service. I cannot be held responsible for anything bad that would happen to your device, including data loss.`

Could you clarify this statement ? 

Aside from data loss, is there any risk identified ? Could we consider the image produced by Brunch as safe (excluding the physical access risk) ? 

By the way thank you @sebanc  for your great work.

**Comment by sebanc** [comment]
Hi,

This is quite unlikely but:
- As brunch is not the intended way for chromeos to work, at some point a chromeos script could potentially behave badly with brunch and delete data unexpectedly.
- Also chromeos recovery images include device firmware updates (that I try to disable) but that a close enough device might potentially accept the and get flashed with the wrong firmware.

I cannot really guarantee that both cannot happen even though I consider this unlikely and there has not been reported cases for now.
