### ISSUE TITLE
Unable to Boot

### ISSUE THREAD

**Issue by axeriox** [sebanc/brunch#50]
Hi there, I'm having issues booting as it kernel panics upon selecting the USB I created using the [guide](https://github.com/sebanc/brunch#install-chromeos-on-a-usb-flash-drive--sd-card-1) in the Readme.

Attached below is the verboose logs before it forcibly restarts the computer. 

![image0](https://user-images.githubusercontent.com/17935272/79469183-c2cbb080-7ff7-11ea-95b4-cfe9dfaec11b.png)

System Specs:
Model: Medion Erazer - X7859 
CPU: Intel i5 8300H (TPM Enabled, Secure Boot Disabled, SGX Disabled)
RAM: Single 8GB Stick
GPU: Nvidia GTX 1060 (Wasn't running as MSHybrid was enabled in the BIOS and the laptop display **should** only run on the iGPU)
GPU2: Intel UHD 630

**Comment by sebanc** [comment]
Hi,

Thanks for the printscreen and the detailed description.

Could you post a short video of the boot process (the source issue most probably occurs prior to the printscreen you posted) ?

**Comment by axeriox** [comment]
Here's the video you requested. 

https://gfycat.com/uglybewitchedindianhare

**Comment by sebanc** [comment]
Thanks for the video, it seems that the partition /dev/sdc5 is corrupted. Could you re-download the chromeos recovery and try again the process ?

**Comment by axeriox** [comment]
Alright.

**Comment by sebanc** [comment]
Forgot to ask, what size is your usb flashdrive ?

**Comment by axeriox** [comment]
16 GB.

**Comment by sebanc** [comment]
ok 16gb is perfect

**Comment by axeriox** [comment]
Okay I have finished creating the .img file I'll proceed to using Rufus to write the file onto the USB

**Comment by axeriox** [comment]
Right USB flashed I'm gonna reboot and record for any changes

**Comment by axeriox** [comment]
![44FC374D-4E74-49A9-A2D2-A52E3846BE35](https://user-images.githubusercontent.com/17935272/79489980-08967200-8014-11ea-8ba3-a0db35cfc6bf.jpeg) Hi again, the installation was going fine until it froze at this, any idea how to fix it?

**Comment by sebanc** [comment]
Everything is normal until here, it did not display the welcome screen ?

**Comment by axeriox** [comment]
I meant everything was going fine in this text console but then it just froze after that line

**Comment by sebanc** [comment]
ok i was just confirming cause that is the exact point where chromeos welcome screen is supposed to be displayed.

Actually I think, chromeos i running but there is a display issue.

 Could you reboot, press "e" quickly when you see the grub screen and add "fbcon=map:1" after cros_debug ?

**Comment by axeriox** [comment]
![image](https://user-images.githubusercontent.com/17935272/79492051-56f94000-8017-11ea-9d57-63da70f8b1ec.jpg)
Going to try that

**Comment by axeriox** [comment]
Hi sorry for not replying in a while, I'm having issues with the USB being too slow. So I'm going to retry it via the Linux [method](https://github.com/sebanc/brunch#dual-boot-chromeos-from-your-hdd).

**Comment by sebanc** [comment]
Hi, I tried to improve the support for dual gpu in the new release. Could you give it a try without modifications first and if it does not work with "fbcon=map:1" added to the kernel command line ?
