### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by DevHamid** [sebanc/brunch#503]
Hello, i have issue with playback video, which is not working. Youtube videos can't play both on browser and Youtube app. I really wonder, is driver or codec issue which i don't have knowledge to resolve it. Hopefully we are can fix it. Thanks before.

Note: idk tested in another website, but i think is not working too.

**Comment by sebanc** [comment]
This is usually related to an audio issue. Do you have sound in chromeos ?

Could you attach a dmesg to this issue ? (run "dmesg > ~/Downloads/dmesg.txt" in crosh shell and attach dmesg.txt to this issue)

**Comment by DevHamid** [comment]
hello, thanks for respond, here's the log file 

[dmesg.txt](https://github.com/sebanc/brunch/files/5178285/dmesg.txt)

thnx before.

**Comment by sebanc** [comment]
Could you try to run "sudo alsactl --file /usr/share/alsa/ucm/bytcr-rt5651/asound.state restore" in crosh shell after boot and then try to play a video ?

**Comment by DevHamid** [comment]
still not working.

sudo alsactl --file /usr/share/alsa/ucm/bytcr-rt5651/asound.state restore
No state is present for card Audio
alsactl: sysfs_init:48: sysfs path '/sys' is invalid

Found hardware: "HdmiLpeAudio" "" "" "" ""
Hardware is initialized using a generic method
No state is present for card Audio
alsactl: sysfs_init:48: sysfs path '/sys' is invalid

Found hardware: "bytcr-rt5651" "" "" "" ""
Hardware is initialized using a generic method

**Comment by sebanc** [comment]
Could you try to replace the content of /usr/share/alsa/ucm/bytcr-rt5651 with the files available in the below repo ?
https://github.com/alsa-project/alsa-ucm-conf/tree/master/ucm2/bytcr-rt5651

**Comment by DevHamid** [comment]
what command i must suppose to type? sorry before

**Comment by DevHamid** [comment]
![Screenshot 2020-09-08 at 10 18 55 PM](https://user-images.githubusercontent.com/13690753/92497094-81000880-f22b-11ea-80e2-ff24da33716a.png)

Playback now works, but audio only work on tws

**Comment by sebanc** [comment]
what do you mean by "tws" ?

**Comment by DevHamid** [comment]
> what do you mean by "tws" ?

true wireless bluetooth headset. other than that still no sound.
No sound on speaker
No sound on headset cable

**Comment by DevHamid** [comment]
![Screenshot 2020-09-09 at 9 33 29 PM](https://user-images.githubusercontent.com/13690753/92605735-a4d35500-f2e4-11ea-993b-ede720f73348.png)

alsamixer unusable

**Comment by DevHamid** [comment]
I decide to move to another issue
