### ISSUE TITLE
How do I access the Downloads folder from Crosh shell?

### ISSUE THREAD

**Issue by Pumpino** [sebanc/brunch#525]
I downloaded the latest Brunch update and recovery to the Downloads folder.

I opened a Crosh shell using Ctrl-Alt-T and typed "shell".

However, I can't for the life of me locate the Downloads folder. I've updated previously and don't remember having a hard time finding it, so I'm wondering what's happened.

Any ideas? Thanks.

**Comment by arzanulhaq** [comment]
you could try 
cd ~/Downloads/

**Comment by Pumpino** [comment]
I found it in /home/user/random/MyFiles/Downloads.
