### ISSUE TITLE
Acer C720 internal mic issue

### ISSUE THREAD

**Issue by mikka9** [sebanc/brunch#531]
It works, but at very very low level.
"options=internal_mic_fix" added.

**Comment by sebanc** [comment]
Could you try to create a file /etc/modprobe.d/alsa-fix.conf with the below content ?

options snd_hda_intel index=1 model=,alc283-chrome

source: https://wiki.archlinux.org/index.php/Chrome_OS_devices#Fixing_audio

**Comment by mikka9** [comment]
I think, my mic has internal issue, because in win10 and mint it has the same problem(
Thanks
