### ISSUE TITLE
Proper right click

### ISSUE THREAD

**Issue by TKFRvisionOfficial** [sebanc/brunch#535]
So for me everything worked beautifully. I have a Asus VivoBook Max D541N and used coral (i did this because the cpu build into my laptop was also used for a chrome book and that one use this). Because this is a normal laptop it has a proper right-click-button. But it dosent work. It just does the normal click. Ofcourse I can use two fingers but is there maybe a way to remap this button to the right click?

Thanks

**Comment by sebanc** [comment]
Chromeos disables right click when multi-touch gestures are enabled, I don't think it is possible to have both.

**Comment by TKFRvisionOfficial** [comment]
Thats to bad...anyways...can someone add the  "Asus VivoBook Max D541N" to the comaptible devices? Thanks...
