### ISSUE TITLE
Chrome OS Recovery Website not working (https://cros-updates-serving.appspot.com)

### ISSUE THREAD

**Issue by vasuratanpara** [sebanc/brunch#537]
The Website for Chrome OS Recovery (https://cros-updates-serving.appspot.com/)  which is mentioned in Readme file it isn't working.

![img](https://user-images.githubusercontent.com/15255654/93954423-aefd4680-fd1b-11ea-89cf-a711a02b542e.png)

**Comment by balopez83** [comment]
Not sure how long it will work with the main site being down but try this alternate site: https://cros.tech/

**Comment by vasuratanpara** [comment]
Thanks @balopez83
