### ISSUE TITLE
not able to sleep with brunch r 85 testing 20200919

### ISSUE THREAD

**Issue by ameyjoshi3068** [sebanc/brunch#538]
Cannot sleep with the latest brunch update by pressing shortcut search+shift+l
As soon as Chrome OS sleeps it turns on again in 1-2 seconds
The smart lock feature also doesn't work

I have seen in the changelog that the attempt to improve sleep has been implemented 

Can the fix be made optional (with framework option)?

Device: Dell Inspiron 3647 pc
  With Intel 4th gen Intel(R) Pentium(R) Processor G3240 
Options: acpi_power_button , suspend_s3

**Comment by ameyjoshi3068** [comment]
Can I downgrade brunch directly using `ChromeOS-update` or it will trigger powerwash?

**Comment by sebanc** [comment]
I had no feedbacks confirming this change was actually helping with suspend so I am probably going to revert it in next release.

Going back to the previous brunch r85 should not trigger a powerwash as it is the same kernel version, however I cannot guarantee it and you should still backup your important data.

**Comment by ameyjoshi3068** [comment]
OK Thanks
