### ISSUE TITLE
MMC install issue that was previously non-existent.

### ISSUE THREAD

**Issue by 5074pokemon** [sebanc/brunch#540]
I've noticed that I can no longer install the brunch framework from a USB flash drive. Older versions of the framework would install just fine, but I've recently encountered a trackpad issue, so I decided to re-image my asus netbook with a clean version of the latest framework and chrome recovery image, now the installer says that my storage is not a valid disk name despite what fdisk says.
![image](https://user-images.githubusercontent.com/62725853/94222875-8ceefa00-febc-11ea-9e25-83a0c532b202.png)
![image](https://user-images.githubusercontent.com/62725853/94222910-a4c67e00-febc-11ea-8c19-8c62ee73db13.png)

**Comment by sebanc** [comment]
I have indeed changed the destination device check in latest release, however it seems it behaves correctly for my sdcard.

Could you post the output of the 2 below commands ?

`if [ ! -b "/dev/mmcblk1" ]; then echo true; else echo false; fi`

`if [ ! "$(lsblk -npo pkname "/dev/mmcblk1" | grep /dev | uniq)" == "/dev/mmcblk1" ]; then echo true;
 else echo false; fi`

**Comment by 5074pokemon** [comment]
![image](https://user-images.githubusercontent.com/62725853/94231599-5328ee00-fed2-11ea-911f-4cb22d243d93.png)

**Comment by sebanc** [comment]
In theory both should be false. Could you also post the output of `lsblk -npo pkname "/dev/mmcblk1" | grep /dev | uniq` and also just `lsblk -npo pkname "/dev/mmcblk1"`

**Comment by 5074pokemon** [comment]
Both commands output nothing
![image](https://user-images.githubusercontent.com/62725853/94283273-cce6c900-ff1e-11ea-88a2-c6bbe9e8a10c.png)

**Comment by sebanc** [comment]
Ok so this is the issue, could you post the output of `lsblk "/dev/mmcblk1"` ?

**Comment by sebanc** [comment]
Nevermind, I will fix it in the next release by changing the way I check for valid block devices

**Comment by 5074pokemon** [comment]
Found a workaround to install onto my laptop, so I'm closing the issue.
Temporary Workaround:
Linux USB and two versions of the framework: The latest version, and a slightly older one that will still install. Borrow the install_chromeos.sh from the old version of the framework and use it to install Chrome OS directly to the flash storage with the new framework image files. So far, haven't found any issues with my installation.
