### ISSUE TITLE
chromeos-install.sh - "/dev/nvme0n1 is not a valid disk name"

### ISSUE THREAD

**Issue by swebervna** [sebanc/brunch#543]
I installed Chrome OS with Brunch yesterday and it worked just fine, but after editing the grub I got it stuck in a boot loop so I wiped the disk and tried installing it again. But now, everytime I run the chromeos-install.sh script, I get the error "/dev/nvme0n1 is not a valid disk name", even though that is exactly what the disk is.

When I lsblk, I see /dev/nvme0n1. There's no way I'm typing it incorrectly.

Any help is greatly appreciated, thanks. :)

**Comment by supechicken666** [comment]
Just type nvme0n1 during the script is ok

**Comment by swebervna** [comment]
> Just type nvme0n1 during the script is ok

I tried that and I get:
df: nvme0n1: No such file or directory
Not enought space to create image file

**Comment by supechicken666** [comment]
Try using gparted to make a new platform table

**Comment by swebervna** [comment]
> Try using gparted to make a new platform table

I recreated my media, something with Brunch must've been damaged in my download from the website. It's working now 👍
