### ISSUE TITLE
Trying to hide console output when booting

### ISSUE THREAD

**Issue by swebervna** [sebanc/brunch#544]
I used sudo edit-grub-config and replaced it with this:
`set timeout=2

menuentry "ChromeOS" {
  regexp --set disk "(^.+)(,gpt)" $root
  linux ($disk,7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off cros_secure cros_debug enforce_hyperthreading=1 console= options=enable_updates
  initrd ($disk,7)/lib/firmware/amd-ucode.img ($disk,7)/lib/firmware/intel-ucode.img ($disk,7)/initramfs.img`

Saved the changes, shutdown my computer, started it back up, and now I'm immediately taken to the GNU GRUB command line screen.

The laptop I'm performing this on is a Dell Inspiron 5481

**Comment by Skawtnyc** [comment]
Add quiet after cros_debug
