### ISSUE TITLE
Surface Go 2 Wifi not working

### ISSUE THREAD

**Issue by cdurau** [sebanc/brunch#547]
Hey guys,

I love project brunch and just bought a Surface Go 2 in the base version with 64GB to install it on. 
So far everything seems to work fine, even pen and bluetooth, except for the wifi connection. The toggle is off and if I turn it on, it won't find any Hotspots. The chip is Intel Wifi 6 AX200.

I tried the iwlwifi_backport option, but it did not work either. 

Did somebody get it to work on a Surface Go 2 or some similar device with the same wifi adapter?

**Comment by sebanc** [comment]
Hi,

The "iwlwifi_backport" option has been reported working on Surface Go 2. Did you install chromeos in dual boot or single boot ?

Could you post your grub config ?

Also,  is secure boot enabled on your SG2 ?

**Comment by cdurau** [comment]
Hey Sebanc,

I added the framework options to the wrong line at the end of the grub.cfg not at the line starting with linux... Wifi is working now :-)

Thank you very much for your quick reply!
