### ISSUE TITLE
Play Store Issues

### ISSUE THREAD

**Issue by sgtstadanko** [sebanc/brunch#55]
Hi.  I have noticed that the Google Play store window isnt redrawing and sometimes turns black until you move it or resize the app.  Is there some flag to apply to fix this?

**Comment by sebanc** [comment]
Hi, the latest testing release has a fix included, did you try it ?

**Comment by sgtstadanko** [comment]
I used brunch_r80_k4.19_stable_20200407. Is there a way to update to testing release without rebuilding images? I have just installed all to internal drive.

**Comment by sebanc** [comment]
Yes, download the latest testing release (no need to extract it) and run "sudo bash chromeos-update -f <path_to_brunch_release_archive>" in crosh shell.

**Comment by sgtstadanko** [comment]
That fixed it. Thanks a brunch.
