### ISSUE TITLE
update to dev87

### ISSUE THREAD

**Issue by sujal2102** [sebanc/brunch#551]

**Comment by sujal2102** [comment]
can i update chromeos to dev87 withoud any bug.

**Comment by sujal2102** [comment]
I mean without

**Comment by sujal2102** [comment]
what is brunch next repo

**Comment by ameyjoshi3068** [comment]
@sujal it is not recommended to update to dev channel until matching brunch is available **but** if you want to test new features you surely can upgrade but be ready to face bugs(unlikely but can)
I would recommend a complete backup to be safe

about the brunch-next, it is a private repo for testing of higher brunch framework with 5.4 kernel
It is found that most devices with less than intel 4th gen processors are unable to boot with it.

**Comment by sujal2102** [comment]
can you tell me which recovery images are for <=intel 3 processor

**Comment by ameyjoshi3068** [comment]
This is mentioned in readme of this repo
Currently:

"rammus" is the recommended image for devices with 4th generation Intel CPU and newer.
"samus" is the recommended image for devices with 3rd generation Intel CPU and older.
"grunt" is the image to use if you have supported AMD hardware.

**Comment by ameyjoshi3068** [comment]
I suggest you read the complete readme and then post issues

**Comment by sujal2102** [comment]
thankyou very much but i was talking about other then samus.

**Comment by sujal2102** [comment]
I have updated to dev 87 everything is excellent but camera not working. 
how to fix this ?

**Comment by NSbuilder** [comment]
> @sujal it is not recommended to update to dev channel until matching brunch is available **but** if you want to test new features you surely can upgrade but be ready to face bugs(unlikely but can)
> I would recommend a complete backup to be safe
> 
> **about the brunch-next, it is a private repo for testing of higher brunch framework with 5.4 kernel
> It is found that most devices with less than intel 4th gen processors are unable to boot with it.**

@sebanc Well since rammus is only recommended for intel 4th gen processors and up ( and also common processors ), would you please do a version of brunch that use kernel 5.4?

Also, since Chrome OS 86 binary is unavailable, whould it be ok to use Chrome OS 85 recovery with Brunch 86?
