### ISSUE TITLE
Disable touchscreen?

### ISSUE THREAD

**Issue by jhedfors** [sebanc/brunch#556]
My digitizer is finally starting to malfunction after my HP laptop was dropped by my kid a few months ago.  Pages are randomly scrolling or closing, as I think touches are being registered inadvertently.

How can I disable it? I have seen reference to "Search+Shift+T", but as my keyboard does not have a Search key....  

Thanks.

**Comment by sebanc** [comment]
If I remember well, "search" is the windows key.

Just tried it and it seems to work for me

**Comment by jhedfors** [comment]
Thanks. I swear I tried that, and it didn't work... but it does work now.  Let's see if that makes this computer usable again (without touchscreen).
