### ISSUE TITLE
/dev/sdb is not valid disk name, but disk is present on the system

### ISSUE THREAD

**Issue by supercute** [sebanc/brunch#570]
I tried install to usb disk and get this error. I fixed this by replaced pkname to kname. Maybe this will be useful to someone.
```bash
if [ ! -b "$destination" ] || [ ! "$(lsblk -npo kname "$destination" | grep /dev | uniq)" == "$destination" ]; then echo "$destination is not a valid disk name"; exit 1;
 ```

**Comment by sebanc** [comment]
Thanks for reporting this issue, it should be fixed in brunch r86

**Comment by sebanc** [comment]
Hi, thanks for the report :) this issue should be fixed in brunch r86. Don't hesitate to re-open it if it does not work as expected

**Comment by mecode670** [comment]
this still happens

**Comment by Patrick-web** [comment]
instead of `dev/sdb1 put dev/sdb`
