### ISSUE TITLE
Is there a scope of running this chrome OS in VMware

### ISSUE THREAD

**Issue by ABugNamedBeetle** [sebanc/brunch#574]
Things which are working:
I am successful in creating .iso and installing Chrome OS.
" chromeos_image_tester.sh" is also yielding ok

but I'm getting this error "brunch: ChromeOS was not found on any device"

![image](https://user-images.githubusercontent.com/62416701/95690460-9bb40b80-0c35-11eb-99c5-dc7575a95e79.png)

**Comment by sebanc** [comment]
Brunch does not work in virtualbox due to missing graphic drivers as explained in #303

**Comment by Pikotaro** [comment]
it doesn't support iSCSI. you need to create a SATA drive instead. No iSCSI, NVMe or IDE support

**Comment by ABugNamedBeetle** [comment]
thanks @Pikotaro for the help.
But its now stuck at  "ui main process terminated"(now i think this is gpu issue)
![image](https://user-images.githubusercontent.com/62416701/95879255-c7e59e80-0d93-11eb-940a-fe88411363be.png)

**Comment by Pikotaro** [comment]
you can try disableing 3d acceleration... if you really want to run it in a virtual machine you could try installing ESXi on your PC and enable GPU passthrough.... But this might be not worth it
