### ISSUE TITLE
No Audio/Video Playback - Asus Chromebook C300 Quawks

### ISSUE THREAD

**Issue by Stoobacca** [sebanc/brunch#58]
[dmesg.txt](https://github.com/sebanc/brunch/files/4505260/dmesg.txt)
Hi,

No audio as far as I can tell and video playback is not working. Videos can buffer and stills/previews load up, but video/audio won't play. Tested in YouTube web and app, also Soundcloud to check it wasn't a YouTube error.

OS smooth in Rammus, Play Store and all other components seem to run just fine.

C300 is BayTrail, I believe using max98090 audio. Booting USB using MrChromeBox UEFI. Tested GalliumOS and audio works there.

I've tried several recoveries: Rammus, Eve, Atlas, Terra (C300SA, updated version of mine) and Caroline. Also tested with original Quawks image I came from and same issue.

Thanks

**Comment by sebanc** [comment]
Hi,

It seems like your audio firmware is not installed. Could you attach a dmesg to this issue ?

**Comment by sebanc** [comment]
To get the dmesg, go to crosh shell and run "dmesg > ~/Downloads/dmesg.txt"

Attach dmesg.txt from your Downloads folder to this issue.

**Comment by Stoobacca** [comment]
Hi.

Appreciate the quick response! I'll give it a go and load it up later on. 

Cheers

**Comment by Stoobacca** [comment]
dmesg.txt attached to first post.

Thanks

**Comment by sebanc** [comment]
Thanks for the dmesg, everything seems fine in it as far as i can see.

Could you run "sudo edit-grub-config" and add "options=disable_intel_hda" after cros_debug ?

**Comment by Stoobacca** [comment]
No luck, still the same. I did notice now when rebooting at 'rebuilding ChromeOS rootfs' higher up there's a line 'ALSA device list: no soundcards found'
![IMG_20200420_201135](https://user-images.githubusercontent.com/22343852/79791170-c7b89900-8344-11ea-81eb-aa6a28ef5f4b.jpg)

**Comment by sebanc** [comment]
Hi,

The 'ALSA device list: no soundcards found' message is normal as the driver is built as a module and not yet loaded

Could you run the following commands:

sudo alsaucm -c chtmax98090 set _verb HiFi set _enadev Headphone
sudo alsaucm -c chtmax98090 set _verb HiFi set _enadev Speakers
sudo alsaucm -c chtmax98090 set _verb HiFi set _enadev HeadsetMic
sudo alsaucm -c chtmax98090 set _verb HiFi set _enadev InternalMic
sudo alsactl store

Reboot and see if sound works.

**Comment by Stoobacca** [comment]
OK Cool,

I can't run the commands, I get some errors. 
![Screenshot 2020-04-21 at 7 29 51 AM](https://user-images.githubusercontent.com/22343852/79834292-b99a6500-83a4-11ea-8ce5-9506edbfcbcf.png)

Tried without 'options=disable_intel_hda' too just in case but I get the same error.

**Comment by Stoobacca** [comment]
Not sure if it's useful at all but contents of /usr/share/alsa/ucm:
![Screenshot 2020-04-21 at 4 16 26 PM](https://user-images.githubusercontent.com/22343852/79883415-cdb58500-83eb-11ea-967e-35bfecc79496.png)

**Comment by sebanc** [comment]
Hi,

Thanks for all the logs, I am trying to build a test image with changes included in the alsa ucm config but I am having problems with the kernel which are unrelated to this issue.
I will tell you once the test image is ready.

**Comment by Stoobacca** [comment]
Update (still no luck)

I had a look at the errors and see the files don't exist, so I'm attempting to put the files where they are expected to be...

- I created the folder 'GOOGLE-Quawks-1.0-Quawks' under /user/share/alsa/ucm/
- Then copied chtmax98090.conf and HiFi.conf from /usr/share/alsa/ucm/chtmax98090/ to the new folder
- I renamed the chtmax98090.conf  to 'GOOGLE-Quawks-1.0-Quawks.conf'
- I then created the directory 'alsa' under /var/lib/ as this folder didn't exist
- I created the file 'asound.state' and used nano to paste the contents of the GalliumOS Baytrail state file (https://github.com/GalliumOS/galliumos-baytrail/blob/master/var/lib/alsa/asound.state)

This allowed your original commands to work but no change in sound. The GOOGLE-Quawks-1.0-Quawks directory was removed on a reboot but the asound.state file is still there.

Am I on the right track at all!? I will continue browsing for fixes but I'm not sure I know enough to get it working!

**Comment by Stoobacca** [comment]
> Hi,
> 
> Thanks for all the logs, I am trying to build a test image with changes included in the alsa ucm config but I am having problems with the kernel which are unrelated to this issue.
> I will tell you once the test image is ready.

Oh cool thanks, really appreciate your help!

**Comment by sebanc** [comment]
> Update (still no luck)
> 
> I had a look at the errors and see the files don't exist, so I'm attempting to put the files where they are expected to be...
> 
> * I created the folder 'GOOGLE-Quawks-1.0-Quawks' under /user/share/alsa/ucm/
> * Then copied chtmax98090.conf and HiFi.conf from /usr/share/alsa/ucm/chtmax98090/ to the new folder
> * I renamed the chtmax98090.conf  to 'GOOGLE-Quawks-1.0-Quawks.conf'
> * I then created the directory 'alsa' under /var/lib/ as this folder didn't exist
> * I created the file 'asound.state' and used nano to paste the contents of the GalliumOS Baytrail state file (https://github.com/GalliumOS/galliumos-baytrail/blob/master/var/lib/alsa/asound.state)
> 
> This allowed your original commands to work but no change in sound. The GOOGLE-Quawks-1.0-Quawks directory was removed on a reboot but the asound.state file is still there.
> 
> Am I on the right track at all!? I will continue browsing for fixes but I'm not sure I know enough to get it working!

My idea is the same as yours, copy the ucm files as for some reason chromeos expects them somewhere else.
However, if I am not mistaken the right repo for your device is "galliumos-braswell" which does not seem to need the asound.state file.

**Comment by Stoobacca** [comment]
Ah OK!

So maybe I've copied the wrong config? I'll see if I can do anything about it but I'm not sure I'll manage to get it working!

Look forward to trying your fix whenever it may be available.

Thanks again

**Comment by Stoobacca** [comment]
I was basing the BayTrail files on the Platform given on the Chromium dev info page. Does it not strictly relate to the platform of the device? I've tried the Braswell too but not working for me either. I'm sure I'm probably doing something wrong though!

https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices
![Screenshot 2020-04-22 at 11 17 06 AM](https://user-images.githubusercontent.com/22343852/79970652-25ef9400-848b-11ea-8756-15ee19a21c10.png)

**Comment by sebanc** [comment]
My mistake, I was looking at "ASUS Chromebook C300SA"... I am going to look at Baytril repo more closely

**Comment by Stoobacca** [comment]
> My mistake, I was looking at "ASUS Chromebook C300SA"... I am going to look at Baytril repo more closely

No problem! Thought I'd post just in case. Thanks

**Comment by sebanc** [comment]
> Update (still no luck)
> 
> I had a look at the errors and see the files don't exist, so I'm attempting to put the files where they are expected to be...
> 
> * I created the folder 'GOOGLE-Quawks-1.0-Quawks' under /user/share/alsa/ucm/
> * Then copied chtmax98090.conf and HiFi.conf from /usr/share/alsa/ucm/chtmax98090/ to the new folder
> * I renamed the chtmax98090.conf  to 'GOOGLE-Quawks-1.0-Quawks.conf'
> * I then created the directory 'alsa' under /var/lib/ as this folder didn't exist
> * I created the file 'asound.state' and used nano to paste the contents of the GalliumOS Baytrail state file (https://github.com/GalliumOS/galliumos-baytrail/blob/master/var/lib/alsa/asound.state)
> 
> This allowed your original commands to work but no change in sound. The GOOGLE-Quawks-1.0-Quawks directory was removed on a reboot but the asound.state file is still there.
> 
> Am I on the right track at all!? I will continue browsing for fixes but I'm not sure I know enough to get it working!

Well, as far as I can say you are really on the right track, those steps should in theory have it working. Just make sure, you have correct permissions for the new alsa ucm folders/files.

**Comment by sebanc** [comment]
The folder that got deleted is probably because the framework was rebuild which usually happens only when a chromeos or brunch update is applied.

**Comment by Stoobacca** [comment]
I've run ls -l and get the following:

GOOGLE-Quawks-1.0-Quawks directory:
drwxr-xr-x. 2 root root 4096 Apr 22 10:29 GOOGLE-Quawks-1.0-Quawks

Files within directory:
-rw-r--r--. 1 root root  100 Apr 22 10:26 GOOGLE-Quawks-1.0-Quawks.conf
-rw-r--r--. 1 root root 4918 Apr 22 11:10 HiFi.conf

alsa directory:
drwxr-xr-x. 2 root                root                4096 Apr 22 10:35 alsa

asound.state:
-rw-r--r--. 1 root root 86405 Apr 22 10:35 asound.state

The file permissions look the same as the other directories/files but I'm not I'm not sure about setting permissions in shell, could you let me know if these look right or the command if the above needs modifying?

Cheers

**Comment by sebanc** [comment]
Indeed, that's perfect, I don't understand why sound does not work...

**Comment by sebanc** [comment]
If you have a /etc/cras directory; could you try to remove it and reboot ?

**Comment by Stoobacca** [comment]
No cras file, although alsamixer does default to "cras".

When I select sound car I get the following options:

- default
0 HDA Intel PCH
1 chtmax98090
enter device name...

**Comment by sebanc** [comment]
i think you run your tests with "options=disable_intel_hda"

**Comment by Stoobacca** [comment]
Sadly no luck. Added that back in, rebooted and let Brunch rebuild.

Then run the following

sudo mkdir /usr/share/alsa/ucm/GOOGLE-Quawks-1.0-Quawks/
sudo cp /usr/share/alsa/ucm/chtmax98090/chtmax98090.conf /usr/share/alsa/ucm/GOOGLE-Quawks-1.0-Quawks/
sudo cp /usr/share/alsa/ucm/chtmax98090/HiFi.conf /usr/share/alsa/ucm/GOOGLE-Quawks-1.0-Quawks/
cd /usr/share/alsa/ucm/GOOGLE-Quawks-1.0-Quawks/
sudo mv chtmax98090.conf GOOGLE-Quawks-1.0-Quawks.conf

Also tried the alsaucm commands and another reboot but still no.

Alsamixer now has no HDA Intel, but defaults to CRAS and no sound

**Comment by Stoobacca** [comment]
I also tried modifying asound.conf to the below (to make it default to the chtmax98090), which does change the default in alsa but no sound.. my guess is that we need to use CRAS though?

#Route all audio through the CRAS plugin.
pcm.!default {
#       type cras
        type hw
        card 0
}
ctl.!default {
#       type cras
        type hw
        card 0
}

**Comment by sebanc** [comment]
I think ChromeOS sees that your device is a chromebook and applies specific rules for it.
I will try to disable CONFIG_GOOGLE_FIRMWARE in the next testing release to see if maybe it would allow your sound card to be recognized as in a standard kinux distro.

**Comment by Stoobacca** [comment]
Cool, I'll give it a go once it's ready. Appreciate the help!

**Comment by Stoobacca** [comment]
It's fixed! (maybe fully!!). I've played around a lot so I'm not sure if I changed anything else BUT I think it is only the asound.state file causing the problem, and then a daft error on my part with the initial fix attempt! I've checked and the new .conf files I made previously are not there, so that step appears to be unnecessary, it is just the asound.state (again.. I think). 

I've reinstalled to start fresh so had to recreate the asound directory and file, I thought I'd document the commands below, as it can be annoying when someones says "I've solved it" and then doesn't post the actual solution.. correct me if any of the commands below look wrong xD

Also worth a note to anyone who may have the same error.. After making the below changes there was no audio but videos and audio websites would actually play (just silently), but then I went to double check mid post and it's all magically working. Can't say if the fixes will stick or comment on stability yet, but it's working.

sudo mkdir /var/lib/alsa/
cd /var/lib/alsa/
sudo touch asound.state
sudo nano asound.state
copy contents from 'working' statefile.. save (ctrl X > Y > Enter)

I noticed the statefile says 'state.byt-max98090', so I've corrected to 'state.chtmax98090'
reinitialised with sudo alsactl restore


The restore gives errors but not posted as sound is working!

**Comment by Stoobacca** [comment]
OK so doesn't persist on reboot, running sudo alsactl restore makes it start again, but still silent.

I'm not sure what makes the sound burst into working, but I'm getting close!

**Comment by sebanc** [comment]
Congrats on your findings and being very close to solving this issue :)

I am thinking the remaining issue might be related to the audio card autosuspend not working properly, what you can try is to find your soundcard in attributes in /sys (probably something like `sudo find /sys/devices | grep max98090`), locating the power/control file and doing `echo "on" | sudo tee /sys/devices/...../power/control`

**Comment by sebanc** [comment]
Forgot to say, it won't survive a reboot but there are ways to automate it

**Comment by Stoobacca** [comment]
> Forgot to say, it won't survive a reboot but there are ways to automate it

No worries, well I'm happy having to run it if I need to. I've run your command so I'll see if that at least makes it simpler!

Also noticed the headphone jack doesn't work (I imagine neither does HDMI audio). Headphones get identified by ChromeOS but sound doesn't switch to the Jack.

I might fiddle with it but for now I'm happy it works mostly!

**Comment by sebanc** [comment]
Hi,

I have found the fix for the audio card to be correcly recognized as "chtmax98090" and included the configuration files.

Could you try the new release with "options=baytrail_chromebook" added to the kernel command line ? (audio should work out of the box)

Not sure if the headphones, mic issues are still present though

**Comment by Stoobacca** [comment]
Hi,

Thanks for the update.

I'm downloading the r81 branch now and will give it a go.

I'll let you know how I get on.

Cheers

**Comment by Stoobacca** [comment]
So I created a new Rammus USB with the latest r81 Brunch release. I booted the USB and added options=baytrail_chromebook to the grub launcher. Still no audio.

Should the command work from USB boot?

**Comment by Stoobacca** [comment]
> So I created a new Rammus USB with the latest r81 Brunch release. I booted the USB and added options=baytrail_chromebook to the grub launcher. Still no audio.
> 
> Should the command work from USB boot?

Scrap that. Seemed to work on second try. It's laggy on my USB so I'm installing and will test from proper install

**Comment by Stoobacca** [comment]
Sound is working! Thanks so much for sorting it out!

Just a note.. Headphones work but the jack doesn't mute the Chromebook speakers, but I can get around it by turning Chromebook volume fully down and then plugging in headphones.

Thanks for your work on my problem and on the project generally!

Much appreciated.

**Comment by Stoobacca** [comment]
So I've looked into the headphone issue.

I can see that the headphone jack is being muted correctly when plugged and unplugged.

However the speakers are not being muted correctly.

I've checked the /chtmax98090/HiFi.conf and it looks fine as far as I can tell. I've also tried including the command to mute the speakers in the headphone enable and disable sequences but no luck.

Any idea how I might check this? I'll keep researching otherwise!

Cheers

**Comment by sebanc** [comment]
Sorry I am not very experienced with debugging audio, I was just able to revert a modification in the chromeos kernel that was causing the main issue but i don't think i will be able to help much more. The driver that's used in the 4.19 linux kernel is also not the same as the original chromeos one so I am not even sure it could work.

Maybe someone on the linux/galliumos forums has solved this issue or might be able to help.

**Comment by Stoobacca** [comment]
No worries, thanks anyway!

I'm looking at Gallium at the moment to see if I can find a similar issue. I'm fairly certain I found something on this error when I was looking up my first problem so hopefully I can find it again!

Thanks

**Comment by djamesrock** [comment]
Can something in this bug fix help?
https://bugzilla.kernel.org/show_bug.cgi?id=115531#c122

**Comment by sebanc** [comment]
I don't think I can help further on this issue so I will close it, don't hesitate to re-open it if needed.

**Comment by mohamedh648** [comment]
I got the same problem running samus 91 how do I run that command : options:baytrail_chromebook or is that a modified version of chrome os Im a newbie so I don't know alot I would appreciate it if somebody help me

**Comment by Stoobacca** [comment]
> I got the same problem running samus 91 how do I run that command : options:baytrail_chromebook or is that a modified version of chrome os Im a newbie so I don't know alot I would appreciate it if somebody help me

So it's been well over a year since this message.. but if you're still trying this or if anyone happens to be searching for baytrail chromebooks or chtmax max98090..

You want to run the terminal with Ctrl + Alt + T, then type "shell" and hit enter. Once in the shell, type "sudo edit-grub-config" and hit enter. In the grub config, add "baytrail_chromebook" after where it says options= and then exit with Ctrl + X

Reboot and hopefully you'll have audio. I haven't got it working on newer versions with the chromebook audio flag

**Comment by chuc2rk** [comment]
> baytrail_chromebook

same no sound on my HP 845 Ryzen 7. I try Chrome OS flex, my laptop have sound
