### ISSUE TITLE
[Question] Can I use brunch 86 with Chrome OS 85?

### ISSUE THREAD

**Issue by NSbuilder** [sebanc/brunch#580]
Since Chrome OS 86 binary is unavailable, whould it be safe to use Chrome OS 85 recovery with brunch 86?

Is it ok in general to use brunch higher than Chrome OS version? [ For ex: brunch 86 with Chrome OS 81 ]

**Comment by jhedfors** [comment]
Yes, I believe they are always backward compatible unless otherwise indicated. I have done this many times.
