### ISSUE TITLE
ChromeOS crashing at login

### ISSUE THREAD

**Issue by jhedfors** [sebanc/brunch#591]
I enable some experimental flags, now chrome/chromeos crashing back to login screen.  Anyway to fix without powerwash/rebuild?

Edit: I ended up powerwashing.... it is crazy the chromeos does not have a safe mode log-in. I am really hesitant to enable any flags now...

**Comment by Tash254-ke** [comment]
Which flags did you enable that might have caused this?

**Comment by WesBosch** [comment]
ChromeOS does actually have a safemode that activates if it detects too many crashes in a row, it will automatically turn off all flags in that scenario

**Comment by jhedfors** [comment]
@WesBosch As i understand, and from my experience, that is not work for this scenario. Flags are not turned off and a powerwash is the only way to resolve.

Further discussion here;
https://bugs.chromium.org/p/chromium/issues/detail?id=660170

**Comment by jhedfors** [comment]
@sebanc OK, well same thing happened again, only now it can't be explained away by enabling flags, as i have not touched the flags since I powerwashed a few days ago.  I had booted into Windows and or Linux Mint and back to Chrome OS.

When logging in, Chrome browser attempted to load, and had the "restore pages" prompt. Screen would not accept any input then went black after a few seconds, and it attempted to load again. This repeated a couple more times before returning to log-in screen.  I am using Mint now, and am not sure I want start over with a fresh installation every week.

**Comment by sebanc** [comment]
The only things I can think of that could cause that are:
- corrupt chromeos synced data (might be due to flags notably)
- custom boot scripts not behaving correctly

I have the same chromeos install for 2 months now, also regularly booting ubuntu and occasionally windows and never faced this issue.

**Comment by jhedfors** [comment]
> The only things I can think of that could cause that are:
> 
> * corrupt chromeos synced data (might be due to flags notably)
> * custom boot scripts not behaving correctly
> 
> I have the same chromeos install for 2 months now, also regularly booting ubuntu and occasionally windows and never faced this issue.

I have no flags enabled (I have reset them to be sure), and have not custom boot scripts. Hopefully it does not happen again. Thanks.
