### ISSUE TITLE
I can't use Linux beta in chrome os

### ISSUE THREAD

**Issue by the1tamil** [sebanc/brunch#596]
Thanks to all

**Comment by Skawtnyc** [comment]
Enable virtualization in BIOS.

**Comment by the1tamil** [comment]
> Enable virtualization in BIOS.
On bro

**Comment by princepjamie06832** [comment]
If missing 'Linux (Beta)' section on left sidebar, you need to enable virtualization in BIOS settings in order to use it.

**Comment by the1tamil** [comment]
Thanks for all finally the the problem is solved thanks to all 🤓👍

**Comment by 0neday** [comment]
useful
