### ISSUE TITLE
Android video screens not working.

### ISSUE THREAD

**Issue by COOORN** [sebanc/brunch#601]
Whenever there's a screen where a video is supposed to play(Youtube, Game Pass cloud streaming, etc.), I can't see it, but can only hear it. I tried enabling the alternative android container option but it doesn't work. Is there a workaround to this or an option I have to enable?

**Comment by sebanc** [comment]
What's your laptop model ?

**Comment by COOORN** [comment]
Dell Inspiron 5000 2 in 1. It has an intel core i7 with 8gb ram. My other old computer(Inspiron 3000 core i3) works, though.

**Comment by sebanc** [comment]
Ok, I was expecting it would be a very old laptop but it is not the case...

I guess you used "rammus" recovery image, could you try "nami" and "hatch" ?

**Comment by COOORN** [comment]
I don't want to break my working set up with my other computer, sorry. I'm on my old computer now so I'm good now. Should I close this issue, since I don't have a problem with this anymore but it still doesn't work?

**Comment by sebanc** [comment]
Yes, if you are fine with it, it is probably better to close it.
