### ISSUE TITLE
can i disable native chromeos updates after enabling

### ISSUE THREAD

**Issue by sar777-dev** [sebanc/brunch#602]
I want to ask (mainly from sebanc) that can we disable native chromeos updates after enabling it using "enable_updates" kernal command statement because after downloading chromeos recovery images it may contain issue which may google solve by pushing  OS fix updates but if it continuously be enabled, then it may get upgrade to next chromeos version and if brunch version not get updated or available, it may get ustable.

**Comment by Crescendo-BLYAT** [comment]
The OS update is not auto in brunchbook, you need to trigger it manually in the Settings > About Chrome OS.

**Comment by sar777-dev** [comment]
I had figured it out how to stop updating, simply remove added kernal command line modifications.

**Comment by ayushguptahere** [comment]
> 

Can you say me the procedure
