### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by gjbnh1701** [sebanc/brunch#607]
I continue to be BLOWN away at how good this is..But I upgraded my AIO in the last week and sound no longer works. It has an Intel/Realtek HD chip-set in it...works out in the box under linux...is there a way to pass a command to the kernel?? Otherwise it is flawless!!

**Comment by sebanc** [comment]
I am not sure I understand, did sound work on previous brunch versions ?

Which brunch / chromeos versions are you on ?

**Comment by gjbnh1701** [comment]
chrome os 85 and Brunch 85...used the same usb key on previous system, no problems...not the case on new system....even rie did chromeos on new system under windows AND linux. The wireless changed which I fixed, so I can get online. But no sound now. Windows identifies sound as Realtek High Definition Audio.

**Comment by sebanc** [comment]
Ok so sound never worked with brunch on the new system if I understand correctly. What's your computer model ? Also, could you try to update to chromeos r86 by enabling updates ? (There was a bug with audio in r85)

**Comment by gjbnh1701** [comment]
HP AIO Ff0003w is the model...

**Comment by sebanc** [comment]
I added you to "brunch-next" repository which has kernel 5.4 (you should have received a github invite), could you try it and see if sound works ?

**Comment by gjbnh1701** [comment]
Will try ASAP...

**Comment by sar777-dev** [comment]
when you are satisfied please close this issue.

**Comment by Ahmettrkr0** [comment]
Hello, I did a bios reset there is no sound in chrome os, but there is sound, I need urgent help

**Comment by Ahmettrkr0** [comment]
@gjbnh1701 @sebanc
