### ISSUE TITLE
Touchpad doesn't work

### ISSUE THREAD

**Issue by EddieGBU** [sebanc/brunch#623]
Hi! I have a problem with my touchpad and would like help.
I installed Chrome OS correctly on a USB to test before installing it on my hard drive, everything worked perfect there so I decided to install it on my pc, deleting Windows.
I followed the same steps as before (changing sdb to sda) and now the touchpad does not work.
I used the same files in both installations.
The click or slide does not work so it is useless.
The touchpad option doesn't even appear in settings now.
I have tried alt_touchpad_config and 2 and it doesn't fix it.
Sorry if I have bad English but I am using the translator.
I have an HP laptop and it uses the elan drivers.
Thanks in advance

**Comment by sar777-dev** [comment]
I also have Hp laptop it's Hp convertible x360 and its touchpad works great than windows like in scrolling.
try to install again using new fresh files. also which method you are using to install?

**Comment by EddieGBU** [comment]
I used the method that is in "code". My laptop is unfortunately not convertible :(.
What files do you think I can change? I used the latest version of brunch and version 85 of rammus.

**Comment by EddieGBU** [comment]
I just looked at the ChromeOS release page and there seems to be a new version. I will try to update tomorrow. Thank you

**Comment by sar777-dev** [comment]
why don't try other recovery images other than rammus like - snappy, kip, soraka, chell. 
Try to use recovery image in which hp chromebook have been made.In these hp recovery images Hp chromebook have their own 'hp' binaries which may get compatible which your hp laptop.
Right now I'm using 'snappy' recovery image as it have solved bluetooth disconnection problem which was in rammus.

**Comment by EddieGBU** [comment]
Thanks for the help but I already fixed it.
I added several kernel command lines and now it works almost perfect (gestures don't work).
These are the kernel command lines that I used in case someone occupies them.
i8042.noloop
i8042.nomux
i8042.nopnp
i8042.reset
module_blacklist=i2c_hid,i8042
module_blacklist=hid_multitouch
psmouse.proto=imps
psmouse.elantech_smbus=0
psmouse.synaptics_intertouch=0
module_blacklist=elan_i2c
If any of those are bad for the pc, please tell me.

**Comment by sar777-dev** [comment]
why had you added
module_blacklist=hid_multitouch
if you blacklist multitouch module, how will you use multitouch gestures( like two-finger gestures).

**Comment by EddieGBU** [comment]
The truth is that I don't understand much about those commands😅. I only did what the forum told me. I'm going to remove it right now.

**Comment by EddieGBU** [comment]
I removed it but the gestures still don't work. Thanks anyway.

**Comment by sar777-dev** [comment]
try removing 
psmouse.elantech_smbus=0
module_blacklist=elan_i2c
see if multi-gesture works

**Comment by EddieGBU** [comment]
Nope, it still doesn't work. I tried deleting module_blacklist=i2c_hid,i8042 too but it didn't work either.

**Comment by EddieGBU** [comment]
I'll try another release, I'll try kip.
One question, can I use the command chromeos-update? Or it may cause some problem

**Comment by sar777-dev** [comment]
I think you misunderstood something I listed the commands to be removed from the rest of your commands not to use it alone.
Actually Chrome OS cannot be installed directly – that's where branch take care of these things.
If you want to update Chrome OS you can try using framework options that is 'enable_updates' by modifying grub using cross-shell command line.
If you want help how to modify grub menu ask me.

**Comment by sar777-dev** [comment]
I had also used  framework option 'enable _updates' when ChromeOS 86 was not found on the website, then it got matched with the brunch r86, also solved the  problem of high CPU usage using Android apps.

**Comment by EddieGBU** [comment]
I deleted what you told me to delete. I was wondering if I could use the chromeos-update command to change releases (from rammus to kip).

**Comment by sar777-dev** [comment]
that's not possible because you are trying to change rammus to kip means you are changing one device to another.
This can be done only by fresh installation.
also does touchpad gestures worked?

**Comment by EddieGBU** [comment]
Gestures didn't work until I changed alt_touchpad_config from 1 to 2 but now swiping is very laggy. I prefer swiping over gestures so I will revert the changes.

**Comment by sar777-dev** [comment]
Have you tried other recovery images other than rammus?

**Comment by EddieGBU** [comment]
Yes, I have tried Hatch, Kip and Octopus. Only octopus made the touchpad work but the swipe is very laggy. Sometimes it detects the swipe and sometimes it doesn't.

**Comment by sar777-dev** [comment]
Try framework options in 'optupus' recovery image 
"alt_touchpad_config"
"alt_touchpad_config2"
by making changes in grub menu.

**Comment by sar777-dev** [comment]
Is your older or newer?
Also try chell

**Comment by EddieGBU** [comment]
I think it is new, I will try the methods I used before in Octopus. If there are no results then I will try another.

**Comment by sar777-dev** [comment]
Can you post 'dmesg' 
Type 'dmesg > ~/Downloads/dmesg.txt' in shell and it will save the file in Downloads folder.

**Comment by EddieGBU** [comment]
[dmesg.txt](https://github.com/sebanc/brunch/files/5495733/dmesg.txt)
I discovered something. I put sudo modprobe -r psmouse and sudo modprobe psmouse elantech_smbus=1 in shell and now the touchpad works perfect, is there a way to automate that command?

**Comment by sebanc** [comment]
Yes, adding "psmouse.elantech_smbus=1" on the kernel command line (after cros_debug) should do the same.

**Comment by EddieGBU** [comment]
Wait a sec, i'll try

**Comment by EddieGBU** [comment]
Thank you! Everything works perfect, gestures, clicks, swipe, everything!

**Comment by sar777-dev** [comment]
That's good news to hear.

**Comment by EddieGBU** [comment]
Hello, it's me, again. The touchpad just crashed again, I tried removing the kernel command and putting it back in and it doesn't work.

**Comment by EddieGBU** [comment]
I'd better go back to Windows. Very good project but unfortunately my laptop is very incompatible. I liked the system so I'll be back when I get another device. Bye

**Comment by sar777-dev** [comment]
See you soon

**Comment by bybenjamin** [comment]
> Yes, adding "psmouse.elantech_smbus=1" on the kernel command line (after cros_debug) should do the same.

The system works perfectly. Thank you for the project. Touchpad stops working after suspend. What I did to get it running again was '' sudo rmmod i2c_hid ; sudo modprobe i2c_hid '' How do I prevent the i2c_hid module from suspending Thanks in advance for your help

**Comment by AkhmadFaiz012** [comment]
> Yes, adding "psmouse.elantech_smbus=1" on the kernel command line (after cros_debug) should do the same.

Thank you so much this work perfectly, anyway can u explain why when i plug charge in my laptop the battery icon not change and still same but the percentage still up, thanks
