### ISSUE TITLE
can fingerprint reader could be included in upcoming brunch.

### ISSUE THREAD

**Issue by sar777-dev** [sebanc/brunch#624]
In my Hp convertible x360, PIN doesn't work at login screen only  password is accepted but after locking up PIN works fine.
@sebanc could be please add fingerprint support at login as this way works faster than typing password as in latest ubuntu fingerprint support had came, if its implemented in brunch it would be more wonderful.

**Comment by supechicken666** [comment]
See #455 for more info about fingerprint reader support on brunch
