### ISSUE TITLE
Videos won't play.

### ISSUE THREAD

**Issue by circl-lastname** [sebanc/brunch#642]
YouTube or any video app won't play videos. Not even the camera app. I tried to disable hardware acceleration but it did nothing. Any solutions?

**Comment by sebanc** [comment]
What's your laptop model ?

**Comment by circl-lastname** [comment]
Unmodified HP ProBook 4530s.

**Comment by sebanc** [comment]
which cpu model do you have ?

**Comment by circl-lastname** [comment]
Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz

**Comment by sebanc** [comment]
The below thread mentions a dual gpu on some models and the possibility to select the integrated gpu in the bios:
https://askubuntu.com/questions/1264579/issues-with-ubuntu-20-04-on-hp-probook-4530s

Is it applicable to your model ?

**Comment by circl-lastname** [comment]
Yes, I have the same model. I'm gonna try to do that.

**Comment by circl-lastname** [comment]
Thank you! It's working now.
