### ISSUE TITLE
Clear instructions for installing Chrome OS on Legacy/MBR devices

### ISSUE THREAD

**Issue by Suleman-Elahi** [sebanc/brunch#647]
I tried to install it on my old notebook(INTEL Dual Core processor) and used this video as tutorial: https://www.youtube.com/watch?v=UElQAh5SCmo

I used my pendrive as destination to install ChromeOS and now after booting from USB, I am getting this:

![20201114_163205](https://user-images.githubusercontent.com/24384996/99145880-797c3600-2698-11eb-9da9-b2dacb66f062.jpg)

Any idea how to fix this? Thanks.

**Comment by Suleman-Elahi** [comment]
Oh... sorry. After having a look at other issues, I got it now... the invalid opcode!!!!

**Comment by sebanc** [comment]
Exactly, I am not related to any video tutorial but the youtube should probably mention this which is stated in the readme:

`Supported devices:
Intel hardware (CPU and GPU) starting from 1st generation "Nehalem" (refer to https://en.wikipedia.org/wiki/Intel_Core),`

**Comment by Suleman-Elahi** [comment]
Yeah thanks.. I have a i3 based latop... i will install it on that....
