### ISSUE TITLE
Dell XPS 7590 OLED

### ISSUE THREAD

**Issue by shad0wfile** [sebanc/brunch#650]
Hey - we had talked maybe about a year ago re: trying to get oled brightness to work. I've hunted for solutions with no luck yet.

I've seen in some recent posts you have a test build on 5.4 kernel, and I've seen some launchpad articles where they say it may be addressed in that kernel rel.

Any chance for an invite to give it a try?

Thanks!

**Comment by sebanc** [comment]
Sure, invite sent :) Try the release in the "brunch-testing" repository.

**Comment by shad0wfile** [comment]
Gave it a try, no luck.. back to the waiting game :)

Thanks!

**Comment by sebanc** [comment]
Sorry but I have never really understood the problem with OLED, is it that brightness is always at 100% ?

**Comment by shad0wfile** [comment]
Yeah, always 100% - and on an OLED.. it's brutal, retina burning in low-lit areas. There has to be some kind of resolution out there, the Samsung Galaxy Chromebook is OLED and they have it working on there, guessing it has some flag somewhere set for it.

**Comment by sebanc** [comment]
As far as I can tell, OLED are not supported in the standard linux kernel but is compensated in linux by software color profiles.

Apparently the corresponding way to do this in chromeos would be to set night light to the expected percentage. Could you try it ?

**Comment by shad0wfile** [comment]
I gave night light a try, it still stays very bright just in different tones. Yeah I figured as much re: the other chromebook. 

Thanks for the tips and taking a look, I'll keep looking around to see if I can find anything that works.

**Comment by sebanc** [comment]
Could you try the release in brunch-unstable repo ?

**Comment by shad0wfile** [comment]
I gave it a shot, have it loaded up right now - no luck though. Using the keyboard buttons or trying the manual slider in the chromeos menu just slides side-to-side with brightness staying the same.

Let me know if you want me to collect any additional details on it.

**Comment by sebanc** [comment]
Could you check if your brightness work on a ubuntu 20.10 live usb flashdrive ? (I implemented a patch that was present in the ubuntu kernel, maybe your device does not work with it)

**Comment by shad0wfile** [comment]
Ah, that may be why, I'll give it a shot, historically the only Linux OS "out of the box" to work is PopOS! (ubuntu derivative) because they sell OLED laptops.

**Comment by sebanc** [comment]
I am looking at popos kernel source but I don't find much in it. Could you try to add "i915.enable_dpcd_backlight=1" to the kernel command line ?

**Comment by shad0wfile** [comment]
I just tried default ubuntu and it didn't work (verified). Let me try the dpcd backlight command into the latest test rel you pushed, will report back.

**Comment by shad0wfile** [comment]
I tossed this in and rebooted:
`linux ($disk,7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off cros_secure cros_debug i915.enable_dpcd_backlight=1 \`

Didn't change anything, just wanted to verify that's the correct spot for it in the grub conf.

**Comment by sebanc** [comment]
Yes that's correct. I will try to apply the "linux-oled" patches from arch aur when they get ported to 5.10

**Comment by shad0wfile** [comment]
Sounds good!

**Comment by sebanc** [comment]
I applied the linux-oled patches to 5.10 kernel in the latest brunch-unstable build if you want to try it

**Comment by shad0wfile** [comment]
I gave it a shot, no luck. I have no idea why this panel won't honor the latest kernel release, much like I have no idea what PopOS could be doing to make it work, very strange.

Thanks for giving it a shot.

**Comment by sebanc** [comment]
Did you change "/kernel" to "/kernel-5.10" in the grub config ? (default kernel is 5.4)

**Comment by shad0wfile** [comment]
Awesome! That fixed it.. working flawlessly now.

Thanks for all the help!

**Comment by sebanc** [comment]
Nice to see that it eventually worked :)

**Comment by sebanc** [comment]
Fyi, the OLED brightness patch introduced a regression for some users, starting from the next release you will have to enable it using "options=oled_display"
