### ISSUE TITLE
Stuck @ chromeos-boot-alert: self_repair (MacBook5,2)

### ISSUE THREAD

**Issue by arc-2394** [sebanc/brunch#653]
After trying to install on MacBook5,2 (Early 2009) I am stuck at chromeos-boot-alert: self repair

**Comment by sebanc** [comment]
Sorry but if I am not mistaken, MacBook5,2 have core 2 duo processors which are not supported with brunch.

**Comment by arc-2394** [comment]
Oh ok, I'm a newbie to this and probably should've read up thank you for your help!
