### ISSUE TITLE
 k5.4 unstable 20201114 Something  wrong about  Google App Store - ThinkPad edge S420

### ISSUE THREAD

**Issue by wggglggg** [sebanc/brunch#655]
5.4 unstable  +  chromeos_13421.73.0_samus_recovery_stable-channel_mp-v3.bin,   system show there`s something wrong about Google App Store, following the picture, can`t open it.
 
https://ibb.co/tJhc1Rc
also Bluetooth can open the button,  cellphone can`t research the Chrome OS.
and , try another club ( 5.4 unstable + chromeos_13310.59.0_samus_recovery_stable-channel_mp-v3.bin ).  chrome web and app store  is the same problem like   **Two problems -ThinkPad edge S420
#654 opened 10 hours ago by wggglggg**

**Comment by sebanc** [comment]
A google search shows that your laptop has an AMD gpu, could you try disabling it in the bios (if possible) ?

If you cannot disable the AMD gpu in the bios, please attach an lsmod to this issue (run `lsmod > ~/Downloads/lsmod.txt` in crosh shell and attach lsmod.txt from your Downloads folder.

**Comment by wggglggg** [comment]
Do u mean type RUN LSMOD in system? Where to type? Which app? And the whole code is?

**Comment by ameyjoshi3068** [comment]
@wggglggg here are the steps
1. press ctrl+alt+t this will open crosh terminal.
2. Type `shell` and press enter.
3. Run `lsmod > ~/Downloads/lsmod.txt`

**Comment by wggglggg** [comment]
really helpful,  I'll do it today later, thank you



发自我的小米手机
在 ameyjoshi3068 <notifications@github.com>，2020年11月18日 上午7:50写道：

@wggglggg<https://github.com/wggglggg> here are the steps

  1.  press ctrl+alt+t this will open crosh terminal.
  2.  Type shell and press enter.
  3.  Run lsmod > ~/Downloads/lsmod.txt

**Comment by wggglggg** [comment]
bash: run : command not found



发自我的小米手机
在 ameyjoshi3068 <notifications@github.com>，2020年11月18日 上午7:50写道：

@wggglggg<https://github.com/wggglggg> here are the steps

  1.  press ctrl+alt+t this will open crosh terminal.
  2.  Type shell and press enter.
  3.  Run lsmod > ~/Downloads/lsmod.txt

**Comment by wggglggg** [comment]
bash: run : command not found



发自我的小米手机
在 sebanc <notifications@github.com>，2020年11月18日 上午1:43写道：

A google search shows that your laptop has an AMD gpu, could you try disabling it in the bios (if possible) ?

If you cannot disable the AMD gpu in the bios, please attach an lsmod to this issue (run lsmod > ~/Downloads/lsmod.txt in crosh shell and attach lsmod.txt from your Downloads folder.

**Comment by wggglggg** [comment]
I`m sure about watching Youku  Iqiyi Tencent Video on WEB,
you must open v2ray  or the same kind of apps ,before you watch them on website, chrome os  needs download something through VPN just few seconds ( 5~10 sec). Unless you reboot pc  or log out system, then you can watch them even leave VPN away,

**Comment by wggglggg** [comment]
> A google search shows that your laptop has an AMD gpu, could you try disabling it in the bios (if possible) ?
> 
> If you cannot disable the AMD gpu in the bios, please attach an lsmod to this issue (run `lsmod > ~/Downloads/lsmod.txt` in crosh shell and attach lsmod.txt from your Downloads folder).

I`ve checked the BIOS, it`s Integrated Graphics already, 
pictures following:    
https://ibb.co/gjk9p7h
https://ibb.co/tJhc1Rc

**Comment by wggglggg** [comment]
chronos@localhost / $ lsmod
Module                  Size  Used by
x86_pkg_temp_thermal    16384  0
intel_powerclamp       16384  0
crc32c_intel           24576  0
ghash_clmulni_intel    16384  0
aesni_intel           368640  21700
crypto_simd            16384  1 aesni_intel
glue_helper            16384  1 aesni_intel
psmouse               135168  0
intel_rapl_msr         16384  0
thinkpad_acpi          90112  0
hid_logitech_hidpp     32768  0
hid_logitech_dj        24576  0
snd_hda_codec_hdmi     49152  1
snd_hda_codec_conexant    20480  1
snd_hda_codec_generic    69632  1 snd_hda_codec_conexant
ledtrig_audio          16384  3 snd_hda_codec_generic,snd_hda_codec_conexant,thinkpad_acpi
snd_hda_intel          36864  3
rtl8192ce              57344  0
snd_intel_dspcfg       24576  1 snd_hda_intel
rtl_pci                32768  1 rtl8192ce
snd_hda_codec         110592  4 snd_hda_codec_generic,snd_hda_codec_conexant,snd_hda_codec_hdmi,snd_hda_intel
rtl8192c_common        45056  1 rtl8192ce
rtlwifi                98304  3 rtl_pci,rtl8192c_common,rtl8192ce
snd_hda_core           69632  5 snd_hda_codec_generic,snd_hda_codec_conexant,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
r8169                  77824  0
realtek                20480  1
snd_hwdep              16384  1 snd_hda_codec
mei_hdcp               16384  0
libphy                 65536  2 r8169,realtek
mei_me                 24576  1
mei                    69632  3 mei_hdcp,mei_me
i915                 1708032  34
intel_gtt              20480  1 i915
drm_kms_helper        135168  1 i915

**Comment by sebanc** [comment]
Indeed, it is integrated graphics, I can see only three things which could cause that:
- An incorrect Google sync, try resetting it: Login to your Google dashboard account -> Go to the "Chrome" application -> Manage synced data and click on "reinitialize synced data"
- The use of a slow usb flashdrive
- Your VPN

**Comment by wggglggg** [comment]
Nothing wrong with VPN , and the OS is loaded in the harddisk,  so I tried to reinitialize synced data,     then The Web Problem is done. 
The apps circling problem has been salved, even though it`s not a good choices, like I mentioned  log in the system,  click any app , off course it`s circling , just leave them there,  log out the OS ( not reboot ), log in again, click app again, wait in   2min , the app start. 
Anyway, thank you for your suggesting.

**Comment by wggglggg** [comment]
> Indeed, it is integrated graphics, I can see only three things which could cause that:
> 
> * An incorrect Google sync, try resetting it: Login to your Google dashboard account -> Go to the "Chrome" application -> Manage synced data and click on "reinitialize synced data"
> * The use of a slow usb flashdrive
> * Your VPN

Nothing wrong with VPN , and the OS is loaded in the harddisk, so I tried to reinitialize synced data, then The Web Problem is done.
The apps circling problem has been salved, even though its not a good choices, like I mentioned log in the system, click any app , off course its circling , just leave them there, log out the OS ( not reboot ), log in again, click app again, wait in 2min , the app start.
Anyway, thank you for your suggesting.
