### ISSUE TITLE
Video Problem in Arch and Linux Error in  Chrome Os (Brunch)

### ISSUE THREAD

**Issue by mrLoliKing** [sebanc/brunch#66]
There's a problem in hardware acceleration on Arch the video playback is green.
And the Linux is going to error in my machine it won't install.
The the screen capture or recording in arch won't work and it going to freeze the screen and the arch will crash.

My Machine and Chrome Version:
Chrome Version: 

80.0.3987.162 (Official Build) (64-bit)

My Machine:
HP Probook 4520s
Intel Core i3-350M Processor (2.26 GHz, 3MB L3 cache)
Intel HD Graphics (Ironlake)

**Comment by sebanc** [comment]
Hi,

I am working on improving crostini compatibility, however i am not sure if it will help for your config. If you can test, It would be helpful for me to know if crostini works on cloudready ?

**Comment by mrLoliKing** [comment]
Ok i'll send you tomorrow or Monday the results because its 12:43 am in my time right now and i need to rest for tomorrow to some research and solve this problem too

**Comment by sebanc** [comment]
no worries, when you have the time

**Comment by mrLoliKing** [comment]
Um the crostini in cloudready is working on my machine 100%

**Comment by mrLoliKing** [comment]
There's no problem in cloudready using a crostini linux at all thats the results

**Comment by sebanc** [comment]
Thanks for the feedback, i will try to achieve the same result

**Comment by mrLoliKing** [comment]
Good Luck

**Comment by mrLoliKing** [comment]
I'll wait for the results

**Comment by sebanc** [comment]
Could you try the latest testing release ?

**Comment by mrLoliKing** [comment]
Ok wait a sec

**Comment by mrLoliKing** [comment]
Can i test this tommorow its already night tho

**Comment by mrLoliKing** [comment]
I will give you the results when im done testing

**Comment by mrLoliKing** [comment]
Still not fix:
![IMG_20200506_172722](https://user-images.githubusercontent.com/64266507/81161918-f24e5700-8fbe-11ea-815b-5337d8e4b7c5.jpg)
![Uploading IMG_20200506_172253.jpg…]()

**Comment by mrLoliKing** [comment]
![IMG_20200506_172253](https://user-images.githubusercontent.com/64266507/81162059-29bd0380-8fbf-11ea-9538-1c22e20f2b65.jpg)
S

**Comment by sebanc** [comment]
Could you try with "samus" recovery image ?

Anyway, you will have to switch to "samus" as "rammus" will fail on your device from r83 (google has added cpu instructions to the build which are not supported by your device...

**Comment by mrLoliKing** [comment]
Im going to test tommorow its already night

**Comment by mrLoliKing** [comment]
Sorry i cant test this month im so busy ill going tell you the results if i have exact time to test 🤔😟

**Comment by sebanc** [comment]
You have to remove "virtio_gpu" (crostini gpu acceleration) from /etc/ui_use_flags.txt for crostini to install.

**Comment by mrLoliKing** [comment]
Um idk if i can do this in time but i will try it

**Comment by sebanc** [comment]
I am closing this issue as the solution provided should work but feel free to reopen it if it is not.
