### ISSUE TITLE
Thinkpad X1 Carbon 4th gen - Touchpad Gesture

### ISSUE THREAD

**Issue by Damix48** [sebanc/brunch#663]
Hi, I installed ChromeOS r86 on my Thinkpad X1 Carbon 4th gen. Gesture trackpad works only with two finger but the three finger gesture  not works.

**Comment by sebanc** [comment]
On some devices adding "psmouse.synaptics_intertouch=1" to the kernel command line enable 3 fingers gestures.

Otherwise you will have to refere to #305

**Comment by Damix48** [comment]
It works, thank you
