### ISSUE TITLE
Trouble installing on Dell XPS M1330 Intel Core 2 Duo T5250 / 1.5 GHz 

### ISSUE THREAD

**Issue by MP715** [sebanc/brunch#668]
Using mbr_support.tar.gz.  Tried Rammus and Samus 86.  Install appears successful. See attached.

![2020-11-23 23 20 20](https://user-images.githubusercontent.com/74952249/100059963-849a3900-2df1-11eb-8f50-41395970e11c.jpg)

**Comment by sebanc** [comment]
Sorry but as discussed on telegram, there are no current chromeos recoveries compatible with core 2 duo.
