### ISSUE TITLE
Asus UX303LA (UX303LAB) Touchpad Not Working

### ISSUE THREAD

**Issue by selimsandal** [sebanc/brunch#672]
Hi,
I installed chromeos using Brunch r86 k4.19 stable 20201014 (latest). My touchpad is not working. Here are the outputs for "udevadm info" mouse0 and mouse1" I attached "udevadm info" outputs for mouse0 and mouse1. When I press touchpad buttons cursor appears but does nothing.

![Screenshot 2020-11-27 at 19 14 16](https://user-images.githubusercontent.com/49725809/100468357-4f3d6600-30e5-11eb-9e8b-f572a4974b65.png)
![Screenshot 2020-11-27 at 19 14 26](https://user-images.githubusercontent.com/49725809/100468360-51072980-30e5-11eb-942f-1812d3fc9400.png)

Laptop: Asus UX303LA (UX303LAB)

**Comment by darkxduck** [comment]
try the touchpad fixes they worked for me

**Comment by metalzero24** [comment]
> try the touchpad fixes they worked for me

I went to terminal as root and tried options=alt_touchpad config and config2
then typed reboot
same problem nothing works
