### ISSUE TITLE
How to increase trackpad speed beyond setting.

### ISSUE THREAD

**Issue by muckc** [sebanc/brunch#676]
I can find how to do it anywhere, sorry if this is not the place to ask.
I'm using alt touchpad config2 option, the touchpad and scrolling speed is pretty slow. I've already increased scrolling speed by modify the 40-touchpad-cmt.config file, so i'm wondering if there are any option line that change the touchpad speed? Thank you.

**Comment by stateandrei5** [comment]
chrome://flags/#allow-scroll-settings
