### ISSUE TITLE
I dont understand this

### ISSUE THREAD

**Issue by mrLoliKing** [sebanc/brunch#68]
Can you give me a example command of this plss.. just for dual boot

sudo mount < the destination partition (ext4 or ntfs) which will contain the disk image > ~/tmpmount
Create the ChromeOS disk image:

**Comment by sebanc** [comment]
Hi,

Use "lsblk" command to identify the partition on which you want to install the chromeos image, for exemple if in lsblk the name is of the partition is sda4, the full name of the partition to use in the mount command is /dev/sda4.

**Comment by mrLoliKing** [comment]
Oh thanks this is helpful now i understand 😊
