### ISSUE TITLE
Where did QEMU go?

### ISSUE THREAD

**Issue by MilkyDeveloper** [sebanc/brunch#681]
I saw a commit yesterday that removed QEMU from the installed packages list. I know I can install it using chromebrew, but it's a nice feature for it to be included.

**Comment by sebanc** [comment]
Hi, I removed qemu thinking that since I added "brioche" repository, you should now be able to setup a better qemu with X11 and virt-manager support or virtualbox.

Have you tried "brioche" yet ?
