### ISSUE TITLE
Touchscreen stops working immediately after logging in

### ISSUE THREAD

**Issue by bdodroid** [sebanc/brunch#694]
On my Surface Go 2 the touchscreen works perfectly fine (including pen) until I login, at which point touch/pen becomes completely unresponsive.

I'm running r86 k5.4 stable 20201201 and have added the ipts option to the kernel line.

Am I missing something? or is the ipts not compatible with surface go 2?

**Comment by sebanc** [comment]
Surafec Go devices are not concerned by ipts, try removing this option.

**Comment by bdodroid** [comment]
I have tried with and without ipts option and I get the exact same result unfortunately

**Comment by bdodroid** [comment]
I did a powerwash and so far everything seems to be working now. 

I'm not sure what exactly I did that would have cause touch/pen to fail only after logging in but I must have done something it didn't like. 

Things I did:
added iwlwifi_backport to grub
enabled Hyper threading in the chrome flags 
enabled Linux beta
Installed Crossover for Chrome OS in crostini 
Installed Shadow via android app store
