### ISSUE TITLE
Camera not working anymore

### ISSUE THREAD

**Issue by lorenzopreda** [sebanc/brunch#698]
after i uptaded brunch to latest release r86 k5.4 and chrome os to Version 87.0.4280.88 (Official Build) (64 bit) the system does not recognize my built in camera anymore. In particuler, when i open the camera app, it just gets stuck in loading page with the small camera icon in the middle probably trying to find some camera. I tried to restart the system many times (with previous frameworks it worked) but nothing seems to change. Is there something i can do? Thank you very much

**Comment by Crescendo-BLYAT** [comment]
#691
