### ISSUE TITLE
[Wish/Documentation] How to install onto a secondary partition on Mac

### ISSUE THREAD

**Issue by stangri** [sebanc/brunch#71]
Hello,

Using a local Ubuntu machine, I've successfully created the bootable USB (well, actually microSD card + USB adaptor) for my Macbook Air 4,2 using instructions you have posted.

It boots just fine and I've gone as far as a welcome screen and tried out the Guest login.

I would prefer to install the ChromeOS in a partition of my Macbook's SSD drive. I've created a 24Gb partition (visible as /dev/disk0s3 from macOS and /dev/sdb when booted into ChromeOS on the bootable USB), however when trying to run `sudo chromeos-install -dst /dev/sdb` from Chrome shell while booted from the bootable Chrome OS USB I get error 12 unable to write or some such. 

Since there's no `cgpt` binary, I cannot use the install script from macOS, what is the recommended way of installing ChromeOS onto a separate partition on a Mac device only running macOS? I don't have an external USB drive I could install Linux on.

I've also tried just dd-ing the bootable image onto /dev/disk0s3, however when trying to boot from that partition, I then end up with the grub CLI prompt without any idea how to proceed further.

**Comment by sebanc** [comment]
Hi,

I think you should use the dual boot method for windows method mentioned in the readme (after creation of the usb drive which you already have). 

Booting using the usb should be easy, the difficult part will probably be if you want to install grub on your mac (which I cannot document but there are online resources).
