### ISSUE TITLE
Play Store not working on 10th gen, Possible fix

### ISSUE THREAD

**Issue by mithickartik** [sebanc/brunch#717]
@sebanc Play store is working on some 10th gen devices and not all. So maybe its a kernel problem, can you plz try to upgrade to kernel 5.6 maybe or 5.10 from 5.4? I am also happy to help.

**Comment by sebanc** [comment]
Brunch uses chromiumos kernel which is only available for "long-term" kernel branches (4.19, 5.4 and 5.10).

You can try a first build of 5.10 kernel by installing the latest brunch-unstable release and changing "/kernel" by "/kernel-5.10" in your grub configuration.

I don't think that it will solve this issue but it would be a good surprise if it does.

**Comment by mithickartik** [comment]
@sebanc where can I find this brunch-unstable though?

**Comment by sebanc** [comment]
It's one of my github repos

**Comment by mithickartik** [comment]
oh ok thanks I will try it.

**Comment by princepjamie06832** [comment]
Check it out at #983
