### ISSUE TITLE
Eraser on the Surface Pen cap doesn't work properly on surface go (r86/r87, k5.4)

### ISSUE THREAD

**Issue by dieson2000** [sebanc/brunch#720]
the cap has been recognized as a nib, but it works well as a eraser with k4.19(86/r87)
"options=ipts" seems no improvement

surface go gen1(8/128), r86 and now r87, dual boot with win10, with framework options: "suspend_s3" "advanced_als"

and thanks for your program, now i use this tablet mostly with ChromeOS, it saves this poor touch screen experience

**Comment by sebanc** [comment]
Could you try the brunch-unstable release ?

**Comment by dieson2000** [comment]
> Could you try the brunch-unstable release ?

did you mean [this](https://github.com/sebanc/brunch-unstable/releases/tag/r87-unstable-20201225)? i will try it.

**Comment by dieson2000** [comment]
updated to r87(20201227)，removed  "/kernel-4.19" , now the PEN works well
