### ISSUE TITLE
iwork10 flagship's touch screen flips left and right

### ISSUE THREAD

**Issue by moexco** [sebanc/brunch#73]
I tried to install chromeOS on my iwork10 flagship, Almost everything works.

But the screen touch has flipped left and right.

I don't know how to fix it, I cannot modify the touch screen parameters using xinput in chromeOS.

This is a great project, Thank you for everything you’ve done.

**Comment by sebanc** [comment]
Hi,

Could you attach a dmesg to this issue please ?

To get the dmesg, go to crosh shell, run "dmesg > ~/Downloads/dmesg.txt" and attach the dmesg.txt file from your Downloads folder.

**Comment by moexco** [comment]
[dmesg.txt](https://github.com/sebanc/brunch/files/4539267/dmesg.txt)
Sorry I was negligent, it's here

**Comment by sebanc** [comment]
No worries, actually forgot to precise but I would need a dmesg after a fresh reboot

**Comment by moexco** [comment]
[dmesg.txt](https://github.com/sebanc/brunch/files/4539470/dmesg.txt)
after reboot

**Comment by sebanc** [comment]
Could you update the latest testing release, normally it should be fixed ?

**Comment by sebanc** [comment]
I believe this issue is fixed so I will close it, don't hesitate to re-open it if needed.
