### ISSUE TITLE
Lenovo G580 Support

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [sebanc/brunch#731]
My device is a Lenovo G580 with a 2nd generation processor and with BIOS/UEFI support. My BIOS doesn't have the option to choose to just boot from UEFI mode so I can't boot the device with your rom because UEFI has always been installed as an MBR partition and MBR partitions in UEFI mode are invisible to me - only GPT can be seen as UEFI hard drive. Could you create some windows program that will install rom in usb as GPT-Only and from USB boot to install in hard drive as GPT-only. Of course, I also tried to choose a standard boot but it didn't want to work probably because your rom can only work in UEFI mode?

**Comment by sebanc** [comment]
You can try the mbr_support.tar.gz patch available in the master branch of this repo.

1) Extract the latest release
2) Extract the mbr_support.tar.gz patch
3) Follow the rest of the instructions
