### ISSUE TITLE
Surface Go Issues

### ISSUE THREAD

**Issue by manelscout4life** [sebanc/brunch#742]
Hey great job but I have noticed the following bugs that maybe you can help me with.

I have noticed that there is no auto rotate 

I have also noticed that after using the power button to put the surface to sleep and then using it to wake it up the power button will no longer put the tablet back to sleep. Letting it sit untouched will put it back to sleep and the power button will wake it but the power button will not put it back to sleep. 

I'm on R87 with the 5.4 kernel

**Comment by tml89** [comment]
How did you solve this issue? I've noticed the same issue on Fedora
