### ISSUE TITLE
Does chrome os will be stable on my pc. And which should be best recovery for me?

### ISSUE THREAD

**Issue by yegender124001** [sebanc/brunch#753]
Hi, @sebanc I only just want to ask that does chrome os will be at stable condition on my device. I have tried Chrome os dual boot. And think to install it on hard disk.

My PC Specs:

Processor:i3 2nd gen
Motherboard: DH61HO
Hard Disk : 1 TB
Wireless Dell Mouse and Keyboard
Monitor: DELLIN1910

I have tried never ware cloudready on it. It works well on it. I have tried Chrome os also. It also worked fine just with some lags and android issue. I think that it may be not after installation to hard disk. I install it because I have only this option. Please tell me that does it will be stable. 

Thanks

Your Friend

**Comment by sar777-dev** [comment]
Why not try asking  "brunch-toolkit" from WesBosch? that has compatibility check feature which detects the recovery image to use https://github.com/WesBosch/brunch-toolkit

**Comment by yegender124001** [comment]
Thanks. I only just want to use Chrome os for my studies. I think it will work best for me. I need stability to just to get no intrupption in my study.

**Comment by yegender124001** [comment]
Thanks. I only just want to use Chrome os for my studies. I think it will work best for me. I need stability to just no intrupption in my studies

**Comment by yegender124001** [comment]
Does this script will work on never ware cloudready?

**Comment by sar777-dev** [comment]
I didn't tried it on neverware cloudready but you can it a try following through instructions provided on Wesbosch readme page, or why don't live boot any linux distro and install 'brunch-toolkit' and check you compatibility with your hardware.

**Comment by yegender124001** [comment]
> I didn't tried it on neverware cloudready but you can it a try following through instructions provided on 'Wesbosch' readme page, or why don't live boot any linux distro and install 'brunch-toolkit' and check you compatibility with your hardware.

Does this will install chrome os in hard disk without a USB without making a img file ?

**Comment by sar777-dev** [comment]
Yes, you can also use 'brunch-toolkit' to install brunch ChromeOS on your hard disk/SSD.

**Comment by yegender124001** [comment]
> Yes, you can also use 'brunch-toolkit' to install brunch ChromeOS on your hard disk/SSD.

Thanks. I will try it.

**Comment by yegender124001** [comment]
Hi, I have installed it using brunch-toolkit. It works. I always tries Samus image for my PC. But it tells that compitable is another. Thanks for it.

**Comment by yegender124001** [comment]
But now It has some lag. And play store is slow in working.
