### ISSUE TITLE
Youtube "Glitch" lines

### ISSUE THREAD

**Issue by VivihugoFranz** [sebanc/brunch#754]
Hey, first of all, sorry for bad English, it's not my native language.
Hello to everyone.
I recently started to use Chrome OS in my computer with Brunch, and it works wonderfull. Thanks a lot for this project.
But, almost every time I'm on Youtube, some lines apears on the bottom of the video. I have no idea why it's happening, and I did'nt see anyone with the same problem. 
![Screenshot 2020-12-28 at 14 49 47](https://user-images.githubusercontent.com/76565873/103234218-dcaaea80-491d-11eb-9cf7-374c1cddc30b.png)

**EDIT** I noticed that is just on Youtube. It doesn't seem to be happening in any other players.

My laptop configs are:
Dell Latitude E5440
i5 4310U
8GB RAM
Running ChromOS 87.0.4280.109 
Brunch r87 stable 20201227

**Comment by sebanc** [comment]
It seems to be a known chrome bug with your gpu, try changing the zoom percentage in chrome or the display size in settings.

**Comment by VivihugoFranz** [comment]
Yeah, I checked it. I'm new into "Non Windows world", so i tought that was chrome OS problem. I look for that, thanks.
