### ISSUE TITLE
Blank screen after chrome os logo

### ISSUE THREAD

**Issue by yegender124001** [sebanc/brunch#761]
Hi @sebanc I have installed chrome os on vmware. I got boot splach. Then a blank screen. Please see this

![image](https://user-images.githubusercontent.com/57976250/103407994-bb990280-4b86-11eb-9ffe-a78946d61459.png)
![image](https://user-images.githubusercontent.com/57976250/103407999-be93f300-4b86-11eb-8f37-783d4dd8a3c3.png)

Then after
![image](https://user-images.githubusercontent.com/57976250/103408028-d9666780-4b86-11eb-9649-5b33578d18b3.png)

I think it can be installed on a vmware virtualmachine by your future updates of brunch

Thanks

**Comment by ameyjoshi3068** [comment]
Chrome OS cannot be installed on the virtual machine due to a lack of graphics drivers as mentioned [here](https://github.com/sebanc/brunch/issues/303#issue-637525469) by sebanc

If you are interested you can try adding them youreslf.

**Comment by yegender124001** [comment]
OK I will try to add them.

**Comment by Jhone-Harry** [comment]
Hello, Installing ChromeOS on VMware Workstation Pro is what I want to do. There is a statement that "visual machines are not supported" on the GitHub downloads page. Is it possible to make work on VMware Workstation or VirtualBox?
Please, if you can assist, I appreciate it.

**Comment by Jhone-Harry** [comment]
Hello, @yegender124001 Installing ChromeOS on VMware Workstation Pro is what I want to do. **a success for you? Have you added the drivers?**
Please, if you can assist, I appreciate it.

**Comment by yegender124001** [comment]
> Hello, @yegender124001 Installing ChromeOS on VMware Workstation Pro is what I want to do. **a success for you? Have you added the drivers?** Please, if you can assist, I appreciate it.

Cloudready aka Chrome OS Flex Works but not chrome OS when i tried. Chromium OS works too. But i didn't tried installing drivers
