### ISSUE TITLE
Play store takes forever to open even after applying android_init_fix

### ISSUE THREAD

**Issue by BigFhungus** [sebanc/brunch#767]
My play store and all play store apps took forever to open (15-30 minutes), so I applied the android_init_fix, and still the problem persists, any suggestions?

**Comment by sebanc** [comment]
Sorry but I have never been able to fix this issue which affects a few devices.

You could try to reset Chrome sync but I am not sure it will help in this case:
Login to your Google dashboard account -> Go to the "Chrome" application -> Manage synced data and click on "reinitialize synced data"

**Comment by yegender124001** [comment]
You should try the this https://github.com/WesBosch/brunch-toolkit
And then use that image which is in the output of this script. It may work.
I use samus and I have this issue but when I use this script it gives output to me that the recovery image is other.

**Comment by BigFhungus** [comment]
Thank you for your response, I will try this out.

**Comment by khanhtranngoccva** [comment]
Have you waited one minute on the login screen? What are your PC specs?

**Comment by sebanc** [comment]
Honestly, I have no idea why this happens on some laptops. I am willing to try something else but I would need "lsmod" logs taken from the latest brunch release. (run "lsmod > ~/Downloads/lsmod.txt" in crosh shell and attach lsmod.txt from your downloads folder).

**Comment by BigFhungus** [comment]
Thank you for the suggestions, but I have uninstalled brunch from my laptop
