### ISSUE TITLE
No space left on device during install 

### ISSUE THREAD

**Issue by busybox11** [sebanc/brunch#769]
Hey,
I'm trying to install brunch to a blank 32GB USB stick.
Unfortunately, the 3rd partition stops at 67% saying that there's no space left on this device (see screenshot below).
![image](https://user-images.githubusercontent.com/29630035/103463630-07d27700-4d2e-11eb-89c3-8cf2071ffecf.png)

Here is the output of the created partition table:
![image](https://user-images.githubusercontent.com/29630035/103463638-1325a280-4d2e-11eb-88b8-bde02cfb42d2.png)

And here is how my GParted looks like:
![image](https://user-images.githubusercontent.com/29630035/103463670-554ee400-4d2e-11eb-9dd8-4ae00b94a3c9.png)
(Don't pay attention to the last unallocated space, it's because of my manipulation, I'm trying to grow the ROOT-C partition manually).

I'm using `brunch_r87_stable_20201227.tar.gz`, `chromeos_13505.73.0_grunt_recovery_stable-channel_mp-v6.bin.zip` on an AMD A9-9425.
Here is my `brunch` folder.
![image](https://user-images.githubusercontent.com/29630035/103463739-e920b000-4d2e-11eb-8dc5-24f4d4abd96b.png)

Thanks for this awesome project and I hope you'll be able to help me!

**Comment by busybox11** [comment]
I tried to run it again and now for some reason it does not do the same thing.
It's still not working tho.
![image](https://user-images.githubusercontent.com/29630035/103467521-2184b600-4d50-11eb-81a8-027b4d691a56.png)

**Comment by sebanc** [comment]
Reboot your computer and try again

**Comment by busybox11** [comment]
Reboot? Yeah, I can do that. Why would that be a problem tho?

**Comment by sebanc** [comment]
The partition table of the usb flashdrive could not be properly updated which prevents flashing partitions, a reboot should fix it

**Comment by busybox11** [comment]
Okay, I'm going to do it ASAP then. I'll keep you updated on that. Thanks for your help!

**Comment by busybox11** [comment]
![image](https://user-images.githubusercontent.com/29630035/103467921-2c414a00-4d54-11eb-9ce5-ba7492ac0dbd.png)
Oh yeah, it seems that it's working now. I'll keep you updated.

**Comment by busybox11** [comment]
![image](https://user-images.githubusercontent.com/29630035/103468080-c655c200-4d55-11eb-8920-816a7432b981.png)
Yeah, it worked. I apologize for this useless issue, thank you for your time anyway!
Thanks again for this incredible project :)

**Comment by sebanc** [comment]
No pb :)
