### ISSUE TITLE
What version?

### ISSUE THREAD

**Issue by pixlofc** [sebanc/brunch#773]
i already did this, but wich chrome os should i use? i have a notebook with aa i3 6006u (6th gen).

**Comment by sebanc** [comment]
I would suggest rammus as it is the one brunch is tested on.

**Comment by pixlofc** [comment]
ok I will try

**Comment by pixlofc** [comment]
can i run 89 on the latest brunch @sebanc ?

**Comment by ameyjoshi3068** [comment]
@pixlofc Yes, r89 should work. But be sure to backup any data as it may have bugs.

**Comment by pixlofc** [comment]
thanks
