### ISSUE TITLE
Self Repairing Chrome OS

### ISSUE THREAD

**Issue by yegender124001** [sebanc/brunch#775]
Hey, @sebanc today I start chrome os in my pc after a long time. Now I got a problem that all worked fine but after launching of brunch chrome os open. Then I got a loading and it says self-Repairing Chrome os. What should I do to recover It. I have installed Google hatch image in my pc

Thanks

**Comment by sebanc** [comment]
Try to turn off fast startup in windows:
https://support.lenovo.com/gt/en/solutions/ht501793

**Comment by yegender124001** [comment]
OK I will try it again. But the fast startup is turned off in my PC already

**Comment by yegender124001** [comment]
Sebanc No success. I got this again.
![IMG_20210104_111207_161](https://user-images.githubusercontent.com/57976250/103504654-0dd76d80-4e7e-11eb-8923-2ff618452599.jpg)

Please help me

**Comment by sebanc** [comment]
Boot to windows and press SHIFT while shutting down the computer. Not sure why this happens if fast startup is disabled though

**Comment by yegender124001** [comment]
It leaves again there. No success again

**Comment by sebanc** [comment]
Weird, try to run a checkdisk in Windows on the partition which contains the chromeos is image

**Comment by yegender124001** [comment]
I have installed on my windows partition.  I am checking my windows partition by using chkdsk c:

**Comment by yegender124001** [comment]
It stucks. 
![image](https://user-images.githubusercontent.com/57976250/103508494-17190800-4e87-11eb-816b-916d9dee186e.png)

**Comment by ameyjoshi3068** [comment]
I would suggest you create a separate partition and move .img to that partition.
If you can create ext4 from Linux then go for it.
Don't forget to change your grub config according to the new partition.

**Comment by yegender124001** [comment]
> I think this issue is most likely due to NTFS partition error(corruption).
> I would suggest you create a separate partition and move .img to that partition.
> If you can create ext4 from Linux then go for it.
> Don't forget to change your grub config according to the new partition.

It didn't stucked. I have connected PC to a remote session. So, It is a performance reason. I have do it again and It run without sticking.So, my Windows partition is not corrupted

**Comment by ameyjoshi3068** [comment]
@yegender124001 Its good to know your partition was not the issue.
If I was in the place of you, I would have replaced all files from recovery image and brunch to .img.
So that any issue left behind get solved instead of waiting here for solution.

**Comment by yegender124001** [comment]
OK I will try to copy it. If the issue remains then I will write here
