### ISSUE TITLE
Drawing problems on boot

### ISSUE THREAD

**Issue by F1F7Y** [sebanc/brunch#79]
![IMG_20200427_211419](https://user-images.githubusercontent.com/64418963/80488556-cef03000-895e-11ea-9fe5-88add5240d93.jpg)
When booting it draws this (image), from multiple attempts I 100% know that this all is text. The image was taken on the first boot when it was building, yet it does this on every boot before it shows the 'chrome' splashscreen.

I'm running rammus v80 and the latest brunch v80 testing. My notebook is the HP ProBook 430 g2. The same happened on the stable version of brunch v80.
A note-worthy thing is also that secureboot doesn't like the certificate and so it is turned OFF, I never was able to boot with secureboot and so I don't know if this screen is drawn with with it.

My notebook doesn't have a fullHD (it's 1366 x 768) screen wich I feel like is causing it to draw like this.

**Comment by sebanc** [comment]
Hi,

Could you try to add `vt.handoff=1` to the kernel command line (after cros_debug) by running "sudo edit-grub-config" ?

**Comment by F1F7Y** [comment]
![Screenshot 2020-04-28 at 19 35 52](https://user-images.githubusercontent.com/64418963/80518967-839e4780-8987-11ea-9fc6-07c00dfff279.png)
This is how the edited file looks like, just making sure I did what you wanted me to try. It didn't help, the messed up text still shows as normal.

**Comment by juicypop** [comment]
You could try "nomodeset" in the kernel line

Actually i didn't tried this yet on Chrome os but it solved kind of these glitches in the past for me

**Comment by lfom** [comment]
If you see the GRUB menu normally, then you can try to add this line just below "ChromeOS":
`set gfxpayload=keep`

**Comment by F1F7Y** [comment]
![Screenshot 2020-04-29 at 13 02 44](https://user-images.githubusercontent.com/64418963/80590111-a37f4b00-8a1b-11ea-8eb6-94ad09aa6a39.png)
I've tried both `nomodeset` (my notebook wasn't able to boot with this) and `set gfxpayload=keep` yet the text is still messed up, my question is if there is a way to tell the bootloader the screens resolution, maybe that could fix the problem.
I'm gonna try and educate myself on this matter, thanks for the replies, if you have any other suggestions please post them here, thanks.

**Comment by F1F7Y** [comment]
Also something important, the GRUB menu desplays normally, it's the section between the grub menu and chrome os splashscreen.

**Comment by lfom** [comment]
Then the video mode isn't set correctly in ChromeOS... I don't know if it would work, but you can manually set the video mode adding something like `video=1024x768` to the kernel line.

**Comment by sebanc** [comment]
Could you also try adding "vga=normal" to the kernel command line ?

**Comment by F1F7Y** [comment]
![Screenshot 2020-04-30 at 09 40 16](https://user-images.githubusercontent.com/64418963/80685630-c5360c00-8ac7-11ea-8a26-0e062d5c236c.png)
`vga=normal` didn't do anything.

**Comment by F1F7Y** [comment]
After searching aroud I found a comment made by @sebanc in an issue around google play and android apps not working suggesting to add `console=` in the kernel line after cross_debug wich worked! There is still a distorted `_` blinking, but at least I won't get people staring and making comments about it. Thanks to everyone who made suggestions.

**Comment by sebanc** [comment]
FYI, someone with the same issue as yours (actually an HP Probook also) solved it by going to the bios and setting Advanced > boot options > boot mode > UEFI Hybrid (with CSM).

Hope it helps
