### ISSUE TITLE
How to access Partitions and edit Kernel Commands

### ISSUE THREAD

**Issue by Aditya5607** [sebanc/brunch#794]
I am having trouble to access Partitions and edit Kernel Command Line as u said in https://github.com/sebanc/brunch/issues/14 to @santhoshr
I actually wanted to configure the grub. cfg to enable Chrome OS updates

**Comment by khanhtranngoccva** [comment]
edit-grub-config

**Comment by Aditya5607** [comment]
But where to type it

**Comment by khanhtranngoccva** [comment]
Ctrl + Alt + T > shell > sudo edit-grub-config
Add options=mount_internal_drives,enable_updates just before the initrd line.
