### ISSUE TITLE
Grub error on BIOS

### ISSUE THREAD

**Issue by supersri811** [sebanc/brunch#841]
error: no such partition
You need to boot the kernel first
This happens even after I extract the mbr_support.tar.gz package

**Comment by supersri811** [comment]
I have an i3 processor and the computer is hp pavilion dv6

**Comment by sebanc** [comment]
This usually means that rootc.img from the brunch archive has not been written to partition 7, did you unpack it from the brunch archive ?

**Comment by supersri811** [comment]
yes

**Comment by sebanc** [comment]
Are you trying to dual boot or to install to hdd ?

**Comment by supersri811** [comment]
dual boot

**Comment by supersri811** [comment]
actually triple boot , windows, linux mint and chrome os

**Comment by sebanc** [comment]
As written in the main readme, dual boot is not supported with mbr because most legacy grub do not support it.

However, there were some success reports with the legacy grub from arch linux.

**Comment by supersri811** [comment]
Okay I'll try that
