### ISSUE TITLE
TP-Link UB400 Bluetooth adapter Not work

### ISSUE THREAD

**Issue by rohtakcity** [sebanc/brunch#873]
I have Bluetooth dongle UB400 that work perfectly in windows and Linux. But UB400 not work in brunch r88 stable. Is anyway that UB400 Bluetooth adapter work in Brunch chromeos

**Comment by sebanc** [comment]
Could you try kernel 5.10 ? (refer to the main readme)

**Comment by sebanc** [comment]
As a side note, not sure what you are trying to pair but chromeos only allows to pair sound (headset, speakers) or input devices.

**Comment by rohtakcity** [comment]
thanks problem solve now
