### ISSUE TITLE
Full Disk Encryption? 

### ISSUE THREAD

**Issue by DestroyerXyz** [sebanc/brunch#874]
Is it possible to implement Full Disk Encryption like it is by default in ChromeBooks?

**Comment by sebanc** [comment]
Unless I am mistaken chromebooks do not have full disk encryption, only userdata is encrypted.

On another note, chromebooks have dm-verity only verifies the rootfs integrity, however to be efficient it needs a specific bootloader such as the ones on chromebooks. With a standard UEFI bios, anyone can temporarily modify the grub config to disable dm-verity which completely defeats its purpose anyway.
