### ISSUE TITLE
i have a problem installing dual chrome os i get this error.

### ISSUE THREAD

**Issue by djgerman10** [sebanc/brunch#876]
i have a problem installing dual chrome os i get this error.

![Screenshot from 2021-02-12 18-16-25](https://user-images.githubusercontent.com/48584512/107808016-bc0ce780-6d47-11eb-8caf-9d4300443239.png)

![Screenshot from 2021-02-12 18-19-40](https://user-images.githubusercontent.com/48584512/107808034-c202c880-6d47-11eb-8772-aa3a1e6c9fa0.png)

![Screenshot from 2021-02-12 18-19-48](https://user-images.githubusercontent.com/48584512/107808051-c7f8a980-6d47-11eb-9b2f-97e17ad1c7a2.png)

**Comment by NR-No-Rage** [comment]
U have installed Chromebrew?

**Comment by kushmittal2009** [comment]
> i have a problem installing dual chrome os i get this error.
> 
> ![Screenshot from 2021-02-12 18-16-25](https://user-images.githubusercontent.com/48584512/107808016-bc0ce780-6d47-11eb-8caf-9d4300443239.png)
> 
> ![Screenshot from 2021-02-12 18-19-40](https://user-images.githubusercontent.com/48584512/107808034-c202c880-6d47-11eb-8772-aa3a1e6c9fa0.png)
> 
> ![Screenshot from 2021-02-12 18-19-48](https://user-images.githubusercontent.com/48584512/107808051-c7f8a980-6d47-11eb-9b2f-97e17ad1c7a2.png)

@djgerman10 Make sure you use the chrome-install.sh file that sebanc provided then just ignore this message. Boot into windows 10. Then open explorer and go to where you made the chrome os image. There you will see another file named something like grub. Open it. Copy all the contents inside the stars. Then install grub 2 win. Add a new configuration custom code and paste that code there. On next boot select chrome os and done!
