### ISSUE TITLE
how to change kernel?

### ISSUE THREAD

**Issue by djgerman10** [sebanc/brunch#881]
I have **intel bay trail**, I want to put the kernel 4.19 because it doesn't work at all well.

![Screenshot 2021-02-13 at 06 36 12](https://user-images.githubusercontent.com/48584512/107846846-d71e3c80-6dc5-11eb-9a17-bd5307795f6f.png)

_I am lost, someone who can help me?_

**Comment by b4iterdev** [comment]
You are dual-booting, so if you are using grub2win, boot into windows, open grub2win app, manage boot order, click chrome os, then click in boot config file, notepad will show up then you can change the kernel ( https://github.com/sebanc/brunch#changing-kernel-version )

**Comment by b4iterdev** [comment]
If your problem has solved, please consider close this issue.
