### ISSUE TITLE
is it possible to put kernel 3.12 backports?

### ISSUE THREAD

**Issue by djgerman10** [sebanc/brunch#892]
is there any way to put kernel 3.12 backports? which supports gma500 driver module

Because there is no system other than windows 7 that supports intel gma3600 graphics

**Comment by madhits** [comment]
I have a gma3500 core2duo system using cloudready. So cloudready has this.

**Comment by sebanc** [comment]
This is not an issue of gfx drivers but of cpu instructions sets.

Cloudready does not use specific cpu instructions when they build ChromiumOS from source but google does in ChromeOS recovery images.

**Comment by djgerman10** [comment]
in cloudready it doesn't work either.

https://guide.neverware.com/technical-details/

**Comment by sebanc** [comment]
My point is that it is 100% sure brunch cannot work on core 2 duo.

**Comment by djgerman10** [comment]
it's an Atom N2600, I think it's even worse haha

**Comment by sebanc** [comment]
Actually Atom 2600 should work but there is a bug with 5.4 kernel, try with kernel 4.19 (refer to the main readme)
