### ISSUE TITLE
Brunch r88 seems not be working on Asus Chromebox CN60

### ISSUE THREAD

**Issue by RagnarLodbrok79** [sebanc/brunch#897]
I have tried r88 four times, both vid Chrome 88 and 87.
Evertime I try: I see the white screen with Chrome logo, after that I see a black screen with a mouse cursor. I can move the cursor. When I click the left bottom corner the computer shut off, I can click all the other corners or everywhere without anything happes.

Brunch 87 + CrOS 87 and 88 is good.

**Comment by sebanc** [comment]
Could you try the latest brunch-unstable release ?

**Comment by RagnarLodbrok79** [comment]
Yes, it works with latest unstable Brunch 88 and CrOS 88.

I got some errors when upgrading Brunch, don't know if it's normal?

![Screenshot 2021-02-21 at 09 56 29](https://user-images.githubusercontent.com/79371412/108621449-ef7c0000-7432-11eb-8076-520791f101f1.png)

**Comment by sebanc** [comment]
This error happens as you are running the script from the downloads folder but it is harmless.

I had to make a change in the new brunch-unstable release and I would need you to verify that it still works on your device. Could you try it ?
https://github.com/sebanc/brunch-unstable/releases

**Comment by Buktahula** [comment]
I tried it, everything seems to be working fine (5 minutes test), only Android apps are very slow it feel's like mouse input or screen refresh is not working properly

**Comment by RagnarLodbrok79** [comment]
I have also tried it now. It works.
I also have a feeling Android apps are a bit slow.
![Screenshot 2021-02-21 at 16 48 09](https://user-images.githubusercontent.com/79371412/108630408-063b4a80-7465-11eb-92c4-bec34de7f287.png)

**Comment by RagnarLodbrok79** [comment]
I'm new to github, should I close this issue now?

**Comment by RagnarLodbrok79** [comment]
Now the android apps (lag on mouse input or screen refresh rate) is good as well!
