### ISSUE TITLE
Tablet Mode

### ISSUE THREAD

**Issue by XeroWolf7** [sebanc/brunch#92]
I have a 2 in 1 device and when i fold it, it doesn't go in tablet mode. Is their any fixes?

**Comment by sebanc** [comment]
Hi

What's your laptop model ?

**Comment by XeroWolf7** [comment]
I have the Lenovo Yoga Pro 3 1370.

**Comment by sebanc** [comment]
As far as I can see there is no linux kernel driver to detect tablet mode on your device.

Your options are:
- Use CTRL+ALT+SHIFT+T to switch from/to tablet mode.
- Use "sysfs_tablet_mode" framework option to trigger tablet mode via command line.
- Use "force_tablet_mode" framework option to always stay in tablet mode.

**Comment by XeroWolf7** [comment]
Thanks! Its a little bit inconvenient, but it works!
