### ISSUE TITLE
chromeos-install.sh file not running

### ISSUE THREAD

**Issue by Siphowin** [sebanc/brunch#935]
When I run the install.sh file it runs well until it gets to running chromeos-install.sh, it reports an error:

chromeos-install.sh: line 7: syntax error near unexpected token `$'\r''

chromeos-install.sh: line 7: `usage()

My HP stream notebook has ubuntu installed and its internal memory is known as mmcblk0 which I have edited in the install.sh file. I have tried multiple versions of brunch and the rammus chromeos recovery but I haven't had any luck.

**Comment by WesBosch** [comment]
We do not support that install.sh file and will not be providing help for it's problems. Try using the chromeos-install.sh as directed by the github readme and do not use video guides or external files that aren't linked here on this repo.

**Comment by TheSwisscheese2013** [comment]
Did you ever figure it out?same issue here.

**Comment by TheSwisscheese2013** [comment]
> When I run the install.sh file it runs well until it gets to running chromeos-install.sh, it reports an error:
> 
> chromeos-install.sh: line 7: syntax error near unexpected token `$'\r''
> 
> chromeos-install.sh: line 7: `usage()
> 
> My HP stream notebook has ubuntu installed and its internal memory is known as mmcblk0 which I have edited in the install.sh file. I have tried multiple versions of brunch and the rammus chromeos recovery but I haven't had any luck.

Did you ever figure it out?

**Comment by WesBosch** [comment]
> > When I run the install.sh file it runs well until it gets to running chromeos-install.sh, it reports an error:
> > 
> > chromeos-install.sh: line 7: syntax error near unexpected token `$'\r''
> > 
> > chromeos-install.sh: line 7: `usage()
> > 
> > My HP stream notebook has ubuntu installed and its internal memory is known as mmcblk0 which I have edited in the install.sh file. I have tried multiple versions of brunch and the rammus chromeos recovery but I haven't had any luck.
> 
> Did you ever figure it out? 

Run the brunch install file (chromeos-install.sh) directly by following the github guide and don't use the install.sh file provided by kedar or other YouTube videos or blogs. 

This issue is probably because of a broken variable in that unsupported script, so following the correct guide will probably not have this problem

**Comment by Siphowin** [comment]
Thank you so much for the help, I ran it directly from the instructions on github and it worked as I'm writing this on the laptop. The only reason I used the install.sh is that I had searched on google for putting chromeos on a laptop and it was those vids that came up, sorry about making the mistake but I'll know for next time!
