### ISSUE TITLE
Chrome OS probelm

### ISSUE THREAD

**Issue by kingmaj0r** [sebanc/brunch#946]
hi, when I installed chrome os on to my pc it just stays frozen on the chrome screen.

my pc specifications:
cpu: amd ryzen 5
gpu: nvida geforce gtx
motherboard: msi
ssd: nvme 500gb

**Comment by potatocubez** [comment]
I don't think Chrome OS natively supports Nvidia cards just yet

**Comment by kingmaj0r** [comment]
oh welp
