### ISSUE TITLE
Lenovo D330 power off himself as soon as the welcome screen appear

### ISSUE THREAD

**Issue by cino31** [sebanc/brunch#95]
Hello , on Lenovo D330 as soon as the system boot on the welcom GUI, it goes off after 5 sec
How to force it to ignore shutdown command or to ignore touch screen also ? 
CPU : Intel N4000 
IGPU : Intel HD 600
Latest rammus 80 and latest beta brunch 81

**Comment by sebanc** [comment]
Hi,

There is an issue on latest testing which seems to generate this issue on some laptops, could you try the stable release ?

**Comment by cino31** [comment]
Thank you it's working fine now ! Keep the good work .

**Comment by sebanc** [comment]
Happy to hear that it works :)
