### ISSUE TITLE
brunch installer not installing grub.

### ISSUE THREAD

**Issue by neoname** [sebanc/brunch#951]
basically i used the samus 87 image to install brunch on my pc using the linux mint livecd. everything went seemingly without error however grub was nowhere to be found. the strange part is that the config was in /dev/sda12, though...

**Comment by neoname** [comment]
update: basically the .efi files were there but for some reason my pc didn't want to boot them. strange...

**Comment by Agazart** [comment]
Hi, i have the same probleme. Did you manage to solve it. 
Thnaks
