### ISSUE TITLE
how do i install chrome os?

### ISSUE THREAD

**Issue by kingmaj0r** [sebanc/brunch#958]
hi, can someone help me install chrome os on my pc?
right now I got windows 10.

pc specs:
GPU: Nvidia GeForce gtx 1060
CPU: ryzen 5
ram: 16GB
SSD: nvme 500GB
motherboard: msi

**Comment by Andytheclown** [comment]
It’s not compatible with Nvidia. So that’s simple. Remove it and then it will probably install. Proably....

**Comment by kingmaj0r** [comment]
rip will they soon support nidia

**Comment by kingmaj0r** [comment]
> It’s not compatible with Nvidia. So that’s simple. Remove it and then it will probably install. Proably....

rip will they soon support nidia

**Comment by kingmaj0r** [comment]
does it support it now? nvidia

**Comment by potatocubez** [comment]
> does it support it now? nvidia

No.

**Comment by kingmaj0r** [comment]
okay, thank you do you know when tho?

**Comment by kingmaj0r** [comment]
> > does it support it now? nvidia
> 
> No.

okay, thank you do you know when tho?

**Comment by zainullahk** [comment]
Never support will never come this is not official project
