### ISSUE TITLE
Lenovo Miix 510-10ICR Issues.

### ISSUE THREAD

**Issue by Nevuly** [sebanc/brunch#966]
Hello, Sir.

I got a some issues in Miix 510-10ICR, I need to report to you to get advise.

1. Screen brightness control is not work, and default brightness is low. (It only works in 40%)
2. Screen Auto Rotation is not work.
3. Both Cameras not work.

I used Chrome OS r89, and latest brunch with 5.4 kernel, with wizpig image

I checked your brunch kernel, I found auto rotation sensor and cameras. But defconfig is not defined to 'y' just in 'm'.
I think If I switch to 'y', that's are work correctly. But I don't sure about that.
And I can't resolve screen brightness control and default brightness.

Can you advise to me how to fix it in kernel?

Thanks for your work, This project makes my tablet get revive.

**Comment by singlag** [comment]
confirm same issus in Miix 510 (R102 / V94)
camera sensor is OV2680 and OV5645
IMU is Bosch accelerometer

https://pcsupport.lenovo.com/us/zh/products/tablets/miix-series/miix-510-12ikb/downloads/driver-list/component?name=%E6%99%B6%E7%89%87%E7%B5%84
