### ISSUE TITLE
Infinite boot loop (Loading Brunch Framework)

### ISSUE THREAD

**Issue by Saroj-padhy** [sebanc/brunch#976]
Facing bootloop after installing chrome os in HDD.
I tried to install chrome os by using linux live image.
Installed it in a HDD completely.
Then it showed rootfs etc.
Then restarted and kept showing loading brunch framework and again restart. 
![PXL_20210324_140708794](https://user-images.githubusercontent.com/81323914/112360460-5b82aa00-8cf8-11eb-9a63-acc66503446c.jpg)
![PXL_20210324_162714190](https://user-images.githubusercontent.com/81323914/112360477-5faec780-8cf8-11eb-84e5-c441f5716f63.jpg)

System specs:
Intel Pentium G series 4th gen (G3240)
No external GPU
4gb Ram

Rammus recovery 87 
Brunch , tried both 87 stable and 88 stable. 
Same error.

**Comment by Saroj-padhy** [comment]
@sebanc help.

**Comment by Saroj-padhy** [comment]
Ok it's solved when I changed kernel to 4.19. 😁

**Comment by Saroj-padhy** [comment]
Restarting brings the problems again. How to edit grub permanently. ? @sebanc or any other #experts.

**Comment by Roa1375** [comment]
> Ok it's solved when I changed kernel to 4.19. 😁

How do you change kernel version? I have same problem

**Comment by MrZethaz** [comment]
> > Ok it's solved when I changed kernel to 4.19. 😁
> 
> How do you change kernel version? I have same problem

enter in debug mode  on boot and select kernel 4.19 :)

**Comment by Roa1375** [comment]
> select

And how to enter debug mode?!

**Comment by ASOwnerYT** [comment]
How do I enter debug mode???

**Comment by AdityaBhati1** [comment]
in the grub menu press **E** and here you are in debug mode .
 
but i don't how to change kernel version ?

 would anyone help?

**Comment by billal78** [comment]
> in the grub menu press **E** and here you are in debug mode .
> 
> but i don't how to change kernel version ?
> 
> would anyone help?

Hi, after pressing E (when you're in debug mode), press F2 then add -4.19 after kernel  (kernel-4.19) then boot by pressing F10
I hope i helped

**Comment by Napoleon99999** [comment]
Please help what to write after grub>
I still can't understand how to change kernel.
Please tell step by step what to do after entering debugging mode. It shows grub>

**Comment by Napoleon99999** [comment]
Please help what to write after grub>
I still can't understand how to change kernel.
Please tell step by step what to do after entering debugging mode. It shows grub>

**Comment by cyberghost-whitedevil** [comment]
Press E and then use your keyboard and add -4.19 to kernel. Then press f10.. no need to press f2

**Comment by mukulrajput112** [comment]
> Press E and then use your keyboard and add -4.19 to kernel present in the code. Then press f10.. no need to press f2

Bro this code is not saving in my pc and problem is not solved

**Comment by Sherazus** [comment]
Can you chat with me in messenger.i have same problem.Plz reply.
My id link:https://www.facebook.com/sherazus.tahmeed

**Comment by Sherazus** [comment]
> Facing bootloop after installing chrome os in HDD. I tried to install chrome os by using linux live image. Installed it in a HDD completely. Then it showed rootfs etc. Then restarted and kept showing loading brunch framework and again restart. ![PXL_20210324_140708794](https://user-images.githubusercontent.com/81323914/112360460-5b82aa00-8cf8-11eb-9a63-acc66503446c.jpg) ![PXL_20210324_162714190](https://user-images.githubusercontent.com/81323914/112360477-5faec780-8cf8-11eb-84e5-c441f5716f63.jpg)
> 
> System specs: Intel Pentium G series 4th gen (G3240) No external GPU 4gb Ram
> 
> Rammus recovery 87 Brunch , trie

> Ok it's solved when I changed kernel to 4.19. 😁

Can you chat with me in messenger. I have same problem.plz reply
My id: https://www.facebook.com/sherazus.tahmeed

**Comment by Cybernautici74** [comment]
> Press E and then use your keyboard and add -4.19 to kernel present in the code. Then press f10.. no need to press f2

Io ancora no n riesco a capire come cambiare kernel. Potete aiutarmi con calma con i commandi o screenshot grazie

**Comment by Cybernautici74** [comment]
> > in the grub menu press **E** and here you are in debug mode .
> > but i don't how to change kernel version ?
> > would anyone help?
> 
> Hi, after pressing E (when you're in debug mode), press F2 then add -4.19 after kernel (kernel-4.19) then boot by pressing F10 I hope i helped

Io non ancora riesco a capire come cambiare kernel. Mi potete dare i comandi con calma o uno screenshot grazie
