### ISSUE TITLE
Android 64 bit apps support

### ISSUE THREAD

**Issue by alvarohnl** [sebanc/brunch#978]
Hi, is there any recovery imagem that is compatible with Android 64 bit apps? 
At the moment I'm running the samus recovery image.

**Comment by princepjamie06832** [comment]
Yes, it runs 64-bit on Android apps. However, Chromium OS have dropped support for 32-bit.

**Comment by alvarohnl** [comment]
The rammus recovery image is compatible with 654 bit apps.
