### ISSUE TITLE
Android Container on 10th Gen Intel Compatibility

### ISSUE THREAD

**Issue by princepjamie06832** [sebanc/brunch#983]
Recently updated to v90 in beta, it seems Android Container is working okay. It's called ARCVM and running Android 11.

I am running Brunch r88 stable 20210223 with Kernel 5.4 and 'Hatch' recovery on ASUS VivoBook X512JA - Intel Core i3-1005G1, 8GB memory & 128 GB storage.

**Before v90,** when I attempting to open Play Store. But I got error encountered, it said 'Something went wrong'. It seems Android Container don't work in Ice Lake Platform. I found error code 8 when Google Play apps and services failed to start without ARCVM.
**In v90,** my second attempt to open Play Store and it working. After update, error are no longer present when opening Play Store. Version 90 stable are now available. How funny is, it turns out issue when I attempting to open Play Store and I got error encountered with code 2 at first time but it's normal by restarting computer.

If you interested to test v90, switch to Beta channel and only available for 'Hatch'. 
Next month will rollout v90 stable and comes with Android 11. Remember, don't pick wrong recovery image, otherwise Play Store may not open without ARCVM. If any encounter error? Let us know. Once reach v90 stable, @sebanc will updating this repository that 10th Gen Intel don't compatible with Android Container.
**Update April 7:** I heard 'Rammus' and 'Samus' are getting Android 11 update. If you have 10th Gen Intel, it is recommend to use 'Hatch' to get longer duration than other recovery images. You can try 'Rammus' to get it work Android Container. However, 'Samus' will be reached end of life in this year of June. After last software update for 'Samus', you may no longer to receive new updates.
**Update April 21:** Chrome OS 90 released but 10th Gen slowly to release. If you switching to Stable channel, you have to perform powerwash. You can backing up data before powerwashing.
**Update May 9:** 'Volteer' recovery image available for 10th or 11th Gen Intel. It turns out 'Hatch' delayed or did not released for version 90. It comes with ARCVM starting version 90 but Android 11 will be later. If you have 11th Gen, you'll need to change to Kernel 5.10 otherwise it may not boot properly and rendering black screen. I may close this issue soon after updated.
**NOTE:** Running on Chrome OS 90 and still based on Android Pie. Android 11 upgrade will be later. Android Container on 10th Gen Intel works fine without issues. I'm using 'Volteer' recovery instead that 'Hatch' release delayed.

**Comment by rvaldomir** [comment]
i have i51021u gen and decided to try puff instead rammus, as with rammus i was experiencing a lot of hangs / freeze and serveral unexpected restarts.

maybe you can try with that one. 

it is more for chromebox, i decided to use that as i have NUC box.

but i think for i5 10th gen in laptops you can use hatch as the ASUS Chromebook Flip C436FA uses 10th gen of intel

**Comment by princepjamie06832** [comment]
> i have i51021u gen and decided to try puff instead rammus, as with rammus i was experiencing a lot of hangs / freeze and serveral unexpected restarts.
> 
> maybe you can try with that one.
> 
> it is more for chromebox, i decided to use that as i have NUC box.
> 
> but i think for i5 10th gen in laptops you can use hatch as the ASUS Chromebook Flip C436FA uses 10th gen of intel

If you have desktop version with 10th Gen Intel, you can try 'Puff' recovery image but v90 slowly to release for 10th gen.

**Comment by princepjamie06832** [comment]
I'm closing this issue. It seems Android Container on 10th Gen Intel is working perfectly. Since I tried out unstable Kernel 5.4, 
Google Play Store was not working until now.
