### ISSUE TITLE
Chrome os loading brunch framework issue...

### ISSUE THREAD

**Issue by meyogesh2007** [sebanc/brunch#998]
Hi, i tried to install Chrome os as dual boot.
after installing with linux and config boot with grub2win, when i want to login in my chromos, i get this message and my laptop will restart automatically.

Loading brunch Framework...
My cpu is Intel i3 4th gen

**Comment by Sayor0630** [comment]
You have to change Branch Karnel version to Karnel 4.19. Otherwise, it doesn't work on most 4th gen PCs. I had this problem. But it solves by changing Karnel to Karnel 4.19 in Grub.

**Comment by Sayor0630** [comment]
**_replace "/kernel" on the grub configuration linux line with "/kernel-4.19_**

**Comment by meyogesh2007** [comment]
I reinstall chrome os with latest brunch version and it works...
